### PR TITLE
bitcoin-paper: Greatly improved Romanian translation

### PR DESCRIPTION
**Pull request by neuro-fishy**
The actual proposed new translation improves dramatically the existing one from the following points of view:

- current translation contains crucial translation flows, including, but not limited to: (1) overall correction of the translated text, (2) the translated sentences do not make sense in Romanian, (3) the translated sentences are not coherent, (3) the translated sentences contain very severe grammar issues. The new proposed translation is correct from the translation process point of view, it is coherent, it is typo-free, it contains no grammar / spelling issues and it fully reflects Satoshi's ideas from the original document as they sound in Romanian language

- current translation does not contain the diagrams translated in Romanian, while the new proposed one contains diagrams fully translated in Romanian

- current translation does not respect even by far the original document's font, font size, font color, alignment, pagination (number of pages) and text framing inside the document. The new proposed translation fully respects the visual aspect of the original document: each page starts and ends with the same text as the original document; the translated text and its color / font / alignment / size / pagination also respect the source document

- current translation does not contain mathematics formulas translated in Romanian, while the new proposed translation contains also the formulas translated in Romanian

- current translation does not have inserted the page number, while the new proposed document contains also the page number

- aesthetically, the new proposed translation mirrors completely the original document, while the current translation was created in a deep not professional manner.

This topic from BitcoinTalk (and its posts) also reflects all the issues of the actual translation and, as a plus, there are several images reflecting the serious problems of the current translation: https://bitcointalk.org/index.php?topic=5285986.0.

Please be so kind and revise this new translation proposal, taking into account all the improvements mentioned above and also the topic from BitcoinTalk.org. Thank you.

### CODE REVIEW

**Comment by Komodorpudel** [comment]
@neuro-fishy Thanks for addressing this. And really great job! Can any other Romanian speaker confirm here on GitHub that this version is now indeed accurate?

@Cobra-Bitcoin will then merge.

**Comment by Cobra-Bitcoin** [comment]
Thank you for this, unfortunately it's hard for us to review the quality of a translation, so it can sometimes happen that a bad translation of the whitepaper slips through.

As @Komodorpudel said, we will wait for a native Romanian speaker to confirm the quality of this particular translation, and then we will merge.

**Comment by neuro-fishy** [comment]
Thank you for the reply and for the kind words.
I guess that I will have to ask the (_few_) active Romanian from Bitcointalk to make GitHub account and confirm.
I _hope_ that would be OK... (I'm open to suggestions).

**Comment by Komodorpudel** [comment]
> Thank you for the reply and for the kind words.
> I guess that I will have to ask the (_few_) active Romanian from Bitcointalk to make GitHub account and confirm.
> I _hope_ that would be OK... (I'm open to suggestions).

In my opinion it is also okay if someone confirms within your bitcointalk thread that the translation is good as it is :) So no GitHub account needed.

**Comment by tachyonix** [comment]
Hi, I also wanted to confirm here that I've read both translations and I have to admit I'm a little ashamed about the first one. Thanks GazetaBitcoin for bringing this into our attention and for acting accordingly to create a better one. Thank you too Neuro-fishy for helping him with that. I agree that your translation is on a hole other level.

**Comment by Fillippone** [comment]
Hello, I am Fillippone from Bitcointalk.org (I can eventually sign a message to prove that). 

Gazeta Bitcoin translated a number of my threads into Romanian and made fantastic work. He also helped me finding typos or inconsistencies in the original posts. This only means the dedication and meticulosity of his work. 

A per Neuroticfish diagrams, you don't have to be a Romanian speaker to assess the quality of the work.

**Comment by Cobra-Bitcoin** [comment]
OK, it seems we have more than enough feedback to go ahead and merge this. Thanks to everyone who checked the translation. Makes me happy to know a much better version of the paper in Romanian exists now.

**Comment by neuro-fishy** [comment]
Thank you @Cobra-Bitcoin for the merge (and the overall professional handling of this Git).

I have a question though. Not a big deal, but the translator name was not updated on the web page ( https://bitcoin.org/en/bitcoin-paper ). Should I make the change and a new pull request for something that small?

**Comment by Komodorpudel** [comment]
> Thank you @Cobra-Bitcoin for the merge (and the overall professional handling of this Git).
> 
> I have a question though. Not a big deal, but the translator name was not updated on the web page ( https://bitcoin.org/en/bitcoin-paper ). Should I make the change and a new pull request for something that small?

Yep, just go ahead with another PR. @Cobra-Bitcoin will merge then.

**Comment by neuro-fishy** [comment]
Thanks @Komodorpudel I will do that then. Many thanks for the support and guidance!

**Pull request merged**
