### PR TITLE
Update screenshots, fees infor for Unstoppable Wallet

### PR DESCRIPTION
**Pull request by Dianaaiym**

### CODE REVIEW

**Comment by Dianaaiym** [comment]
@Cobra-Bitcoin Please accept our pull request, which contains changes to the screenshots of our wallet and some modifications in functionality.

**Comment by crwatkins** [comment]
@Dianaaiym Thanks for the updates to the listing!

* Please update the screenshot files to comply with the requirements  as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)
  * 250 X 350 px 
  * Optimized with `optipng -o7 file.png` 
* Please replace the existing screenshots with files of the same name
   * This provides better repository history
   * This provides consistency with other wallet filenames
* Please provide screenshots with no borders or titles
  * Consistent with the previous screenshots
  * Consistent with the other mobile wallet screenshots on the site

**Comment by crwatkins** [comment]
I concur with the fee score upgrade to `checkgoodfeecontrolfull`.

**Comment by Dianaaiym** [comment]
> @Dianaaiym Thanks for the updates to the listing!
> 
> * Please update the screenshot files to comply with the requirements  as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)
>   
>   * 250 X 350 px
>   * Optimized with `optipng -o7 file.png`
> * Please replace the existing screenshots with files of the same name
>   
>   * This provides better repository history
>   * This provides consistency with other wallet filenames
> * Please provide screenshots with no borders or titles
>   
>   * Consistent with the previous screenshots
>   * Consistent with the other mobile wallet screenshots on the site

Thank you for your response. We have updated the screenshots and kept their names the same.

**Comment by crwatkins** [comment]
Thanks for such quick updates!

LGTM.

**Pull request merged**
