### PR TITLE
Add Blockstream Jade as HWW

### PR DESCRIPTION
**Pull request by bitcoinhelp**

### CODE REVIEW

**Comment by crwatkins** [comment]
Thanks for the submission!   Have you carefully reviewed the [requirements ](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and do you believe that Jade meets them all?   Are there questions on any of them?

**Comment by bitcoinhelp** [comment]
> Thanks for the submission! Have you carefully reviewed the [requirements ](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and do you believe that Jade meets them all? Are there questions on any of them?

Hi Craig, thanks for the quick response! I had looked over the requirements and I do believe Jade meets all of them - and that the necessary text/images were submitted correctly.

Please don't hesitate to reach out if you need any extra info

**Comment by crwatkins** [comment]
I have reviewed the Jade wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design, however because the HSTS preload directive is missing on the website, I cannot at this time recommend it for listing.  I will be glad to recommend Jade for listing once this website issue is resolved.

Note that as a "hardware wallet," only the hardware and firmware components of the device were evaluated.  Wallet software that runs externally to the Jade device was not evaluated in this review.  Sparrow, Electrum, and Blockstream's Green wallet were used during this review, but not evaluated.

One unique feature of the primary operation mode of the Jade device is the reliance on an externally hosted PIN server to enforce PIN security and seed encryption on the device.  While the product is entirely open source, there is no published specification of the PIN protocol that is sufficient to allow a detailed review without reverse engineering the protocol from the source code and no such reviews have been found.

Full QR support is a fairly recent addition to the product and there were numerous scanning issues observed during the review which were reported.

I concur with the scoring in b9beb08.

## Blockstream Jade
### Firmware 0.1.46
### Review Version 2023033101

## Wallets

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was provided by Blockstream at no cost.

**NOTE** Only the hardware/firmware is being evaluated here.  Wallet software running external to the device is not being reviewed.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

  **PASS** Sufficient feedback found without concerning issues
  * Significant discussions on twitter, Reddit, and Bitcointalk
  * Numerous superficial reviews in blogs and YouTube
  * A few in-depth reviews of models with older firmware including
    * [BTC Sessions on YouTube](https://www.youtube.com/watch?v=_U1jsTeqbTw)
    * [Alex Waltz on YouTube](https://www.youtube.com/watch?v=qzQjECidF88)

  **NOTE** The Ledger Donjon team published [Firmware Extraction: Evil-Maid Attacks on Blockstream Jade Hardware Wallet](https://blog.ledger.com/blockstream/) however there are no current listing criteria related to attackers having physical access to the wallet.

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

  **PASS** No indication found

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication found


- No indication that the wallet uses unstable or unsecure libraries

  **PASS** No indication found.

- No indication that changes to the code are not properly tested

  **PASS** No indication.  Significant tests at https://github.com/Blockstream/Jade/blob/master/test_jade.py

- Wallet was publicly announced and released since at least 3 months

  **PASS** Jade was announced and was available in January 2021

- No concerning bug is found when testing the wallet

  **PASS** No concerning bugs have been found

- Provides a bug reporting method on the website and/or in the app

  **PASS** https://help.blockstream.com/

- Website supports HTTPS and 301 redirects HTTP requests

  **PASS** http://blockstream.com redirects to https://blockstream.com

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

  **PASS** https://blockstream.com B rating (because of TLS 1.0 and 1.1 support)

- Website serving or linking to executable code or requiring authentication uses HSTS
  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

  **FAIL** HSTS is enabled with max-age=31536000, but missing preload directive

- The identity of CEOs and/or developers is public

  **PASS** The identities of the principals are well-known https://blockstream.com/about/

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **N/A** Addresses and paths are chosen by wallet software

- Avoid address reuse by using a new change address for each transaction

  **N/A** Addresses and paths are chosen by wallet software

- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS**  Jade uses [anti-exfil protocol](https://blog.blockstream.com/anti-exfil-stopping-key-exfiltration/) with companion apps that support it, but uses RFC 6979 with those that do not

- User has access to private keys for all major components of the wallet

  **PASS** User has access to BIP39 seed during setup

- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

  **N/A** Keys are stored on the device

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

  **PASS** During setup the wallet allows manual copying of the seed phrase and performs a partial verification with the user

  - Restoring wallet from backup is working

  **PASS** Restoring wallet from backup was successful

  - Source code is public and kept up to date under version control system

  **PASS** https://github.com/Blockstream/Jade/

- If user has no access to some of the private keys in a multi-signature wallet:
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet

  **N/A**

- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)

  **PASS** Device requires user confirmation to sign a transaction

  - Protects the seed against unsigned firmware upgrades

  **PASS** Firmware upgrades must be signed

  - Supports importing custom seeds

  **PASS**  Custom seeds were successfully imported

  - Provides source code created for all open components and provides detailed specification for blackbox testing of
    any closed-source secure elements

  **PASS** Fully open source at https://github.com/Blockstream/Jade/

Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

  **N/A**

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

  **FAIL** HSTS is enabled, but not on preload list

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

  **PASS**

  - Provides users with step to print or write their wallet seed on setup

  **PASS** Setup provides a step to write down the wallet seed

  - Uses a strong KDF and key stretching for wallet storage and backups

  **PASS** Uses AES256 for wallet storage and HMAC-SHA256 for PIN stretching

  - On desktop platform:
    - Encrypt the wallet by default

  **N/A**

- For hardware wallets:
  - Prevents downgrading the firmware

  **PASS** Downgrading is allowed, but it is possible to set a version number in the eFuse of the chip such that the bootloader does not allow a downgrade to a lower version.

**Comment by bitcoinhelp** [comment]
> The summary is that the wallet passes on security and overall design, however because the HSTS preload directive is missing on the website, I cannot at this time recommend it for listing. I will be glad to recommend Jade for listing once this website issue is resolved.

Hi Craig - just wanted to note that this has been corrected on the website. Please let us know if you need anything else

**Comment by crwatkins** [comment]
blockstream.com website now has 

```strict-transport-security: max-age=31536000; includeSubDomains; preload```

LGTM.   I recommend Jade for listing.

**Comment by Cobra-Bitcoin** [comment]
LGTM. Will merge later today.

**Pull request merged**
