### PR TITLE
Add LUBANSO X1 to hardware wallets

### PR DESCRIPTION
**Pull request by zzir**
LUBANSO X1, a multi-currency hardware wallet with a bank-grade secure chip, provides security protection through its unique, trusted operating system and anti-attack algorithm engine.

### CODE REVIEW

**Comment by crwatkins** [comment]
Thanks for your submission, @zzir.  I can't find any source code on your GitHub page.  Can you correct the the pointer to the source code in this PR?

**Comment by zzir** [comment]
@crwatkins Thank you for your kind notice. We already corrected it. We have a professional security review team. Our team focus on digital asset security. We will open the source code in the future not now.

**Comment by crwatkins** [comment]
A required criterium for hardware wallets is:

* Provides source code and/or detailed specification for blackbox testing if using a closed-source Secure Element

The community has fairly [strong opinions](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1622) on the value of allowing open peer review of wallets. For hardware wallets either open (public) source code or detailed specifications for blackbox testing are required. The specifications should be sufficiently detailed to allow unaffiliated practitioners to test the device compliance. In the past, these policies have allowed persons to examine and test hardware wallets and disclose the issues that they have found.

Are you providing detailed specifications or should we put this PR on hold until the source code is available?  I recommend the latter since even with detailed specifications it may take much longer, with much more effort, or may not be possible at all to fulfill all the criteria for listing without source code.

**Comment by zzir** [comment]
@crwatkins Thank you for your Information. Considering the current situation, we will request an add until we open source code. You can close this PR.

**Comment by crwatkins** [comment]
@zzir Thanks!  I look forward to your next PR.

**Pull request closed without merging**
