### PR TITLE
Revert prefinal alert notice to prevent people from upgrading

### PR DESCRIPTION
**Pull request by achow101**
@Cobra-Bitcoin This is urgent

We do not want people to upgrade yet because 0.13.1 is almost released. 
 
We can revert this after the release and just before the actual alert is sent.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Done https://github.com/bitcoin-dot-org/bitcoin.org/commit/1d66c5fc8c4054e2ce21ec881e270df01aabceea.

**Comment by MarcoFalke** [comment]
@achow101 I think this can be reverted again, now?

**Comment by achow101** [comment]
Yep. Just need to update the dates. I'll do that in about an hour.

**Comment by achow101** [comment]
See #1401

**Pull request closed without merging**
