### PR TITLE
Update jgarzik email, PGP public key block.

### PR DESCRIPTION
**Pull request by jgarzik**
PGP cross-validation:
http://gtf.org/garzik/bitcoin/psa3-bitpay.txt
http://gtf.org/garzik/bitcoin/psa3-pobox.txt

### CODE REVIEW

**Comment by laanwj** [comment]
ACK, matches the key that I have

**Comment by harding** [comment]
ACK https://github.com/jgarzik/bitcoin.org/commit/19d26b807c63d25860d0310a723c6cb14adae35e.  Verified that http://gtf.org/garzik/bitcoin/psa3-bitpay.txt is signed by the jgarzik-bitpay.asc key currently in the repository and that it lists the key ID of the key being added in this PR.

@jgarzik two questions:

1. Can you clean up the key block being added in this request?  It has a bunch of revoked/expired keys in it:

        phobos:148:~/dev/bitcoin.org$ gpg jgarzik-pobox.asc 
        pub  1024D/03CC8A77 2005-05-27 [revoked]
        uid                            Jeff Garzik <jgarzik@pobox.com>
        sub  2048g/CB9C16DB 2005-05-27 [revoked: 2009-11-07]
        pub  1024D/707FFFD2 2009-11-07 [revoked]
        uid                            Jeff Garzik <jgarzik@pobox.com>
        sub  4096g/68998285 2009-11-07 [revoked: 2011-10-18]
        pub  4096R/01782B2F 2011-10-17 Jeff Garzik <jgarzik@pobox.com>
        sub  4096R/2AA9AC3A 2011-10-17 [expires: 2017-10-15]

2. Do we still need the jgarzik-exmulti.asc file in the repository?  If not, can you also remove it in this PR?

**Comment by jgarzik** [comment]
@harding 

1) It's the standard "gpg --armor --export" output,  higher security to have revoked keys in there, and it's very little data overall.

2) sure

**Comment by harding** [comment]
ACK 704aa21679eae3699e18f0155295a1647be3ada0 -- verified it has the same key I verified above.  @jgarzik thanks for updating!

In the absence of critical feedback, this pull will be merged on Wednesday.

**Comment by saivann** [comment]
Perhaps late, but I confirm that I just verified the chain of trust between previous and new keys.

**Pull request merged**
