### PR TITLE
bitcoin-paper: Add Estonian Translation

### PR DESCRIPTION
**Pull request by liigalihtnebtc**
Estonian translation for bitcoin whitepaper

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Anyone Estonian can verify this?

**Comment by ekukxs** [comment]
I can verify it is an understandable work, though it would need some grammatical work to be done on it. The author of this request has also contacted me in the past, seemingly offering to cooperate, asking me to hand him my project in order for him to "fix it" and publish it. However, since I asked him to specify what he thought had to be fixed, he has not responded. This took place about a week ago.
My translation, however, has gotten feedback from numerous Estonians, which I have used to make it better, and it has already been published on a couple of Estonian websites such as www.faval.eu and www.kryptoraha.ee.
[Bitcoin_Valge_Paber.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5917994/Bitcoin_Valge_Paber.pdf)

**Comment by aivarsomelar** [comment]
verified and seems good

**Comment by ekukxs** [comment]
Needs some work, plenty of grammatical errors as well as numerous mistranslations. The author of thread has also attempted to to steal my project, asking me to hand it to him in order for him to "fix it" and then publish it. After I asked him what he thought needed fixing, he has not responded. This happened about a week ago.

My project, which has gotten feedback from numerous Estonians, which I have used to improve it, and has already been published on a couple of Estonian websites: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3584

**Comment by ekukxs** [comment]
Needs some work, plenty of grammatical errors as well as numerous mistranslations. The author of this request has also attempted to steal my project, asking me to hand it to him in order for him to "fix it" and then publish it. After I asked him what he thought needed fixing, he has not responded. This happened about a week ago.

My project, which has gotten feedback from numerous Estonians, which I have used to improve it, and has already been published on a couple of Estonian websites: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3584

**Comment by ekukxs** [comment]
Needs some work, plenty of grammatical errors as well as odd translations. The author of this request has also contacted me in the past, seemingly offering to cooperate, asking me to hand him my project in order for him to "fix it" and then publish it. However, since I've asked him what he thought needed fixing and offered to cooperate (instead of just handing over my project to him), he has not responded. Looks a lot like **attempted theft** to me. This happened about a week ago.

My project, which has gotten feedback from numerous Estonians, which I have used to improve it, and has already been published on a couple of Estonian websites: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3584

**Comment by liigalihtnebtc** [comment]
Well, that escalated quickly. yes i did contact you but decided to upload my work anyway since I spent so much time on it and didn't just want to throw it out the window because someone was doing same work on same time. 
Attempted theft? How to steal something which is open-source?

Anyway, I don't know how to go on from here. Need some tie-breaker or something :D

Peace! I'm only here to support Bitcoin.

**Comment by ekukxs** [comment]
I'm afraid things tend to escalate quickly when you act maliciously. There is no explanation as to why you stated that my project had "grammatical errors to be found in it" (which it almost certainly does not, **and yours does**), then asked me to hand my project over to you in order for you ti _fix it_, and then simply stopped emailing me after I asked to cooperate with you instead of forfeiting my project to you.
It is open source but it is clear that you have chosen the path of solo glory over cooperation, even going to the length of giving false feedback about my project in hopes of sartling me into handing it over to you so that you could "fix it". You had every chance to respond to my email and cooperate with me, it has been **7 days** since you first emailed me and I responded to you.

**Comment by liigalihtnebtc** [comment]
Sorry, was busy and didn't check that e-mail.

**Pull request closed without merging**
