### PR TITLE
Stop calling Passport wallet open source

### PR DESCRIPTION
**Pull request by ai-oleynikov**
Parts of Passport's firmware are licensed under MCD-ST Liberty SW License Agreement V2:
- https://github.com/Foundation-Devices/passport2/blob/3d570fba50b40d65a04087127138426c2570e5a0/ports/stm32/usbd_conf.c#L17
- https://github.com/Foundation-Devices/passport2/blob/3d570fba50b40d65a04087127138426c2570e5a0/ports/stm32/usbhost/Core/Inc/usbh_def.h#L13
- https://github.com/Foundation-Devices/passport2/blob/3d570fba50b40d65a04087127138426c2570e5a0/ports/stm32/usbhost/Class/MSC/Src/usbh_msc_scsi.c#L13
- https://github.com/Foundation-Devices/passport2/blob/3d570fba50b40d65a04087127138426c2570e5a0/ports/stm32/usbd_cdc_interface.h#L19
- etc.

MCD-ST Liberty SW License Agreement V2 is not an open source license at least due to the following terms it contains:

> 4.	This software or any part thereof, including modifications and/or derivative works of this software, must be used and execute solely and exclusively on or in combination with a microcontroller or microprocessor device manufactured by or for STMicroelectronics.
> 5.	No use, reproduction or redistribution of this software partially or totally may be done in any manner that would subject this software to any Open Source Terms. “Open Source Terms” shall mean any open source license which requires as part of distribution of software that the source code of such software is distributed therewith or otherwise made available, or open source license that substantially complies with the Open Source definition specified at www.opensource.org and any other comparable open source license such as for example GNU General Public License (GPL), Eclipse Public License (EPL), Apache Software License, BSD license or MIT license.

https://web.archive.org/web/20221012024530/https://www.st.com/software_license_agreement_liberty_v2

So we shouldn't call Passport wallet open source.

### CODE REVIEW

**Review by AugustoResende — APPROVED** [review]

**Comment by crwatkins** [comment]
I agree in principal.  The criteria for listing include “Source code is public” and that has been the recent emphasis.  @sethforprivacy Do you have a recommended alternative description for Passport here?

**Comment by sethforprivacy** [comment]
> I agree in principal. The criteria for listing include “Source code is public” and that has been the recent emphasis. @sethforprivacy Do you have a recommended alternative description for Passport here?

Thanks for mentioning me so I can chime in!

First off, we did a quick investigation and noticed that the only affected code relates to USB hardware abstraction layer that we don't use (Passport does not have a functional data circuit for USB at all, only power). We're working now on seeing if we can simply remove all of the code that has this unique license on it completely as it's just a default import from MicroPython's HAL. I can update here as soon as that is done.

Second, we noticed that due to this code currently being in our repo, our list of licenses was inaccurate, which was a mistake on our part. Good catch on that, @ai-oleynikov! We'll defer changing the licenses listed until we can get the code removed entirely from the repo (once we ensure that it doesn't break anything else due to dependencies etc.).

Third, I still stand behind the phrase "Passport is fully open source" as it meets every criteria for open source _where possible._ Every hardware wallet for Bitcoin must unfortunately use restrictively licensed code in the hardware abstraction layer/firmware blobs for the MCU, as all MCUs are closed-source hardware and carry restrictive licenses. These restrictive licenses are inherited from the MicroPython project itself for the hardware abstraction layer as seen [here](https://github.com/micropython/micropython/blob/master/ports/stm32/usbd_conf.c).

Outside of these HAL sections, Passport's firmware is 100% open source by all definitions and will always remain so.

Passport also meets the strict open source hardware definitions and licensing requirements for [CERN Open Hardware Licence Version 2](https://opensource.org/license/cern-ohl-s/) as you can see in this repo: https://github.com/Foundation-Devices/passport2-hardware/tree/main

You can also see that the CERN open source hardware license explicitly allows these non-open blobs as a necessity, as almost all hardware today has proprietary blobs/drivers/HAL:

image

[Source](https://ohwr.org/project/cernohl/wikis/faq#q-are-non-open-binary-software-blobs-allowed-to-run-in-hardware-licensed-under-cern-ohl)

Note that if this criteria around restrictive MCU code is taken seriously, it means that *no Bitcoin hardware wallet is open source* as they all use restrictive MCUs with restrictive licenses. i.e., you can see the same for Trezor [here](https://github.com/trezor/trezor-firmware/blob/9b78dd107bf7b58cf57bede897d441beff37b917/core/embed/trezorhal/stm32f4/usbd_conf.c#L4).

**Comment by sethforprivacy** [comment]
An update here, we did a review and all of the files that carried the non-free license were not used at all in Passport's firmware and have been removed:

https://github.com/Foundation-Devices/passport2/pull/402

AFAICT there is no reason for this pull request to be merged, as Passport meets even this extremely strict definition of open source.

**Review by AugustoResende — CHANGES_REQUESTED** [review]
I don't approve it anymore.

**Comment by crwatkins** [comment]
@sethforprivacy Thanks for the update!   

@ai-oleynikov  Thanks for opening this issue.  It seems this can be closed now.   Do you agree?

**Comment by ai-oleynikov** [comment]
Thanks @sethforprivacy for handling this so professionally. Thanks everybody. I'm closing the PR now.

**Pull request closed without merging**
