### PR TITLE
Update choose-your-wallet.html

### PR DESCRIPTION
**Pull request by btcmuyuu**
Hive is dead, as per its founder: https://www.reddit.com/r/Bitcoin/comments/3llr1a/hive_wallet_no_longer_being_developedtime_to_bail/cv7fmjy

hivewallet :
It wasn't the "web guy" you spoke to, it was me, Wendell, the founder/creator.
I apologize for the issues people have been having with Hive. You're right, I should have more clearly announced the glacial (not entirely frozen, see below) development, but we can't actually reach all of our users, and we assume that everyone knows our GitHub URL (github.com/hivewallet), which shows pretty transparently what is or is not going on.
Hive Web and Hive iOS are BIP32/BIP39 compatible, so you should be able to directly use your passphrase in any other wallet supporting that standard. This includes the excellent Bread Wallet, and I believe Mycelium as well.
It would be nice if some new maintainers for one or more of the platforms appeared, because with the patches that Wei created recently ( live @ http://hive-js.herokuapp.com ), it actually does work fine. However, these changes have not been rolled into the iOS version, and no one over here who might touch it uses OS X for development anymore.
We'll keep our servers on, but the wallets are basically unsupported. Again, because we respect your privacy and collect no data other than raw wallet numbers, we can't simply reach out to all of our users by email or some other means. Please help to spread the word by retweeting this:
https://twitter.com/hivewallet/status/645402186260721664

### CODE REVIEW

**Comment by saivann** [comment]
Thanks for submitting this pull request.

Can you remove the associated translations from `_translations/en.yml` and icons and screenshots from `img/screenshots` and `img/wallets`?

Otherwise LGTM.

**Comment by btcmuyuu** [comment]
Ok, I'll do that now.

**Comment by saivann** [comment]
@btcmuyuu Your branch seemed correct at a first glance before you closed the pull request. Do you need some help with anything?

**Comment by btcmuyuu** [comment]
I was using someone else's computer and posted from his account apparently. Had a bit of a 'mare trying to take the commit back, huh. All because of trying to hurry that fix and github not deleting binaries from the web interface :) it that works feel free to merge it.

Regards.

**Comment by saivann** [comment]
@btcmuyuu No worry :) Thanks!

For the record, I confirm that Hive Web currently does not work, and Hive for iOS was previously dropped in https://github.com/bitcoin-dot-org/bitcoin.org/issues/1040 for the same reason (ping @w-hive in case you want to leave a comment).

In the absence of critical feedback, this pull request will be merged on September 22th.

**Comment by crwatkins** [comment]
I support removing the listing for the Hive wallet based on the above reference, PR #1040, and other recent discussions.  I look forward to future development on Hive and re-listing in the future.

**Comment by w-hive** [comment]
+1

**Pull request merged**
