### PR TITLE
Update ja.yml

### PR DESCRIPTION
**Pull request by sjntn**
Improve translation in ja #890

### CODE REVIEW

**Comment by coderwill** [comment]
@sjntn Hello, thanks for contributing! This is just a quick note to let you know that we're double-checking the strings.

**Comment by sjntn** [comment]
@coderwill ok, thanks!

**Comment by coderwill** [comment]
@sjntn - Hi Shoya! I hope you had a nice weekend. Reaching back out on this translation - [are you by chance a member of the Japanese translation team for Bitcoin.org on Transifex](https://www.transifex.com/organization/bitcoinorg/team/10848/members/ja/)? I did a quick check and didn't see your username on there.

The reason I ask is because we originate all translations out of there, and quite a bit of the process is automated at this point. This translation update you've provided seems to be coming together very well, but it's a bit out of sync with our Japanese translation on there. If you are already on Transifex just let me know your username. We can make you a reviewer so that you have access to approve and correct the existing translations like you've done in this PR.

I'd also be more than happy to migrate these translations you've already done into there.

If you have any specific questions about how Transifex works or you'd like to sync up so I can help you on anything, feel free to IM me on Google Hangouts, my ID is: will@trek.io

Thanks again for your help!

**Comment by sjntn** [comment]
@coderwill Thanks for great description! I just joined Transflex. It's my username; sjntn.

**Comment by coderwill** [comment]
@harding We can close this PR.

**Pull request closed without merging**
