### PR TITLE
Satoshi Nakamoto PGP Key

### PR DESCRIPTION
**Pull request by PartTimeLegend**
Should be retained for public record. They may one day return, and for
prosperity we must remember them.

### CODE REVIEW

**Comment by luke-jr** [comment]
@theymos Can you elaborate on how you know this is Satoshi's key? Are you the only one who can vouch for it?

**Comment by theymos** [comment]
@luke-jr He [posted a link to it on the forum](https://bitcointalk.org/index.php?topic=458.msg5772#msg5772). That link doesn't work anymore, but I downloaded it when he posted it. Presumably other people around at that time could also verify.

**Comment by carnesen** [comment]
FWIW The key in this PR is the same as [the one archived by the Wayback Machine](https://web.archive.org/web/20110228054007/http://www.bitcoin.org/Satoshi_Nakamoto.asc)

**Comment by ABISprotocol** [comment]
His fingerprint can also be [found here](https://github.com/pmlaw/The-Bitcoin-Foundation-Legal-Repo/blob/master/Bylaws/Bylaws_of_The_Bitcoin_Foundation.md) where it appears to have been put there by @petertodd ~ https://github.com/pmlaw/The-Bitcoin-Foundation-Legal-Repo/commit/fb70771a9927e04ebe5ae33c46ba6589a9703e40#diff-d0129f70bb1534be58edb5b8e567d8f0

**Comment by harding** [comment]
@ABISprotocol Peter just extended the key fingerprint to its full 20 bytes.  The shorter key ID was in the [original commit](https://github.com/pmlaw/The-Bitcoin-Foundation-Legal-Repo/commit/6097f0e9bd64b3c58ba2d157e6440c695699864e) for that repository.

**Review by Bhouben — APPROVED** [review]
I like it!

**Review by Bhouben — APPROVED** [review]
satoshinakamoto.asc

**Pull request closed without merging**
