### PR TITLE
Adds exchange in Chile, Colombia and Peru

### PR DESCRIPTION
**Pull request by agustinf**
This PR adds SurBTC.com, an exchange with bank accounts in Chile, Colombia and Peru, to the list of exchanges. 
The flags for Chile and Peru where missing, so this PR adds those too.

image

### CODE REVIEW

**Comment by Mirobit** [comment]
utACK

**Comment by wbnns** [comment]
Unless others object, this will be merged on Sunday, August 6th.

**Comment by wbnns** [comment]
@agustinf Can you please fix the merge conflict in `_templates/exchanges.html`? Once you've done so, we can merge this. 👍

**Comment by agustinf** [comment]
@wbnns done! 👍

**Comment by wbnns** [comment]
@agustinf Thanks!

**Pull request merged**
