### PR TITLE
Add Wasabi Wallet

### PR DESCRIPTION
**Pull request by nopara73**
This is a working in progress pull request to add Wasabi Wallet to Bitcoin.org website.  

Wasabi Wallet is an open-source, cross-platform, non-custodial, privacy focused Bitcoin wallet for Desktop. Its main features are built-in Tor, CoinJoin and coin control.

# ToDo

See comment: https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-449769291

# Concerns

- While the development of Wasabi Wallet started in [April of 2016](https://api.github.com/repos/zkSNACKs/WalletWasabi) under the name of HiddenWallet, Wasabi Wallet has only been released in [August 1, 2018](https://github.com/zkSNACKs/WalletWasabi/releases/tag/0.7.2), which raises the question if the product should mature before making it to the site.

# Help With Translation

Consider helping the translation work: https://github.com/zkSNACKs/WalletWasabi/issues/963

# Feedback

If you have any feedback as to what should be improved on the wallet in order to make it to the site I am all ears of.

# Screenshot

image

# References

- Tor website: http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion
- Clearnet website: https://wasabiwallet.io/
- GitHub (Source Code): https://github.com/zkSNACKs/WalletWasabi
- Technical Overview and Future Plans: https://github.com/zkSNACKs/Meta

### CODE REVIEW

**Comment by crwatkins** [comment]
@nopara73 Thanks for the submission!  I think this may be the first WIP community supported wallet listing PR.  One note on the English wallet description:  Most of the other wallet descriptions begin with a full sentence usually including the verb "is", while your description begins with a phrase describing the wallet.  I'm not sure that the inconsistency would currently be obvious, or even noticeable, but if we use the descriptions in other places in the future, it would good to maintain the consistency.

**Comment by nopara73** [comment]
I started to create the wallet folder, 3 more things left to do:

- [ ] Add Bulgarian translation.
- [ ] Add screenshot.
- [ ] Think about `level` and `validation`.

For context:
```
level:
  description: |
    The wallet's overall security level.
      1 - full nodes
      2 - SPV using random servers (e.g. P2P SPV, Electrum servers, etc...)
      3 - Hybrid & multisig wallets
      4 - Web wallets
```

```
validation:
  description: How much assurance the user has that their bitcoins are real
  type: string
  enum:
    - checkgoodvalidationfullnode
    - checkgoodvalidationfullnoderequired
    - checkneutralvalidationvariable
    - checkpassvalidationspvp2p
    - checkpassvalidationspvservers
    - checkpassvalidationservers
    - checkfailvalidationcentralized
```

For now I set the `level` to `3` and `validation` to `checkfailvalidationcentralized`. This could either stay like this or I can create new categories.  
Wasabi's validation is as follows:

1. First a centralized server creates an index. This index contains block hash and filter pairs.  
2. Clients download this index over Tor.  
3. Client from the index figures out which blocks it is interested in (there are false positives.)  
4. Client asks random nodes for blocks: one block - one node, over clearnet.  
5. Client verifies the downloaded block's hash matches to the already known hash (downloaded from the server in step 2.) and validates the block.

While the "Hybrid" may be a sufficient description for the `level`, if it means something general and not something specific, but the `validation` is just not right. I put centralized there, but it is more distributed, since both the central server and random node validates blocks. The traditional centralized validation would suggest that the central server can trick the clients however it wants, but in this case, the central server must make sure the client downloads blocks from him and only him in order to trick the client. So three options arise here:

1. Leave everything as it is: level 3, validation: centralized.
2. Leave level as it is, add new category to validation.
3. Add new category to level and validation.

Thoughts?

**Comment by nopara73** [comment]
@crwatkins I finished this PR. The question regarding improving validation categories still remain, but that can be a separate PR, too.

**Comment by crwatkins** [comment]
@nopara73 Thanks.  I'll review the scoring shortly after I've had a little more time with the wallet.  In the meantime, you will want to update the `screenshot` value in wasabi.md.  Have you already reviewed all of the [criteria](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) for wallet listing and believe that wasabi meets them?

**Comment by nopara73** [comment]
>  In the meantime, you will want to update the screenshot value in wasabi.md.

Thanks.

> Have you already reviewed all of the criteria for wallet listing and believe that wasabi meets them?

Yes, would you like me to explicitly detail it here?

**Comment by crwatkins** [comment]
@nopara73 Thanks!  No need at this time.

**Comment by crwatkins** [comment]
Since Wasabi 1.0 was released on 31 October, it will be eligible for listing on 31 January 2019.  We can start the review process in the meantime.

**Comment by nopara73** [comment]
# 1. Feedback

> Sufficient users and/or developers feedback can be found without concerning issues, or independent security audit(s) is available

## Users

Me and some other developers address user feedbacks/questions/issues/etc.. on [/r/WasabiWallet](https://old.reddit.com/r/WasabiWallet/). We also have Telegram group and other content created by our users. We recently started to collect them in a place we call [the Dojo](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Community/Dojo.md).

## Developers

Comparing to all other desktop wallets on the site, [our GitHub page](https://github.com/zkSNACKs/WalletWasabi/) seems to be in a better shape/more active if we look a the issues, pull requests, number of contributors, stars, number of commits, etc.. than arcbit's, bither's greenaddress's and msigna's and it may be somewhat even to Armory's.

# 2. Issues

> No indication that users have been harmed considerably by any issue in relation to the wallet
> No indication that security issues have been concealed, ignored, or not addressed correctly in order to prevent new or similar issues from happening in the future
> No indication that the wallet uses unstable or unsecure libraries
> No indication that changes to the code are not properly tested
> No concerning bug is found when testing the wallet

No.

# 3. Maturity

> Wallet was publicly announced and released since at least 3 months

By 31 January 2019, established here: https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-450372036 by @crwatkins.

## 4. Website

> Website supports HTTPS and 301 redirects HTTP requests

Yes: http://wasabiwallet.io

(Well, except the onion mirror, but onions doesn't use/need HTTPS anyway: http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion)

> SSL certificate passes Qualys SSL Labs SSL test

https://www.ssllabs.com/ssltest/analyze.html?d=wasabiwallet.io

image

> Website serving executable code or requiring authentication uses HSTS with a max-age of at least 180 days

The website is pure html+css, it has no javascript.

# 5. Company

> The identity of CEOs and/or developers is public

Yes: https://zksnacks.com/#contact

# 6. Best Practices

> Avoid address reuse by displaying a new receiving address for each transaction in the wallet UI

Yes, when money arrives to an address it even disappears from the list.

> Avoid address reuse by using a new change address for each transaction

Yes.

> Uses deterministic ECDSA nonces (RFC 6979)

I guess so, the NBitcoin library hides this from me. @lontivero @NicolasDorier can you save me from half an hour of reading it up?

> User has access to private keys

Yes.

> If private keys or encryption keys are stored online: ...
> If user has exclusive access over its private keys: ...
> If user has no access to some of the private keys in a multi-signature wallet: ...
> If hardware wallet: ...

No.

# 7. Optional Criterias

> Received independent security audit(s)

No.

> Does not show "received from" Bitcoin addresses in the UI

It doesn't.

> Provides a bug reporting policy on the website

From the website:

image

From the software:

image

> Website serving executable code or requiring authentication is included in the HSTS preload list

Again, there's no script on the website.

> Supports HD wallets (BIP32)

Yes.

> Provides users with step to print or write their wallet seed on setup

Yes.

> Uses a strong KDF and key stretching for wallet storage and backups

Most likely, but NBitcoin also hides it from me. @NicolasDorier @lontivero ?

> Encrypt the wallet by default

Yes.

**Comment by lontivero** [comment]
>>Uses deterministic ECDSA nonces (RFC 6979)

> I guess so, the NBitcoin library hides this from me. @lontivero @NicolasDorier can you save me from half an hour of reading it up?

Yes, it does. NBitcoin uses deterministic nonces by default. https://github.com/Metacosa/nbitcoin/blob/master/NBitcoin/Crypto/ECKey.cs#L71

>> Uses a strong KDF and key stretching for wallet storage and backups.

>  Most likely, but NBitcoin also hides it from me. @NicolasDorier @lontivero ?

Wallet storage is protected by the algorithm described in bip38 which uses scrypt as KDF.

**Comment by crwatkins** [comment]
Hey @nopara73, thanks for the notes on the criteria list.  When I write a review on a wallet, I usually try to review all the criteria together and then publish all of the recommendations together.  I do this because some developers grow tired of a (sometimes seemingly) long list of exceptions, particularly when there are a few that they are willing to remedy, but in the end aren't able to remedy them all.  Some prefer the entire list all at once.  However, since we're all working on this PR as a community and a WIP, I'll let you know of one administrative details I just noticed in your notes:  The HSTS criteria applies to sites that offer executable code for download.  The reasoning here is obvious: We should make it as hard as easily possible to hijack or redirect the downloads of the wallet.

In any case, it's just a good idea to have HSTS on wasabiwallet.io as well as have it in the preload list.

**Comment by nopara73** [comment]
@crwatkins Thanks.

I'll look up HSTS and most likely add it: https://github.com/zkSNACKs/WalletWasabi/issues/1026

**Comment by nopara73** [comment]
HSTS is added.

**Comment by Cobra-Bitcoin** [comment]
Really love this wallet. Would be great if we could promote it to privacy conscious users. The more people using this type of wallet, the better off we'll all be from creepy blockchain analysis companies.

I hope it gets through the review process.

**Comment by crwatkins** [comment]
> HSTS is added.

You may want to consider adding preload also to that HSTS.

**Comment by nopara73** [comment]
@crwatkins Done!

**Comment by crwatkins** [comment]
I've [previously](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2752#issuecomment-447039715) expressed concern about wallets that only support bech32 addresses for both sending and receiving.  We don't currently have any criteria that specifically relate to address format, however I've always assumed an unwritten generic "interoperability with other wallets" criteria.  Since Wasabi supports sending to legacy addresses, I'm less concerned that it only allows receiving to bech32 addresses.

Since we have no specific criteria related to this, I would be interested in hearing from the community any concerns related to only receiving to bech32 addresses.

As an aside, I think in the future we may want to somehow have separate categories or designation/scoring for beginner vs. advanced wallet users.  It would mitigate a number of concerns we have encountered recently worrying that it would be a disservice to novice users to recommend wallets that are clearly too complex for them to use, while simultaneously being excited about the advanced features of the wallet.  In the future, I plan to open an issue/PR to discuss this (sooner if this happens to generate enough discussion off topic to this PR as I certainly don't expect this listing to depend on it).

**Comment by theymos** [comment]
@crwatkins I think that best practice now would be to use P2SH-wrapped SegWit addresses for receiving but support sending to all address types. [Bech32 adoption](https://en.bitcoin.it/wiki/Bech32_adoption) is still not perfect.

I don't think that it's a deal-breaker, though.

**Comment by Cobra-Bitcoin** [comment]
@crwatkins Really agree on separate categories for beginner friendly vs. advanced wallets. Not sure what's happening with the planned phase two redesign of the wallets page to improve UX, but that should be definitely something we think about if we ever go ahead with the redesign.

I think as the wallets page gets more bloated, we'll need to have better filtering and separation anyway. We'll eventually need to differentiate between Lightning supporting wallets too.

**Comment by harding** [comment]
> Since Wasabi supports sending to legacy addresses, I'm less concerned that it only allows receiving to bech32 addresses.

I share this opinion.  If users are having difficulty getting funds into a wallet, they can nag their devs or switch to a different wallet.  It's the reverse problem---difficulty getting money out of a wallet---that can actually harm users.  I suggest any new criteria for wallets be based only on the type of addresses they can spend to.  Since Wasabi can spend to all commonly-used address types, it would pass under any such sensible criteria.

**Comment by crwatkins** [comment]
I would like to discuss the privacy disclosure scoring which is currently (1113c4c) proposed as

```
 privacydisclosure: "checkpassprivacydisclosurefullnode"
```

which in English is described as
```
checkpassprivacydisclosurefullnode: "Avoids disclosing information"
```

My understanding is that Wasabi, through the use of BIP157, downloads blocks (with false positives) over the clear P2P network and thus would be more accurately described by:
```
checkfailprivacydisclosurespv: "Discloses limited information to peers"
```
(Remember that our labels are never actually rendered on the site, so we should concentrate on the rendered text and ingore the words in the label.)

While I believe that the Wasabi disclosure is significantly less severe than SPV wallets with the same scoring, we currently don't have that level of granularity in the scoring.  Until we adjust our privacy scorings (a matter for a separate discussion/PR) I believe this should be scored.

```
 privacydisclosure: "checkfailprivacydisclosurespv"
```
Thoughts?

**Comment by NicolasDorier** [comment]
@crwatkins afaik, wasabi does not use BIP157 on the network. It embed a block filters inside the install package of wasabi wallet, and then just download the whole blocks from the network from here.

**Comment by nopara73** [comment]
> Someone monitoring which blocks are downloaded by a particular can look for transactions in those blocks that are connected to each other and make the assumption (with a reasonable probability of being correct) that those transactions belong to that wallet.

For that you must set up a bunch of fake nodes and make sure you hijack all the Bitcoin nodes the client connects to, and you must keep this up not only for a few minutes or hours, but for months or years.  

This debate is a bit like cryptography vs pure math. Sure it is theoretically possible to brute force SHA-256, but it is extremely unlikely.

**Comment by harding** [comment]
@nopara73 

> For that you must set up a bunch of fake nodes and make sure you hijack all the Bitcoin nodes the client connects to, and you must keep this up not only for a few minutes or hours, but for months or years.

Or your ISP could just eavesdrop on your connection and see what blocks you download, since according to your [notes](https://github.com/zkSNACKs/Meta) the connection is currently in the clear:

> After Wasabi receives the filters from the backend, it can download the required blocks (there are false positives, too) one block from one peer. This does not currently happen over Tor since the NBitcoin library we use to do the job does not support Tor yet.

Even if Tor is in use, there are multiple attacks possible.  Someone who controls the list of nodes Wasabi connects to can direct each user to a different set of nodes and so use that to track what blocks they request.  Or an ISP can use size differences in blocks requested over Tor as a sidechannel for determining which blocks the user requested. (Ditto for time differences---if your ISP knows a new block was just produced and something that looks like Wasabi+Tor requests and receives a binary blob about the size of that block, the ISP can guess that the wallet has tx in that block.) Or maybe Wasabi will have a bug that allows specific clients to be fingerprinted.  Tor's encryption is not quantum-resistant, so people could log traffic today and decrypt it in a future where QC is available.  Etc....

Additionally, one doesn't have to passively wait for a BIP157/158 client to request a block---one can encourage it to do so by sending dust spam (tiny-value transactions) to addresses believed to be controlled by the wallet.  The BIP158 filter doesn't include any information about the size of the outputs, so the wallet is forced to download any outputs paying it even if it wants to ignore penny-sized attacks.

By comparison, a full node downloads every block exactly once whether or not that block has a transaction in it, which means there is no way for the transaction retrieval mechanism to leak information about the wallet's addresses.  That's the information-theoretic perfect privacy the current fullnode score is meant to apply to.

All said, BIP157/158 is still much better than BIP37 which basically hands out information not just about your used addresses but also your future addresses.  That's why I support different categories for BIP37 versus BIP157/158, although both should still be shown as inferior to full node transaction scanning privacy.

**Comment by nopara73** [comment]
@NicolasDorier @lontivero What do we use on Linux and Mac for secure random source in `new Key()`? @crwatkins asked me in a PM.

**Comment by lontivero** [comment]
dotnet abstracts the details and provides us an uniform interface, the [System.Security.Cryptography.RandomNumberGenerator](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator). NBitcoin allows us to add additional entropy to re returned number, i think that's because @NicolasDorier didn't trust on a closed source library, after all for Windows at least it relies on the proprietary windows library.

**Comment by harding** [comment]
@nopara73 I wonder if I'm not being clear enough about the simple form of the attack, so here's an extended description.

Alice uses Wasabi.  Mallory is Alice's ISP, providing home Internet service.  Alice creates a new wallet, generates a new address, and uses an exchange to send some bitcoins to that address.  The transaction containing that payment is mined into block 123.

Alice's Wasabi wallet receives the filter for block 123, sees that the block might contain a transaction interesting to the wallet, and downloads the block.  Since the request is over the public (unencrypted) Internet, Mallory logs block 123 as being interesting to Alice.

Later Alice participates in a coinjoin that gets mined in block 456.  Again, Alice downloads block 456 and Mallory logs that block.

Even later Alice spends some of her money in a transaction that gets mined in block 789.  Again, Alice downloads that block and Mallory logs it.

Now Mallory wants to attempt to build a profile of Alice.  Mallory uses the block chain to look for connections between the transactions in blocks 123, 456, and 789---and notices that there's path from an output received in 123 to inputs and outputs in 456 to inputs and outputs in 789.  This is highly suggestive that Alice was a party to all those transactions, despite there being a coinjoin involved.

This privacy leak doesn't require access to a single node, nor any fancy equipment.  It only requires being an ISP, a tcpdump equivalent, and some block chain analysis.  If you want, you can test out the connection monitoring part on your laptop right now using Wireshark (which has some nice Bitcoin dissectors built in).

**Comment by nopara73** [comment]
@harding You forgot the false positives, but anyway, the attack requires the specific ISP of the user and any Blockchain analysis company to collude in a most likely unlawful way in most countries. If a user's threat model includes protection against such a high-end conspiracy, then chances are the user already uses Whonix/Tails or other default traffic torifiers.

**Comment by harding** [comment]
@nopara73 in my country, government agencies [routinely](https://www.nytimes.com/2015/08/16/us/politics/att-helped-nsa-spy-on-an-array-of-internet-traffic.html) work with ISPs to spy on their users (and, of course, I'm not proud of that).  I think it's the same for a lot of countries.

The point here is that downloading specific blocks has a very real potential for leaking information that's not a risk in clients that download all blocks, and so it's appropriate that Bitcoin.org score these two operating modes differently.  For that reason, I agree with @crwatkins that `checkpassprivacydisclosurefullnode: "Avoids disclosing information"` is not the right score for Wasabi.

I am happy, of course, to support a new score that better reflects the advantages of targeted-block downloads used by BIP157/158 clients (and Wasabi's own current version of that).

**Comment by nopara73** [comment]
@harding By that logic Bitcoin Core discloses even more information to your ISP by simply broadcasting transactions over the clearnet.

**Comment by harding** [comment]
@nopara73 

> Bitcoin Core discloses even more specific sensitive information to your ISP by simply broadcasting transactions over the clearnet

My node relayed 6 GB of data in the last 24 hours using both clearnet and Tor (which Bitcoin Core will use automatically if it's available on the computer---it'll even automatically setup an ephemeral hidden service if you've enabled Tor cookie authentication).  Buried in those over 300,000 unique transactions may or may not have been transactions originating from one or more of the wallets on my intranet, including my personal hot and watching-only wallets.  How does an attacker separate my potential specific transactions from all the others I merely relayed?

> I don't think you have any doubt in your mind [...]

I feel like you're starting to take this discussion personally.  That wasn't my intent.  I'm a huge fan of what you're doing with Wasabi and I really would like to see it listed here and on other sites, so I'll back off and try to stay out of further discussion on this issue.  Thank you and @lontivero for all the work you've done to help improve Bitcoin privacy.

**Comment by nopara73** [comment]
> How does an attacker separate my potential specific transactions from all the others I merely relayed?

Relayed transactions must first arrive to you. If it never arrives, only leaves your node, that's the one.

> I feel like you're starting to take this discussion personally.

I agree, my apologies, I will try to keep the conversation on point.

**Comment by crwatkins** [comment]
@lontivero @NicolasDorier 
> dotnet abstracts the details and provides us an uniform interface, the System.Security.Cryptography.RandomNumberGenerator. 

Please forgive my dotnet ignorance.   Does dotnet provide the entropy modules for Linux and Mac?  I'm trying to understand the source of entropy on all supported platforms.

**Comment by lontivero** [comment]
The dotnet framework provides an uniform cross-platform interface as I said that abstracts the internal details, however we can follow the code ans see the tree different implementations:

* [RandomNumberGeneratorImplementation.OSX.cs](https://github.com/dotnet/corefx/blob/release/2.2/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/RandomNumberGeneratorImplementation.OSX.cs)
* [RandomNumberGeneratorImplementation.Unix.cs](https://github.com/dotnet/corefx/blob/release/2.2/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/RandomNumberGeneratorImplementation.Unix.cs)
* [RandomNumberGeneratorImplementation.Windows.cs](https://github.com/dotnet/corefx/blob/release/2.2/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/RandomNumberGeneratorImplementation.Windows.cs). It seems for windows it uses bcrypt as a final step (just a curiosity)

Digging a bit more we can find the the code that calls the native functions:
* **OSX** [System.Security.Cryptography.Native.Apple/Interop.Random.cs](https://github.com/dotnet/corefx/blob/release/2.2/src/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.Random.cs) As you see it finally calls a native function defined [System.Security.Cryptography.Native.Apple/pal_random.c](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_random.c) that calls the OSX function `CCRandomGenerateBytes`. In other words it trusts on the operating system PRNG.

* **Linux** [System.Security.Cryptography.Native/Interop.RAND.cs](https://github.com/dotnet/corefx/blob/release/2.2/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.RAND.cs). I calls the a native function defined [here](https://github.com/dotnet/corefx/blob/29e580bb69bbd0bc857e28bbc905ede6c8e41d3b/src/Native/Unix/System.Security.Cryptography.Native/openssl.cpp#L1175) and I stop here because the file header says:
> // Enable calling OpenSSL functions through shims to enable support for
// different versioned so files naming and different configuration options
// on various Linux distributions.

**Comment by crwatkins** [comment]
@lontivero Thanks for your notes on your random number sources.  I quickly reviewed them to assist in verifying our criteria
```
No indication that the wallet uses unstable or insecure libraries
```
but did not perform any type of security audit on their generation.

**Comment by crwatkins** [comment]
I have reviewed the Wasabi wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the device was released less than three months ago, I cannot recommend it for listing at this time.  If an outstanding [bug](https://github.com/zkSNACKs/WalletWasabi/issues/1104) found during the review is fixed, I can recommend it for listing on 31 January 2019.

Note that Wasabi wallet only receives to bech32 addresses.  We don't currently have any criteria that specifically relate to address format, however I've always assumed an unwritten generic "interoperability with other wallets" criteria. Since Wasabi supports sending to legacy addresses, I'm less concerned that it only allows receiving to bech32 addresses.

Per [previous comments](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-453831024) I believe that the scoring in 1113c4c should be updated to

```
privacy: "checkpassprivacybasic"
privacydisclosure: "checkfailprivacydisclosurespv"
```

I would support creating finer grained privacy scoring in the future, but I would be happy to list this wallet sooner with this score unless the developers would prefer to wait.

In addition, I think there was some confusion with the `transparency` score being

```
transparency: "checkgoodtransparencydeterministic"
```

I believe it should be changed to

```
transparency: "checkpasstransparencyopensource"
```
since Wasabi does not currently support deterministic builds.  With those changes to 1113c4c, I concur with the scoring.


## Wasabi Wallet
### Version 1.1.0
### Review Version 2019012201


The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

**PASS** There is a fairly active user community https://www.reddit.com/r/WasabiWallet/ and developer community https://github.com/zkSNACKs/WalletWasabi/ . User support is done on both forums.  User discussion at https://www.reddit.com/r/Bitcoin/comments/9sziy5/privacy_wasabi_wallet_10_is_finally_released/ .

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

**PASS** No indication

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

**PASS** No indication


- No indication that the wallet uses unstable or unsecure libraries

**PASS** No indication.  Uses NBitcoin.  It is [claimed](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-454482200) that NBitcoin obtains entropy from the standard OS specific entropy sources.

- No indication that changes to the code are not properly tested

**PASS** Little indication; tests at https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Tests/

**NOTE** Development is very fast paced and probably could use more review before release.  Recently a password length limit was instituted resulting in [some users not being able to access funds](https://github.com/zkSNACKs/WalletWasabi/issues/1103) in a hard fork.

- Wallet was publicly announced and released since at least 3 months

**NOTE** Wasabi 1.0 was released 31 October  2018.  Eligible for listing on 31 January 2019.

- No concerning bug is found when testing the wallet

**PASS** No concerning bug was found while testing.  A number of small bugs were found which were addressed quickly such as https://github.com/zkSNACKs/WalletWasabi/issues/1091

- Website supports HTTPS and 301 redirects HTTP requests

**PASS** http://wasabiwallet.io redirects to https

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

**PASS** https://wasabiwallet.io rating A+

- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days

**PASS** https://wasabiwallet.io max-age is 365 days

- The identity of CEOs and/or developers is public

**PASS** https://zksnacks.com/#contact

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

**PASS** Receive addresses immediately disappear from the UI once a transaction is received

- Uses deterministic ECDSA nonces (RFC 6979)

**PASS** [Claims](https://github.com/MetacoSA/NBitcoin/blob/b6394b8f1fccd9b2fa6de152eb87ff7b3a35eb27/NBitcoin/Crypto/ECKey.cs#L71) to use low R deterministic nonce (not tested)

- Avoid address reuse by using a new change address for each transaction

**PASS**

- User has access to private keys
- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

**N/A**

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

**PASS** Provides BIP39 phrase when wallet is created

  - Restoring wallet from backup is working

**PASS** The wallet was restored using the BIP39 phrase on Wasabi as well as Electrum.

  - Source code is public and kept up to date under version control system

**PASS** https://github.com/zkSNACKs/WalletWasabi

- If user has no access to some of the private keys in a multi-signature wallet:

**N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:

**N/A**

  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element

Optional criteria (some could become requirements):

- Received independent security audit(s)

**NOTE** No audit

- Does not show "received from" Bitcoin addresses in the UI

**PASS** Does not show "received from"

- Provides a bug reporting policy on the website

**PASS** The support link on https://wasabiwallet.io links to reddit.com; app Report Bug menu item points to http://github.com/zkSNACKs/WalletWasabi/issues

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

**PASS** https:://wasabiwallet.io has been submitted to the preload list

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

**PASS** Uses BIP84 path

  - Provides users with step to print or write their wallet seed on setup

**PASS**

  - Uses a strong KDF and key stretching for wallet storage and backups

**PASS** Uses BIP38 password protection

  - On desktop platform:
    - Encrypt the wallet by default

**PASS** Uses BIP38 password protection for storing the master seed

**NOTE** Does not encrypt address labels

- For hardware wallets:
  - Prevents downgrading the firmware

**N/A**

**Comment by nopara73** [comment]
1. Rebased.
2. Changed transparency to checkpasstransparencyopensource

**Comment by nopara73** [comment]
> Per previous [comments](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-453831024) I believe that the scoring in [1113c4c](https://github.com/bitcoin-dot-org/bitcoin.org/commit/1113c4cd3d6a2a64236ed2209a797a6a9e8d915e) should be updated to
> `privacy: "checkpassprivacybasic"`

@crwatkins It was not discussed in previously, your linked comment was about `privacydisclosure`. Which I would like to reflect on also, but first I'd like to confirm with you if this was just a typo by you or you have something in mind.

FTR:

- `checkgoodprivacyimproved: "Improved privacy"`
- `checkpassprivacybasic: "Basic privacy"`

**Comment by crwatkins** [comment]
@nopara73 Thanks for asking; I should have provided more background.   The `privacy` score is an "umbrella score" that is derived by the algorithm specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#score) based on `privacyaddressreuse`, `privacydisclosure`, and `privacynetwork`.

**Comment by nopara73** [comment]
Since the discussion on network level privacy [ended by me pointing out](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-454320530) that Bitcoin Core without Tor broadcasts all its transactions on the clearnet, thus ISP can figure out accurately which tx was broadcasted by the local node, regardless if we are talking about a listening node or not, I believe downgrading Wasabi's privacy scoring to be equivalent with Bread Wallet's would be misleading and a disservice to the community.

To progress the conversation forward on network level privacy, let me write a comprehensive analysis and comparison between Wasabi, Core and Bread. My intuition is that it would sufficiently highlight that Wasabi and Core is way more similar to each other than Wasabi and Bread regarding network level privacy.

Finally I'd like to note that from the next release Wasabi will autodetect any running listening full node and fetch the block from it through local P2P connection. If there is none, then it will try to fetch the block from the disk, from the `blocks` folder, and only if Wasabi doesn't find those sources will it move ahead and use its P2P connections for block fetching. https://github.com/zkSNACKs/WalletWasabi/pull/1113

However for the analysis, I'd like to ask for sine time, since I have some deadlines coming up.

**Comment by crwatkins** [comment]
@nopara73 
>To progress the conversation forward on network level privacy, let me write a comprehensive analysis and comparison between Wasabi, Core and Bread. My intuition is that it would sufficiently highlight that Wasabi and Core is way more similar to each other than Wasabi and Bread regarding network level privacy.

I think that would be very interesting read.

Perhaps some background on the scoring may help you in your position.  The rest of this comment really just refers to bitcoin.org and may even be slightly off topic for this PR.

The _scoring_ (perhaps not the best name for it; the scores are the values that are assigned to categories) criteria has been established with community consensus.  I've been interpreting it for a few years in line with what I believe that the consensus intended and I have some organizational recollection of decisions and the reasoning behind those decisions.  Scores are generally chosen for wallets on a case by case basis of the score that the wallet best meets or exceeds.  Seldom are wallets directly compared or ranked.  The scores are intended to describe an individual wallet.   If new scores are needed to describe a new type of wallet, a new score would be created, but historically that has seldom (or never?) happened.  I'm all for it, but only if it is a significant new score with multiple wallets qualifying, or anticipated to qualify, in the near future (one wallet does not make a score).  Similarly any wallet with a score that it does not meet or exceed should be changed.

**Comment by crwatkins** [comment]
As detailed in my [review above](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788#issuecomment-456229044) I believe Wasabi Wallet is eligible for listing as the [bug cited](https://github.com/zkSNACKs/WalletWasabi/issues/1104) has been fixed and the three month release time period is now satisfied.

I still believe that the scoring should be changed to
```
privacy: "checkpassprivacybasic"
privacydisclosure: "checkfailprivacydisclosurespv"
```
but otherwise I concur with scoring in 7eff4e0.

As I've mentioned, I would support changes to the privacy scoring criteria in the future which would likely result in a different score being applied here.

I would recommend a merge with the above change.

**Comment by nopara73** [comment]
As I promised I have done a [comparision](https://medium.com/@nopara73/bitcoin-core-vs-wasabi-wallet-network-level-privacy-bdca1d501387) between Core's and Wasabi's network level privacy.

Also we have addressed the ISP adversary issue raised in this PR: Now Wasabi communicates over Tor on the P2P layer, in a way that it only connects to onion nodes, so the end-to-end encryption defeats the ISP adversary raised here. https://github.com/zkSNACKs/WalletWasabi/pull/1265

Note that, for a handful of releases now, if a full node was running in the background Wasabi was (and still is) automatically acquiring the blocks from it instead of peers, so this issue was partly addressed previously, too.

**Pull request merged**
