### PR TITLE
Adding Bitvo to the list of Canadian exchanges.

### PR DESCRIPTION
**Pull request by smayzes**

### CODE REVIEW

**Comment by 7thsecret** [comment]
Hello. 

Shawn updated the code for me based on the instructions. 

Is anything else required for listing? 

Thanks

Tristram

**Comment by Cobra-Bitcoin** [comment]
@7thsecret There is alphabetical ordering, so Bitvo needs to be below Bitbuy. Also remove the title from the link, it should just be href like all the other links.

Once those changes are done, it will be merged.

**Comment by 7thsecret** [comment]
Thanks Cobra.

tw

**Comment by Cobra-Bitcoin** [comment]
Looks good now. Thanks.

**Pull request merged**
