### PR TITLE
Add blog post - Help Choose Bitcoin.org's New Design

### PR DESCRIPTION
**Pull request by wbnns**
This PR adds a new blog post letting people know about the different designs that have been put together to date as part of the ongoing [Bitcoin.org redesign](https://github.com/bitcoin-dot-org/bitcoin.org/projects/1). It includes a link to a poll so people can vote on which one they like best, which is a prerequisite to extending the new design work into subpages of the site.

I'm waiting on a couple of updated links from @natiwa (the mobile layout for version 1, and the desktop layout for version 3). Once we have these, we can make this post live. If anyone else has any additional comments, questions or feedback to make the post better, please let me know.

Here's a live preview of the post:
https://bitcoin.cryptopelago.com/en/posts/vote-on-the-new-site-design

### CODE REVIEW

**Comment by wbnns** [comment]
Added link to post to view results.

**Comment by Cobra-Bitcoin** [comment]
Looks great, ACK.

**Comment by natiwa** [comment]
All links seem to work for me but sure here are the new ones: 
Ver 1 Mobile: https://invis.io/BJF8UVJYA#/272475274_1-8-18_Bitcoin-org_Ver1__Mobile_320px
Ver 3 Desktop: https://invis.io/6VFF8CB9CJA#/274446152_19-01-18_Bitcoin-org_Ver3_Desktop_1200px

**Comment by wbnns** [comment]
Thanks, merged.

**Pull request merged**
