### PR TITLE
Wasabi 2.0 logo and screenshot

### PR DESCRIPTION
**Pull request by CAnorbo**
The Wasabi Wallet 2.0 design completely changed, this PR contains the new logo and a screenshot from the new version of the wallet.

### CODE REVIEW

**Comment by nopara73** [comment]
Not sure if anything changed, but when I created the original PR the pic sizes were important. So I suspect you should make them `W: 250px | H: 350px` and `W: 144px | H: 144px`.

**Comment by CAnorbo** [comment]
> Not sure if anything changed, but when I created the original PR the pic sizes were important. So I suspect you should make them `W: 250px | H: 350px` and `W: 144px | H: 144px`.

Thank you, I fixed them.

**Comment by crwatkins** [comment]
@CAnorbo Thanks for the update!  Have the new images been optimized with `optipng -o7 file.png` as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)?

**Comment by CAnorbo** [comment]
> @CAnorbo Thanks for the update! Have the new images been optimized with `optipng -o7 file.png` as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)?

I uploaded the optimized images.

**Review by nopara73 — APPROVED** [review]
LGTM

**Comment by crwatkins** [comment]
LGTM.   Thanks for the update.

**Comment by Cobra-Bitcoin** [comment]
LGTM.

**Pull request merged**
