### PR TITLE
Updates Ninki Wallet description

### PR DESCRIPTION
**Pull request by Ninkip2p**

### CODE REVIEW

**Comment by harding** [comment]
LGTM.  Thanks!

**Comment by crwatkins** [comment]
OK with me.

**Comment by saivann** [comment]
I'm fine with the change itself. However, is this change worth resetting 13 translations?

**Comment by Ninkip2p** [comment]
@saivann Hi, i take your point and it might seem like a trivial change, however it is something I have been thinking about for some time from analyzing the flow of users we get, their expectations and support requests. This is part of a number of changes including displaying this text on our app pages and on the chrome store page, removing our listing on bitcoin.com (as I feel there isn't enough user education and it raises expectations too high) and also being more explicit on the operational security risks when a user creates an account.

**Comment by saivann** [comment]
FWIW I'm sort of neutral between accommodating translators or @Ninkip2p . I am only worried that other wallet developers will want to update their description more often, and that creates a lot of work.

**Comment by harding** [comment]
My vote is for merging this.

@Ninkip2p and I were talking in IRC about a month ago, and (if I understand correctly) the problem is this: he has an advanced wallet designed for power users, but he suspects that his Bitcoin.org wallet listing is attracting Bitcoin newbies who are getting confused by his wallet.

The intention of this change of text is to discourage those newbies from choosing Ninki.  This benefits him directly by maybe reducing the time he spends on support; it also benefits those newbie users by directing them to a more appropriate wallet so they're less likely to end up disappointed or frustrated---which I think is a change worthy of re-translation.

**Comment by Ninkip2p** [comment]
@harding exactly this, yes.

**Comment by saivann** [comment]
@harding @Ninkip2p Great, thanks!

**Comment by crwatkins** [comment]
I'm good with scheduling this merge.

**Comment by harding** [comment]
In the absence of critical feedback, this will be merged on Friday.

**Pull request merged**
