### PR TITLE
Dev Projects links updated

### PR DESCRIPTION
**Pull request by Mirobit**
Added a few full implementations and changed links to the actively used repository.

### CODE REVIEW

**Comment by wbnns** [comment]
@Mirobit This is great, thanks a bunch.

Unless others object, this will be merged on Sunday, August 6th.

**Comment by wbnns** [comment]
@Mirobit Could you please fix the merge conflict in `_templates/development.html`? Once that is done, I'll merge. 👍

**Comment by Mirobit** [comment]
Resolved

**Comment by wbnns** [comment]
@Mirobit Thanks!

**Comment by cjennyc28** [comment]
K

**Pull request merged**
