### PR TITLE
Update OP_RETURN glossary to reflect current behavior

### PR DESCRIPTION
**Pull request by adlai**

### CODE REVIEW

**Comment by cpmx** [comment]
This fails the Travis check but this commit should work fab0245fc43f4460c992dce2cadb97678e49ac77

**Comment by btcdrak** [comment]
After deployment of 0.12, it will be 83 bytes.

**Comment by harding** [comment]
@adlai Thanks for your PR!  I recently did a more comprehensive rewrite of these sections with additional details and fixes from some complaints about the current text: https://github.com/bitcoin-dot-org/bitcoin.org/pull/1191

It's just waiting for review.

**Comment by luke-jr** [comment]
@btcdrak No, it won't... the meaning of the setting changes also (the 3 bytes are the additional bytes counted now).

**Comment by adlai** [comment]
@harding Sorry for the duplicate. I'm closing this in favor of the more thorough PR you linked.

**Pull request closed without merging**
