### PR TITLE
Added HTTPS to all links that support it in _templates

### PR DESCRIPTION
**Pull request by i-rme**
Added HTTPS to all links that support it in _templates

### CODE REVIEW

**Comment by Mirobit** [comment]
ACK

**Comment by wbnns** [comment]
@i-rme Thanks - can you please fix the merge conflict in `_templates/resources.html`?

**Comment by i-rme** [comment]
I believe they are fixed now.

**Comment by wbnns** [comment]
@i-rme Hello, could you please rebase again? After that, we'll schedule this to be merged.

**Comment by wbnns** [comment]
@i-rme Thanks.

Unless others object, this will be merged on Sunday, March 5th.

**Pull request merged**
