### PR TITLE
Assobit for capacity increases

### PR DESCRIPTION
**Pull request by gabridome**

### CODE REVIEW

**Comment by gabridome** [comment]
The error is about missing coyrights.

Is the part I translated?

 +# Questo file è protetto dalla  licenza MIT License (MIT) reperibile su
 +# http://opensource.org/licenses/MIT.

**Comment by gabridome** [comment]
I did make a mistake translating the copyright part. My fault.

**Comment by gabridome** [comment]
I have a problem with the last build failure. What does the error log actually mean?
reported here below:
- ./_site/it_IT/bitcoin-core/capacity-increases-FAQ.html
  *  linking to internal hash #size-bump that does not exist (line 495)
/home/travis/build/bitcoin-dot-org/bitcoin.org/vendor/bundle/ruby/2.0.0/gems/html-proofer-2.1.0/lib/html/proofer.rb:179:in `print_failed_tests': HTML-Proofer found 1 failure! (RuntimeError)
	from /home/travis/build/bitcoin-dot-org/bitcoin.org/vendor/bundle/ruby/2.0.0/gems/html-proofer-2.1.0/lib/html/proofer.rb:81:in `run'
	from _contrib/bco-htmlproof:62:in `<main>'
make: *** [check-html-proofer] Error 1
The command "make travis" exited with 2.
cache.2
store build cache
$ bundle clean
0.00s0.73snothing changed, not updating cache
Done. Your build exited with 1.

**Comment by harding** [comment]
@gabridome thanks for doing this!  I reviewed the translation in Google Translate, rebased it, added links from the English versions, and merged.  It should be live on the site in about 10 minutes.  Thanks again!

**Comment by gabridome** [comment]
Wow. Pretty excited. Thank you.
Il 05 gen 2016 9:46 PM, "David A. Harding" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
