### PR TITLE
Add Bitcoin Global to list of P2P platforms

### PR DESCRIPTION
**Pull request by vladyslavstartsev**

### CODE REVIEW

**Comment by vladyslavstartsev** [comment]
If there is a need in some description, I'm happy to add it. But there is no description what should be added.

**Comment by vsus** [comment]
As far as I know, the website was created on July and it almost has no visits.

**Comment by vladyslavstartsev** [comment]
@vsus what is the minimum age of the platform that you will accept?

**Comment by vsus** [comment]
I'm not a maintainer of Bitcoin.org. I just wanted to mention some facts I consider relevant.

**Comment by Cobra-Bitcoin** [comment]
We usually add only established platforms, so you need to build out more and get more usage, because it isn't beneficial for us to point our users to services that aren't really being used yet.

Sorry, hope you understand.

**Pull request closed without merging**
