### PR TITLE
Update community.html

### PR DESCRIPTION
**Pull request by santy2001**
Just adding the Bitcoin Colombia Fundation (non-profit)

### CODE REVIEW

**Comment by santy2001** [comment]
I already request the pull for the flag and is waiting for been added

**Comment by Cobra-Bitcoin** [comment]
You need to make sure the tests pass.

**Comment by santy2001** [comment]
the test will pass if you aprrove the pull request of the flag CO.png

**Comment by wbnns** [comment]
@santy2001 Hello, thanks for taking the time to put together this PR. Can you please include the changes in #1352 in this PR as well? For this addition, all of the changes should be together, in one PR. If you need help, please let us know.

**Comment by santy2001** [comment]
I already add a pull request , with the  2 files, and the Travis test pass, #1424 . Please refer there and add the request.

**Comment by santy2001** [comment]
CLOSED BECAUSE WAS DEFINED TO PUT THE REQUEST ON #1424

**Pull request closed without merging**
