### PR TITLE
First pass for dark mode

### PR DESCRIPTION
**Pull request by jdabs**
#3151 
-  Minimal CSS partial for dark mode
-  Media query on screen.scss

Please test and review it. My eyeballs have looked at it too long and thus this PR.

This PR includes no toggle option. The icon that looks like it is becoming the standard toggle button is this one:
https://fontawesome.com/icons/adjust?style=solid

### CODE REVIEW

**Comment by wbnns** [comment]
@jdabs 

Thanks so much. We'll review.

**Comment by wbnns** [comment]
@jdabs 

Thanks again for working on this. It seems there are two main issues from which most problems stem - conflicting styles overriding one another, and the palette itself. For the palette, am thinking we should be taking a closer look at anchoring on a material design palette (reference: https://material.io/design/color/dark-theme.html#ui-application):

image

There is a bit of a clash at present between the `head`, `hero` and content sections, as well as the typography (e.g. font colors) themselves. Here is an example from the Blog:

image 

Also some additional feedback:

+ Let's add a toggle button, and see what it looks like to the right of the language toggle in the footer.
+ The `bitcoin` text in the bitcoin logo in the top-left should change to white while in dark mode.
+ Icons should also change, so that they don't appear with whitened hard edges (like in the `Get started with Bitcoin` section on the homepage)
+ Text is rendering a bit darkened and illegibly in places (like on the `Getting started with Bitcoin` page, especially in the numbered steps)
+ The `See also` section doesn't appear to be rendering correctly in the Developer Documentation
+ The search box in the Developer Documentation does not toggle to dark mode
+ The text is illegible on the Bitcoin paper page
+ Icons are illegible on the Resources page
+ The `alert` class when used, does not seem to toggle into dark mode
+ The text is illegible on the Events page
+ Much of the Bitcoin Core pages are illegible
+ Some sections of the FAQ page do not seem to render correctly in dark mode
+ Code excerpts, like on the `Running a Full Node` page, do not seem to toggle into dark mode
+ The text is illegible on much of the About page
+ The text is illegible on the Blog (already mentioned above)

* * *

Based on this, would recommend another round of updates to work toward resolving more of the above issues.

**Comment by jdabs** [comment]
@wbnns thank you for that thorough feedback. 

I will keep working with it, and anyone else who wants to help, please do and let me know in the comments

**Comment by jdabs** [comment]
@wbmns yea, I like the material pallette also

**Comment by wbnns** [comment]
@jdabs 

Thanks again for your help.

**Comment by jdabs** [comment]
@wbnns I'm putting together a toggle button feature. Is it ok if I use the user's localStorage so that we can keep their setting in memory when they navigate across the site? This looks like the most convenient way to do this and without disturbing the user.

**Comment by Cobra-Bitcoin** [comment]
@jdabs Shouldn't be a problem.

Really good stuff so far, looking forward to seeing improvements made and then hopefully we can merge it soon after.

**Comment by jdabs** [comment]
@wbnns, @cobra-bitcoin. I'm getting there. I think the icon toggle behaves better. I still am QAing the pages and colors. 

The white background icons, I can't do much with. I am not the best at icon design. The `fill: #000;` isn't working like I hoped for svgs....

**Comment by wbnns** [comment]
@jdabs 

Thanks for the continued effort on this. For the icons, don't worry, we can take care of that.

**Comment by jdabs** [comment]
@Cobra-Bitcoin I'm not sure if you're interested in the dark mode code in this PR. I'd be glad to hear your input.

**Comment by Cobra-Bitcoin** [comment]
@jdabs Will review and get back to you shortly. Very interested to get this merged. Thanks for working on this, and sorry for missing it, the "changes requested" label threw me off, and it was hidden behind a lot of other PRs.

**Comment by jdabs** [comment]
@Cobra-Bitcoin no problem. I know there's been a lot going on : )  I'm glad for that, though.

**Comment by Cobra-Bitcoin** [comment]
@jdabs I just reviewed and this looks really awesome! Thank you so much for working on this.

It just needs a rebase and it will be ready to merge. I think the few minor issues I had were caused by some of the old files still lingering around, so pulling in the recent changes will fix it (since we've also upgraded the Ruby version).

Very good stuff. 👍

**Comment by jdabs** [comment]
OK, I will have more time this week to repull the site, rebuild locally, and update the scss

**Pull request closed without merging**
