### PR TITLE
Add Buy Bitcoin Worldwide to Directories

### PR DESCRIPTION
**Pull request by JTuwiner**
This adds Buy Bitcoin Worldwide to the resources page. 

This is an important tool for new users who want to buy bitcoin in their country. The country directory is here: https://www.buybitcoinworldwide.com/en/ . It is available in 13 languages. 

Another tool that helps people buy bitcoin based on location and payment method: https://www.buybitcoinworldwide.com/coinfind/

### CODE REVIEW

**Comment by wbnns** [comment]
@JTuwiner Hello, apologies that there hasn't been a reply to this pull request yet. This message is just to confirm that your submission is under review.

**Comment by Mirobit** [comment]
ACK. The best exchange overview out there.

**Comment by JTuwiner** [comment]
@wbnns No problem. Let me know if you need any more info from my side. I've already waited more than a year...so waiting a bit longer won't kill me :)

**Comment by wbnns** [comment]
Unless others object, this will be merged on Wednesday, December 14th.

**Comment by crwatkins** [comment]
LGTM

**Comment by JTuwiner** [comment]
Hey, thanks for merging this! I'm checking the website https://bitcoin.org/en/resources but I don't see the link to BBWW despite the merge. Any idea when it will be on the live site?

**Comment by wbnns** [comment]
@JTuwiner You're welcome. It's live now. 👍

**Comment by JTuwiner** [comment]
Looks great! Thank you so much for getting this set up. Hope it helps many new users get their first bitcoins :)

**Comment by wbnns** [comment]
@JTuwiner Thanks, you're welcome sir. Cheers to that. 👍

**Pull request merged**
