### PR TITLE
added bitfinex

### PR DESCRIPTION
**Pull request by DorothyRMartin**
added bitfinex to the international exchanges list

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
NACK. Bitfinex has major problems right now.

**Comment by DorothyRMartin** [comment]
You can deposit fiat, you can withdraw fiat.
You can deposit crypto, you can withdraw crypto.
Yes they have some legal action, regardless, NYAG has said trade on, the 'loan' they didn't like was returned and money was raised from investors.

So whats the problem, or is this just some kind of personal issue you have with them which you're unable to articulate ?

**Comment by wbnns** [comment]
@DorothyRMartin Thanks for the PR, but agree with @Cobra-Bitcoin and also think the exchange shouldn't be added at this time.

**Comment by DorothyRMartin** [comment]
Okay, what requirements are we waiting for them to fill exactly to be added ? 
Like I said, neither has provided any reason to not to add them... 
In the spirit of being fair and unbiased, i do not see why not.
They help finance bitcoin core development, first to implement liquid / blockstream elements, have a program for funding lnd development, their platform works, better than stamp/coinbase in terms of liquidity, spread, reliability, ws api etc.

**Pull request closed without merging**
