### PR TITLE
Added Easy Crypto to AU and NZ

### PR DESCRIPTION
**Pull request by alangrainger**
Added Easy Crypto's local AU and NZ websites

### CODE REVIEW

**Comment by wbnns** [comment]
@alangrainger 

Hello, thank you for the pull request. Please let us know once you've had a chance to review our [documentation regarding the addition of exchanges](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md), and let us know how you'd like to proceed.

**Comment by AVGolden** [comment]
15mqwraPN4pn8k2oqSvRe5sLLATQmU46BZwTHFg1NBo8YeF6n987EME9WX9bN8bT64PdhEoNugr53zxCmRGgLvkLvP1

**Comment by wbnns** [comment]
@alangrainger 

Closing this for now, but we'll be standing by when you're ready.

**Comment by andrewecau** [comment]
Hello @wbnns - I just wanted to follow up on behalf of Alan in having us added to the NZ and Australian areas.  What is the process from here please?

**Pull request closed without merging**
