### PR TITLE
Updating Blockchain size from "20GB" to "65GB".

### PR DESCRIPTION
**Pull request by jonathancross**
Accounts for all variations in the 27 translations.

FYI: Here is the shell commands used to update (may come in handy next time):

    cd bitcoin.org/_translations
    for F in *;do /usr/bin/perl -p -i -e "s/20GB/65GB/g" $F;done
    for F in *;do /usr/bin/perl -p -i -e "s/20 GB/65 GB/g" $F;done
    for F in *;do /usr/bin/perl -p -i -e "s/20 /65 /g" $F;done
    for F in *;do /usr/bin/perl -p -i -e "s/20ГБ/65ГБ/g" $F;done
    for F in *;do /usr/bin/perl -p -i -e "s/20ＧＢ/65GB/g" $F;done

Yes, it *could* have been simplified, but it took care of all crazy variations with no mistaken matches  ;-)

### CODE REVIEW

**Comment by greenaddress** [comment]
ACK

**Comment by FelixWeis** [comment]
Since the block chain size is constantly growing, it would be good to include a date every time it is mentioned so "[...] storage for the full block chain size (over 65GB, **as of January 2016**) [...]"

see also https://en.wikipedia.org/wiki/Wikipedia:As_of

**Comment by jonathancross** [comment]
@FelixWeis That would in fact be nice, but unfortunately it would require many new translations.
In #1234 there is a suggestion of trying to make the number a variable that can be changed.

**Comment by jonathancross** [comment]
Hi all.
There is much we could do to make it more dynamic, add additional info, etc. but the current info is just wrong and misleading.

Any reason not to merge this while discussing additional improvments?

**Comment by MarcoFalke** [comment]
Agree with @jonathancross and @laanwj: This should be merged soon as it does not seem anyone came up with a dynamic solution in the last months.

Ping @harding

**Comment by harding** [comment]
Untested ACK.

**Pull request merged**
