### PR TITLE
Add Bitbuy to Exchanges

### PR DESCRIPTION
**Pull request by adamgoldman**
Adding one of Canada's top exchanges, Bitbuy to the exchanges section for Canada

### CODE REVIEW

**Comment by wbnns** [comment]
@adamgoldman 

Hello, could you please let us know if the issues mentioned in #2810 have been resolved?

**Comment by adamgoldman** [comment]
@wbnns 

1. In Firefox  (latest version), the user dashboard overflows offscreen: 
FIXED
2. When depositing bitcoin, there is no validation for the originating address that's requested, to ensure that it is a valid bitcoin address:
FIXED - We now use proper custody infrastructure, and users are NOT required to enter an address when depositing on Bitbuy. A deposit address is simply generated and provided to the user.
3. It seems it takes one business day to deposit bitcoin:
FIXED - As per #2 deposits are now processed in real-time

All issues in #2810 have been resolved.

**Comment by adamgoldman** [comment]
@wbnns Just following up on this.

**Comment by wbnns** [comment]
@adamgoldman Thank you.

This is scheduled to be merged on Friday, April 26th.

**Pull request merged**
