### PR TITLE
Add Croatian whitepaper translation

### PR DESCRIPTION
**Pull request by LuxBTC**
[bitcoin_hr.docx](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5638564/bitcoin_hr.docx)
[bitcoin_hr.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5638565/bitcoin_hr.pdf)

### CODE REVIEW

**Comment by jdabs** [comment]
This looks good in the formatting, though I can't speak to the translation itself.. . @wbnns / maintainers should commit.

**Comment by Cobra-Bitcoin** [comment]
Thank you for translating! Just curious, why is there a .zip file in there?

We only need a .pdf in there, nothing else. If you remove the .docx and .zip file I'll merge.

**Comment by LuxBTC** [comment]
> Thank you for translating! Just curious, why is there a .zip file in there?
> 
> We only need a .pdf in there, nothing else. If you remove the .docx and .zip file I'll merge.

First I tried to upload it via Will Binns repository where I needed to upload .odt file as well but couldn't for some reason so I put it in .zip.  I didn't know Bitcoin.org only needs .pdf.

I would gladly make changes and remove .docx and .zip but I don't know how to do it. I'm not github user and it's giving me a headache. Can you help me?

**Comment by Cobra-Bitcoin** [comment]
I'll add the translated paper to the site for you separately, but let's wait for someone Croatian to verify the quality of the translation.

**Comment by djurko** [comment]
> I'll add the translated paper to the site for you separately, but let's wait for someone Croatian to verify the quality of the translation.

I'm a native Croatian speaker. I read the translation and it looks pretty good to me.

**Comment by Cobra-Bitcoin** [comment]
@djurko Thanks for verifying.

@LuxBTC I added the whitepaper for you in a separate PR without the zip/doc files: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3593. Thanks so much for working on this.

**Comment by LuxBTC** [comment]
> @djurko Thanks for verifying.
> 
> @LuxBTC I added the whitepaper for you in a separate PR without the zip/doc files: #3593. Thanks so much for working on this.

Thank you @Cobra-Bitcoin !

**Pull request closed without merging**
