### PR TITLE
Upgrade Armory fee control from pass to good

### PR DESCRIPTION
**Pull request by achow101**
Armory 0.96.0 allows users to set RBF on a transaction and to subsequently bump the fee of said transaction.

### CODE REVIEW

**Comment by crwatkins** [comment]
@achow101 That's good news!  Thanks for submitting the update.

1. The Armory listing ```Visit website``` link points to a page that claims that the latest release is 0.95.1.  Could you either update the link or update the web page to point to the correct release?

2. Is the official binary distribution from Github?  The OSX release seems to be missing.

**Comment by achow101** [comment]
@crwatkins should be updated now. I was waiting on the merge for the release post.

There were a few problems getting OSX to build properly. That should be fixed and released in a week or so as 0.96.1 along with our offline distributions.

**Comment by crwatkins** [comment]
LGTM.

**Comment by Mirobit** [comment]
The homepage now links to the 0.96.0 release.

LGTM.

**Comment by wbnns** [comment]
Unless others object, this will be merged on Wednesday, May 10th.

**Pull request merged**
