### PR TITLE
Rebrand digitalbitbox to BitBox

### PR DESCRIPTION
**Pull request by TheCharlatan**
The wallet rebranded and we are using a new website: shiftcrypto.ch

### CODE REVIEW

**Comment by crwatkins** [comment]
LGTM; utACK.

@TheCharlatan While currently only an optional criterium, we may require HSTS preload in the future.  Since it is generally a good idea, you might want to consider submitting https://shiftcrypto.ch to https://hstspreload.org for inclusion in browser preload lists.

**Comment by TheCharlatan** [comment]
Force pushed a change to the icon. Sorry for the delay.

**Comment by jonasschnelli** [comment]
ACK

**Comment by wbnns** [comment]
@TheCharlatan No worries, thank you.

This is scheduled to be merged on Monday, December 31st.

**Pull request merged**
