### PR TITLE
Merge redesign branch into master

### PR DESCRIPTION
**Pull request by wbnns**
Preview link:
https://bitcoin.cryptopelago.com/

Tentative merge date (unless others object):
Sunday, June 3rd

Todo:
- [x] Fix merge conflicts
- [x] Address any remaining user feedback and/or issues
- [x] Additional round of testing on [BrowserStack](https://www.browserstack.com/)

For additional feedback and/or suggestions, please comment on this issue and I will consolidate into remaining todo items.

Cc: @Cobra-Bitcoin

### CODE REVIEW

**Comment by crwatkins** [comment]
I am concerned about the level of testing which this has received.  When I can look at the preview for less than 60 seconds and find 404 errors (see #2402) this suggests to me a lack of testing of the most basic functions.

I am also concerned that we are still struggling with basic design flow in #2347.  While I think that the current redesign is "acceptable", I don't think that was the low bar that we were trying to achieve.  I  was hoping for at least "better" than the UX on the current site, and I'm not sure that we've achieved that yet.

For these reasons, I don't believe this is ready for merge.

**Comment by Cobra-Bitcoin** [comment]
The redesign looks very good! Glad we're finally about to go live.

ACK, but before we merge, we need to fix the issue mentioned in https://github.com/bitcoin-dot-org/bitcoin.org/issues/2402. We need to filter the wallets client side, and avoid the unnecessary loading which makes the choose your wallet page feel much less interactive.

@crwatkins  Regarding the UX, I think the experience on mobile is a lot better, and once the issue you raised is fixed, I think it'll be better on desktop too. Personally I would like to see the black navigation top bar bought back when inside a particular wallet (this thing: https://i.imgur.com/Hi6BLVe.png), because having it made it much easier to swap between wallets when inside a page, and it felt more intuitive. It looked really good too.

But let's just try to get this merged as soon as we can, after a bit more testing.

**Comment by wbnns** [comment]
@crwatkins

Thanks for mentioning the 404. We'll be sure to fix. If you have other specific/objective recommendations, please let us know and we'll take a look at those, too.

**Comment by achow101** [comment]
I'm going through the entire redesign website right now and will update this comment with comments/issues that I see.

- Facebook and Twitter links by the title of each page redirect to the page itself
- The cookie privacy policy box is still the old website style

**Comment by wbnns** [comment]
@achow101 Heya! Big thanks for volunteering some of your time to go through stuff - it's much appreciated. We're going through things and fixing them. I'll send you an update afterward.

**Comment by Cobra-Bitcoin** [comment]
Text is displayed wrong (e.g. "mobile" and "android", also same when inside a particular wallet) on mobile devices when inside a wallet category (https://bitcoin.cryptopelago.com/en/wallets/mobile/android/).

textweird

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

>Text is displayed wrong (e.g. "mobile" and "android", also same when inside a particular wallet) on mobile devices when inside a wallet category (https://bitcoin.cryptopelago.com/en/wallets/mobile/android/).

Hey, apologies, I'm not sure I understand - do you mean "mobile" and "android" should be capitalized?

**Comment by Cobra-Bitcoin** [comment]
@wbnns Yeah, and also when inside a wallet, it displays incorrect text:

broken

**Comment by wbnns** [comment]
@Cobra-Bitcoin Ok, I see it - thanks.

**Comment by harding** [comment]
I notice that the Travis CI builds print [multiple warnings](https://travis-ci.org/bitcoin-dot-org/bitcoin.org/builds/387072622?utm_source=github_status&utm_medium=notification).

At least one of those warnings indicates one of the linters used (jshint) isn't working, so it isn't emitting errors.  Tesitng builds on my system, jshint works and prints the following errors, causing the build tests to fail:

```text
./_site/js/responsiveAccordion.js
line 2, col 3, Missing "use strict" statement.
line 18, col 3, Missing "use strict" statement.
line 25, col 3, Missing "use strict" statement.
./_site/js/loadMorePosts.js
line 2, col 3, Missing "use strict" statement.
line 2, col 24, Missing "use strict" statement.
line 7, col 36, Expected '===' and instead saw '=='.
line 9, col 42, Missing semicolon.
line 11, col 3, Missing "use strict" statement.
./_site/js/devsearch.js
line 3, col 47621, Missing semicolon.
./_site/js/main.js
line 272, col 23, Missing semicolon.
line 635, col 6, Don't make functions within a loop.
line 646, col 22, Expected '===' and instead saw '=='.
line 646, col 13, Confusing use of '!'.
line 650, col 6, Don't make functions within a loop.
line 689, col 6, Don't make functions within a loop.
Makefile:266: recipe for target 'check-jshint' failed
make: *** [check-jshint] Error 1
```

**Comment by wbnns** [comment]
@harding Thanks for the report, we'll check into that.

**Comment by wbnns** [comment]
@achow101 Thanks again for spending time reviewing. I've numbered what you mentioned so we can track them:

1. This is because there's an `onclick` event that handles the population of the URL once it's clicked/touched so that the page can be shared on social media.
2. Fixed.
3. This is same as behavior as the current site. Good idea - we'll implement this as a feature post-deployment of the redesign.
4. Fixed.
5. Fixed.
6. Fixed (this is part of resolving a merge conflict).
7. Fixed.
8. Fixed.
9. Fixed.
10. Fixed.
11. Understood. The initial links are sections within those pages.
12. Fixed.
13. Fixed.
14. Nice find, have not fixed this one yet, still looking into it. I do not think this is severe enough to block us from going live. We'll take care of it soon.
15. The jump has been fixed and now mirrors the behavior of the current site. For the on-page behavior the issue here is that we have unique URLS for the wallets and operating systems so that we appear in search engine results for various wallet-related queries (e.g. "bitcoin wallet for android"). If we go solely on-page, we'll lose those results and traffic (our wallets page is the second most viewed page on the site). We're going to do further enhance the wallet pages to improve this behavior post-deployment of the redesign.

@Cobra-Bitcoin Thanks also for the additional reviews. The wallet text display issue is fixed (everything is properly capitalized, now). For the on-page display/behavior of wallets (e.g. potentially dropping the unique urls and going 100% client-side/JS to display wallets so that a new page doesn't load), I'd recommend we pursue this alongside what I mentioned in the last list item above so that we don't potentially lose traffic and get penalized in search results (orphaned pages getting dropped that are no longer linked to on the site).

**Comment by wbnns** [comment]
Resolved the issue with Travis CI not running JSHint (therubyracer and libv8 needed to be upgraded). Also took care of what was being reported by JSHint, afterward, when it ran.

**Pull request merged**
