### PR TITLE
Add link to bitcoinwide.com

### PR DESCRIPTION
**Pull request by glagola**
Hi, it's second attempt (relates to #3218). The issues you [mentioned](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3218#issuecomment-570273745) were fixed: enhanced search results relevance; fixed typos and etc. It took more time then we thought, but anyway hope you will like it :)

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Awesome, looks really good. Will be merged in a few days.

**Comment by glagola** [comment]
Awesome, thanks.

**Comment by Cobra-Bitcoin** [comment]
Hey, sorry, I had to revert the change because it wasn't building. We have a fallback that requires every .svg file to also have a .png file available in the same location, so if you make a new pull request with both svg and png versions of the search icon, I'll merge it right away.

**Comment by glagola** [comment]
@Cobra-Bitcoin Hi, no problem, I created new pull request with the search icon in both versions #3425

**Pull request merged**
