### PR TITLE
Reinstate Armory

### PR DESCRIPTION
**Pull request by achow101**
It has been three months since Armory's removal. This PR relists Armory onto the choose your wallet page.

### CODE REVIEW

**Comment by luke-jr** [comment]
Have the circumstances around its removal changed?

**Comment by achow101** [comment]
@luke-jr not sure what you mean...

I was just going by @Cobra-Bitcoin comment here: https://github.com/bitcoin-dot-org/bitcoin.org/pull/1235#issuecomment-185676811

Armory currently meets all of the criteria and IMO the fork is trustworthy.

**Comment by crwatkins** [comment]
Armory fills a unique niche in our wallet listings and I'm anxious to have this excellent work re-listed.  Over the past few months there has been a fair amount of confusion over the maintenance and the future of the wallet.  I've tried to follow the discussions on bitcointalk as best as I can.

While not a hard criterion (my interpretation), most wallets have a public facing web site, usually fulfilling one or more of the wallet listing requirements, such as identifications of the principals of the project or bug reporting policies.  (I believe these criteria can also be met using other methods.)  One confusing issue here is that http://www.bitcoinarmory.com/ is a very well done, very informative web site describing something called an Armory Wallet, using the same branding in the PR and referencing a significant amount of information that does not seem to pertain to the wallet referenced in this PR.  Can someone make an authoritative statement on how this website does or does not relate to the wallet in this PR?  (To try to be clear, I'm not looking for a rehashed explanation of the history from the forums, I'm looking for a statement from someone that believes they have the authority to make it.)

Likewise, it could set aside a lot of confusion here should someone (perhaps @achow101, @sunnankar, or @goatpig) with authority on the project be able to state the current intent of the project.  (Very few words would be needed.)

In any case, it is clear that there is an amazing amount of working being done by @goatpig on a wallet named Armory!

**Comment by achow101** [comment]
@crwatkins Armory is no longer affiliated with http://www.bitcoinarmory.com/ and Armory Technologies Inc (ATI). The only official places for Armory are now [goatpig's repo](https://github.com/goatpig/BitcoinArmory) and the [Armory sub-forum on Bitcointalk](https://bitcointalk.org/index.php?board=97.0)

**Comment by sunnankar** [comment]
@achow101 and @crwatkins The Armory project, www.bitcoinarmory.com, encompasses the Armory Bitcoin wallet started in 2011 and the IP is held by Armory Technologies Inc. where etotheipi was the lead developer and goatpig has developed full-time on the wallet for several years.

In early 2016 etotheipi shifted attention from ATI to a non-Bitcoin related full-time job. Meanwhile goatpig has continued developing and is currently working on Segwit and other updates. We are currently looking at ways to fund goatpig's efforts and future updates will most likely be included on www.bitcoinarmory.com

It is unclear why @Cobra-Bitcoin removed Armory in the first place since all of this internal activity has never posed any security issues to either the current 0.93.3 wallet or there being any discontinuity in the developers for any future releases since goatpig has been integrally involved in all 0.90 releases onward.

**Comment by crwatkins** [comment]
Thanks @achow101.   What's the name of the new "organization" (or product) now?  Just "Armory"?  (I'll try to represent it accurately.)  Do you know why there is a http://www.bitcoinarmory.com/ site?  Might they also ask us to list a wallet called Armory with the same branding? I suspect you don't speak for them, but do you have any information that they are likely to request listing of their wallet also?  (Note that in theory that should not be a problem because we have forks listed now, but not usually of the same name.)

One concern (which may not be significant) is that if a user doesn't follow the link in this PR, but rather uses any search engine to find the code to download, will very likely end up on bitcoinarmory.com.  Is that an issue?  Again, I'm anxious to get this listed, I'm just trying to clear up some confusion.

**Comment by achow101** [comment]
@sunnankar ok, now I'm confused. I was told that @goatpig is the only "official" developer and anything related to Armory that wasn't under his control is not official. He said that bitcoinarmory.com was not under his control, and thus not Armory's official website. Unless something has changed that he hasn't told us about.

@crwatkins It is still "Armory". According to @sunnankar, that website is still supposed to represent the same project so I don't think there will be any problems there except that it may not be up to date.

And yes, I don't really have the authority to speak on this; I am just going by what I have been told when discussing this on bitcointalk.

It could be an issue if people do end up on bitcoinarmory.com and the site is not updated with the latest software.

**Comment by goatpig** [comment]
Sunnankar is one of the original investors in ATI. I believe bitcoinarmory.com is in his possession (if not, I expect he has control over its content). Armory the brand name is the property of ATI. Sunnankar and the quorum of parties that hold ownership over that brand are graciously letting me use it for my fork.

The current Armory repository (owned by etotheipi) is not developed anymore, as etotheipi himself has moved on to a non Bitcoin related full time job and all former employees moved on but me. I proposed to further development on my own dime and time and was met with approval from all parties involved, be it the community, etotheipi or the ATI share holders.

My fork has no dedicated website currently because that implies time and skills I do not possess. Also, the ATI shareholders are keeping bitcoinarmory.com up in hope to revive the project in the future.

As a result, to avoid later conflicts and reduce the amount of overlap in PR and branding image, I have posted binaries for my fork on the release page of my repo, as suggested by the community. 

Once litenode (0.95), BIP32/44 support (0.96) and Segwit (0.97) will be implemented, the technological gap Armory is suffering from now will be closed. By then I will have more availability to deal with the PR side of the project. 

I expect enough time will have passed in that period to assess the state of the Armory project under ATI's guidance and if it can be revived. I will move forward with that aspect of the project in accordance to such future developments.

Keep in mind that bitcoinarmory.com only posts binaries for code on etotheipi's repository, which covers up to 0.93. My repo holds my binaries for the latest version on my fork, namely 0.94, and the soon to be released 0.95. In that light, I do not believe users can confuse the original project and my fork in a meaningful way. 

Regarding goals, as you may know, all the code I release is under the MIT license, and I intent to steer development towards power user and business use cases, with features like fast supernode, easy to integrate web stack interface and modularizing code into stand alone libraries. 

This is all working towards putting together an open source industry standard for top down, locally ran and controlled bitcoin processing service, built around full nodes.

**Comment by crwatkins** [comment]
Thanks everyone for the clarifications.

I hope we can work toward reconciling the different versions on github and bitcoinarmory.com to reduce confusion.  There are still a lot of links out there to bitcoinarmory.com from web pages and search engines.

I recommend Armory for listing.

**Comment by ABISprotocol** [comment]
I also do recommend Armory for listing, I just wish that there was a way that the stuff we see on https://github.com/goatpig/BitcoinArmory/releases could also be shown at https://www.bitcoinarmory.com/download/ - If it's to be listed again then please make sure to link to @goatpig releases so that people don't inadvertently link to the website (until such time that there is a website, I guess).

**Comment by laanwj** [comment]
@goatpig This doesn't seem to be a good position to be in as open source project. Have you thought about changing the name (and branding) of the project to avoid confusion and potential future legal problems? (e.g. one common example of this would be Debian's fork of Firefox, Iceweasel)

This also removes some concerns from users, as well as from sites linking to the project (like here), as well as concerns with the website.

**Comment by goatpig** [comment]
@ABISprotocol I don't control bitcoinarmory.com, that belongs to ATI. Their current policy (I believe) with that domain is to offer binaries for the code they fully own, i.e. 0.93.x versions of Armory. 

You could say the current state of affairs is that ATI tolerates my fork (and me using their trademark), but have yet to make a definitive move in either embracing it or opposing it (in which case I'd have to rebrand).

@laanwj the ATI share holders are still in the process of figuring out the future of their organization and the trademark that goes with it. Some meaningful milestones will be reached on that front sometimes this summer. 

Up until then, they won't forward development. What happens after that, I don't know. Currently I have a verbal agreement with the share holders, where they acknowledge that I sustain the value of their brand name by maintaining the code base, and thus gracefully allow me to use it.

My current intention is to enjoy this arrangement until fall, at which point I expect to have implemented BIP32/44 and segwit support. With (then) a clear view on the corporate side, I will have to evaluate the situation and act accordingly.

Originally, the share holders stated they were open to giving me a renewable authorization (in writing) to use their trademark as long as I don't monetize it (which I don't intent to anyways). If that proposal still stands come September, I will do due diligence.

If it doesn't, I will consider starting a crowd funding campaign (after probing the Armory community) to purchase the trademark and domain name from the share holders. As you may tell, I am attached to this name and would hate to see it go away.

If push comes to shove, I will have to rebrand. Hopefully it won't go down that path.

--------------

As for reinstating Armory on bitcoin.org, that's a tricky question. I am Armory in practice, but not on paper. Listing both bitcoin.org and my github release page will indeed confuse users, but anyone coming on the Armory forums to seek help or report bugs will be redirected to my versions.

Maybe the wiser path is to wait for fall when I can bring clarity to the situation. I hope I'm not shooting myself in the foot saying this.

**Comment by crwatkins** [comment]
@goatpig It looks like we are taking the ["wiser path"](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1301#issuecomment-225040188) that you suggested and are waiting to hear from you on any updates on this situation.  Be sure to let us know when you know, as I would like to see Armory listed again when it is appropriate.  Again, thanks for your commitment to the project.

**Comment by Kludge1** [comment]
FYI...goatpig's Armory fork now has a new website: http://btcarmory.com/

**Comment by achow101** [comment]
Rebased this onto master and set the link to the new website

**Comment by crwatkins** [comment]
@achow101 thanks for the update.  It's great to see the project moving forward and I'm glad to see the information on the new website.

There are a few requirements on the trust and security aspects of the wallet's website from the [wallet criteria](https://github.com/bitcoin-dot-org/bitcoin.org#wallets).  Specifically, the following criteria need to be met for listing:

- Website supports HTTPS and 301 redirects HTTP requests
- SSL certificate passes [Qualys SSL Labs SSL test](https://www.ssllabs.com/ssltest/)
- Website serving executable code or requiring authentication uses HSTS with a max-age of at least 180 days

Note that HSTS preload is not yet required (although I would recommend it), so it would be good to change the link in the listing to https.

Once these criteria are met, I'll be happy to recommend Armory for listing.

**Comment by achow101** [comment]
@crwatkins The main issue with HTTPS is that Github Pages does not support HTTPS for custom domains.  Do you have any ideas on how we could do that?

**Comment by achow101** [comment]
I've added HTTPS support to the website.

**Comment by crwatkins** [comment]
CloudFlare is fine.  Could you have them redirect http to https?
Also, be sure to update the URL in the PR to https.

**Comment by achow101** [comment]
Done.

**Comment by crwatkins** [comment]
LGTM.  Thanks @achow101.  I recommend Armory for listing.

**Pull request merged**
