### PR TITLE
Adds Coldcard

### PR DESCRIPTION
**Pull request by nvk**
Second time is the charm, Cobra encouraged me to open this PR again.

### CODE REVIEW

**Comment by crwatkins** [comment]
@nvk  Great!  Thanks for resubmitting.

To move this along as fast as possible could you point out how the six issues in the [original review](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-433630363) have changed or been addressed?   In particular, can you explain the keyboard issues and how they have been addressed and what the expected performance is now?  Also, it would sure save some time if you can site any new technical reviews or evaluations (anything more than unboxings or demonstrations).

**Comment by nvk** [comment]
Copied from the end of the previous thread:

1. The wallet has been released for at least three months
2. The wallet has received sufficient user feedback
3. The coldcard.com web site security (redirection, HSTS) has been improved
4. The device keypad no longer generates spurious presses and is easier to use
5. The PR has been updated for style and scoring
6. Removal of the 10% fee restriction has been considered

Answers:

1. Wallet has been around for a while now.
2. There been lots of reviews, [here is one](https://bittybot.co/uk/coldcard-review/) and a [video review here](https://www.youtube.com/watch?v=f8dBNrlwJ0k)
3. this was [completed](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-437074901)
4. [Latest firmware](https://blog.coinkite.com/coldcard-v110/) has improved the touch and the [new Mk2 version has real keys](https://twitter.com/nvk/status/1087370543689433088) 
5. Not sure what you need changed.
6. Was addressed on this [firmware upgrade](https://blog.coinkite.com/coldcard-v110/)

**Comment by maxwellmons** [comment]
Hi @nvk. What is Coldcard's warranty and return policy?

**Comment by nvk** [comment]
> Hi @nvk. What is Coldcard's warranty and return policy?

Cheap & FOSS, so officially sold "as is". 

But, we do make a point at replacing any factory defective devices for free, also ship them to ppl for free.

**Comment by crwatkins** [comment]
@nvk, can you comment more on the new Mk2?  I'm optimistic it will solve all the existing keypad issues.
1. Does my optimism sound realistic to you?
1. I don't see the original version on your web site.  Will it continued to be offered or will Mk2 replace it?
2. The Mk2 seems to be in pre-order.  Do you have a target delivery date yet?
2. Are there any other changes other than the keypad that we should be aware of, specifically anything that would change any functionality?  
3. Will they run the same code (other than keypad specific drivers and settings)?

Thanks.  I'll review the other items shortly.

**Comment by nvk** [comment]
@crwatkins 

1. Yes, it's a physical keyboard (metal contacts under membrane) so RFI on capacitive touch is a non-issue.
2. This coming batch is all physical keys, there is no point in maintaining two separate versions.
3. It's in production, we hope to be shipping out soon. (The video of the actual manufacturing test unit was on that video above)
4. Same, just physical contact now.
5. All the same functionality. The new version has incremental improvements like power control, more protected bus trace, etc...

**Comment by crwatkins** [comment]
I apologize for answering questions one at time, but I'm trying to move things along instead of saving up until I can provide all the answers.  Feel free to batch up my comments until I review the entire list.

@nvk wrote 

> Not sure what you need changed.

1.  Description text
2. **transparency** score

From the original review

> In regards to the description text in [...], for style and consistency reasons, there should be no words in all capitals nor any exclamation marks, and the spellings "open-source" and "MicroPython" should be used. I would further recommend, but up to you, for readability that open-source be only mentioned once, backup be only mentioned once (sentences combined), and that "no app required" be removed or reworded because clearly Electrum is required. The score for transparency is **checkgoodtransparencydeterministic** but I don't see any deterministic build procedures such as Gitian or Docker, so I suspect you want to change it to **checkpasstransparencyopensource**.

I know that's a lot of picky notes, so I'll just provide an example of what I mean that you can work with if you like:

"Coldcard is an easy to use, ultra-secure, open-source and affordable hardware wallet that is easy to back up via an encrypted microSD card. Your private key is stored in a dedicated security chip. MicroPython software design allows you to make changes."

**Comment by nvk** [comment]
Thanks, @crwatkins tweaks made.

**Comment by crwatkins** [comment]
***Resolutions of the open items***

1. The wallet has been released for at least three months

  The wallet was eligible for listing on 15 November 2018

2. The wallet has received sufficient user feedback

  There have been more reviews and user feedback since the last review including the video that @nvk mentioned above (the review @nvk mentioned was reference in the original review here).

  https://www.bitnewslive.net/2018/11/08/review-coldcards-btc-hardware-wallet-is-air-gapped-for-added-security/56250/

  https://www.reddit.com/r/Bitcoin/comments/9tuhay/coldcard_wallet_is_a_pain_in_the_ass_dont_buy/
 
https://www.reddit.com/r/Bitcoin/comments/aaehwm/coldcard_wallet_response_to_walletfail_unaffected/

  While some of the feedback is not completely posItive, any feedback implies some level of usage.  I believe this borders on the bare minimum of feedback that we expect.

3. The coldcard.com web site security (redirection, HSTS) has been improved

  Confirmed that coldcardwallet.com is on the HSTS preload list.

4. The device keypad no longer generates spurious presses and is easier to use

  @nvk states above that a new version with physical buttons which solves this issue will soon be shipping.

5. The PR has been updated for style and scoring

  This was updated in 3d0a413 & 6b4b47c.

6. Removal of the 10% fee restriction has been considered

  This is now configurable.

---

I recommend testing of the new Mk2 device for any keypad issues as soon as it is released .  After being tested without issue by any regular contributor, I would recommend immediately (without any additional three month delay) listing the new Mk2 device.

**Comment by crwatkins** [comment]
A new Mk2 device was provided to bitcoin.org by Coinkite at no cost.  I reviewed the new keyboard on the device by restoring a 24 word seed and signing a message with the device using Electrum.  I found no issues with the new keyboard. I recommend Coldcard for listing.

I concur with the scoring in 6b4b47c.

**Comment by wbnns** [comment]
@crwatkins Thank you.

This is scheduled to be merged on Wednesday, May 1st.

**Comment by nopara73** [comment]
I know this PR has been merged already, but I guess another confirmation doesn't hurt. I reviewed the Coldcard Mk2, too and it fixed the cable and button issues the Mk1 had, so I'd give a 5 day late ACK for this PR.

**Comment by wbnns** [comment]
@nopara73 Thanks!

**Pull request merged**
