### PR TITLE
Add OKCoin to list of exchanges

### PR DESCRIPTION
**Pull request by dyljm1**
https://www.okcoin.com

### CODE REVIEW

**Comment by Lev-8** [comment]
dyljm1:patch-1

> https://www.okcoin.com

**Comment by Lev-8** [comment]
#3431

**Comment by Lev-8** [comment]
Файли змінені

**Comment by haidersf** [comment]
> Файли змінені
What is the next step to get us published on bitcoin.org? It looks like the PR was approved. Thanks.

**Comment by haidersf** [comment]
Thank you @Cobra-Bitcoin. Anything we need to do from our end as a next step?

**Comment by Daniel-Leedan** [comment]
@haidersf The PR merged, OKCoin published on bitcoin.org.

URL: https://bitcoin.org/en/exchanges

## Screenshot

image

**Comment by haidersf** [comment]
thank you! really appreciate it.

**Pull request merged**
