### PR TITLE
add Bull Bitcoin to exchange list (Canada)

### PR DESCRIPTION
**Pull request by mixamilast**
Add Bull Bitcoin ( Bullbitcoin.com) to the exchange list for Canada

### CODE REVIEW

**Comment by wbnns** [comment]
Hello, we began to review the exchange, however, we've encountered issues. Please let us know when they are resolved and we'll reopen the PR / resume the review.

### Mobile

The layout appears broken on mobile (iPhone X, Pixel 2 XL) for users who aren't logged in (i.e. people visiting the homepage on their phone for the first time):

image

As well as for people who are logged in:

image

It seems one or more styles are overflowing beyond 100% of the width of the viewport, causing the horizontal scrolling effect. Meanwhile, the navbar is stopping at 100% of the viewport size.

### Desktop

For people who aren't on mobile, when logged in, the "Announcement" text on desktop (Chrome) gets cut-off and can no longer be seen. People wouldn't be able to tell if there is an announcement due to this:

image

People who aren't logged in, can see the Announcement without issue:

image

**Comment by mixamilast** [comment]
We have made the corrections

**Comment by mixamilast** [comment]
We have made the corrections. Thanks for the feedback.

**Comment by wbnns** [comment]
Reopening; we are reviewing this again.

**Comment by wbnns** [comment]
@mixamilast 

Just an update, we reached out to Bull Bitcoin via email last week regarding the recently updated [documentation](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md) for adding exchanges, to see how you all would like to proceed.

**Comment by wbnns** [comment]
We did not receive a reply from Bull Bitcoin. Closing for now.

**Pull request closed without merging**
