### PR TITLE
Update mSigna link

### PR DESCRIPTION
**Pull request by nickycutesc**
The original link for mSigna throws a connection error. Perhaps the website's certificate expired?

### CODE REVIEW

**Comment by crwatkins** [comment]
Yes, @nickycutesc the certificate has expired.

@CodeShark You might want to check the certificate.

**Comment by laanwj** [comment]
welcome to the season of forgotten certificate updates :smile:

**Comment by jdabs** [comment]
@laanwj & @CodeShark there's an open source app for that https://certificatemonitor.org/

**Comment by nickycutesc** [comment]
Here's another link affecting mSIGNA:

https://bitcoin.org/en/wallets/desktop/windows/msigna/

**Comment by wbnns** [comment]
Two weeks have passed without a reply. This is also the second time the website has gone down in the past year, where we've had to notify the developer (#2767). Lastly, the GitHub repository for the wallet itself, hasn't been updated in two years.

#3223 has been opened to remove the listing.

**Pull request merged**
