### PR TITLE
Add correctly sized icon for Simple Bitcoin Wallet

### PR DESCRIPTION
**Pull request by btcontract**

### CODE REVIEW

**Comment by crwatkins** [comment]
@btcontract, thanks for such a quick update to your icon; I'm sorry we didn't catch that before merging.

LGTM.

**Comment by schildbach** [comment]
These commits should be squashed into one. There is no need to replace and delete the icon 4 times in 5 commits (one commit being empty).

**Comment by crwatkins** [comment]
True.

**Comment by btcontract** [comment]
Similar PR from @schildbach replaces icon in one commit, should I just close this one?

**Comment by laanwj** [comment]
> These commits should be squashed into one. There is no need to replace and delete the icon 4 times in 5 commits (one commit being empty).

Yeah, this looks strange, and apparently didn't work.

**Comment by btcontract** [comment]
Well this is embarrassing. I've used github web interface to upload a correct icon last time because was away from working machine. Here's a new PR which undoes this one and adds an icon avoiding web interface, hope I did it right this time: https://github.com/bitcoin-dot-org/bitcoin.org/pull/1321

**Comment by schildbach** [comment]
I think it's a webserver synching problem. The git repo has the correct icon.

**Pull request merged**
