### PR TITLE
Add Specter Wallet

### PR DESCRIPTION
**Pull request by k9ert**
This PR wants to add specter-wallet ([website](https://specter.solutions),[github](https://github.com/cryptoadvance/specter-desktop)) to the bitcoin.org wallet selector.

Here are the answers to the question in managing-wallets.md.

thanks and cheers

## Sufficient users and/or developers feedback can be found without concerning issues, or independent security audit(s) is available
We have quite some coverage from Bitcoin-influencers e.g. [Livera](https://stephanlivera.com/episode/205/) and [TFTC](https://talesfromthecrypt.libsyn.com/214-ben-kaufman). There is a security-focused review from Michael Falxman at https://btcguide.github.io/. 

## No indication that users have been harmed considerably by any issue in relation to the wallet
Nothing found or heard about.

## No indication that security issues have been concealed, ignored, or not addressed correctly in order to prevent new or similar issues from happening in the future
We address them quite fast as we're focusing on security very much.

## No indication that the wallet uses unstable or unsecure libraries
We're quite quick adopting new versions. Currently we've already included [HWI2](https://github.com/cryptoadvance/specter-desktop/pull/1001) and we're releaseing almost every 3 weeks on average. 
We're also using the dependabot on github to get notified on security issues.

## No indication that changes to the code are not properly tested
See our section on [automated testing](https://github.com/cryptoadvance/specter-desktop/blob/master/DEVELOPMENT.md#developing-on-tests). We do unit- and end2end-testing (via cypress) apart from a lot of manual testing on each release.

## Wallet was publicly announced and released since at least 3 months
See the first question with the coverage on Social Media.

## No concerning bug is found when testing the wallet
We didn't found any.

## Provides a bug reporting method on the website and/or in the app
Whenever you get an exception on the screen, there is a direct link to our [issue-tracker](https://github.com/cryptoadvance/specter-desktop/issues) on github. We also provide a link to our [Telegram-group](https://t.me/spectersupport) which has over 1100 members in the meantime, many of them technical and advanced Users.

## Website supports HTTPS and 301 redirects HTTP requests
```
➜  ~ curl -I http://specter.solutions/                                  
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 22 Mar 2021 10:22:26 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://specter.solutions/
Host-Header: 8441280b0c35cbc1147f8ba998a563a7
X-HTTPS-Enforce: 1
X-Proxy-Cache-Info: DT:1
➜  ~ 
```

## SSL certificate passes [Qualys SSL Labs SSL test](https://www.ssllabs.com/ssltest/)

  See: https://www.ssllabs.com/ssltest/analyze.html?d=specter.solutions where we get an overall-rating of "A"

## Website serving or linking to executable code or requiring authentication uses HSTS

Not sure what this is about?!

  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

## The identity of CEOs and/or developers is public
Specter-desktop is developed by https://specter.solutions which is mainly Stepan Snigirev, Ben Kaufman and Kim Neunert. The CEO of specter-solutions is Moritz Wietersheim.

## Avoid address reuse by displaying a new receiving address for each transaction in the wallet UI
Yes.

## Avoid address reuse by using a new change address for each transaction
Yes.

## Uses deterministic ECDSA nonces (RFC 6979)
Yes, as specter-desktop is using Bitcoin Core and Core does that.

## User has access to private keys for all major components of the wallet
The connection from teh app to HWW for cold-storage is the main point of specter-desktop. However there is also a hotwallet which we encourage to only use for minor amounts and test-purposes.
The backend for the hotwallet-feature is Bitcoin-Core.

## If private keys or encryption keys are stored online
Depends on the meaning of online (regarding the hot-wallet feature). Specter-desktop is a software to host on your own. Usually people use it in the form of an Electron-app, some use it in node-packagers like raspiblitz or umbrel. If that's "online" and the user is using the hotwallet-feature, then we're storing keys online.

## If user has exclusive access over its private keys:

##Allows backup of the wallet
For the hotwallet, the user has to write down the keys himself. Apart from that, all config (xpubs/txs/...) are available for a backup.

### Restoring wallet from backup is working
Yes.

### Source code is public and kept up to date under version control system
[Yes](https://github.com/cryptoadvance/specter-desktop)

## If user has no access to some of the private keys in a multi-signature wallet
No applicable

### CODE REVIEW

**Comment by crwatkins** [comment]
@k9ert Thanks for the submission!   Also thanks for the careful review of the listing criteria.   That will certainly help speed up the process.

> * Website serving or linking to executable code or requiring authentication uses HSTS
>
> Not sure what this is about?!

This relates to [RFC6797](https://tools.ietf.org/html/rfc6797) and the willingness to be included in the [HSTS preload list](https://hstspreload.org/) which is used by most (all?) major browsers to hardcode HTTPS-only sites.  The awkward wording of the criterion was a result of trying to not tie the requirement to the submission nor the inclusion to any one particular browser vendor.

**Comment by k9ert** [comment]
Thank you for your fast reply. We're currently looking into getting HSTS fixed as this is indeed not yet done.
If you have any additional questions or recommendations, happy to answer them!

**Comment by crwatkins** [comment]
Thanks @k9ert 

Our normal Travis CI is not running currently to verify the files in this PR, so I did a quick look to keep us moving along.  I don't normally do this, so be sure to challenge anything I might have wrong here.

* Screenshot: The png files must go in /img/screenshots, be 250 X 350 px and optimized with optipng -o7 file.png.

I believe the screenshot submitted is 350x250, not 250x350

* Icon: The png file must go in /img/wallet, be 144 X 144 px and optimized with optipng -o7 file.png. The icon must fit within 96 X 96 px inside the png, or 85 X 85 px for square icons.

The icon file seems to be the correct size, but perhaps you want a transparent background instead of the light blue.   If you do indeed want that blue background, it should fit within 85x85 (to be honest, I didn't check but I think it is much bigger than that).

In the `walletspecterdesktop` translation string, could you move it up at least three lines in the file to group it with the other wallet descriptions?

Could you rename specter-desktop.md to specterdesktop.md?  I'll claim it is for consistency and to match the `id` in the file, and I think that's all, but I do know the build system had problems in the past and this might be safer.

The features list includes 2FA.  We define it as

* Two-factor authentication (2FA) is a way to add additional security to your wallet. The first 'factor' is your password for your wallet. The second 'factor' is a verification code retrieved via text message or from an app on a mobile device. 2FA is conceptually similar to a security token device that banks in some countries require for online banking. It likely requires relying on the availability of a third party to provide the service.

Specter certainly has multiple hardware wallet support, and perhaps that could vaguely be considered "two factor" by some, but this designation is more targeted at a third party service.   Referring to the the multisig feature defintion:

* To qualify for supporting this feature, the wallet must give the user the ability to delegate authority to other users participating in multiple party transactions. While some services provide authorization features (such as 2FA) based on multisignature technology, that is not this feature.

By these definitions, Specter obviously qualifies for the multisig feature, but I don't believe it employs 2FA as defined here.  Is that right?

Likewise, environment is listed as  `checkpassenvironmenttwofactor`which should probably instead be `checkfailenvironmentdesktop` (like Bitcoin Core).

The validation score is listed as `checkgoodvalidationfullnode`, but the currently released version requires a Bitcoin Core node be installed so it should probably be `checkgoodvalidationfullnoderequired` to explain a full node needs to be installed.   I know future versions will make this install much easier, but they will still technically require an install, right?

**Comment by k9ert** [comment]
Hey Craig, thank you very much so far, appreciated! 
I've addressed most of your points:
* new screenshot with the right size optipnged
* icon: I guess i misunderstood that, so now we have a transparent "border" around the light-blue. I took 85px. Not 100% sure what's meant with "square icons" as 96x96 is square to me as well.
* Moved the translation-string
* renamed the file, the id-inside and all other file-names are now specterdesktop.*
* agree that 2fa does not fit here. Should have read more closely. Removed the feature
* Also changed the environment to `checkfailenvironmentdesktop`

Also we have HSTS figured out in the meantime. We're green according to:
https://hstspreload.org/?domain=specter.solutions

The last point about the fullnode-validation: We have released yesterday with the download-feature. So i think specter-desktop qualifies for `checkgoodvalidationfullnode`.

> I know future versions will make this install much easier, but they will still technically require an install, right?

It depends on what you exactly consider an "install":
* Does it mean it downloads artifacts from the internet?
Yes, currently the bitcoind-daemons are downloaded from the internet. (including verifications of keys/sha256)
The same is happening internally when you start the electron-binary: It will fetch the current valid specterd-binary from github-release-page but is that an installation? I don't think so.

* Does "installation" means that the operating-system is used in any way starting an installer or something?
The bitcoind-download and kicking off is entirely done within specter. No interaction apart from clicking specter-buttons is necessary

* Does the "installation" creates directories outside the existing ones, making other changes to the OS or creating huge amount of new data?
No, by default specter will store the bitcoind-binaries and the data inside its `~/.specter` folder, ONLY. However, yes, the pruned-node-data will get downloaded and you'll need another 4G of free space on disk.

* Does "installation" means that the user is responsible for maintaining that installation?
The changes in pre3-pre9 made sure that specter is taking responsibility for that "installation". You can watch the logs from within specter but that's only necessary if something goes south similiar to showing stacktraces if specter-crashes. So technically we're using bitcoind as an internal component of specter (but completely unmodified).

So i think even from a technical point of view, it's not an "install" and therefore `checkgoodvalidationfullnode` is correct.

Let me know what you think.

**Comment by crwatkins** [comment]
@k9ert Thanks for all your very quick updates!   I will check them out shortly.   I’m sorry I forgot to ask one question about deterministic builds yesterday:  Do you have any instructions for deterministic builds?  You submission selected that tag and I couldn’t find any.

**Comment by crwatkins** [comment]
Thanks for such fast updates.

>  I took 85px. Not 100% sure what's meant with "square icons" as 96x96 is square to me as well.

I _think_ that means that icons that are square and have content out to each corner should limit their size to 85x85, while those that are round, or have irregular edges can extend to 96x96.  The first time I saw that I found it very curious, but when the icons are presented as a group together, it does seem to work out very well.

> The last point about the fullnode-validation: We have released yesterday with the download-feature. So i think specter-desktop qualifies for checkgoodvalidationfullnode.

Unless anyone objects to your explanation, while the review is based on the previously (before yesterday) released version, the scoring will be based on yesterday's version.

I think the only outstanding item is my question above regarding deterministic builds.  Thanks!

**Comment by k9ert** [comment]
> Unless anyone objects to your explanation, while the review is based on the previously (before yesterday) 
> released version, the scoring will be based on yesterday's version.
Oh, i guess we should have waited for 2 more days in that case. What would you recommend? Should we create a new PR? pre6 is not that different from the release and it had the download-feature already built in (if that helps).

> I think the only outstanding item is my question above regarding deterministic builds. Thanks!
I've created build-instructions here:
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/build-instructions.md

As we're in practice almost entirely (not the MacOS builds) create the release-artifacts automatically,  there is also a description on how to create your own release-infrastructure here:
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/continuous-integration.md#cicd-dev-env-setup

**Comment by crwatkins** [comment]
@k9ert Thanks! 

As you mention in that doc
> The result unfortunately is not stable in terms of identically sh256-hashes, though.

Regretfully, that's the type of deterministic build we are referring to here, so the transparency should be `checkpasstransparencyopensource`

**Comment by k9ert** [comment]
> Regretfully, that's the type of deterministic build we are referring to here, so the transparency should be 

I was not sure because that haven't been mentioned in the document. I've adjusted it and also changed to `checkgoodvalidationfullnoderequired`.

**Comment by crwatkins** [comment]
> I've adjusted it and also changed to `checkgoodvalidationfullnoderequired`.

I haven't heard any objections, so that could go either way as far as I'm concerned.  Feel free to change it now or later.

**Comment by crwatkins** [comment]
I have reviewed the Specter Desktop wallet from Specter Solutions based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design and I'm glad to recommend Specter Desktop for listing.

**NOTE** v1.2.2 was reviewed, but the scoring reflects the newer v1.3.0.

I concur with the scoring in aa8d1fa

---


## Specter Desktop
### Version v1.2.2
### Review Version 2021032701

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

  **PASS** Over 50 contributors on GitHub, some known developers, is one of the best forms of feedback.  Also, numerous YouTube howto videos and howto guides provide feedback on the quality as well as frequent feedback in [GitHub issues](https://github.com/cryptoadvance/specter-desktop/issues).

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

  **PASS** No indication

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

  **PASS** No indication

  **NOTE** Specter relies heavily on Bitcoin Core via RPC.  Specter can be called on to generate a BIP39 mnemonic for a hot wallet and does so using [Trezor's Mnemonic library](https://github.com/trezor/python-mnemonic/) which relies on Python's os.urandom().  Without knowing all the OSs that this might be installed on, it's slightly concerning that multiple entropy sources are not used. However, the hot wallet feature is labeled "less secure and are not recommended for use with significant amounts" and there is an option for the user to supply an external mnemonic.  

- No indication that changes to the code are not properly tested

  **PASS** Automated unit testing and end-to-end testing is [performed](https://github.com/cryptoadvance/specter-desktop/blob/master/DEVELOPMENT.md#developing-on-tests) by Cypress.

- Wallet was publicly announced and released since at least 3 months

  **PASS** Tagged releases with release notes have been available for over nine months

- No concerning bug is found when testing the wallet

  **PASS** No concerning bugs found

- Provides a bug reporting method on the website and/or in the app

  **PASS** Multiple contact options at https://specter.solutions and links in the app

- Website supports HTTPS and 301 redirects HTTP requests

  **PASS** https://specter.solutions redirects

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

  **PASS** https://specter.solutions: A Rating

- Website serving or linking to executable code or requiring authentication uses HSTS
  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

  **PASS** https://specter.solutions/

- The identity of CEOs and/or developers is public

  **PASS** https://specter.solutions/about/

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **PASS**

- Avoid address reuse by using a new change address for each transaction

  **PASS**

- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS** Uses Bitcoin Core (or hardware wallets) for signatures

- User has access to private keys for all major components of the wallet

  **PASS** Private keys are not stored by Specter.  Private keys are stored by hardware wallets or in Bitcoin Core when using the (not recommended by Specter) hot wallet option.

- If private keys or encryption keys are stored online:

  **N/A**

  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

    **PASS** BIP39 mnemonic can be recorded for the hot wallet option

  - Restoring wallet from backup is working

    **PASS** A BIP39 mnemonic was restored successfully

  - Source code is public and kept up to date under version control system

    **PASS** https://github.com/cryptoadvance/specter-desktop/ with very good release tagging and release notes

- If user has no access to some of the private keys in a multi-signature wallet:

  **N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:

  **N/A**

  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code created for all open components and provides detailed specification for blackbox testing of
    any closed-source secure elements

Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

  **PASS**

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

  **PASS** specter.solutions is included

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

    **PASS**

  - Provides users with step to print or write their wallet seed on setup

    **PASS** Specter provides this for the hot wallet option

  - Uses a strong KDF and key stretching for wallet storage and backups

    **NOTE** Specter does not store any private key information and it does not provide any encryption options for local storage or backups

  - On desktop platform:
    - Encrypt the wallet by default

      **FAIL** Note that Specter does not encrypt local storage, but no private key information is stored, so this would be more of a potential privacy concern than a direct funds security issue.

- For hardware wallets:
  - Prevents downgrading the firmware

    **N/A**

**Comment by crwatkins** [comment]
Thanks for the squash.
LGTM 848ffe7

**Comment by k9ert** [comment]
Squashed the commit and changed:
>        validation: "checkgoodvalidationfullnode"
in agreement with Craig.

**Comment by Cobra-Bitcoin** [comment]
This looks ready for merge, though I need to run the tests on this branch locally before merging to catch any issues because Travis isn't working right now.

**Pull request merged**
