### PR TITLE
Rpc 0.14.1 update

### PR DESCRIPTION
**Pull request by Mirobit**
Updated the RPC commands documentation as of 0.14.1

@harding I am sorry to ask but it would be great if you find the time to review this.

### CODE REVIEW

**Comment by harding** [comment]
@mirobit excellent update, as always!  I sent some suggested edits in https://github.com/Mirobit/bitcoin.org/pull/8 , but otherwise this LGTM.  Thank you!

**Comment by Mirobit** [comment]
@harding Thank you very much for the fast and thorough review. Merged all edits.
Also fixed some examples.

**Comment by harding** [comment]
a889ba7 LGTM.  Thanks!

**Comment by wbnns** [comment]
Unless others object, this will be merged on Wednesday, May 10th (tomorrow).

@Mirobit @harding Thanks!

**Pull request merged**
