### PR TITLE
added bitaps.com to Charts and Statistics

### PR DESCRIPTION
**Pull request by 4tochka**
bitaps.com  - Addresses distribution chart, last blocks, mempool stats and fee distribution chart, nodes map, PoW stats ...

### CODE REVIEW

**Comment by 4tochka** [comment]
bitaps.com - Addresses distribution chart, last blocks, mempool stats and fee distribution chart, nodes map, PoW stats ...

**Comment by crwatkins** [comment]
bitaps.com does not seem to be listening on http (port 80).
Is it intentional not to have a redirect there?

**Comment by wbnns** [comment]
@crwatkins Loads here; it redirected to https. Did you get a timeout error?

**Comment by 4tochka** [comment]
fixed firewall rules for 80 port opened

**Comment by wbnns** [comment]
This is scheduled to be merged on Friday, February 15th.

**Pull request merged**
