### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by mateuszrybin**
Hey guys,

So this is kind of a big pull request :)

It about the redesign that I suggested last year: #1078 

**I do have some problem:**
1. I have tested with travis and the only test that fail is check-jshint.
2. I just can't get the event page to work, I have tried and tried.
3. Also last year I had problem with glossary index page, so I rewrote it manually. 
   ..
4. the flags are also missing in menu I see now when I made the preview, so will fix that later :)

**Preview:** http://mateuszrybin.github.io/

if there anything you need, just say. And sorry about the delay. 
Cheers,
Mateusz

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
You've done an amazing job on this, but I'm personally not a fan of the new design, I think it makes things look excessively big. Would be interested to hear what others think though.

**Comment by carnesen** [comment]
@mateuszrybin I think the new site design looks great, a marked improvement over the current one. I'm sorry to say that since last fall when you opened https://github.com/bitcoin-dot-org/bitcoin.org/issues/1078, there's been a mass exodus of contributors to this site due to disagreements with the site owners @Cobra-Bitcoin and @theymos. In particular the Bitcoin Core team has spun on their own separate site https://bitcoincore.org/. The previous primary maintainer of this site @harding is busy at https://21.co/, and the other maintainer @saivann I'm not sure, but I haven't seen any activity here from him in quite a while. That's why your pull request sat idle for 17 days. The eventual terse response from the site owner is a fitting indicator of the current state of affairs here. On principle I no longer contribute, but in this case I thought you'd appreciate some background info to better understand what you're up against in trying to get this PR accepted. Thank you for your hard work, and good luck!

**Comment by mateuszrybin** [comment]
Hey @carnesen thanks for the background info. Yee that is kind of sad to hear. I really approached you taking the time to explain the situation. Hopefully it will improve, but now I atleast know why the lack of any respons. Thanks!

**Comment by g4p** [comment]
The design has some nice improvements, but the use of space could be improved: the design seems to be made for a very large resolution and not be as responsive to lower resolutions as it might be

**Comment by mateuszrybin** [comment]
Hey @g4p. It's responsive down to mobile, so I am a bit confused about your statement. Could you explain more :)

**Comment by crwatkins** [comment]
Hey @mateuszrybin this is an incredible amount of good work, particularly given how complex this site is; congratulations!

I think I understand what @Cobra-Bitcoin and @g4p may be referring to about size.  For example, on my 1440x900 laptop I can only see the icons of eight wallets (if I scroll just right, only four if I'm at the top of the page) because they are quite large.  I would like to be able to see the entire selection of wallet icons at once.

I pay most attention to the wallet area of this site and I have to say that I definitely appreciate the changes that you have made to eliminate the popups and the mouse overs, which I believe were somewhat difficult to use at times.

I have one note about some lost information in the wallet privacy scoring.  You convey pass/fail status of the scoring categories with the color of the text of the headers.  However when I open the privacy section there are three subsections which previously indicated pass/fail status by the color of the text.  I'm not necessarily suggesting that you color the text, but rather somehow indicate the pass/fail status of the subsections (using the existing algorithm to choose).

**Comment by mateuszrybin** [comment]
Hey @crwatkins, Thanks for the feedback. Yee the privacy need a bit more work.

About the sizing, the whole website is designed using relative units (RMS), so the size can be easily change to whatever you want. Just go into inspector in chrome, click on html tag and change the "font-size" to whatever and tell me what size fits best. I personly thing that the larger size is better being that bitcoin.org is a information giving type site. 

But I haven't work on the site since I made the request, because the question if it will be approved is blurred and I would like to have a confirmation from the site owner/owners, @Cobra-Bitcoin, and a list of fixes and adjustment that are needed to have the design approved.

**Pull request closed without merging**
