### PR TITLE
Updated requirements in full-node.md

### PR DESCRIPTION
**Pull request by Jorgeminator**
Updated disk space and bandwidth requirements due to blockchain growth.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK bc8ad6e

**Comment by jgarzik** [comment]
ACK as written, though my preference would be 80 G.

**Comment by harding** [comment]
PR updated to use site-wide variables for chain size (initial download) and disk space needed (higher than strictly necessary to allow for moderate growth).  For the disk space needed, this was bumped up to 80G per @jgarzik's suggestion.  Preview:



We can do some rewriting here when 0.12 is released and it becomes possible to use pruning without disabling the wallet.

Since the current values are out of date and the general feedback seems positive, I'm marking this as merge scheduled for Thursday.  Please comment if you have unaddressed concerns.

**Comment by MarcoFalke** [comment]
> We can do some rewriting here when 0.12 is released and it becomes possible to use pruning without disabling the wallet.

Also there is `-maxuploadtarget` in `0.12`.

**Pull request merged**
