### PR TITLE
[Full-Node] Added Win7 Daemon doc.

### PR DESCRIPTION
**Pull request by Gyomu**
Win7 Daemon doc as stated in #988

### CODE REVIEW

**Comment by harding** [comment]
@Gyomu thanks!  These look perfect to me.  Here's a preview of how they'll look when merged: http://dg0.dtrt.org/en/full-node#win7-daemon

In the absence of critical feedback, this pull will be merged Tuesday.  (You can close #988 whenever you want, or I'll close it when this gets merged.)

**Comment by Gyomu** [comment]
Seems perfect to me too. Closing this then.

**Comment by harding** [comment]
@Gyomu whoops; this should stay open for merging while #988 can be closed.  I'll fix it up.

**Comment by Gyomu** [comment]
whoopsie indeed. Wrong ticket closed. :/

**Pull request merged**
