### PR TITLE
Add Karsha Exchange

### PR DESCRIPTION
**Pull request by khashmeshab**
No2X Running Bitcoin Core.

### CODE REVIEW

**Comment by Mirobit** [comment]
NACK:
- More a digital money exchange that also supports Bitcoin than a real bitcoin exchange.
- Looks dodgy: no about us, Iranian bank account, perfect money

**Comment by khashmeshab** [comment]
Replying to Mirobit:
- We support 8 cryptocurrencies, and 4 e-currencies, plus bank transfer and Visa and MasterCard. Previously we only supported Bitcoin. Our altcoins system is new, we are working on it to make it more cryptocurrency-friendly!
- No about us: you can find it in our whois. Iranian bank account: probably was shown automatically based on your location and our balance. There are accounts in Canada and UK too. Perfect Money: what about it? Most of our customers buy/sell Bitcoin to that!

Also please take a look here:
https://en.bitcoin.it/wiki/Karsha_Mobile_Payment_Interface
And here:
https://en.bitcoin.it/wiki/Karsha_Shopping_Cart_Interface

Both are now defunct, but they show we are in Bitcoin business for a long time. We are one of the first exchanges which support Bitcoin. We had little activity in previous years, and that's why we are not known in the field. Our domain is 8 years old.

**Comment by khashmeshab** [comment]
Hello again,

It's been 20 days since I submitted this PR. We've been already added to the Bitcoin Cash and Monero exchanges list. If there is any problem, please let me know so we could resolve them.

We are in this business for more than 8 years, and while it's true that there are little reviews of our website and services, but there is absolutely zero negative reviews of us. Also, nobody has objected to this PR. The lack of reviews are mostly because we were mostly working with local clients. We were also mostly inactive for the past two years. Now we've got new investments, we've upgraded our automatic exchange system, and introduced new services. We are serious to have a share in the cryptocurrency market. I appreciate your help.

Thank you.

**Comment by wbnns** [comment]
@khashmeshab Hello, thanks for submitting this. According to your exchange's Facebook page, you all are an Iranian exchange, so if you would like your site to be potentially included, please resubmit as an exchange in Iran, rather than as an addition to the international category. Also, when you resubmit, could you please clarify how you all will be handling the upcoming fork?

**Comment by khashmeshab** [comment]
@wbnns Hello. The Facebook page is years old, and is only automatically updated by our Twitter account. As I said, we were a local exchange in Iran for years. Then I moved to the UAE and our exchange website was mostly inactive for about two or three years. Then I received some investments and decided to re-open the website.
We provide service to international customers, I don't understand why should we categorized as an Iranian exchange? Simply because we still have a bank account there? We have bank accounts in Canada and the UK too. Then again, our website completely blocks Iranian IP addresses, because of reasons.
With above explanations, if you still insist that we are an Iranian exchange, then OK. I can remove the Iranian bank account from our website. I can remove any trace to Iran from our Facebook page if that solves the problem. We are not Iranian anymore. We provide global services. We block Iranian IPs.
I would be thankful if you rethink your decision.

**Comment by wbnns** [comment]
@khashmeshab Ok, thanks for clarifying - yes, probably not a good idea to categorize yourself as Iranian, then, since you're blocking them. I was only recommending that because your Facebook page said you all were there (looks like that has been changed, now). I don't think based on what you've said so far that you all should be in the "International" category.

Maybe you could submit a pull request for potential inclusion, for where your headquarters are, and we can consider that after additional review.

**Comment by khashmeshab** [comment]
@wbnns Thank you for your answer. Well, I was Iranian, now I live in the UAE. We have investors from Russia, UK, Canada, Ireland, and China. It really categorizes us as "International". But if you still insist, I prefer to send a PR to be included under the "Europe" section. My last choice would be "UAE". Please let me know if any of these are acceptable.
About the upcoming fork, we are strongly No2X. Although we may add the resulted coin under the "B2X/Bitcoin2X" name later, if the conflicts got resolved, and the resulted coin has any trading benefits for us. Our "BTC/Bitcoin" name would always be what bitcoin.org accepts as Bitcoin. We may also add Bitcoin Gold as BTG.
Thank you for your time.

**Comment by khashmeshab** [comment]
@wbnns I sent another PR to be listed under the "United Arab Emirates" section. Thank you for your help.

**Pull request closed without merging**
