### PR TITLE
Remove wallet listing multibithd

### LINKED ISSUE #1601: Remove Multibit HD from site
Please remove MultibitHD from your site. The balance becomes unconfirmed, unspendable, and inaccessible, even though no transactions have been sent for months, even though the wallet was repaired several dozen times.
https://bitcoin.stackexchange.com/questions/53356/multibit-wallet-says-my-balance-is-unconfirmed-even-though-ive-not-sent-a-tran

https://www.reddit.com/r/btc/comments/6beg3p/warning_stay_away_from_multibit_hd_your_entire/

### PR DESCRIPTION
**Pull request by crwatkins**
This closes #1601 removing the wallet listing for MultiBit HD.  I am looking forward to the updates to the wallet so that we can re-list it.

### CODE REVIEW

**Comment by harding** [comment]
Tested ACK.

Note, our policy in the past has been to immediately delist wallets when requested by the wallet author (e.g. #1121) without the usual Merge Scheduled comment period.  Because of that, I suggest this be merged as soon as the maintainers are available to do so.

We, of course, do try to prioritize the re-adding of wallets that voluntarily removed themselves when they're ready to be readded, and I echo @crwatkins's remarks in looking forward to MultibitHD returning to Bitcoin.org.

**Comment by wbnns** [comment]
@harding @crwatkins Thanks guys - this has been merged.

**Comment by luke-jr** [comment]
Huh? It looks like the request was to remove *Multibit Classic*, not Multibit HD...? Where did the author request HD be removed?

**Comment by harding** [comment]
@luke-jr https://github.com/bitcoin-dot-org/bitcoin.org/issues/1601#issuecomment-305854506 "All versions of Multibit are currently suffering from one or more bugs that prevent users from effectively using them."

Bitcoin.org only listed Multibit HD, not Multibit Classic.

I believe this PR was correct, please let me know if we're missing something.

**Pull request merged**
