### PR TITLE
Add The Rock Trading

### PR DESCRIPTION
**Pull request by mikexine**
Adding The Rock Trading (https://therocktrading.com)

### CODE REVIEW

**Comment by wbnns** [comment]
@mikexine Hello, thanks for submitting this. Could you please revise this PR and place TRT under `Italy`? You can also add a section for `Malta` if you would like. In the future we can also consider putting TRT as an international listing once you have a [global Alexa ranking](http://www.alexa.com/siteinfo/therocktrading.com) of approximately 250,000 or lower.

**Comment by wbnns** [comment]
@mikexine Thanks!

Unless others object, this will be merged on Sunday, February 12th.

**Comment by mikexine** [comment]
@wbnns thanks to you!

**Comment by wbnns** [comment]
@mikexine You're welcome!

**Pull request merged**
