### PR TITLE
Un-expire laanwj release key

### PR DESCRIPTION
**Pull request by laanwj**
Looks like I re-exported the expired key in #1513. This should fix that.

To check use:

```bash
curl -s https://raw.githubusercontent.com/bitcoin-dot-org/bitcoin.org/2017_03_update_key/laanwj-releases.asc | gpg2
pub  rsa4096/0x90C8019E36C2E964 2015-06-24 [expires: 2019-02-14]
uid                             Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>
```
(the laanwj.asc key was properly updated in #1513)

### CODE REVIEW

**Comment by andrea-chiavazza** [comment]
ACK
I get the same output running the command above.

**Comment by ndrchvzz** [comment]
Is the problem meant to be fixed after this merge?
I'm still getting the out-of-date key from bitcoin.org:
```
curl -s https://bitcoin.org/laanwj-releases.asc | gpg
pub   rsa4096 2015-06-24 [SC] [expired: 2017-02-13]
      01EA5486DE18A882D4C2684590C8019E36C2E964
uid           Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>
```

**Comment by laanwj** [comment]
In git the new key has been merged:
```
curl -s https://raw.githubusercontent.com/bitcoin-dot-org/bitcoin.org/master/laanwj-releases.asc | gpg2
```
Apparently it has not propagated to the website yet.

**Comment by wbnns** [comment]
@ndrchvzz @laanwj Hello, this will be live upon the next deployment.

**Pull request merged**
