### PR TITLE
Adds Coinberry to the list of Canadian exchanges

### PR DESCRIPTION
**Pull request by tjalil**

### CODE REVIEW

**Comment by tjalil** [comment]
Hey @wbnns, checking in on the status of this PR.

**Comment by wbnns** [comment]
@tjalil 

Hello, it's not possible to provide an estimate just yet since the exchange hasn't been reviewed, but we'll provide status updates here as they become available. Others may also have feedback they would like to add in the interim.

**Comment by wbnns** [comment]
Unless others object, this is scheduled to be merged on Monday, July 15th.

**Comment by tjalil** [comment]
hey @wbnns, checking the status of this PR. Any particular reason this wasn't merged yesterday?

**Comment by wbnns** [comment]
@tjalil 

Hello, apologies - we misread the merge date and had it rescheduled for tomorrow. It's merged, now.

**Comment by tjalil** [comment]
Thank you @wbnns

**Pull request merged**
