### PR TITLE
Alerts: SPV Mining more details

### PR DESCRIPTION
**Pull request by harding**
This adds more details to the current alert message.  With F2Pool now fully validating, I've also reduced the number of recommended extra confrimations to wait from 30 to 15.  According to @gmaxwell's online version of the [fork probability calculator](https://people.xiph.org/~greg/attack_success.html), 15 confirmations on the longest chain from 25% of hash rate has a probability of 0.01%.

Preview: http://dg0.dtrt.org/en/alert/2015-07-04-spv-mining

CC: @petertodd @luke-jr

### CODE REVIEW

**Comment by luke-jr** [comment]
0.01% is too high IMO.

**Comment by harding** [comment]
@luke-jr I'll leave it at 30 then until we're sure more hash rate is safe.

**Comment by saivann** [comment]
@harding Thanks for writing this. Please find fixes for broken HTML here, last commit on this branch:
https://github.com/bitcoin-dot-org/bitcoin.org/commits/spv-smallfixes

I can't comment on the accuracy, but otherwise LGTM!

**Comment by harding** [comment]
Commit https://github.com/bitcoin-dot-org/bitcoin.org/commit/c04bfa6832d4032afe271dffbec6f56aa6ad716a changes the extra confirmations back to 30 and removes the text about SPV wallets being more vulnerable than usual because of expected soft fork problems.  (Requested by @gmaxwell, who just said it looks good on IRC)

**Comment by harding** [comment]
Pushed commit 9f30adba9fdcb59be50aa6a399938e6045409d4f to master with the following changes:

- Move list of good/bad pools to the wiki.  If we suspect people are lying about what validation their pools do, we can move the list back here; otherwise, I think letting people list their own pools will be a more productive use of everyone's time.

- Suggest upgrading to 0.10.2 because of DoS vulnerabilities in earlier versions unrelated to this alert.

- Update the times

**Comment by saivann** [comment]
@harding Thanks! Just fixed a typo with an additional commit.

**Comment by harding** [comment]
@saivann remember you need to sign tip commits (or update manually on the build server).  I have another small change to make as [recommended by reddit](https://www.reddit.com/r/Bitcoin/comments/3c305f/if_you_are_using_any_wallet_other_than_bitcoin/csrvunr), so I'll push that in a moment after I see if there are any other good suggestions.

**Pull request merged**
