### PR TITLE
Revert "Merge pull request #1178 from Cobra-Bitcoin/remove-coinbase"

### PR DESCRIPTION
**Pull request by hoffmabc**
This reverts commit 7d1cdd94651461ff13ad4ed10b05b2374690fac2, reversing
changes made to cc79a1ee7de9a2a6366898b7ace3a33d9853d24e.

### CODE REVIEW

**Comment by MillyBitcoin** [comment]
But the people in charge own the domain so I don't think this will do much.

**Comment by CelestialWalrus** [comment]
Voting for.

**Comment by jlopp** [comment]
ACK, for all the good it will do...

**Comment by essofluffy** [comment]
ACK

**Comment by jcliff** [comment]
ACK. Coinbase is too important of an onramp for new users to be left out.

**Comment by barmstrong** [comment]
ACK :+1:

**Comment by nomnombtc** [comment]
ACK

**Comment by tomasvdw** [comment]
ACK

**Comment by guruvan** [comment]
ACK

**Comment by arodic** [comment]
ACK

**Comment by jrmithdobbs** [comment]
NACK. Bitcoin.org is not for altcoins.

**Comment by maddenw** [comment]
ACK

**Comment by Cobra-Bitcoin** [comment]
NACK

**Comment by Grix** [comment]
Yes please.

**Comment by taariq** [comment]
ACK.

**Comment by shinohai** [comment]
NACK.

**Comment by hoffmabc** [comment]
It's not about altcoins @shinohai it's about a wallet that clearly supports Bitcoin. @Cobra-Bitcoin probably should just close this as it seems like while it enjoys a clear majority for reinstatement you will not merge it. Is there any type of warning text or additional modification that can be made here to save the PR?

**Comment by cscott** [comment]
ACK

**Comment by MorgUK** [comment]
ACK

**Comment by jrmithdobbs** [comment]
Close and lock already.

**Comment by CelestialWalrus** [comment]
@jrmithdobbs "Discussion is ok unless you don't agree with me"

**Comment by wesmint** [comment]
+1 to merge

**Comment by ABISprotocol** [comment]
Hello, I would like to make a comment here.  I was going to make a comment in #1178 (having watched the conversation and observed the merge that was made) but by the time I could get around to it, having been on vacation, and getting back to reading everything again carefully (including this pull request and comments), then 1178 ended up being locked except for collaborators, thus I never had a chance to express my views on the subject.  So I would like to express them here.

Unfortunately I don't think my ideas will make anyone happy because I don't agree specifically with a straight removal of Coinbase as it was done in pull request 1178, nor do I agree particularly with the simple revert which is proposed by this pull request on which I am commenting.

In the past, [I have pointed out, in a still-open issue in this repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues/996#issuecomment-143164573) that the definitions and characterizations associated with web wallets that are displayed when you click on them, which are a result of the scoring, leave something to be desired, and need to be re-written and improved.  As that applies to Coinbase:  Note that at the time I made my remarks I suggested that with respect to that language which is applied to Coinbase, I did not suggest changing the language as it existed prior to the merge in pull request 1178, and my reasoning was, because I felt the language presented properly warned the user about the deficiencies inherent in Coinbase before the user would download or use anything.  (However, as I will explain further below, that is not the only issue to analyze here.)

This is a complex issue, and I would suggest that anyone reading my remarks not take them out of context.  To get the bigger picture of how people are thinking about it, please read all comments on Issue #996 and perhaps add your own thoughts to that thread.

Furthermore, there are additional issues to analyze (in my humble opinion) before you should take the action of making a merge in connection with this pull request, namely, the following:

1) One should analyze whether or not we should have the Coinbase item in the wallet category.  Although I was not in favor of the pull request 1178 which was so contentious and which has led to this suggested pull request #1180 - nonetheless, I personally don't feel that Coinbase belongs in the wallet category.  You can see [some of my reasoning on that from an open issue on Bitcoin bank listings](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162159330) as well as a comment from @crwatkins - [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702) - which merits consideration in the context of this discussion and analysis.

2) The person who is originating the pull request should not be the person who actually makes the merge.  I'm not sure how this is to be handled for this repository -- @harding / @Cobra-Bitcoin -- I've brought this up before in other issues or pull requests in this repository.  Perhaps one way of managing this would be to use [PullApprove](https://github.com/integrations/pullapprove)?  This is a concern of mine regardless of what pull request we are talking about.  Having one person propose some pull request and slam through a merge regardless of who it is, decreases the collaborative aspect of this endeavor associated with this repository and effort for bitcoin-dot-org.

3) I do not agree with any practice which involves locking out people who are not designated collaborators. Because this was done on PR 1178, I was unable to comment there, even though I had waited to comment and watched the discussion.

In conclusion, I do not agree with PR 1178, nor do I agree with this pull request (PR 1180) as it is currently written.  I have been one of the most vocal opponents of use of web wallets and have often warned against the problems and dangers associated with their use; Coinbase's financial censorship of users is just one of many of the aspects of such problems or dangers.  However, I do not agree with the idea of excluding entirely a presentation of things like Coinbase from bitcoin-dot-org, but rather, I think things like Coinbase (which is a brokerage that offers a wallet application) should be given a different listing category and placed in a spot where it will get less traffic than other wallets.  I feel similarly about web wallets, again, please see my remarks at Issue #996 for more details.

Thank you for reading this comment and for your consideration as you evaluate how to move forward.

**Comment by CelestialWalrus** [comment]
@ABISprotocol @theymos' "censorship of users is just one of many of the aspects of such problems or dangers."

**Comment by arodic** [comment]
The most important thing about #1178 it that it sends a signal that no company should even consider ideas that are not approved by core team without consequences.

**Comment by MarcoFalke** [comment]
> not approved by core team

The bitcoin core developers and the bitcoin.org site maintainers are two different parties.

In fact most of the bitcoin core developers did not even comment on #1178. And as far as I can see none of them wrote "ACK".

**Comment by HostFat** [comment]
@MarcoFalke 
How do you know that Cobra-Bitcoin isn't an investor of Blockstream or his business gets gain from a not-scaling Bitcoin?

**Comment by MillyBitcoin** [comment]
@HostFat Of course you have to expect that.  The main incentive for developers to get involved is to profit from that involvement.  

This whole thing is playing out in a very similar way as the Coinlenders/inputs.io, donations to BitcoinTalk, and GLBSE where Theymos and some accomplice enticed people to do things as part of a "community effort."  They make all these weird arguments and then in the end everything collapses into disaster.

**Comment by jgarzik** [comment]
ACK - this situation is completely unprofessional, and the removal PR should have never been merged.

I already had users asking me on twitter if Coinbase-BTC was still safe to use.

This looks like amateur hour to outsiders - a business experiments with something that diverts from the Official Line, and bitcoin.org immediately de-lists them.  That's anti-innovation, anti-freedom-of-choice and discourages anyone from diverging from the Official Line.

Ultimately bitcoin.org is devalued not Coinbase.

**Comment by MarcoFalke** [comment]
I agree with @jgarzik (see my comment in #1178).

<sub>Personally, I think web wallets should be removed from the site altogether but that is a completely different topic and does not belong here.</sub>

**Comment by luke-jr** [comment]
ACK returning Coinbase for the moment. (Also agree with removing webwallets in general, though.)

When/if Coinbase is removed, it should be for a legitimate reason and fairly applied to other services, not because they simply are doing experimentation that does not affect their public production services. The latter should be *encouraged*.

**Comment by SergioDemianLerner** [comment]
ACK

**Comment by bpdavenport** [comment]
ACK

**Comment by ferdynice** [comment]
Seems reasonable to put it back on.

**Comment by jrmithdobbs** [comment]
Rescind my previous NACK since they have indeed not switched to an alt pin at this time.

Will not ack on grounds that a web wallet isn't a wallet but out of scope.

**Comment by djbooth007** [comment]
ACK

**Comment by losh11** [comment]
ACK

Even @luke-jr agrees!

**Comment by cloudnthings** [comment]
ACK

**Comment by dexX7** [comment]
ACK -- even though I somewhat share the sentiment of #1178, the merge seemed premature and too hasty.

**Comment by carnesen** [comment]
ACK. I was and am deeply opposed to the original pull request, both in spirit and content and how it was immediately merged by its submitter without any regard for the usual processes in place for this site.

**Comment by gavinandresen** [comment]
ACK. jgarzik expressed my thoughts well.

**Comment by TheKnowin** [comment]
ACK. I'm with jgarzik on this one.

**Comment by algesten** [comment]
i'm with jgarzik and gavinandresen

**Comment by aalness** [comment]
ACK

**Comment by hoffmabc** [comment]
any updates on this @Cobra-Bitcoin @harding ?

**Comment by harding** [comment]
@hoffmabc Coinbase was removed by the domain owners; it can only be added back by them.  I'm not one of the owners.

**Comment by sandakersmann** [comment]
ACK

**Comment by HostFat** [comment]
@harding then are you at least being paid for for handle this repository?

**Comment by hoffmabc** [comment]
I thought you merged the policy causing his six months ago. I guess I'm mistaken.

**Comment by cypherdoc** [comment]
ACK

**Comment by tmm360** [comment]
ACK

**Comment by mohrt** [comment]
ACK. Satoshi would not approve.

**Comment by DougTanner** [comment]
ACK

**Comment by eleuteromaniaco** [comment]
ACK.

I agree with luke-jr in that Bitcoin "banks" should not be listed. But Coinbase has a real multisig wallet too.

**Comment by mmitech** [comment]
Who are the domain owners of bitcoin.org and what is/was the guidelines that they had/have to follow prior getting the ownership ?

**Comment by danhowitt** [comment]
ACK

**Comment by kwood** [comment]
These two things seem indisputable:
1. Hard-forks, with overwhelming consensus, must be considered as Bitcoin faces various challenges
2. Hard-forks cannot reach consensus when parties are unable to discuss or support them in the open

Coinbase is not on an altcoin, they have merely expressed support for a particular hard fork. By punishing them here you are preventing consensus from ever happening.

If you apply this rhetoric to every hard-fork discussion, Bitcoin will certainly die when it inevitably faces a challenge where a hard-fork is necessary.

@harding you must agree with the above? You may not be able to revert this on your own... However you did ACK the original and have considerable influence on this project. I implore you to fight for the right to open discussion.

**Comment by vermorel** [comment]
ACK with @jgarzik

**Comment by unixtastic** [comment]
+1 to merge

**Comment by MarcoPon** [comment]
ACK
*The ball is mine so I decide who shall play!* isn't a very good policy.

**Comment by CelestialWalrus** [comment]
@MarcoPon 

More like: "The ball is someone's else so I decide who shall play! isn't a very good policy."

**Comment by hrishikeshio** [comment]
ACK

**Comment by themusicgod1** [comment]
ACK

**Comment by CoinCadence** [comment]
ACK, @Cobra-Bitcoin is this YOUR site or the communities? Feels like the former...

**Comment by maddenw** [comment]
ACK.

**Comment by doppio** [comment]
ACK

**Comment by FugueWeb** [comment]
ACK

**Comment by escheel** [comment]
ACK

**Comment by buddhamangler** [comment]
ACK

**Comment by pkirk** [comment]
ACK

**Comment by prusnak** [comment]
ACL

**Comment by SpyTec** [comment]
ACK

**Comment by michael-endsley** [comment]
ACK

**Comment by abrkn** [comment]
ACK

**Comment by RobinHoutevelts** [comment]
ACK

**Comment by cr3473** [comment]
ACK!

**Comment by amnesiac84** [comment]
ACK

**Comment by theymos** [comment]
This is not a vote. I will unlock this when it is no longer being brigaded.

**Comment by theymos** [comment]
Coinbase CEO Brian Armstrong [clarified](https://www.reddit.com/r/Bitcoin/comments/40cm78/coinbase_still_delisted_from_bitcoinorg_as_github/cyuq0ta):

> Coinbase will always support the longest chain in bitcoin. Actually lets say longest valid chain where valid is an economic majority.

"Economic majority" might (debatably) not be *quite* correct, but I think that this is sufficient to show that Coinbase is on Bitcoin now and will remain on Bitcoin in at least most likely future cases. It's actually a stronger statement than I ever expected to see.

I talked with Cobra previously about the conditions necessary to allow Coinbase's reinstatement, and Brian's statement here seems to satisfy these conditions. So as things look now, we will not veto Coinbase's reinstatement.

This PR is kind of confusing because there are so many people who have never contributed to bitcoin.org but are posting meaningless ACKs. Can some bitcoin.org regular contributors share their thoughts as to whether you think Coinbase should be reinstated and whether this PR is technically OK?

I think that Coinbase has gone above and beyond on this hardfork issue, so while they're probably worse than some Web wallets like GreenAddress, I tend to think now that they're at least not significantly worse than Circle. So while these sorts of Bitcoin banks are allowed, I'm OK with reinstating Coinbase.

**Comment by coblee** [comment]
@theymos Thanks for being reasonable. Even though we may have different ideas on how best to scale Bitcoin, we all want the best for Bitcoin. Even within the same company, Brian and I don't fully agree on how to scale Bitcoin. That's fine because we both agree that Bitcoin belongs to everyone. And in the end, it will overcome this debate and find the right path.

**Comment by btcdrak** [comment]
@theymos I am not a regular contributor, but I have contributed a little to the site.

I think @barmstrong Brian Armstrong's statement lacks the right nuance, but I think shows good intent. The correct wording would be that they will always "support the longest chain *with the most work*", since that is by definition consensus under Bitcoin's rules.

It seems to me that bitcoin.org exists to bring awareness about Bitcoin and that involves list of Bitcoin services (like wallets and exchanges). I do think bitcoin.org requires minimum standards so it's not just an advertising platform like it's competitors, so that users can make informed decisions about the software and services they chose. I like that bitcoin.org has a set of minimum criterion for wallets based on security, and that there wallets are categorised and labelled according to security trade-offs.

As such, I am OK with listing "bitcoin Banks" and custodial services even if they arent "pure bitcoin", so long as they are marked correctly as such with all the caveats to educate users about their risks. I think this is already the case.

I agree Coinbase's public conduct has been a bit disappointing, especially coming directly from the CEO. I would hope in the future they chose to _engage more positively_ rather than stir and divide.

It certainly does not help to feed negativity which only serves to distract and demotivate. Companies should stop lobbying privately to trying and force their own agendas. There should be more open dialogue and communication from all parties and stakeholders because changing Bitcoin consensus rules really does require almost unanimous support, by design. While multiple Bitcoin implementations are inevitable, they will actually make consensus building harder because ultimately one project will propose a consensus change and will either need to get unanimous adoption of their client, or convince all other software implementations to also roll out their proposal to their users.

As such, I would hope vendors can be encouraged at the very least, not be divisive. That may be something the domain owners would like to address in their mission statement/policy for the site because it does not make sense to me, to promote vendors who try to wield axes.

Overall, I am glad there is a possibility to consider re-add Coinbase.

**Comment by petertodd** [comment]
Re:

> Coinbase will always support the longest **valid chain** in bitcoin. Actually lets say longest valid chain where **valid is an economic majority.**

ACK

**Comment by MillyBitcoin** [comment]
@coblee - You are mistaken, Theymos has never been reasonable.  The guy is a mental case.

**Comment by crwatkins** [comment]
I definitely recommend Coinbase for listing. Coinbase meets our current criteria for wallet listing. I also believe that Coinbase  meets each of the stated requirements in our Hard Fork Policy. 

In regards to the discussions about "Bitcoin banks" a.k.a "custodial wallets", Coinbase meets our current criteria for that type of wallet.  We are currently working on some ideas to address the concerns about different types of wallets providing different capabilities and currently have an issue open to discuss that. 

@theymos  I believe "this PR is technically OK"

**Comment by luke-jr** [comment]
Concept re-ACK (did not confirm correctness of webpage code change, but it doesn't look obviously wrong).

> The correct wording would be that they will always "support the longest chain with the most work", since that is by definition consensus under Bitcoin's rules.

@btcdrak I think you reworded that very wrong... Perhaps you meant "the *valid* chain with the most work"?

**Comment by MillyBitcoin** [comment]
@crwatkins It is critical that "Bitcoin banks" or wallets controlled by a centralized company be included as part of any Bitcoin introductory web site.  Many, many people simply want that irrespective of what the Bitcoin fundamentalists say.  That being said they should be listed in a separate section with a clear explanation as to why they are different.  Understanding the difference is key to newcomers understanding Bitcoin at a deeper level.  I find all these attempt at information control rather strange.  I personally think they are trying to create problems so someone will come along and offer them a large sum to buy them out.

**Comment by harding** [comment]
Per recommendations above from regular contributors (including @crwatkins, our wallet maintainer), I'm building a local preview and will merge as soon as I've verified everything looks good.  (Note: it takes another 10-15 minutes after merge for the change to go live on the site.)

**Comment by carnesen** [comment]
@theymos It's clear from this PR and the one that it reverts where the community stands. There are two NACK's on this: @Cobra-Bitcoin and @shinohai (non-contributor). Just pull it already so we can move on with building a better bitcoin.

**Comment by sunnankar** [comment]
@theymos I am not a regular contributor but am #16 in terms of commits

Concept ACK and NACK

https://bitcoinclassic.com/ has asserted that Gavin Andresen (a Coinbase Advisor https://www.coinbase.com/about), Brian Armstrong and Coinbase are in agreement with: "We are hard forking bitcoin to a 2 MB blocksize limit. Please join us."

Assuming Brian and Gavin both will publicly disavow bitcoinclassic.com and issue them a formal cease and desist then I do think Coinbase should be readded based on your requirements with @Cobra-Bitcoin 

Nevertheless, the NACK portion would apply to Coinbase but also to any other custodian service that also lacks TOS, UAs, etc. that address this issue.

I think the statement from @barmstrong is rather meaningless from a legal perspective. What matters is what is written into the legal documents and agreed to by the company and user.

Any type of custodian relationship entails serious financial and legal implications for customers because those customers do not solely hold the private keys themselves. And what matters with regards to customer's property rights is what is in the Terms of Service, User Agreements, etc. that are agreed to (usually with only a click and are not read). I think it is possible to image that many users will not read the TOS, UAs, etc. but instead rely on bitcoin.org's assessment. 

Consequently, bitcoin.org should have some type of a requirement for listing *any* custodian type services where the TOS directly addresses this issue in particular ways that meet what bitcoin.org considers to be a high standard of care that will help encourage TOSs, UAs, etc. that are written in such a way that customers have extremely strong legal rights and protections regarding any property, funds or other type of financial interest.

**Comment by MillyBitcoin** [comment]
@sunnankar the people running bitcoin.org have no concept of the legal system or the real world for that matter.

**Comment by lichtamberg** [comment]
ACK

**Comment by Aquentus** [comment]
bitcoin.org is a website with the primary aim of educating newbies about bitcoin and the bitcoin ecosystem. Those newbies have no clue about forks, about XT, about classic, about unlimited or any other matter that relates to the blocksize and anything about it simply fully confuses them.

Any information, content, or decision that has relation to the blocksize should be buried somewhere deep in some advanced section, with the primary content being to inform individuals who may have never heard of bitcoin about what bitcoin is, how it can be used, how it can be easily bought, etc.

No person with any influence or decision making ability reads bitcoin.org or is in anyway influenced by it. Nor, may I say, any current bitcoin user because they would be aware of the information it contains. Therefore any decision aimed as a weapon is very limited in influence and, of course, as shown by say bitpay's statements or bitstamp's statements or BCCC any such threats have been called bluff. 

Bitcoin is changing and it is changing for the better. While in 2013 we had only one exchange and were prisoners to it's ddosing, amateurism, the chaos it created and it's eventual huge terrible and devastating bang, we now have multiple exchanges which gives the ecosystem high resilience. Equally, just one client is a dangerous centralised point that can be coerced/corrupted/attacked from within/without. Multiple implementations add resilience. 

Bitcoin.org should reflect the ecosystem and educate newbies about the nature of bitcoin, how it works, how it can easily be acquired, as well as about the nascent new implementations. Perhaps not bitcoin xt, but bitcoin.org should certainly inform individuals about bitcoin unlimited in a neutral - informative only - manner, about bitcoin classic, about bitcoin core, etc.

The decision in regards to coinbase therefore is outdated. XT is a was. It is time now for all who truly hold bitcoin's interest at heart to recognise that the ecosystem is changing for the better and that we need to get around the table, co-operate where we agree, and politely agree to disagree where we don't.

No man holds power in bitcoin land. If any man does then bitcoin's proof of work is worthless. Equally, bitcoin relies on no man to defend it. It is not possible for a charismatic man to seduce the masses. If it is then bitcoin works not.

You ought to end all this theymos, recognising the beneficial changes and prove to us all that you have been acting in good faith. Otherwise you will be asserting malicious intentions which can not further down the line be explained away.

**Comment by barmstrong** [comment]
Thanks @theymos for making the change. Happy to stay in touch in the future so miscommunications don't happen. It's great that we were able to clear things up once we chatted (although it took a long time and happened in public). In the future happy to discuss in private as well.

@sunnankar Coinbase will always stay on the longest valid chain. But we will also publicly discuss and vote on various proposals to improve bitcoin. I don't think this is inconsistent. (Just like you might vote in an election, but still support the winner regardless of whether they are the one you voted for).

**Comment by MillyBitcoin** [comment]
@Aquentus tl;dr - Bitcoin is about inclusion and not exclusion.  ... now my post can be deleted  lol

**Comment by jameshilliard** [comment]
@barmstrong 
> Coinbase will always stay on the longest valid chain. But we will also publicly discuss and vote on various proposals to improve bitcoin. I don't think this is inconsistent. (Just like you might vote in an election, but still support the winner regardless of whether they are the one you voted for).

It really comes down to your definition of what a valid chain is then. Since hard forks require all nodes to upgrade they should not be done unless there is rough consensus among all bitcoin companies. If coinbase chooses to redefine what a valid chain is without community consensus then there will potentially be two competing chains. The real issue comes down to if you are merely supporting a proposal or supporting activation of a proposal in the face of significant objection. Activation of bitcoin classic is already opposed by at least 25% of the hashing power precisely because it is being pushed for activation without community consensus even though those same miners would be ok with an increase to 2MB if there was community consensus.

**Comment by Azulan** [comment]
@theymos isn't reasonable, he's a wannabe tyrant. The great thing about bitcoin is that it doesn't enable tyranny.

**Comment by tulip0** [comment]
@barmstrong 

> Coinbase will always stay on the longest valid chain.

This is very fuzzy statement, validity is determined by the software you are running, and therefor so is "longest". Do note that the Bitcoin consensus does not actually use "longest" chain but the valid chain with the most *cumulative proof of work*, this is a very important distinction.

**Comment by jojva** [comment]
@tulip0 and many others: I think @barmstrong obviously means the *most proof of work* when he says *longest chain*. It's just a shortcut we all understand (or so I thought).

**Comment by chriswheeler** [comment]
> Activation of bitcoin classic is already opposed by at least 25% of the hashing power precisely because it is being pushed for activation without community consensus even though those same miners would be ok with an increase to 2MB if there was community consensus.

Circular logic there surely? The oppose it, because they oppose it?

**Comment by jameshilliard** [comment]
@chriswheeler The difference is between supporting a proposal and supporting activation of a proposal, supporting activation should only be when there is widespread consensus across the entire bitcoin industry.

**Comment by Aquentus** [comment]
@chriswheeler I think you pinged the wrong nick :) you were looking for @jameshilliard

**Comment by ABISprotocol** [comment]
I agree with the earlier comment of @Aquentus which suggested simplification of bitcoin.org via movement of complex topics to a less obvious area to make things smoother on newcomers to bitcoin, so that the more basic ideas, how-to's, and where do I get a wallet is more up front.

**Comment by harding** [comment]
@ABISprotocol pull requests are always welcome.

**Comment by ABISprotocol** [comment]
@harding well, maybe with things toning down a little bit, I will consider crafting one... I don't ordinarily like crafting PRs.  I will consider it though, having made enough suggestions in issues on language.

**Comment by ABISprotocol** [comment]
This is a response to a stale and old pull request.  It seems like some
of these issues and arguments just come up over and over again.  I've
long been opposed to the methods and models of Coinbase and Bitpay.  I
agree that bitcoin belongs to everyone, but at the same point, there is
a path of insanity that we just shouldn't go down.

That path of insanity is the one Coinbase, BitPay and others are taking.

But enough chitchat - I understand the position of bitcoin.org as of
late with respect to Coinbase, BitPay etc. I also understand why some
are upset at bitcoin.org, but ah well.  I simply recommend that people
run the latest version of Core, don't lose so much of one's time on
fora, get sleep, enjoy the outdoors, and enjoy life more.

Oh, and continue to create amazing things.

Cheers,

- o

Charlie Lee:
> @theymos Thanks for being reasonable. Even though we may have different ideas on how best to scale Bitcoin, we all want the best for Bitcoin. Even within the same company, Brian and I don't fully agree on how to scale Bitcoin. That's fine because we both agree that Bitcoin belongs to everyone. And in the end, it will overcome this debate and find the right path.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bitcoin-dot-org/bitcoin.org/pull/1180#issuecomment-170818884
> 

-- 
http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn

**Pull request merged**
