### PR TITLE
Added SpectroCoin exchange

### PR DESCRIPTION
**Pull request by ktamasauskas**
Added SpectroCoin to International Exchanges.

### CODE REVIEW

**Comment by wbnns** [comment]
@ktamasauskas Hello, thanks for the suggestion. Due to surrounding the Bankera ICO that SpectroCoin is part of, I do not think it would be prudent to include them as an international option for new/existing Bitcoin users at this time.

If others disagree, please feel free to comment here so we can reconsider.

**Comment by CIN-47** [comment]
What's the controversy though? It seems they are in crypto business for quite some time and are not doing bad

**Comment by wbnns** [comment]
@CIN-47 It seems they did an ICO guaranteeing returns, with at least part of the returns being distributed via a [weekly revenue share](https://blog.bankera.com/2018/05/11/the-36th-week-net-transactional-revenue-share-has-been-paid/) to SpectroCoin wallets, however, since the token isn't listed anywhere no one can redeem them. Also, no one can transfer them out of SpectroCoin (e.g. to an ERC-20 compatible wallet). A lot of people are complaining on social media about it.

**Comment by CIN-47** [comment]
From what I see in social media, they pay weekly revenue share in ETH and you can do whatever you want with it. I checked Bankera GitHub page, and their contract is there for testing so it seems the project is moving

**Pull request closed without merging**
