### PR TITLE
Remove BitPay

### PR DESCRIPTION
**Pull request by theymos**
BitPay is [fraudulently passing off btc1 as Bitcoin software to which people are required to upgrade](https://blog.bitpay.com/bitcore-segwit-activation/). This is highly unethical and a violation of the [bitcoin.org hard fork policy](https://bitcoin.org/en/posts/hard-fork-policy). Therefore, this pull request removes from bitcoin.org any references to BitPay and their software/services Copay and Bitcore.

### CODE REVIEW

**Comment by lichtamberg** [comment]
**Full ACK**

**Comment by harding** [comment]
Based on [my reading](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1751#issuecomment-323194580) of the BitPay announcement linked above, I do not believe either Copay or Bitcore are currently configured to leave the existing Bitcoin consensus.

I think it would be advisable to proceed slowly and try to get BitPay to clarify their position before we delist them for encouraging the very small number of Bitcore operators to run a btc1 border node that cannot by itself result in any users of a Bitcore service seeing a hard fork.

**Comment by alp-bitcoin** [comment]
ACK

**Comment by crwatkins** [comment]
I agree with @harding that we should request clarification before acting.

**Comment by friendsofbitcoin** [comment]
I see clarification has been requested in both their twitter handles: 
https://twitter.com/compricadev/status/898301613449728000
https://twitter.com/compricadev/status/898301839904354305

**Comment by d1gitalflow** [comment]
ACK 

See [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1751#issuecomment-323208954)

**Comment by miki-bgd-011** [comment]
ACK

**Comment by jgarzik** [comment]
NAK.

It is reasonable and practical to follow the blockchain with the most hashpower (thus most secure).

**Comment by theymos** [comment]
@jgarzik [Bitcoin is not and must not be ruled by miners](https://en.bitcoin.it/wiki/Bitcoin_is_not_ruled_by_miners).

**Comment by d1gitalflow** [comment]
@jgarzik Bitcoin is The Longest *VALID* chain.

**Comment by HostFat** [comment]
@theymos 
Nodes on the bitcoin.pdf are the miners, they are all miners.
The attacker is someone that with a larger amount of hashing power/money is going against the interest of the "honest miners".
If he isn't double spending the money, and he isn't censoring the tx of the other miners, than it isn't attacking anything and anyone.

"Nodes work all at once with little coordination. They do not need to be identified, since messages are
not routed to any particular place and only need to be delivered on a best effort basis. Nodes can
leave and rejoin the network at will, accepting the proof-of-work chain as proof of what
happened while they were gone. **They vote with their CPU power**, expressing their acceptance of
valid blocks by working on extending them and rejecting invalid blocks by refusing to work on
them. **Any needed rules and incentives can be enforced with this consensus mechanism.**"

Not voting nodes aren't nodes.

Even if you change and delete all the pages that you don't like on the bitcoin wiki, you can't change this, or you are just trying to change Bitcoin.

If you move away from this model, you are then moving more and more to this, back to the democracy:
https://en.wikipedia.org/wiki/Tyranny_of_the_majority

**Comment by friendsofbitcoin** [comment]
@HostFat Please stay on topic , this pull request would apply equally whoever is correct about their interpretation of the whitepaper. The reality is we know that many nodes will not switch to btc1 within a dangerously narrow window of 3 months so we are looking at methods at reducing risk for bitcoin users. 

How long of a time period should we give bitpay to qualify their stance since they have been sufficiently notified. 1 Day?

**Comment by d1gitalflow** [comment]
@HostFat theymos was here in the bitcoin scene long before you or any people from your subreddit even got to know what bitcoin was.

Please don't come here with old copypasta, as the discussion here is about if copay wallet stays on bitcoin.org or not. Don't you guys already have bcash? not enough attn? ask roger ver for attention.

Sorry for offtopic, I already gave my ack a few comments above.

**Comment by theymos** [comment]
@friendsofbitcoin I think 1 day is sufficient.

**Comment by mscheel** [comment]
ACK

**Comment by rcamera** [comment]
I agree with @harding and @crwatkins.

@theymos may I suggest give them a couple days or till Monday? After all, their announcement may even be fraudulent, and businesses move quite slowly...

**Comment by shangzhou** [comment]
ACK

**Comment by mpatc** [comment]
ACK, dissenting voices should not be tolerated unless they agree to argue within the narrow band we appropriate. Yes, it's FOSS, but Bitcoin software is Bitcoin core. Bitpay is being so disrespectful of all the amazing work core devs have done!

**Comment by checksum0** [comment]
NACK, you guys are discussing removing the most user-friendly wallet because they don't want to sign an agreement they agreed on? Also, it has literally 0 effect on Wallet users, it's a not to users of bitcore which is not the wallet.

@mpatc Can you please be more assimilated? Dissenting voice must be squashed? Only Bitcoin core is true Bitcoin? Come on.

**Comment by mohrt** [comment]
BitPay knows exactly what they are doing. NAK.

**Comment by mpatc** [comment]
> Dissenting voice must be squashed?

@checksum0 I'm going to assume good faith and forgive you for twisting my words. I said we shouldn't **tolerate** what bitpay is doing. The Bcore development team has made a decision, miners don't rule bitcoin, lightning is the future, $5 fees are great, and these 2x people are trying to hijack something. So either you're on the side of brave devs, or you're on the side of hijackers. Please get in line.

**Comment by JaredR26** [comment]
> @jgarzik Bitcoin is not and must not be ruled by miners.

@theymos isn't that link to just another website you control?

**Comment by bitsko** [comment]
Nack this and nack that other policy you referenced.

**Comment by friendsofbitcoin** [comment]
@checksum0   We can re add the wallet when another version of copay being prepared doesn't place users bitcoins at risk.

**Comment by checksum0** [comment]
@friendsofbitcoin There is no single line of code in copay that can put users fund "at risk". You are lying through your teeth to push your narrative. Sad, real sad.

**Comment by JaredR26** [comment]
Speaking of putting user's Bitcoins at risk, given all of the outrage about Bitpay linking to a client that is compatible with their own services, why isn't Bitcoin.org linking to btc1 so that users can make an informed decision themselves?

Wouldn't it put users at risk to exclude the client that the entire rest of the ecosystem is following?

**Comment by friendsofbitcoin** [comment]
"Wouldn't it put users at risk to exclude the client that the entire rest of the ecosystem is following?"

This is very misleading. 

segwit2x is supported by a mere 21% of companies - https://coin.dance/poli

over 99% of full nodes aren't running btc1 and normal node upgrade speed is longer than 3 months - http://luke.dashjr.org/programs/bitcoin/files/charts/software.html

Here is a comprehensive list of companies who still have not agreed - http://nob2x.org/

**Comment by JaredR26** [comment]
> Here is a comprehensive list of companies who still have not agreed

Have any big name companies actually stated they will reject 2x?  I don't see any on that list, it has all the companies who are neutral / haven't stated their opinion mixed together with the ones who follow no2x

**Comment by friendsofbitcoin** [comment]
The weighted number isn't even 45% , and you suggested "that the entire rest of the ecosystem is following". How do justify this statement?

**Comment by JaredR26** [comment]
> and you suggested "that the entire rest of the ecosystem is following".

I can't find any large businesses other than Blockstream that oppose segwit2x.  Every single one I have found is either neutral or a supporter, and many of the neutral ones seem to be taking the position of following the most PoW chain.  Did I miss the one large Bitcoin business other than Blockstream that opposes segwit2x?  Which one?

**Comment by friendsofbitcoin** [comment]
It is understandable why larger businesses may want to not upset a subset of their clients by taking a position. 

You are avoiding the question. So your definition of "**entire rest of the ecosystem**" is 21 % of businesses with a 41% traffic importance weight?

**Comment by JaredR26** [comment]
> It is understandable why larger businesses may want to not upset a subset of their clients by taking a position.

That would imply that taking a position to refuse 2x would upset their clients, but the numerous large businesses taking a position to support 2x have not done so?  Which side are you trying to argue for again?

**Comment by Azulan** [comment]
Bitcoin.org is no longer a reliable source of Bitcoin information.

**Comment by nukebloodaxe** [comment]
@JaredR26 We have to take the least harmful stance, this means looking at changes which harm the least amount of users.  In this case, 2x has less than 50% support, therefore it does not pass muster.
Additionally, the real issue at stake here is that the end users of the removed product will be unaware of where their funds will actually be transacting; it is a violation of policy after all, and unenforced policies benefit no one.

**Comment by JaredR26** [comment]
> In this case, 2x has less than 50% support, therefore it does not pass muster.

Measured how?  By blocks it has >90%.  By merchant adoption it has >80% through Bitpay and Coinbase?  What's your measurement, and does it include "neutral" and "no vote" in the same category as "opposed"?

**Comment by HostFat** [comment]
I just want let you know that also both bread wallet and bitcoin wallet (android) should probably be removed by the Themos logic, because they are following the chat with most hashpower :)

**Comment by nukebloodaxe** [comment]
@JaredR26 Ah, this is what I like about you, the shifting of the moment as a counter.  I will point out that currently no 2x blocks exist, and will not do so until final activation.  In terms of your >80% figure, I take it that is the non-weighted one, you have consistently pointed out the weighted one is more important and I will stick with that stance here.  Additionally, neutral and no-vote are not yes, this is well understood in voting systems.

**Comment by JaredR26** [comment]
>  I will point out that currently no 2x blocks exist,

Oh, great then!  This pull request can be closed until November then, right?

> Additionally, neutral and no-vote are not yes, this is well understood in voting systems.

Ah, just so we're clear, is Core now claiming all default votes in their favor?  Can I get that on the record?  If so that would make things a lot more clear in regards to the repeated hardfork bit proposals in #btc1...

**Comment by jtoomim** [comment]
In a poll, if you want to know what percentage of respondents support a statement, you divide the number of supporters by the number of respondents. Using the current results from https://coin.dance/poli:

All polled companies:
Unweighted: 21% support, 3% ready, 9% oppose, 67% no response, 0% neutral.
Weighted: 41% support, 3% ready, <1% oppose, 56% no response.

Respondents only:
Unweighted: 64% support, 9% ready, 27% oppose, 0% neutral
Weighted: 93% support, 7% ready, <2% oppose, 0% neutral.

**Comment by nukebloodaxe** [comment]
@JaredR26 I was actually expecting a bit better, could you go back and reformulate your reply?

**Comment by JaredR26** [comment]
If Bitcoin.org is going to remove segwit2x supporters, why stop at Bitpay?  They would need to remove from here: https://bitcoin.org/en/exchanges

Xapo
All Chinese Exchanges
The biggest japanese exchange
Both US specific exchanges
The only south american exchange
The biggest mexican exchange
Ripio
All Middle Eastern exchanges

Plus any exchanges that choose to follow the most PoW chain, so most likely at least half of the rest if not more.

And if Bitpay and Coinbase aren't supported, you might as well remove the links to merchants accepting Bitcoin, since that's most of them.

Can we get a pull request to remove all segwit2x supporters?  If not I can make it myself tomorrow.  Thanks.

**Comment by nukebloodaxe** [comment]
@JaredR26 Are you saying all of these exchanges are acting deceptively, and not telling their customers about which chains will/will not be supported?  That is the crux of the PR here.

**Comment by JaredR26** [comment]
> @JaredR26 Are you saying all of these exchanges are acting deceptively, and not telling their customers about which chains will/will not be supported?

They are all segwit2x supporters.  Bitpay is doing exactly as Bitpay should do as a signatory of the agreement.  Bitpay is being targeted because of segwit2x.  Or are you asserting that any deceptive practices by any businesses warrants removal?  Especially when the "deceptive" is highly debatable and subjective?

Either remove the segwit2x supporters now, or don't pick and choose.

**Comment by vedran6** [comment]
**ACK**

While a network split is a bad thing in and of itself, at least more sophisticated users have the ability to choose what chain to follow. What Bitpay did is dangerous and dishonest because:

1. Copay users won't know what chain they're on.
2. Copay users might inadvertently send their main chain bitcoins to a black hole and permanently lose them due to no replay protection. At least BCH had replay protection implemented using a custom sighash flag.
3. It is dishonest and fraudulent to force consensus-altering rules on unwitting users.

**Comment by JaredR26** [comment]
> It is dishonest and fraudulent to force consensus-altering rules on unwitting users.

Just so we're clear, you're talking about soft-forks here, right?

**Comment by vedran6** [comment]
@JaredR26 

Soft forks do not alter consensus and they are opt-in by default. Proof: Segwit does nothing to affect users with older, non-upgraded clients using legacy transactions.

**Comment by JaredR26** [comment]
> Soft forks do not alter consensus and they are opt-in by default.

Right, new rules forced on unwitting users.  That's what you were saying?

**Comment by vedran6** [comment]
Nothing is forced on non-upgraded legacy users. From their perspective rules introduced in a soft-fork are non-existent.

You don't seem to understand what a soft fork is. Please educate yourself: https://bitcoin.org/en/glossary/soft-fork

**Comment by JaredR26** [comment]
> From their perspective rules introduced in a soft-fork are non-existent.

So you're saying segwit isn't a blocksize increase?

Or you're saying that blocksize increases are non-existent from the perspective of a user?

You really should be more careful with your words.

**Comment by vedran6** [comment]
> Or you're saying that blocksize increases are non-existent from the perspective of a user?

From the perspective of a legacy, non-upgraded user, yes. Legacy users still see 1MB blocks. That's why it's called a soft fork. It appears you're attempting to debate something you don't understand. I suggest reading up on the matter before attempting to participate in public discussions.

**Comment by JaredR26** [comment]
> From the perspective of a legacy, non-upgraded user, yes. Legacy users still see 1MB blocks. 

Ah, so blocksize increases are safe definitely safe then?  Or maybe what you're you saying is that signature data is not actually needed on the blockchain?

It doesn't matter what you pick here.  I could do this all day.  Soft-forks are coercive.

**Comment by maskofmadness** [comment]
Just nuke those fuckers if you haven't been thinking about it, now is a good time to change the pow algo.

**Comment by Cobra-Bitcoin** [comment]
Strong ACK.

All companies that signed the NYA are also in serious danger of being removed IMO, it makes no sense to send users to businesses that have signed that document and plan on exiting the Bitcoin network.

If it looks like these companies will go ahead with their hard fork, I recommend we begin explaining to users that their BTC is in danger in places like Coinbase, Xapo, Bitpay, etc. Someone should write instructions on how to take BTC off of all the major NYA businesses and move them safely into Bitcoin Core wallets. This can be published on all the major Bitcoin communication channels, and we the Bitcoin community can come together and inform journalists about what's going on, we need to reach millions of people and make sure people understand exactly what they need to do to safeguard their wealth from this hostile corporate takeover attempt of the Bitcoin network.

@barmstrong @jgarzik You people fundamentally misunderstand Bitcoin and underestimate how much the community is prepared to defend their money so hostile actors like you can't screw with their coins and freedom. You already have your Bcash altcoin, so instead of trying to mess with people's money, why don't you just let the market decide which coin is superior? This Segwit2x nonsense needs to stop. Bitcoin isn't governed by corporations making agreements together, and if think it is, you will find yourself dealing with thousands of extremely angry and potentially unstable people with nothing left to lose wondering what the hell you did to their money.

**Comment by lacksfish** [comment]
Please remove Bitpay and everyone else not following the NYA and creating an altcoin. 

The sooner we separate Bitcoin with big blocks from the Core, the better.

**Comment by xanather** [comment]
@Cobra-Bitcoin You're the one that fundamentally misunderstands bitcoin. Consensus forms with open communication and moving forward with an agreed proposition, at the current time this happens to be bitcoin's ruleset defined 8 years ago. Not being able to ever change that agreement (i.e. bitcoins ruleset) and saying that any alternative (popular or not) is NOT bitcoin is a disappointment. @theymos has fundamentally hurt bitcoin and continues to due to his policies on the communication platforms that he controls which are designed to stifle such discussion.

You can't use your own definition of bitcoin to define whats an attack and whats not, never-mind making statements that contradict comments made by the original author of the bitcoin network that consensus originally formed around.

NACK, would be better to be neutral about it differences between segwit2x, segwit chains and let users choose, I know a pipe dream.

**Comment by lichtamberg** [comment]
> You can't use your own definition of bitcoin to define whats an attack and whats not

It's not about an attack or not. If someone pushes a HF without community consensus and even denies to add replay protection, user's funds are at risk. Bitcoin.org should not promote clients with this risks so it's logical to remove it.

**Comment by xanather** [comment]
@lichtamberg So how do you measure any HF reaching community consensus if you ignore miners and merchants? Node count? Bitcoin Core would never implement a hard-fork no matter consensus since "they don't define the rules" which is why its better to explain to users the differences between the chains that have emerged otherwise its asking for trouble down the road. This is bitcoin.org not bitcoincore.org.

**Comment by bobquest33** [comment]
Let me put my 2 cents in this thread, to be very clear. There are so many discussions happening here but the core issue is did bitpay commit a scam. And from their blog link https://blog.bitpay.com/bitcore-segwit-activation/. yes they did why.... this is why I think they committed fraud:
They set the title "**Why nodes need to upgrade for Segwit**". Then they day **Nodes which fail to upgrade to support Segwit will face major security risks, including the risk of double-spend transaction fraud.**

Then what they do ... point to  Go to the "btc1 release page and download bitcoin-1.14.5-x86_64-linux-gnu.tar.gz".  Which points to https://github.com/btc1/bitcoin/releases. From what I know the core bitcoin github release page is https://github.com/bitcoin/bitcoin/releases. 

And whats more they also did an addendum to prove their point:
"ADDENDUM, 8/17/17, 5:20 PM ET: Note that btc1 includes support for the Segwit2x scaling proposal. You may choose to use any full node supporting Segwit, but our instructions follow this version of Bitcoin because over 95% of Bitcoin miners have adopted Segwit2x. If you are not running Segwit2x, your node will be on a dysfunctional minority chain when the base block size increases to 2MB."

To legitimize Segwit2x and sending to a alternate bitcoin github link other than the official link is social engineering at its best. And hence I support @theymos  proposal for removing copay and bitpay till they fix their misguided narrative about segwit.

**Comment by martindale** [comment]
@bitjson you still work over there, right?  Can you share some of the reasoning for this post?

**Comment by mpatc** [comment]
As others have said, this is unfair to bitpay. So I am changing from ACK to NACK, only because there are _many other_ fraudulent companies that have signed the NYA agreement, and thus are trying to trick people. We must remove _each and every signatory_ of the NYA for this to be fair! There is a sickness in the bitcoin community, and these actors are **not** acting good faith and trying to change the rules of the game midstream. Good riddance!

Bitpay isn't close to enough. They all need to be gone!

**Comment by nvk** [comment]
Any non Bitcoin Core 0.15 compatible projects should be pre-emptively removed. Noobs using those services wont know they are being forked out of the main chain.

**Comment by harding** [comment]
ACK.

I think BitPay has had sufficient time to clarify their position, but the only clarification posted so far seems to be the addendum to their blog post quoted by @bobquest33 above.  The word "dysfunctional" in that addendum sounds to me like they don't plan to support the Bitcoin block chain after btc1 hard forks off, in which case they should not be listed on Bitcoin.org.

I hope they will soon clarify that they will default to supporting the Bitcoin block chain without contentious hard forks, in which case I will likely be in favor of quickly relisting them.

**Comment by JaredR26** [comment]
Wait, is the reason for removal because of the fraud accusation, or is it
because of segwit 2x?  Because there's many more segwit2x signers.

**Comment by lichtamberg** [comment]
Thanks for taking a strong stance against all this segwit2x shit. I think the bitcoin/core community somehow really has to defend itself more against this whole shitshow.. First step is taken. Thanks.

**Comment by Grix** [comment]
You're free to remove the reference from your site of course, but it's pretty ridiculous to call it fraud and unethical. Bitpay is simply voting for the btc1 implementation as bitcoin and promoting it on their website, just like bitcoin.org is used to vote for the bitcoin core implementation as bitcoin and promoting it. _Yours and bitpay's tactics to promote your own bitcoin ideology is identical_.

**Comment by rikur** [comment]
ACK

**Comment by opetruzel** [comment]
NACK.

Calling their actions "fraud" is itself borderline libel, not to mention wholly inaccurate.

**Comment by RobbinCremers** [comment]
ACK

Misleading people simply is not acceptible!
We are not handing a shoe business ... 
**We are handling real money coming from real people**

**Pull request merged**
