### PR TITLE
Add Trust Wallet

### PR DESCRIPTION
**Pull request by hewigovens**
Hi,

We'd like to add [Trust Wallet](https://trustwallet.com/) to Bitcoin.org, we have added Bitcoin with native segwit support for both Android and iOS recently.

As mentioned [here](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2815#issuecomment-465274358), let's open a new pr to track this. Please let us know if we need to correct or add something more.

Thanks!

### CODE REVIEW

**Comment by crwatkins** [comment]
@hewigovens Thanks for your submission!

Have you carefully verified that Trust Wallet meets all the listing criteria specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)?  Do you have any questions on any of the criteria?

I've very quickly glanced at your submission.  Your submission points to a GitHub user and not a specific repository which you might want to correct.  If I assume that your iOS source is in **trust-wallet-ios** there are no releases tagged there.  To get a passing score on **transparency** your releases need to be tagged (and of course its just a good idea).

The scores that begin with **checkneutral** are for hardware devices that don't actually provide that function themselves.  I suspect you will want to make other choices there.  Let us know if you need any advice on that.

In your wallet description text the words "Crypto Assets" should not be capitalized.  In general, you may want to consider the rewording of that description.   You'll note that it is longer than any other wallet description, so you might want to take that into consideration.  In addition we try to stay away from using superlatives such as "perfect" unless referring to specific technical terminology.  You also may want to consider that this is a listing on bitcoin.org and a large portion of the descriptions is describing other other currencies.  You may want to focus your description on Bitcoin.

**Comment by hewigovens** [comment]
@crwatkins Thanks for the review.

I have updated the description and `transparency` section, we're used to open source, but decide to close source temporary, you can find reason [here](https://medium.com/@trustwallet/why-open-sourcing-android-app-could-be-a-harm-to-the-crypto-community-fb3ae1707dc6).

**Comment by crwatkins** [comment]
@hewigovens Thanks for the update.  The description looks much better.

Regretfully, we have not been listing closed source wallets.  I totally [sympathize](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1622#issuecomment-307810553) with your situation as we have experienced a very similar situation at bitcoin.org as an open source project.   However, [the community is fairly convinced](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1622) that this should remain a requirement.

**Comment by hewigovens** [comment]
Ok, we fully understand this.

**Comment by crwatkins** [comment]
@hewigovens Thanks for your understanding!  Be sure to let us know as soon as the situation changes.

**Pull request closed without merging**
