### PR TITLE
add Passport HW wallet

### PR DESCRIPTION
**Pull request by sifrant**

### CODE REVIEW

**Comment by crwatkins** [comment]
Thanks for your submission.  Could @zachherbert or @FoundationKen comment on this PR?

**Comment by FoundationKen** [comment]
Thanks for the ping Craig!

I would suggest changing the description as below:

```
walletpassport: "Passport is your ultra-secure, yet easy-to-use, air gapped, Bitcoin-only hardware wallet designed to help you reclaim your sovereignty. Passport is fully open source and manufactured in the US, giving you peace of mind that it can be trusted to secure your Bitcoin. It features a secure element for enhanced hardware-level protection of your private seed, a camera for scanning QR codes, a high-resolution color IPS display, and a rechargeable Lithium Ion battery."
```

And for the image, we'd prefer to use this: https://foundationdevices.com/wp-content/uploads/2022/03/Passport_v1.1.png

**Review by chachamora77 — APPROVED** [review]

**Comment by chachamora77** [comment]
f1bdf059fa85d795ba9472c8ff579895c3840373

**Comment by FoundationKen** [comment]
Thanks for updating the image!  If you can update the `walletpassport` text as above, then this can be merged. @sifrant

https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3955#issuecomment-1407455567

**Comment by sifrant** [comment]
Updated the text as well...

**Comment by crwatkins** [comment]
>  If I get it correctly the build failed bc the description is too long...

That is correct.   As specified[ here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)

> The description must be less than 320 characters and be consistent in style with the other descriptions.  Do not use superlatives or exclusive phrases. For example, you might want to comment on ease of use. Don't write "This wallet is the easiest to use" or "This wallet is extremely easy to use"; write "This wallet is easy to use."

I recommend the following 
* Shorten the description to less than 320 characters.   That should be possible without forfeiting much significant information
* Change the beginning to "Passport is a secure ..." to be consistent with the other descriptions, and remove the superlative
* Do not capitalize bitcoin in "your bitcoin" ("Bitcoin-only" in the description is correct as it refers to the proper currency and not specific funds)
* Do not capitalize Lithium Ion

**Comment by FoundationKen** [comment]
@sifrant Updated copy is below.

```
Passport is a secure, easy-to-use, air-gapped, Bitcoin-only hardware wallet designed to help you reclaim your sovereignty. Passport is fully open source and manufactured in the US. It includes a color IPS display, a rechargeable battery, and an advanced secure element chip to secure your private seed.
```

**Comment by sifrant** [comment]
updated & passed, ready to merge...

**Comment by crwatkins** [comment]
I hate to be so picky, but the [requirements ](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) state

* Screenshot: The png files must go in /img/screenshots, be 250 X 350 px and optimized with optipng -o7 file.png.

The image in this PR is just slightly off that.   Could you resize it to 250 x 350?

**Comment by sifrant** [comment]
should be all right now (:

**Comment by crwatkins** [comment]
I have reviewed the Passport wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design, however because the website does not yet support HSTS, I cannot at this time recommend it for listing.  I will be glad to recommend the Passport for listing once this website issue is resolved.

Note that as a "hardware wallet," only the hardware and firmware components of the device were evaluated.  Wallet software that runs externally to the Passport device was not evaluated in this review.  Sparrow, Electrum, and Foundation Device's Envoy wallet were used during this review, but not evaluated.

I concur with the scoring in f32d40d.

## Passport
### Firmware v2.0.5
### Review Version 2023021501

## Wallets

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was provided by Foundation Devices at no cost.

**NOTE** Only the hardware/firmware is being evaluated here.  Wallet software running external to the device is not being reviewed.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

  **PASS** Sufficient feedback found without concerning issues
  * Some discussions on twitter, Reddit, and Bitcointalk
  * Numerous superficial reviews of this and the previous model in blogs and YouTube
  * A few in-depth reviews including
    * [BTC Sessions on YouTube](https://youtu.be/_uGZHg64wwA)
    * [n0noce on Bitcointalk](https://bitcointalk.org/index.php?topic=5421713.0)


- No indication that users have been harmed considerably by any issue in
  relation to the wallet

  **PASS** No indication found

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication found

- No indication that the wallet uses unstable or unsecure libraries

  **PASS** No indication found.  Passport uses some Trezor crypto libraries.

- No indication that changes to the code are not properly tested

  **PASS** No indication.  Significant tests at https://github.com/Foundation-Devices/passport2/tree/main/tests

- Wallet was publicly announced and released since at least 3 months

  **PASS** This model started shipping July 2022

- No concerning bug is found when testing the wallet

  **PASS** No concerning bugs have been found

- Provides a bug reporting method on the website and/or in the app

  **PASS** https://docs.foundationdevices.com/

- Website supports HTTPS and 301 redirects HTTP requests

  **PASS** http://foundationdevices.com redirects to https://foundationdevices.com

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

  **PASS** https://foundationdevices.com A rating

- Website serving or linking to executable code or requiring authentication uses HSTS
  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

  **FAIL** HSTS not enabled

- The identity of CEOs and/or developers is public

  **PASS** The identities of the principals are well-known https://foundationdevices.com/about/

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **N/A** Addresses and paths are chosen by wallet software

- Avoid address reuse by using a new change address for each transaction

  **N/A** Addresses and paths are chosen by wallet software

- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS**  Signed transactions match transactions from other RFC 6979 wallets

- User has access to private keys for all major components of the wallet

  **PASS** User has access to BIP39 seed from device menu and keys can be backed up to an encrypted microSD card

- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

  **N/A** Keys are stored on the device

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

  **PASS** Wallet can be backed up to encrypted microSD card

  - Restoring wallet from backup is working

  **PASS** Restoring wallet from backup was successful

  - Source code is public and kept up to date under version control system

  **PASS** https://github.com/Foundation-Devices/passport2

- If user has no access to some of the private keys in a multi-signature wallet:
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet

  **N/A**

- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)

  **PASS** Device requires user confirmation to sign a transaction

  - Protects the seed against unsigned firmware upgrades

  **PASS** Firmware upgrades must be signed either by 2 of 4 Foundation keys or by the user installed developer key

  - Supports importing custom seeds

  **PASS**  Custom seeds were successfully imported

  - Provides source code created for all open components and provides detailed specification for blackbox testing of
    any closed-source secure elements

  **PASS** Fully open source at https://github.com/Foundation-Devices/passport2  

Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

  **N/A**

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

  **FAIL** HSTS not enabled

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

  **PASS**

  - Provides users with step to print or write their wallet seed on setup

  **PASS** Setup provides a step to backup the wallet to microSD card

  - Uses a strong KDF and key stretching for wallet storage and backups

  **PASS** Uses 7z encryption for backups which performs 524288 cycles of SHA-256 on the 20 decimal digit backup phrase.

  - On desktop platform:
    - Encrypt the wallet by default

  **N/A**

- For hardware wallets:
  - Prevents downgrading the firmware

  **PASS** Firmware cannot be downgraded

**Comment by sethforprivacy** [comment]
Thanks for the review, @crwatkins!

We've enabled HSTS today, preload will be available once it gets pulled into the relevant browser databases:

image

https://www.ssllabs.com/ssltest/analyze.html?d=foundationdevices.com

**Comment by crwatkins** [comment]
Thanks for the quick update.  The HSTS headers LGTM.   I recommend Passport for listing.

**Comment by Cobra-Bitcoin** [comment]
LGTM. Will merge later today.

**Pull request merged**
