### PR TITLE
This community NEEDS to adopt a code of conduct. Recent events make t…

### PR DESCRIPTION
**Pull request by jrmithdobbs**
…his glaringly obvious.

### CODE REVIEW

**Comment by jrmithdobbs** [comment]
Let me know if you'd like me to squash.

**Comment by jrmithdobbs** [comment]
I want to be clear here. I am a staunch supporter of free speech and have previously been opposed to such things. My mind has been changed, not just by this project, by watching friends and talented engineers berated, harassed, and generally have their mental health destroyed.

**Comment by jrmithdobbs** [comment]
I'm unsure as to whether the current contact language is appropriate as I agree with said policy that anonymity preservation should be an option when reporting.

Input?

**Comment by jrmithdobbs** [comment]
This should also be on an actual page somewhere, imho, but I'm not familiar enough to know where to drop it in the code-base. I was trying to get the request into the 3 main bitcoin-core repos at the same time and just thought about this re: the website.

**Comment by yamamushi** [comment]
You really need to stop this trolling nonsense, as this is the 3rd project today you've tried pushing these rules into:

https://github.com/libbitcoin/libbitcoin/pull/355

https://github.com/bitcoin/secp256k1/pull/369

**Comment by unclediazepam** [comment]
The author of this PR is a known troll and bad actor in other open source communities:

https://storify.com/willrad/breaking-linux-user-is-kind-of-an-asshole

This is their attempt to stir up controversy, as evidenced by their tweet:

https://archive.is/O0hjQ

Please don't allow another open source community to be dragged down by these attention seeking trolls. Close this PR and ignore future trolling from @jrmithdobbs.

**Comment by harding** [comment]
To the best of my recollection, Bitcoin.org has never had a case of an inappropriate comment being made by a serious contributor, so I don't think we need a policy to deal with that at the moment.

We have had inappropriate comments made by non-contributors or very minor contributors, which we've dealt with using warnings (when the comment was on the fence), deletions (when the comment was clearly inappropriate or after a warning was made), and (in one case) a ban after a user continued to make inappropriate comments.

Since the system seems to be work, let's not break it.

**Comment by unclediazepam** [comment]
@apoelstra I appreciate you trying to be equanimous on this subject, however, it is precisely "conduct here or elsewhere" that this PR concerns:

From the PR:

> This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.

This type of verbiage can (and has) been used in the past to persecute those for their personal views even when expressed completely separate from the context of the open source project adopting the CoC.

These CoCs are an attempt by professional activists (not project committers) to push authoritarian social politics into open source communities where it doesn't belong. The CoC is not needed and should be viewed for what it is: outsiders attempting to disrupt and push their political agenda with no concern for how their actions negatively effect the open source project.

**Comment by jrmithdobbs** [comment]
I just want to link this here:

https://github.com/bitcoin/bitcoin/pull/7243#issuecomment-166467231

**Comment by jrmithdobbs** [comment]
I still think this is necessary but to avoid another PR getting shit all over I'm going to go ahead and close.

**Pull request closed without merging**
