### PR TITLE
Added BittyBot as a directory resource

### PR DESCRIPTION
**Pull request by BittyBotUK**
I've added BittyBot.co as a directory resource but you might want to re-categorise it? BittyBot is a directory of bitcoin vendors and exchanges in the form of a price comparison website, a great resource for bitcoin newbies to find where to buy bitcoins.

### CODE REVIEW

**Comment by BittyBotUK** [comment]
Any news on when this can be added? It's a really useful resource, especially for bitcoin newbies. It now supports six different currency markets (GBP, EUR, USD, CAD, AUD, NYD) and compares prices from more sites than are listed on http://howtobuybitcoins.info.

**Comment by wbnns** [comment]
@BittyBotUK Hello, apologies for the slow reply! Thank you for contributing and submitting this pull request. I think the current option with `howtobuybitcoins.info` is sufficient for now, however, if others disagree and feel that `BittyBot.co` should be added, too, let's consider it.

**Comment by BittyBotUK** [comment]
@wbnns thanks for responding to the pull request, lets hope others agree it's a useful resource.

**Comment by wbnns** [comment]
@BittyBotUK You're welcome. I'm going to go ahead and close this PR for now. If others request the addition, we can resubmit the PR to propose the change.

**Pull request closed without merging**
