### PR TITLE
Bitcoin Core 0.18.1

### PR DESCRIPTION
**Pull request by laanwj**
Add bitcoin core 0.18.1
Can be merged if it passes travis

### CODE REVIEW

**Comment by wbnns** [comment]
@laanwj 

Thank you.

**Comment by wbnns** [comment]
@laanwj 

It looks like your commits may no longer be signed, FYI. This one (18c7404) here on this PR, and also:

image

**Comment by laanwj** [comment]
strange, at least locally it shows:
```
commit 18c7404b82aab0f7fc44434282ed9128b1cb8d0b (HEAD -> bitcoin-core-0.18.1, origin/bitcoin-core-0.18.1)
gpg: Signature made Fri 09 Aug 2019 10:58:54 PM CEST
gpg:                using RSA key 9DEAE0DC7063249FB05474681E4AED62986CD25D
gpg: Good signature from "Wladimir J. van der Laan <laanwj@visucore.com>" [ultimate]
gpg:                 aka "Wladimir J. van der Laan <laanwj@gmail.com>" [ultimate]
gpg:                 aka "Wladimir J. van der Laan <laanwj@protonmail.com>" [ultimate]
Author: Wladimir J. van der Laan <laanwj@protonmail.com>
Date:   Fri Aug 9 22:57:58 2019 +0200

    Bitcoin Core 0.18.1
    
    Tree-SHA512: 7bcd07c091374510bd3a89b25f2d508de4d1e975602cd003c6517054290791f7632c77b2d1bf025a0bb7cd5a77895e1de9ec13dc28d641308f271716e0019990
```

**Comment by wbnns** [comment]
@laanwj 

It might be happening if `git config --global user.email` isn't an email address that is associated with the GPG key on the [SSH and GPG keys settings page](https://github.com/settings/keys) on GitHub, but not sure.

**Comment by laanwj** [comment]
yeah, that was it, it's solved now, was jut a github display issue fortunately!

**Comment by wbnns** [comment]
Ah, ok, great. :)

**Pull request merged**
