### PR TITLE
add guides panel to resources

### PR DESCRIPTION
**Pull request by RandyMcMillan**
Screen Shot 2021-01-19 at 2 19 25 PM

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
LGTM.

Let's see what other people think.

**Comment by RandyMcMillan** [comment]
I will be happy to remove or add other guides that the community suggests.

**Comment by crwatkins** [comment]
I'm OK with the concept of guides with the caveat that I could imagine that this list could get overrun with random guides without enough description for a user to select something appropriate.   For example, the first guide isn't really a Coldcard[*] guide.   It's more a Specter guide, or even more accurately a Specter/Coldcard/Bitcoin Core guide.  In any case, folks looking for the simplest way to use their Coldcard could be quite disappointed.  

[*] Coinkite is fairly inconsistent with the spelling of Coldcard vs ColdCard, however they do use the "Coldcard" spelling on their legal page as we do on bitcoin.org.

**Comment by RandyMcMillan** [comment]
after some more input/suggestions - i will add/remove any links that are agreed upon...

**Comment by Cobra-Bitcoin** [comment]
OK, I'll merge this, but let's be conservative in the future with how many guides we add to this list. We'll keep it to only the best ones. The resources page always needed more love anyway, so thank you for adding this.

**Pull request merged**
