### PR TITLE
Add Unstoppable wallet

### PR DESCRIPTION
**Pull request by esengulov**
This PR is a followup to the earlier PR for adding Unstoppable Wallet to Bitcoin.org list, https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3054 It's been a long journey! 

The other thread got rather lengthy so I am staring a new one. As per our earlier discussion we have passed on all criteria with the exception of 'feedback availability'. So last 6 months we were trying to address the feedback part while improving the wallet app with more features along the way.

The earlier submission was for version 0.12 and now we are at 0.18. A detailed log of tickets that were addressed over these 6 releases can be found below:

- iOS : https://github.com/horizontalsystems/unstoppable-wallet-ios/projects?query=is%3Aclosed
- Android : https://github.com/horizontalsystems/unstoppable-wallet-android/projects?query=is%3Aclosed

Below are the highlights of what has changed feature wise for Bitcoin since our last submission:

- custom fee selector 
- extensive privacy controls
- double spend alerts
- integration of privacy coins
- synthetic Bitcoin assets i.e. sBTC
- extensive onboarding improvements

There were some other major enhancements done to the wallet which are not listed above i.e. full integration with Ethereum DeFi ecosystem and some of the emerging DeFi Protocols i.e. WalletConnect and Uniswap.

### Active Users

Number of daily active users nearly quadrupled over last 4/5 months. Going from about 1.5 to about 4.5 thousand daily active users. These are the people that user the wallet app daily. 

Along with that the amount of user feedback available in Play Market / App Store has increased significantly as well. During this time we have never seen anyone experiencing serious issues with the wallet i.e. a problem leading to the funds loss. There were bug reports here and there and all cases were addressed. 

### Partnerships

Unstoppable worked with Zcash team to be the first wallet to support fully shielded/private Zcash transactions. That partnership turned out fairly well and we continue working with them on various features.

- https://electriccoin.co/blog/zcash-is-unstoppable-privacy-focused-wallet-first-to-integrate-ecc-wallet-sdks/
- https://forum.zcashcommunity.com/t/zcash-is-unstoppable-ama/37782/15

We are working on other partnerships with players in the cryptocurrency ecosystem as well which, will be announced in the coming weeks.

### Security Audit

Few weeks back we have completed our first security audit by Certik, https://certik.foundation. The audit was specifically focused on private key generation and key storage security. The audit hasn't revealed any serious issues and about to be published on their website. 

The audit did make a couple of minor suggestions related to some non-critical elements all of which are being implemented in the release version 0.19 scheduled for mid January.

All that said, we still remain one of the few wallets out there with verifiably open source code as listed on WalletScrutiny.com.

### User Help / Assistance

We monitor feedback on crypto forums, subreddits, app stores, social channels and Google in general. 

The wallet also got an extensive FAQ section for troubleshooting as well as Academy section for learning cryptocurrency and Bitcoin in particular. Moreover, the users can easily reach us on Twitter, Reddit and via email.

I invite you to check out the wallet website which reflects most of the recent improvements as well, https://unstoppable.money

Looking forward to for your feedback!

### CODE REVIEW

**Comment by crwatkins** [comment]
Thanks for the submission.  It looks like you've been making massive progress!

Could you change your description to be consistent with most of the other listings and start the description with a full sentence instead of just a fragment?  For example:  "Unstoppable is an easy and intuitive to use wallet."

**Comment by crwatkins** [comment]
It looks like you've made quite a few improvements to your fee selection!  However, I don't believe Unstoppable supports RBF or CPFP, is that correct?

The current fee score in the 5fee304 submission is **checkgoodfeecontrolfull** which requires either RBF or CPFP support.   You probably want to change that score to **checkpassfeecontroldynamic**.

I note that the Unstoppable fee selection interface doesn't allow users to choose a custom fee of over 200 sat/byte, which I believe could be constraining in some extreme situations.  I recommend that at some point that restriction be removed, and at that time the fee score should be changed to **checkpassfeecontroloverride** with another PR.

I concur with the other scoring in 5fee304.

As for the sufficient feedback requirements, based on the additional usage, feedback, and the audit, I see no problem meeting that criterion.  I'll be happy to recommend Unstoppable for listing once the description and the fee score has been updated.

**Comment by esengulov** [comment]
> It looks like you've made quite a few improvements to your fee selection! However, I don't believe Unstoppable supports RBF or CPFP, is that correct?

Yes, Unstoppable doesn't support RBF yet. We do plan to add it in the near future. We tried to add earlier and there were some non-standard use cases of that feature which had to be addressed without compromising usability. Thanks for pointing out the inconsistencies in fee score, I made the needed changes. 

> I note that the Unstoppable fee selection interface doesn't allow users to choose a custom fee of over 200 sat/byte, which I believe could be constraining in some extreme situations. I recommend that at some point that restriction be removed, and at that time the fee score should be changed to **checkpassfeecontroloverride** with another PR.

Sounds good. Just to clarify, is it OK for the current fee score to be set to "checkpassfeecontroloverride" or does it need to be downgrade 'non-passing' value until the 200 sat/byte limit is removed? Meanwhile it is set to "checkpassfeecontroloverride".

Thank you!

**Comment by crwatkins** [comment]
Currently the latest commit 4fab804 shows the fee score is **checkpassfeecontroldynamic** which is a passing score and looks good to me.

I'm happy to recommend Unstoppable for listing.

**Pull request merged**
