### PR TITLE
Add Coinmerce.io to exchanges

### PR DESCRIPTION
**Pull request by lucsvo**

### CODE REVIEW

**Comment by syaifudin857** [comment]
Join

**Comment by wbnns** [comment]
@lucsvo 

Hello, when reviewing the exchange we noted that emails received upon creation of a new account go to spam. This is because emails from the exchange are sent via Sendgrid, while the SPF record for the domain is configured for Mandrill.

Please let us know when this is resolved and we will resume the review.

**Comment by lucsvo** [comment]
Hi @wbnns ,

It has been resolved! 
Thanks in advance.

**Comment by lucsvo** [comment]
Hi @wbnns ,

Is there any update on our request?
Looking forward to hearing from you.
Thanks in advance.

Kind regards

**Comment by wbnns** [comment]
@lucsvo 

Hello, we've recently updated our [documentation](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md) for the addition of exchanges. We would appreciate it if you all would review it and let us know how you all would like to proceed.

If you all have any questions, please let us know.

**Pull request closed without merging**
