### PR TITLE
Adding Voyager to US exchanges page

### PR DESCRIPTION
**Pull request by ilyasubkhankulov**
Voyager is a licensed crypto broker, open to residents of the United States. Voyager makes it easy for customers to trade nearly 30 top cryptocurrencies, 100% commission-free. Deposits can be made via ACH, wire transfer, and seven cryptocurrencies.

Voyager is currently available in all U.S. states except New York and is expanding internationally later this year. Users should check Voyager's [availability page](https://www.investvoyager.com/app) for updates.

### CODE REVIEW

**Comment by syaifudin857** [comment]
Join

**Comment by wbnns** [comment]
@ilyasubkhankulov 

Hello, when attempting to review the exchange, we created a new account and were promptly instructed to utilize the account activation link sent to the email address we provided. No email was ever received.

**Comment by wbnns** [comment]
Reopening this PR; we are reviewing this exchange.

**Comment by wbnns** [comment]
We contacted this exchange's support team but did not receive any acknowledgement or reply in a timely manner (> 1 month).

We recommend that a review be deferred for at least six months.

**Pull request closed without merging**
