### PR TITLE
Add Trustee wallet

### PR DESCRIPTION
**Pull request by rhrusha**

### CODE REVIEW

**Comment by crwatkins** [comment]
@rhrusha Thank you for your submission.

Have you carefully reviewed each of the [listing criteria](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)?  Do you believe that you meet every one of the criteria?

Some of the criteria are fairly terse, so if anything isn't clear or if you have any questions, please ask them here.  Please don't assume that you meet any criteria that you don't understand.

**Comment by rhrusha** [comment]
@crwatkins Thank you. 

Regarding this criteria. 
>Wallet was publicly announced and released since at least 3 months

Does this mean release on app markets or first date of sources publication?
The wallet first public release on google play was on Apr 26 but sources we opened much later.   

I will closely review the rest of criteria and update this PR.

**Comment by crwatkins** [comment]
> Does this mean release on app markets or first date of sources publication?

The date is the later of the production (not beta) release and the publication and ongoing maintenance of the source code.  Note however, that new wallets are seldom listed in only three months because of the need for sufficient feedback.   I've written a few times on this pesky criterion, including the last paragraph in [this](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-433630363) review.

**Comment by rhrusha** [comment]
Hi @crwatkins, 

I guess we are ready for review now.

**Comment by crwatkins** [comment]
@rhrusha I'm very confused about your version numbering.   The latest iOS version on the About page in the app is 329 and the commit ID listed (I assume that is a commit ID) doesn't match anything on GitHub.   The iOS app store lists the current version as 1.0.26 with over a dozen versions and the only tagged commits (actually the only commits) on GitHub are 1.0 and 2.0.   Nothing at all seems to match up.  Can you resolve this?

**Comment by wbnns** [comment]
Since it has been over a month without a reply, we're closing this PR for now.

We can reopen it if activity resumes.

**Pull request closed without merging**
