### PR TITLE
Create Developer Reference RPC page for gettxoutproof and verifytxoutproof

### PR DESCRIPTION
**Pull request by ChainQuery**
Create Developer Reference RPC page for gettxoutproof (as of core 0.11.0)

Happy to also create verifytxoutproof, but want to verify I'm submitting this properly first.

-Ian

### CODE REVIEW

**Comment by harding** [comment]
@ChainQuery thanks!  I haven't had a chance to update the docs for 0.11 yet, so your help is much appreciated.

As you can see, the build failed.  The reason is that you need to add the following line to `_include/references.md`:

    [rpc gettxoutproof]: /en/developer-reference#gettxoutproof

You'll see where to add it if you search that file for `gettxout`.  Also, can you search the following additional files for `gettxout` and add an entry for gettxoutproof using the format used in the nearby lines:

- `_autocrossref.yaml`
- `_config.yml`

Then, run from a Linux command line `make manual-updates`.

Sorry, I know that's a lot.  If you can't do everything, do what you can and I'll send you a patch for the rest when I review the PR.  Thanks again!

**Comment by ChainQuery** [comment]
Understood, thanks.

I'll add verifytxoutproof as well and update the additional files.

**Comment by ChainQuery** [comment]
Well, thats all I've got... I pulled it onto my Mac and ran "make manual-updates" but it still has this error:

ERROR:
_site/en/developer-reference.html#gettxoutproof not found
_site/en/developer-reference.html#verifytxoutproof not found

I'm missing something I'm sure, still learning the Git ropes...

**Comment by harding** [comment]
@ChainQuery it's not Git's fault, it's mine for not documenting this process.  I hadn't quite realized how many places stuff needs to be done in order to add a new RPC document.  To fix the current error, open the file `en/developer-reference.md`, search for "txout", and copy-paste-adapt lines like you did in  3fc26caf759cbdf41a8e60003543c1e4f00542ec

I think that should be it... I hope.  Thanks again!

**Comment by ChainQuery** [comment]
Ahhh, it was the "_site" reference in the error I could not find, as there is no _site directory, I understand it now, hope that did the trick...

**Comment by harding** [comment]
@ChainQuery I sent you a PR with some tweaks, but your descriptions were excellent.

The changes to the `_includes/helpers/summaries.md` were the result of you running the manual-updates command I described in a previous comment.  It looks like extra lines were moved around because your locale has a different sort order than mine, so in the PR I sent you I set the locale to plain UTF-8 which should prevent the problem in the future (you don't need to do anything extra).

Once that PR is merged, I'll schedule this PR for merging into the site.  Thanks again!

**Comment by harding** [comment]
@ChainQuery urgh.  I messed up that last commit---sorry---can you make this change:

```diff
diff --git a/_includes/ref/bitcoin-core/rpcs/rpcs/gettxoutproof.md b/_includes/ref/bitcoin-core/rpcs/rpcs/gettxoutproof.md
index 55d8d06..bae4f6f 100644
--- a/_includes/ref/bitcoin-core/rpcs/rpcs/gettxoutproof.md
+++ b/_includes/ref/bitcoin-core/rpcs/rpcs/gettxoutproof.md
@@ -36,7 +36,7 @@ specify the block in which the transaction is included in manually (by block hea
 *Parameter #2---the block to look for txids in*
 
 {% itemplate ntpd1 %}
-- n: "`block hash`"
+- n: "Header hash"
   t: "string"
   p: "Optional<br>(0 or 1)"
   d: "If specified, looks for txid in the block with this hash"
```

**Comment by harding** [comment]
Previews:

- http://dg2.dtrt.org/en/developer-reference#rpc-quick-reference
- http://dg2.dtrt.org/en/developer-reference#gettxoutproof
- http://dg2.dtrt.org/en/developer-reference#verifytxoutproof

In the absence of critical feedback, this will be merged Sunday.

**Pull request closed without merging**
