### PR TITLE
Add Swyftx as an Australian exchange

### PR DESCRIPTION
**Pull request by Swyftx-Pty-Ltd**

### CODE REVIEW

**Comment by wbnns** [comment]
@Swyftx-Pty-Ltd 

Hello, when reviewing the exchange we were unable to sign up because an Australian phone number is required. Sign ups not following the convention of an Australian number result in an error message (e.g. trying to use any other phone number). Also, the error message is slightly non-descript in its insinuation that an Australian number is required:

image


We understand it may be a requirement to be an Australian national in order to use the exchange, however, we recommend that you still allow users to sign up with their preferred phone number. This restriction could potentially be problematic in terms of 2FA/MFA, where-in users may already have it configured with a different non-Australian number for other websites.

Please let us know when this is resolved and we will resume the review.

**Comment by Swyftx-Pty-Ltd** [comment]
@wbnns 

Hi Will, thanks for taking the time to review the site. I'm sorry to hear you were unable to proceed through registration. We agree the error message there is a little non-descript and have updated the error message accordingly. 

In regards to 2FA/MFA, we do not use SMS or phone numbers for those in an attempt to reduce the likely hood of SIM swap attacks. The current requirement for Australian only numbers is part of our compliance processes (AML/CTF), as the ownership of the Australian number in itself does provide some supporting evidence of Australian residency. 

Although we are not entirely object to removing this restriction, we would appreciate it if you could consider the above points and let me know if that satisfies your concerns? If you'd like to try accessing the platform again, you can do so using any number you like that adheres to Australian formatting, +61 4xx xxx xxx (although it won't be able to be verified, which will prevent AUD deposits & withdrawals).

Thanks!

**Comment by Swyftx-Pty-Ltd** [comment]
@wbnns - Just wanted to check in to see if you'd had a chance to review our recent comments on this one?

**Comment by wbnns** [comment]
@Swyftx-Pty-Ltd 

Hello, thank you for following up. We were not able to sign up and conduct an initial review the exchange, due to the above issue.

**Comment by GusGold** [comment]
Hi @wbnns 

We've updated it so that you can signup using any number capable of receiving SMSes. Would you be able to review it now?

Thank you.

**Comment by wbnns** [comment]
@GusGold Ok, sure, thank you. We'll check.

**Comment by wbnns** [comment]
@Swyftx-Pty-Ltd 

Hello, when we tried to sign up, we filled in the sign up information and upon using the `CREATE MY ACCOUNT` button to complete the process, encountered a spinning circle that failed to direct us to a subsequent page:

Screen Shot 2019-06-01 at 19 48 05

We noted the following event in our developer console, in case helpful:

Screen Shot 2019-06-01 at 19 52 53

We were unable to complete the sign up.

**Comment by GusGold** [comment]
Hi @wbnns,

I can see that error in our log, however it occurred before you signed up. It looks like you signed up 3 minutes later which went through fine, however the front end was still dealing with the error, which meant you didn't get logged in after signing up.

Can you please try logging in again with the same credentials you signed up with.

Thank you

**Comment by GusGold** [comment]
Hey @wbnns, just following up on your review. 

Your account was created successfully last time and you can login and review at your convenience.

In line with your original concerns about restricting to Australian phone numbers, please note that there are no geo-based restrictions for depositing/trading/withdrawing crypto assets, however, when depositing/withdrawing fiat assets, we are currently restricted to supporting only Australian residents only.

**Comment by GusGold** [comment]
Hi @wbnns 

Just a friendly reminder to review this when you get a chance.

Thanks!

**Comment by wbnns** [comment]
@GusGold 

Hello, we've encountered additional issues:

1. No prices are quoted in AUD, they are quoted in USD, despite this being an Australian exchange. This could potentially be very confusing for users to not see prices in their local currency, because both AUD and USD use the same "$" symbol.

2. On the homepage, it's noted in the "Media" section that Swyftx is recognized by bitcoin.org, as the first entry in the section. This may give an incorrect impression to site visitors. As indicated in this issue, there have been problems that we've encountered each time we've reviewed the exchange over the past few months.

image

**Comment by GusGold** [comment]
Thanks for the feedback, @wbnns.

1. We've just added AUD trading pairs to Swyftx which is available via the [base currency drop down](https://help.swyftx.com.au/articles/2099820-what-is-the-base-currency-drop-down)

2. We have updated our media section

**Comment by wbnns** [comment]
@GusGold 

Hello, we noted that the homepage still references BTC relative to USD in several places, rather than BTC relative to AUD. It would be important for BTC to be referenced relative to AUD if the exchange were to be potentially added to the list of exchanges in Australia.

**Comment by GusGold** [comment]
Hi @wbnns 

We've updated our homepage to reference AUD instead of USD where appropriate. 

Thank you in advance for your follow-up review.

**Comment by GusGold** [comment]
Hey @wbnns 

Just following up on the updated reference from USD to AUD.

Would love to get your review on it.

Thanks

**Comment by GusGold** [comment]
Hey @wbnns 

Have you had a chance to review the changes made?

Thank you.

**Comment by wbnns** [comment]
@GusGold Hello, no, but we'll let you know when we do.

**Comment by wbnns** [comment]
@GusGold 

Thank you for being responsive in dealing with and resolving the various issues we've discovered during the multiple reviews of your exchange performed over the past few months. After additional consideration, we feel that it would be best to wait until the end of the year and re-review the exchange in early January.

At that time, we are hopeful that:

1. We will not discover any new issues.
2. It will be easier to find user and community feedback on your new exchange. At the moment, it appears there is very little.

Please feel free to follow-up with us in early January and we'll be happy to review your exchange again. Should other active contributors to bitcoin.org elect to review your exchange again in the interim and recommend an earlier inclusion, they are of course welcome to do so.

**Comment by GusGold** [comment]
Hi @wbnns,

I just wanted to provide you a non-exhaustive list of feedback and reviews in the hopes that it will assist you in expediting your re-review:

* [Google](https://g.page/swyftx/)
* [Facebook](https://facebook.com/swyftx/reviews/)
* [CryptoHead](https://cryptohead.io/australia/best-exchanges/)
* [Finder](https://www.finder.com.au/swyftx-exchange-review)
* [CryptoNews](https://cryptonews.com.au/2018/digital-currency-trading-platform-swyftx-trading-australians/)
* [TrustPilot](https://au.trustpilot.com/review/swyftx.com.au)
* [Medium](https://medium.com/@cryptogoodoil/startup-australian-crypto-exchange-swyftx-officially-launches-545e31a2b986)

**Comment by GusGold** [comment]
Hi Will,

We've been gaining a lot of traction, and it's evident in the reviews our customers have been leaving for us. It would be great if you could re-consider the early January timeframe we have with the following reviews and articles:

* 17 reviews on [Google](https://g.page/swyftx/)
* 14 recommendations on [Facebook](https://facebook.com/swyftx/reviews/)
* 13 reviews on [Trustpilot](https://au.trustpilot.com/review/swyftx.com.au)
* 8 reviews on [ProductReview](https://www.productreview.com.au/listings/swyftx)

Along with articles on:
* Rated #1 on [CryptoHead](https://cryptohead.io/australia/best-exchanges/)
* Top 10 on [Finder](https://www.finder.com.au/cryptocurrency/exchanges)
* 5 Stars on [HedgeWithCrypto](https://www.hedgewithcrypto.com/swyftx-review/)

**Comment by wbnns** [comment]
@Swyftx-Pty-Ltd 

Hello, thanks for letting us know. Since we've already reviewed the exchange three separate times this year and have encountered issues each time, we stand by our recommendation to wait until January at the earliest, before reviewing again.

**Comment by GusGold** [comment]
Hi @wbnns ,

Happy new year! It'd be great if you could take the time to re-review Swyftx. We also have live chat available between 9am and 9pm AEST (11pm and 11am GMT) that you can use to ask any questions on.

Below are our updated review counts and links for your convenience:

* ~~13~~ 115 reviews on [Trustpilot](https://au.trustpilot.com/review/swyftx.com.au)
* ~~17~~ 36 reviews on [Google](https://g.page/swyftx/)
* ~~14~~ 31 recommendations on [Facebook](https://facebook.com/swyftx/reviews/)
* ~~8~~ 9 reviews on [ProductReview](https://www.productreview.com.au/listings/swyftx)

**Comment by wbnns** [comment]
@GusGold 

Hello, thank you for the update. We've recently updated our [documentation regarding the addition of  exchanges](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md). We would appreciate it if you'd please review it and let us know how you'd like to proceed.

**Comment by GusGold** [comment]
Thanks @wbnns ,

It's definitely disappointing to see that after a year of denying our PR it's now expected that we pay.

Given that the original pull request was back in February last year, your last review of Swyftx was on June 28th, and all feedback was resolved on July 4th; all of which were way before the new listing documentation was added, reconsideration of the requirements given the circumstances would be appreciated.

**Comment by wbnns** [comment]
@GusGold 

I'm sorry you feel that way, however, please note that Swyftx has failed to pass a review on four separate occasions in the past year. This, combined with sparsely available public feedback at the time, was why the listing request was deferred until 2020 and is now subject to present day requirements as a result.

**Pull request closed without merging**
