### PR TITLE
Corrected some strings to reflect the reality of today.

### PR DESCRIPTION
**Pull request by sandakersmann**
Corrected some strings to reflect the reality of today.

### CODE REVIEW

**Comment by wbnns** [comment]
@sandakersmann Thanks for taking the time to submit a PR, but no.

**Comment by Dopefish123** [comment]
ACK

**Comment by ThoenigAdrian** [comment]
@sandakersmann lol, nice one !

**Comment by indetronable** [comment]
Why not ? Why you lie on your website ?

**Comment by achow101** [comment]
The terms fast, slow, low, and high are all relative terms. The website is not lying as Bitcoin is still faster and has lower transaction fees than traditional money transfer systems. Compared to previous Bitcoin transactions, confirmations may be slower and fees higher, but that is irrelevant to the website which is intended to publicize Bitcoin in contrast to traditional money transfer systems. 

Anyways, @wbnns I suggest that you lock this thread as I think that it will be severely trolled in the near future.

**Comment by tmaddison** [comment]
It's pretty slow, I think your lying.

**Comment by adriandelarco** [comment]
@achow101 Paypal is instant and zero fee for low transactions.

**Comment by Vaesper** [comment]
@adriandelarco paypal transactions aren't money, they are promises of money.

**Comment by schildbach** [comment]
Perhaps the wording should be changed from a classification (e.g. "fast") to something quantifyable ("in a matter of hours")? Then everyone can make his/her own opinion about if that's fast or slow.

**Comment by ebelinski** [comment]
Likewise, let's say that Bitcoin has [5%+](https://www.reddit.com/r/Bitcoin/comments/5q0plz/just_paid_23_cents_on_a_374_transaction_when_does/) processing fees, and let users make up their own mind if that's "high" or "low".

**Pull request closed without merging**
