### PR TITLE
New documentation for adding exchanges (related: #3174)

### LINKED ISSUE #3174: [RFC] Review Fee for Exchanges
The [Exchanges page](https://bitcoin.org/en/exchanges) is a popular page on the site, and receives millions of visits from people who are looking for options to choose from to exchange their bitcoin. As Bitcoin continues to grow in popularity, we're seeing a proliferation of exchanges [requesting to be added to the Exchanges page](https://github.com/bitcoin-dot-org/bitcoin.org/pulls?q=is%3Apr+label%3AExchanges). Being on the page is beneficial to exchanges because it helps them get new customers and also improves their rankings across search engines from being linked to from bitcoin.org (bitcoin.org ranks very high for "buy bitcoin" and "bitcoin exchanges").

Exchanges are reviewed before being added to the site. Each month there are requests that are denied due to issues that arise during reviews (which are technical, thorough and unbiased). In an effort to provide continuous and stable/regular funding to the site, and to remain ad-free and neutral (as opposed to a sponsorship model which has been experimented with in the past that singles out one or more select organizations), we wanted to solicit community feedback about the possibility of requiring an annual non-refundable review fee to all exchanges requesting to be part of the page.

The idea is that the review fee would be non-refundable and would basically cover each exchange being reviewed upon request for potential inclusion along with regular re-reviews on an ongoing basis - these things we already do. So basically, there would be no change to the current workflow, with the exception of the fee.

Cc: @Cobra-Bitcoin

### PR DESCRIPTION
**Pull request by wbnns**
Closes #3174 and provides documentation that can be referenced for how to add an exchange, review fee details plus instruction for waiving fee.

Cc: @Cobra-Bitcoin

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
LGTM. Maybe make the "Payment of this fee does not guarantee inclusion" part bolded for extra emphasis so exchanges fully understand that.

**Comment by wbnns** [comment]
@Cobra-Bitcoin Ok, thanks, 6dfadd86.

This is scheduled to be merged on Wednesday, November 27th.

**Comment by crwatkins** [comment]
Just for the record, I [still](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3174#issuecomment-554579689) do not support charging for reviews.  As I've [said ](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1337#issuecomment-241895424) for a long time now, I view bitcoin.org as a resource for users over a marketplace for vendors.  Charging for reviews may preclude listings that users would have otherwise had access to.  I don't think we should be turning this into an [ROI decision](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3196#issue-527709830) by exchanges, but rather encouraging support of the site by providing  proper acknowledgement and appreciation.

**Comment by Cobra-Bitcoin** [comment]
@crwatkins I think the fees provide a good balance between regularly adding new exchanges that have been properly reviewed, whilst making sure we don't get swamped with exchanges who expect free marketing. If an exchange can't even be bothered to pay less than the cost of a decent laptop or PC for review, it's a service to the users to avoid listing it. These exchanges don't exist as charities, they charge fees to their users respectively, so I don't see the big deal in also charging them for the labour required to thoroughly review their exchange and make sure it meets our standards. This is different than wallets who may not have the resources to pay, and who aren't trying to make money from users.

**Pull request merged**
