### PR TITLE
From version 1.2 to version 2.0, Bitcoin whitepaper korean translation document contribution

### PR DESCRIPTION
**Pull request by mincheolim**
Hello. I'm Mincheol Im. Since 2017, I have been disclosing the translation process of the original English text of the Bitcoin White Paper into Korean and distributing the translated version through my personal blog [1]. After losing interest in this work during the Covid-19 pandemic, I'm releasing this new Korean translation (version 2.0) [1-1, later added]. with improved readability and translation quality after 4 years. As I did four years ago, I would like to display my name and my GitHub link[2] on the bitcoin.org website Bitcoin Whitepaper download webpage[3] and distribute my latest translation files there.

In fact, my earlier translated version has been distributed on the bitcoin.org website for more than three years, since January 2019. However, without my knowledge, the final Korean version (version 1.2) that I translated disappeared from the bitcoin.org website. Disappointingly, a Korean version other than my translation is being distributed using the same file path[4] as before. The version appears to have been submitted by a person named Kyungwon Park. In GitHub's bitcoin-dot-org project commit history, I found a record[5] in which my name as the existing Korean version distributor, was deleted and Kyungwon Park was added.

There is a problem with the Korean translation version of Kyungwon Park that is currently being distributed. First of all, the file size of a 9-page PDF document with text and diagrams is 22MBs or more(22,985,185 bytes, exactly). That's 73 times larger than my latest translated PDF file (312,679 bytes). This huge PDF file would seem reasonable in size if it included GIF animations visualizing the Merkle tree branch removal or block creation process, but no such notable additional information was added. It should be taken into account that there is no clear benefit to deliberately generating more traffic on the Internet by distributing this version, and that there are still many people who have to use the Internet at low speeds and with less data.

I believe it is appropriate to provide a much more lightly polished version of the translation, as I have improved the layout, typography, readability, consistency, and coherence of the document over a period of time. From the beginning of the translation, I respected GitHub's bitcoinwhitepaper translation project guidelines, modified the entire text and diagrams of the original ODT document into Korean, and extracted it into a PDF file, preserving a small file size, document readability, and the original layout. I have been continuously participating in the translation project since posting the first translated version (version 1.1) on the bitcoin.org website. In this process, we supplemented the document up to version 1.2[6] and also contributed to improving the localization level of the Korean translation version. For example, the file name of the Korean translation document posted on the existing bitcoin.org website used the ISO standard country code (kr), but after I left a question about notation practices [7], it was changed to use the language code (ko).

If Kyungwon Park's version was so much better than mine, I don't think I would have bothered to release a new version. But I don't know this person at all, and I've never even talked to him about translation. I don't think this person stole my translation, but I think he would have cooperated with me if he had wanted to improve the expression, design, structure, and coherence of the Korean translation to improve its overall quality and improve reader understanding. Unfortunately, Kyungwon Park's Korean translation file not only lacks any groundbreaking changes in terms of the data it contains, but is also suspected to have been an awkward alteration of Mincheol Im's Korean version (version 1.2), which was distributed through the same channel just before. After uploading version 1.2 of Mincheol Im's Korean translation document and Kyungwon Park's Korean translation document to the diffchecker.com[8] service, which compares PDF file content and metadata, the document metadata is almost identical. In particular, the Date Created of the two documents is the same in year, month, day, and time, and the Modification Date, which is not in my document but only in Kyungwon Park's document, is December 21, 2022, just before uploading to the bitcoin.org website. It's been over 3 years since Date Created. [9]

[1] https://mincheol.im/bitcoin
[1-1, later added] https://github.com/mincheolim/bitcoin.org/blob/5930eb02762ec19df4a5d55a6082433edff78563/files/bitcoin-paper/bitcoin_ko.pdf
[2] https://github.com/mincheolim (Changed from previous https://github.com/imc84)
[3] https://bitcoin.org/en/bitcoin-paper
[4] https://bitcoin.org/files/bitcoin-paper/bitcoin_ko.pdf
[5] https://github.com/bitcoin-dot-org/Bitcoin.org/commit/bc3bcbe521c5cf72a4130968792e904b79b2fa16
[6] https://github.com/mincheolim/bitcoinwhitepaper/commit/7d7fe6889b46a228cb4530839a54a01d818cd914
[7] https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3069
[8] https://www.diffchecker.com/pdf-compare/
[9] screenshot attatched below:
PDF metadata

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
I should begin by saying I appreciate your contributions Mincheol. I hope you don't feel offended by your translation being removed. I agree the file size is too big on the current Korean translation. It should be much smaller.

Are you claiming the new Korean version stole your work and copied your translation? From what I understand, the new version is produced by a professional translator who was paid for this job.

Apparently the new version is supposed to be "more readable and accurate". I don't understand Korean though so I have no way of knowing which translation we should have on the site. It would help a lot if some Korean speakers could give their opinions.

**Comment by mincheolim** [comment]
> I should begin by saying I appreciate your contributions Mincheol. I hope you don't feel offended by your translation being removed. I agree the file size is too big on the current Korean translation. It should be much smaller.
> 
> Are you claiming the new Korean version stole your work and copied your translation? From what I understand, the new version is produced by a professional translator who was paid for this job.
> 
> Apparently the new version is supposed to be "more readable and accurate". I don't understand Korean though so I have no way of knowing which translation we should have on the site. It would help a lot if some Korean speakers could give their opinions.

--

It is unfortunate for this community that the Korean translation of Park currently being distributed is the result of a paid professional translation. This is because the translation results provided by Park are too unprofessional to be considered the work of a paid professional.

Let me first summarize what I want to say. I request that you immediately distribute the latest translation (v2.0) I submitted on bitcoin.org. As an existing translation contributor, there is no reason why I should seek the input of new Korean speakers to provide improved translations. As I have done over the past few years, I can continue to improve it based on user feedback and my own efforts to suit the nature of this community. If ever there was a time to seek the opinions of other Korean speakers in the community, that time should not be now, but at a time in the past when I deleted my existing translation in order to distribute Park's translation [1]. And as a result of my analysis, the translation by Park, a paid professional translator, has many problems in providing a representative Korean translation to Bitcoin community participants around the world. Both the work method and the result show flaws, and if the work is paid for, there will be no room for improvement in the future without additional compensation.

The specific explanation is as follows.

First, I am already ready to deploy a revision (v2.0)[2] of the existing version on bitcoin.org. Compared to my existing translation version (v1.2), this version has improved the consistency of key terms, readability from the perspective of Korean readers, and the beauty of the visual document format. I published a post [3] explaining major improvements as an extension of existing translation work. If there were no procedural problems in the community deleting my existing version of the translation without prior notice and posting Park's translation, it is only fair that there should be no problem in posting my new translation that has been submitted now.

I think it is a reasonable process at this time to distribute my new revised version on bitcoin.org from now on and discuss later if there are any opinions among Korean speakers that Park's translation should be maintained. In the process of replacing my translation, which I improved and managed four years ago[4], with Park's translation this year[1], I can't find any trace of receiving feedback from Korean users. But is there any reason to receive opinions from Korean users in the process of replacing Park's translation with my new translation? This raises questions about procedural fairness, and I hope it doesn't seem like I'm being intentionally rude.

Second, just because my translation does not require compensation, there is no reason to assume that it is less accurate or readable than Park's translation. I am a user who respects the open source community culture and is interested in various translation projects. Although he has not been active during the pandemic, he has been providing translation services in the Bitcoin community for several years. I am also an industry worker who has been analyzing the technology community and industry in Korea. I participate in volunteer translation as part of my personal interests and hobbies. Additionally, I have been posting the Bitcoin paper translation process, changes, and improvements on my blog for several years[3]. As a community member who has revealed my identity and communicated with readers, I am open to the possibility of dialogue in order to answer and improve external issues or questions regarding any of my work results, including translations. Unlike Park's case, I have displayed a link to my GitHub account[5] while distributing my translations, and may also disclose my personal email address[6] in my translations if necessary.

Initially, immediately after confirming that my translation had been replaced, the first thing I did was to ask Park what had happened, but I had no means of contacting him to point out that there was a problem with the translation or the file other than the name displayed. Do you have such means? Is there an avenue open for the community to review the paid work of these professional translators for any issues and request corrections or retractions? Is there room for continued improvement in Park's translations in the future? Otherwise, even if Park's current translation is "more readable and accurate" than other translations, I don't think distributing his work is in keeping with the nature of this community. Even if you are a professional translator who does not focus on a specific topic, it is difficult to produce good translation results if you do not understand the open source community culture and the unique atmosphere and interaction methods of the computer science and IT industries.

Third, Park's translation is actually inaccurate. Here are just two things you can check quickly.

The term “Binomial Random Walk” appears in the second paragraph of “11. Calculations” on page 6 of the paper translated by Park. This means continuous movement whose path is determined by binomial distribution probability. Here, Binomial should be translated into Korean as “이항[Ihaŋ]”. That's my translation, of course. However, Park made the error of translating Binomial as “이산[isʰan].” “이산” in English is "Discrete", not Binomial, and is a superordinate concept of Binomial. In mathematics, subtypes of Discrete distribution[”이산 분포”, isʰan bunpʰo] include "Binomial distribution[”이항 분포”, ihaŋ bunpʰo])", "Multinomial distribution[”다항 분포”, tahaŋ bunpʰo]", "Poisson distribution[”푸아송 분포”, pʰuasʰoŋ bunpʰo] ]", etc. are listed. Park's translation of “Binomial” into “이산” meaning discrete is an obvious mistranslation.

The term “Poisson distribution” appears on page 7, paragraph 8 of the paper. Among the several types of Discrete distribution I introduced earlier, another subtype that is distinct from the Binomial distribution is directly mentioned. Poisson distribution is "푸아송 분포[pʰuasʰoŋ bunpʰo]" in Korean, and both my and Park's translations write it this way. However, in relation to this, the term “Poisson density” appears in the ninth paragraph. I don't have enough skills to explain the mathematical differences between the two concepts, but distribution and density are completely different concepts in statistics. Density should be written as “밀도[milt̕o]” in Korean. However, Park translated both the terms "Poisson distribution" and "Poisson density" as "푸아송 분포." Park's translation of “density” into “분포” is also an obvious mistranslation. This part, in particular, develops an argument that it is practically impossible for an attacker to maliciously manipulate the contents of blocks recorded in the longest chain, but it does not properly convey the meaning of the original text explaining this.

I have attached a screenshot of the document [7] below, which directly compares the corresponding English original text, Park's translation, and my (Mincheol) translation.

Fourth, is my claim that Park's Korean version 'stole' from me? In fact, proving it in terms of content requires a lot of time and energy, even to Korean speakers, and it is difficult to guarantee that it can be clearly proven. However, is my claim that Park's Korean version 'copied' my PDF file from a data or file perspective? Yes, it is quite suspicious and I can give you some clues. And I think this is an inappropriate way of working as “a professional translator who was paid for this job,” and as you can see, the results are also inappropriate.

A representative example is file metadata traces. Regardless of what tool Park actually used, it is difficult to believe that he would have used the ODT file provided by the community to a translator like me. The creation date of the original bitcoin.pdf file on bitcoin.org is April 24, 2009 at 11:33 AM, and the production program is OpenOffice version 2.4. I created the Korean version by editing the original ODT file provided to the translator by the community. The creation date of version 1.2 of the Korean translation that I submitted to the community and distributed on bitcoin.org is September 10, 2019 at 9:57 AM, and the production program is LibreOffice version 3.6. I previously confirmed that the metadata of Park's PDF file and the metadata creation date and time of the translated PDF file that I distributed just before matched. It is clear that the files translated by Park were worked on at a completely different time, but there is absolutely no reason for him to intentionally make the PDF files I translated have the same production program and document creation date. So I think Park worked based on the PDF file of my translation. If so, the source notation "Translated in Korean from bitcoin.org/bitcoin.pdf by Kyungwon Park" listed at the bottom of the title of Park's translation is false.

Fifth, I ask all community members to do one simple test. Anyone can take this test, whether you know Korean or not. Please download the Korean PDF file translated by Park right now and open it with any PDF viewer. And in any part of this file: <Abstract>, <Introduction>, <Transaction>..., select the body text by dragging the mouse, copy it, and paste it into another editor.

Unlike general PDF documents, including my translated PDF file, in Park's PDF file, the pasted text does not maintain the intact paragraph form, some words in the body are missing due to not being selected, and there are incorrect phrases or phrases that are out of order from the original text. You will see the word being inserted. In many cases, you may not be able to properly select text in the intended area.

This means that the visual arrangement of the text that makes up the PDF body does not match the order of the text data in the file, and the unique arrangement of the existing text is damaged internally. Moreover, not from a data perspective, but just looking at the document layout, Park's PDF shows that paragraphs arranged in the same hierarchy in one section have inconsistent and jagged line spacing, which may indicate that he is not sufficiently skilled in document editing and formatting techniques, or that he is not skilled enough in this translation work. It shows that you weren't paying attention while doing it.

If Park's translation was based on an ODT file for translation containing the original content and format of the English version of the Bitcoin paper and was ultimately extracted into a PDF file, there would be no reason for this phenomenon to appear. When he created a translated document, instead of writing the complete content and refining the formatting, he took someone else's PDF file, used a program with PDF editing capabilities, and only partially modified the text in his own style and saved it. It is assumed that this is why this phenomenon occurred. The fact that the file size became unnecessarily large also supports the assumption that Park's PDF was created using a method other than extracting refined PDF documents.

To contrast this phenomenon, I have attached below screenshots [8][9][10] of the text selection and pasting operations in the original English text, Park's translation, and mine (Mincheol). The three screenshots also show that Park's translation file was derived from a clumsy edit of Mincheol's translation file, each containing metadata information indicating the writing program, year, date, and time of creation of the three documents mentioned above.

Sixth, while I acknowledge that what happens in the community doesn't always work out in a way that makes sense to all parties, it's honestly hard not to feel offended that my translation was removed without a trace in this case. Despite the problems I've listed, should we seek further feedback on removing the currently distributed Korean translation of Park? It would have been better for you and other project managers to get input from Korean speakers before hiring a professional translator to create the alternative version currently being distributed. My translation, which had not been challenged by the community for years, was deleted without notice and without any input from Korean users. My translations have now been replaced by paid work by professional translators whose commission I do not know, and I feel as if my previous contributions have not been respected. I believe that the above explanation would have been sufficient for my work to be respected again and for my Pull Request to be accepted by the community. thank you.

--

[1] https://github.com/bitcoin-dot-org/Bitcoin.org/commit/bc3bcbe521c5cf72a4130968792e904b79b2fa16
[2] https://mincheol.im/wp/wp-content/uploads/2023/10/bitcoin_ko.pdf
[3] https://mincheol.im/bitcoin
[4] https://github.com/mincheolim/bitcoinwhitepaper/commit/7d7fe6889b46a228cb4530839a54a01d818cd914#diff-04758f3697f471a49b38defa5a8df61f0ff44876a67f26fade3735e46c5f12b2
[5] https://github.com/mincheolim (Changed from previous https://github.com/imc84)
[6] imc@live.co.kr

[7] Screenshot(A) - (top to bottom) the original paper, Park’s work, and Mincheol’s work difference. Examples of mistranslations in Park's work.
screenshot(A)


[8] Screenshot(B) - The result of selecting, copying and pasting paragraphs from the original paper. And its sole meta data.
Screenshot(B)


[9] Screenshot(C) - The result of selecting, copying and pasting paragraphs from Park’s work. Examples of weird behavior in Park’s work. And its same meta data as mincheol's work.
Screenshot(C)


[10] Screenshot(D) - The result of selecting, copying and pasting paragraphs from Mincheol’s work. And its another sole meta data.
Screenshot(D)

**Comment by tebica** [comment]
I am a native Korean speaker and a long-time Bitcoin holder. When I first read the Bitcoin white paper, there were many Korean translations, but there were many problems with the translation. Later, in 2018, I heard that @mincheolim had created a Korean version that was carefully translated with a lot of effort, and I was pleased with the high quality of the translation. The community was also very happy about the Korean version, and it was the most read translation in Korea for a long time. @mincheolim is a senior IT journalist with many years of experience, who has written many articles about the cryptocurrency industry, especially Bitcoin, and is very knowledgeable about it. Following him on Twitter, I could tell that he not only spent a lot of time working on this project with love, but also wrote every sentence with passion. I know that he revised his work several times and kept improving it to make this translation perfect.

I also agree with @mincheolim 's point above about the new paid translation in terms of completeness and accuracy of the documentation. The wording in Kyungwon Park's translation is inaccurate, and the indentation is inconsistent, which is too bad for an official document. And @mincholim's version shows both Korean and English for important Bitcoin words, which is very important and useful for accurate understanding.

Which is more complete: the work of a paid translator, or the work of an IT journalist with a love for Bitcoin who volunteered his time out of pure passion? We hope you choose the latter.
Bitcoin respects and participates in the open source culture. I look forward to adopting @mincheolim 's Korean translation, which has a [transparent history on Github](https://github.com/mincheolim/bitcoinwhitepaper/commits/master) and has long been supported by the Korean community.

**Comment by myoinbong** [comment]
I am a native Korean speaker, too. and a technical writer working at company in South Korea.
I also agree @mincheolim and @tebica 's opinion. 
I wish @mincheolim 's translation is maintained here.

**Comment by Cobra-Bitcoin** [comment]
OK. Thanks everyone for the feedback. We will bring back @mincheolim's translation.

**Comment by mincheolim** [comment]
okay. I'm relieved that you decided to do so. 

When should we expect changes to the bitcoin.org website where we upload Korean translator names and my new translation files? Please comment if there is anything else I need to do.

And thank you to everyone who found my translation more appropriate here.

**Comment by Cobra-Bitcoin** [comment]
@mincheolim It's scheduled to go live tomorrow.

**Review by mincheolim — COMMENTED** [review]
I just checked the https://bitcoin.org/en/bitcoin-paper webpage, and it seems that the 'go live schedule' that Cøbra talked about has not arrived yet. I left a review myself to make sure that my request was to upload this new Korean translation file to that webpage, display my name as the translator, and link to my GitHub account in my name.

**Comment by Cobra-Bitcoin** [comment]
@mincheolim Your whitepaper is live on the site now. If you click the link you should see it. However the website will take a few more hours to build and update after this commit https://github.com/bitcoin-dot-org/Bitcoin.org/commit/f24181414e0b4f63b0439624fea7a2cca5e6f5d4.

**Comment by mincheolim** [comment]
@Cobra-Bitcoin I have indeed checked, and as you mentioned, the whitepaper and the associated link have been successfully modified as we discussed. Your efforts in making this happen are greatly appreciated.

**Pull request closed without merging**
