### PR TITLE
removes facebook and twitter sharing links

### PR DESCRIPTION
**Pull request by priem19**
1. Social media sharing links are redundant; copy-pasting isn't that hard and doesn't fall victim to trackers.
2. Does the facebook logo really deserve space on bitcoin.org? After all their scandals? These sharing links serve facebook more as free advertisement than it serves the visitors' convenience.
3. It's aesthetically unpleasing; it breaks the symmetry and minimalistic look of the website.
comparison

### CODE REVIEW

**Comment by crwatkins** [comment]
utACK.  I agree with this concept.

**Comment by jdabs** [comment]
I agree. At least should not be in the header. The data collection practices also fly in the face of Bitcoin philosophy

**Comment by priem19** [comment]
> I also believe Google analytics should be removed or replaced

I agree wholeheartedly.

**Comment by laanwj** [comment]
Agree, I doubt anyone uses these to promote bitcoin or bitcoin.org anyhow

**Pull request merged**
