### PR TITLE
Added ThroughBit to the List of Indian Exchanges

### PR DESCRIPTION
**Pull request by dhaval-throughbit**

### CODE REVIEW

**Comment by wbnns** [comment]
@dhaval-throughbit Hello, the exchanges in each country are listed in alphabetical order - could you please revise your PR?

**Comment by dhaval-throughbit** [comment]
@wbnns Hey Will, I have made the changes according to the Alphabetical order in Indian Exchanges
Sorry for the incorrect listing in the first PR

**Comment by wbnns** [comment]
@dhaval-throughbit Thanks, no worries.

Unless others object, this will be merged on Wednesday, May 16th.

**Comment by dhaval-throughbit** [comment]
Thank you for the listing @wbnns, Appreciate it

**Pull request merged**
