### PR TITLE
Add Trust Wallet

### PR DESCRIPTION
**Pull request by hewigovens**
Hi

We'd like to add [Trust Wallet](https://trustwallet.com/) to Bitcoin.org, we have added Bitcoin with native segwit support for both Android and iOS recently. Please let me know if I need to correct or add something more.

Thanks!

### CODE REVIEW

**Comment by hewigovens** [comment]
Yes, the metadata is outdated, We have a new version under Apple review. We support Bitcoin in iOS last December and add Android support this January

**Comment by wbnns** [comment]
@hewigovens 

Hello, thanks for clarifying. Other wallet inclusion criteria aside, it would be potentially very confusing for people who are new to Bitcoin that are looking for a wallet, if they were to navigate to this wallet and see no mention of Bitcoin in either the App Store or on Google Play.

***

App Store:
screen shot 2019-01-26 at 13 28 10

Play Store:
screen shot 2019-01-26 at 13 32 24

***

Please let us know once this has been updated. Closing this PR for now (@crwatkins, or anyone else, if you'd prefer to leave this open until a future date, let me know and I will reopen).

**Comment by hewigovens** [comment]
@wbnns Hi, could we reopen this issue? We have updated descriptions and screenshots

**Comment by wbnns** [comment]
@hewigovens 

Ok, thank you. Can you please open a new PR?

**Pull request closed without merging**
