### PR TITLE
Add hardware and multisig features to Bitcoin Core Wallet

### PR DESCRIPTION
**Pull request by crwatkins**
No one said it was easy.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
LGTM.

**Comment by TyG34** [comment]
[bootstrap.log.txt](https://github.com/bitcoin-dot-org/Bitcoin.org/files/15251976/bootstrap.log.txt)

**Comment by TyG34** [comment]
[bundler.log.txt](https://github.com/bitcoin-dot-org/Bitcoin.org/files/15251977/bundler.log.txt)

**Review by TyG34 — APPROVED** [review]

**Review by TyG34 — APPROVED** [review]

**Review by TyG34 — APPROVED** [review]

**Review by TyG34 — APPROVED** [review]

**Review by TyG34 — CHANGES_REQUESTED** [review]
Where is address to wallets

**Pull request merged**
