### PR TITLE
Bitcoin Core 0.17.0

### PR DESCRIPTION
**Pull request by laanwj**
Can be merged when it passes travis.

### CODE REVIEW

**Comment by wbnns** [comment]
@laanwj Just FYI; failed tests.

**Comment by laanwj** [comment]
thanks, apparently it was snagged by the relative reference to the descriptor documentation, which makes sense, changed it to an absolute URL

**Comment by laanwj** [comment]
passing now

**Comment by wbnns** [comment]
@laanwj Thanks!

**Pull request merged**
