### PR TITLE
Add Bitcoin Core 25.1 release

### PR DESCRIPTION
**Pull request by fanquake**
Similar to #4078.
See also https://github.com/bitcoin-core/bitcoincore.org/pull/991.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Thank you. Will get this merged soon once the binaries are on the server.

**Review by AugustoResende — APPROVED** [review]

**Comment by Rashann2471** [comment]
https://github.com/microsoft/vscode-python.wiki.git_github-pages-challenge-Rashann2471

**Comment by Rashann2471** [comment]
[Metrics.xlsx](https://github.com/bitcoin-dot-org/Bitcoin.org/files/13758196/Metrics.xlsx)

**Comment by lateminer** [comment]
It would be good to merge this one as Bitcoin Core **26.0** has already been released.

**Pull request closed without merging**
