### PR TITLE
Restore test functionality

### PR DESCRIPTION
**Pull request by Cobra-Bitcoin**
Fixes a broken test to ensure that internal links with anchors are checked as described in https://github.com/bitcoin-dot-org/bitcoin.org/issues/2739.

### CODE REVIEW

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

Thanks. Just FYI, looks like this is failing on Travis CI.

**Comment by Cobra-Bitcoin** [comment]
For some reason the tests are timing out and going over the 50 min runtime limit that Travis allows. It's most likely because there's too many links to check, or there's something with the tests making them stuck in an infinite loop. We'll hold off on merging until we can get more reasonable performance.

**Comment by wbnns** [comment]
I spoke w/ Travis CI this week about the timeout issue, which is now resolved, however, now that the test is running successfully it has uncovered some broken same-page anchor links on translated pages which need to be fixed. Will use this branch for that as well.

**Comment by wbnns** [comment]
Broken anchor links are now fixed and all tests are green. Merging.

**Pull request merged**
