### PR TITLE
Move Bitcoin.org Repository To New GitHub Organization

### PR DESCRIPTION
**Pull request by harding**
Later today, we're planning to move the Bitcoin.org repository to a new GitHub organization, i.e. from `bitcoin/bitcoin.org` to `bitcoin-dot-org/bitcoin.org`.  More details are provided in the blog post that's part of this commit (screenshot at the end of this comment).

Note that the new repository doesn't exist yet because we're going to use the [GitHub repository transfer tool](https://help.github.com/articles/transferring-a-repository/) to move everything including issues and PRs.  After we've moved the repository and made sure everything is working, this pull will be merged.

This PR contains three commits:

1. The fully automated `sed s///` that updates all of our links to the old repository.  The specific substitition command is provided in the commit message, please feel free to run it on the master branch to verify links were faithfully updated.

2. A manual substitution of a few other URIs, such as the Travis CI integration links.

3. A blog post describing the move.  Screenshot below:

screenshot-btcorg localhost 2015-06-23 10-32-11

### CODE REVIEW

**Comment by saivann** [comment]
LGTM, thanks for taking care of it!

**Comment by theymos** [comment]
LGTM

**Comment by harding** [comment]
Thanks!.  Starting migration now.  When it's finished and I've checked everything out, I'll merge this PR.

**Comment by harding** [comment]
Welcome to `bitcoin-dot-org/bitcoin.org`!  I think everything is working; the site automatically started building when I pushed these commits, and I'll check the actual pages over when it finishes.

Travis CI might be a bit confused.  Once these commits finish building, I'll commit some of the open event requests individually to give Travis a workout.

Let me know if anyone spots any problems.  Thanks!

**Comment by theymos** [comment]
Thanks a lot for doing the move!

**Comment by luke-jr** [comment]
Not sure this reasoning makes sense. github.com/bitcoin is already not exclusively Bitcoin Core.

**Comment by luke-jr** [comment]
Eh, there was no time for review/comments? :/

**Comment by ABISprotocol** [comment]
It seemed like there was minimal time for review on this, and there should have been more time for comments... that said, what about [when your repositories have been forked](http://www.codelord.net/2012/03/31/migrating-to-a-github-organization/) before you migrate to a new github organization? Apparently, users who have forked your repository will need to update their remote URLs to point to the new Git repository in order to continue opening pull requests -- as per [this Github statement](https://help.github.com/articles/transferring-a-repository/#whats-transferred-with-a-repository).  

Anyway, it does seem that more time would have helped with understanding of the reasoning for this pull request.  I have no real opposition to it, but I think the pullreqs need more... time (for review, comments, etc).

**Comment by gurnec** [comment]
There's never been an "official" change policy for bitcoin.org AFAIK.

I've always *assumed* that there was a de facto policy of "wait a couple of days before making non-trivial changes", but recent events have shown that I am wrong.

It seems that this change is a move towards improving transparency, and that I applaud. I do hope that the bitcoin.org committers/owners make it more clear exactly whose views bitcoin.org represents ([apparently underway](https://github.com/bitcoin-dot-org/bitcoin.org/pull/899#issuecomment-112858644)), and perhaps the method by which those views are determined....

**Comment by harding** [comment]
This move was more abrupt than I planned.  That's my fault, and I apologize.  We had scheduled a time (16:00 UTC today) when three of us would be available in case there were any problems, and I had given myself a couple days to prepare this PR.  But then I got busy and wasn't able to do the work until this morning.  It may have been more appropriate to have delayed to give this more time for discussion, and I'm happy to address any concerns now.  (I think we can undo the change if there's any significant problems found.)

@luke-jr several people, including myself, were under the impression until recently that Bitcoin.org was part of the Bitcoin Core project, so I think taking steps to clarify the separation between the two projects is a good idea.  I also have an already-prepared branch updating the about-us page to provide additional history and organizational structure.  I just have to make one last suggested change from the private review before opening a PR.  That one will certainly get a few days for review!

The new bitcoin-dot-org organization has as its owners on GitHub the same people who co-own the domain, and as its administrators the same people who have maintained the content on the site going back to early 2014.  This move, which has no effect on the content or processes of Bitcoin.org, simply moves ownership of the repository we use for auto-updating the site from the Bitcoin Core developers to the actual domain owners.

@abisprotocol

> Apparently, users who have forked your repository will need to update their remote URLs to point to the new Git repository in order to continue opening pull requests

According to the GitHub docs, it will redirect this transparently.  However, a command is provided in the [blog post](https://bitcoin.org/en/posts/repository-move) for updating your actual remote URL.

Everything seems to work for me; if you have any problems, comment here or open a new issue.

@gurnec 

> I've always assumed that there was a de facto policy of "wait a couple of days before making non-trivial changes", but recent events have shown that I am wrong.

Again, I'm at fault for the abruptness here, and I apologize.   We probably should have a more formal policy.

**Comment by saivann** [comment]
> I've always assumed that there was a de facto policy of "wait a couple of days before making non-trivial changes", but recent events have shown that I am wrong.

I think this is how nearly all issues and pull requests have been handled previously (and should continue to be handled in the future IMO).

David has been squeezed in a short timeframe with the hardfork blog post. Otherwise regarding this pull request, I thought it was more of an announcement (and a call for comments in case someone was noticing something odd). This repository is for the content of the website, not much about how the servers and repositories are configured. Not all configuration changes (server, VM, repository) went through a pull request, since most of them don't affect visitors or contributors.

Similarly, this move should in theory have no impact on how the repository works (although if you find something broken worth mentioning, please do!) .

**Comment by ABISprotocol** [comment]
Thanks for these clarifications on how this has worked, this has been helpful.

**Pull request merged**
