### PR TITLE
Add NDAX to Canadian Bitcoin Exchanges

### PR DESCRIPTION
**Pull request by ndaxio**
Please accept this pull request to add NDAX to bitcoin.org

Thank you

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Please respect the alphabetical ordering.

**Review by ndaxio — COMMENTED** [review]
I have adjusted the order for NDAX thanks

**Comment by ndaxio** [comment]
> Please respect the alphabetical ordering.

Thank you for the comment, i have updated the order.

**Comment by Cobra-Bitcoin** [comment]
LGTM.

**Pull request merged**
