### PR TITLE
Apply more graceful mobile stylesheet to landing page icons

### PR DESCRIPTION
**Pull request by saivann**
This addresses at least one issue mentioned on #1014 , by allowing these elements to be displayed inline on the screen until the space is really stretch enough.

I should have left equivalent space for texts, so variable-width translations should still fit correctly in the available space. At least I have verified various ones without noticing any issue.

Live preview: http://bitcointest1.us.to/en/

### CODE REVIEW

**Comment by harding** [comment]
LGTM.  Thanks!

**Comment by saivann** [comment]
In the absence of critical feedback, this pull request will be merged on August 21th (tomorrow).

**Comment by carnesen** [comment]
Yup, good one! Preview looks good now even at 175%.

**Comment by saivann** [comment]
@carnesen Thanks for reporting the issue!

**Comment by saivann** [comment]
Note; I just added some changes to the CSS for the RTL and IE6 layouts to provide them with the same display, the live preview will be updated in a minute.

**Comment by harding** [comment]
utACK af646e4

**Pull request merged**
