### PR TITLE
Update Bither to indicate HD wallet is now the default

### PR DESCRIPTION
**Pull request by shesek**
Refs: https://github.com/bitcoin-dot-org/bitcoin.org/issues/3043

### CODE REVIEW

**Comment by crwatkins** [comment]
@shesek Thanks!

@songchenwen Can you confirm for us that HD mode (with no address reuse) is now default on all your platforms?  If so, @shesek can update the PR for all Bither platforms.

**Comment by shesek** [comment]
Sure thing! Glad to contribute something back, however small it is. Bitcoin.org has been a fantastic resource.

Regarding platforms, it's worth noting that I only tested on Android.

**Comment by songchenwen** [comment]
Thank you @shesek .

HD mode is the default for Bither on mobile platforms(iOS and Android). On desktop platforms there are 2 buttons for both `HD Account` and `New Private Keys`.

Below is a screenshot for the desktop platform.

photo_2019-07-10 09 58 53

**Comment by crwatkins** [comment]
@songchenwen thanks for getting back to us.   That looks great.  I'm glad to get this updated.

@shesek If you are happy with that, would you like to update the address reuse score for each platform?

**Comment by shesek** [comment]
@crwatkins Oops, I didn't notice I updated iOS only. I force-pushed an update for the other platforms.

**Comment by crwatkins** [comment]
@shesek Thanks for update!   I'm embarrassed (that I didn't notice this before and) to ask for one more.   According to our [scoring criteria  ](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#score)

> To get a passing score, the wallet must avoid address reuse by using a new change address for each transaction.

So your changes now qualify Bither for
```
privacy: "checkpassprivacybasic"
```

Could you update the **privacy** score for the three platforms also?

**Comment by shesek** [comment]
@crwatkins of course, updated.

**Comment by crwatkins** [comment]
LGTM c51024e

**Comment by AdiuvoInc** [comment]
Bither wallet is not working well for several months. Is not showing transactions made. People have tried to get answers from developers but none answer so far. I would remove it from choose your wallet section.

**Comment by crwatkins** [comment]
@Adiuvolnc could you open a separate issue on this?  This PR is closed. Could you also provide some details about what is not working and/or some references?

**Comment by bithernet** [comment]
@AdiuvoInc ,
Bither is a decentralized SPV light wallet, and it needs to sync bitcoin blockchain data with other peers on Bitcoin network.
So if your connections to the bitcoin nodes is ok, and block syncing is running well, Bither will be working fine.
You can find out the block syncing status in "Advanced Options"/"Network Monitoring", and there are two pages: Peers mean the peers that you have connected to, and the Blocks mean the current block you have synced. If the newest local Block's height in your Bither Wallet is the same as the current newest Bitcoin newest block height, then your balance and your transaction data will be fine, and sending/receiving bitcoins will work fine too.
If there are issues on your transaction data or balance, you can also try to use "reload transaction data" function to fix this. (also to remind, even you are using the "reload transaction data" function, you still need to sync to the newest block, because Bither will verify all the blocks' header since you create your wallet)
If you have other questions, you can just tell us the details, and we will check it.
Thanks you, :)

Also, my email address is bithernet@gmail.com, and it is welcome to send email to us.

**Pull request merged**
