### PR TITLE
[RFC] wallets: Remove Bither

### LINKED ISSUE #3377: Removal of Bither pending new review
[Bither](https://bitcoin.org/en/wallets/mobile/android/bither/?step=5&platform=android) has added a splash screen to the Android and iOS versions of their wallet, advertising/instructing users to go download Bitpie, a closed source wallet[1]. Bitpie hasn't been reviewed for inclusion on the site, nor have the developers brought its existence to our attention, despite their current listings for Bither.

image

**Steps to reproduce:**

1. Download Bither for Android or iOS using the links on bitcoin.org.
2. Run Bither for the first time.
3. Completely close Bither.
4. Reopen Bither and see 3-second countdown screen instructing you to go download Bitpie.

We noted there is no way to make the popup go away. It will happen every time the app is opened anew after being completely closed.

Since Bither is instructing users to go download another wallet whenever their wallet is opened, the current wallet listings are arguably being abused (whether intentionally or not) and should be removed, pending a review of Bitpie. 

Cc: @crwatkins

[1] At the time of this issue we don't see any evidence of the code for Bitpie in their [GitHub repositories](https://github.com/bitpiedotcom?tab=repositories), leading us to believe it is closed source.

### PR DESCRIPTION
**Pull request by wbnns**
Closes #3377.

Cc: @crwatkins

### CODE REVIEW

**Comment by crwatkins** [comment]
Here are some of my thoughts on this subject (they are not meant to ack or nack on this PR and I'm not even sure yet what I'm going to recommend at the end):

1. I have the same experience on Android with the three second "advertisement" upon launch.  I have to admit it is kind of odd to
a. Have an ad for another wallet in existing working wallet
b. Have a splash so fast that it is difficult to read the page and click on it in time (seems more annoying than "dangerous")
2.  I do not encounter the same experience with the latest version on iOS (no splash screen each time)
3. I have seen no evidence of Bitpie being open source.   The Bither team seems very proud of the open source status of their other products, so I assume they would be telling us about this if Bitpie was open source.
4. We don't have any explicit criteria specifying what type of ads wallets may carry, but of course we have implicit criteria if we think ads are being deceptive.
5.  Bitpie does seem to be "riding on" the bitcoin.org listing of Bither.   One example on the Bitpie LinkedIn page says 
> Easy and secure way of managing multi-chain coins. Developed by Bither Team, who also made Bither, a http://bitcoin.org  listed wallet.

In the Bitpie listing on the iOS app store, the top feature listed is 
> ・Security: developed by 5-year wallet developing team—Bither, an opensource bitcoin wallet recommended by Bitcoin.org

There are few other examples in places such as https://bitpie.com/about.html. I believe that while those statements are accurate, they may be slightly misleading.

None of this seems to be intentionally misleading (they just seem proud of their credentials).  I recommend requesting:

1. That Bither remove the splash screen in Android as it may be confusing users into thinking that Bitpie is a listed new version of Bither and simply an upgrade.
2. That the Bither team not reference the bitcoin.org listing in any collateral material that is not specifically referring directly to the Bither Wallet.

@songchenwen Could you comment on this?

**Comment by songchenwen** [comment]
Hi @crwatkins and @wbnns . Sorry for the misleading information. This is unintentional. Thank you for reminding us. We will make changes for the requests.

> That Bither remove the splash screen in Android as it may be confusing users into thinking that Bitpie is a listed new version of Bither and simply an upgrade.

We've already changed the splash screen to a NOT misleading content, you may need to close and reopen several times to see the new content. In the next release of Bither, which is already submitted and waiting for review now, the splash screen will be completely removed.

> That the Bither team not reference the bitcoin.org listing in any collateral material that is not specifically referring directly to the Bither Wallet.

We've changed all of this. Description on App Store and Google Play needs to be updated with a new Bitpie release. We've already submitted the new release and been waiting for review now. Reviewing may take longer time due to COVID-19.

**Comment by wbnns** [comment]
@songchenwen 

Thanks for the reply. Could you please clarify what the future plans / intentions are with Bither and why the splash screen was added?

It seems the splash screen may have continued to always show when opening Bither, even if the user had already installed Bitpie as instructed.

**Comment by songchenwen** [comment]
Hi @wbnns 

We’ve been developing Bither for several years. Bither is meant for someone willing to know a little bit about Bitcoin technology and to run a SPV node on his phone. Bither will stick to a Bitcoin-only wallet of open source, SPV node and hot/cold wallet model with QR code support.

The splash screen was initially made as an advertisement place. We hoped it could be a revenue for our open source project. But there is no suitable ad yet. So we temporarily put Bitpie there. Because it’s not meant to redirect users from Bither to Bitpie by design, it doesn’t detect whether Bitpie is already on the device.

When the next release is available, this splash screen will be gone, and so will the annoying experience.

**Comment by wbnns** [comment]
@songchenwen 

Hi, ok, understood. Thanks.

**Comment by crwatkins** [comment]
@songchenwen Thanks for the extremely fast response and update!

**Pull request closed without merging**
