### PR TITLE
added links for bitaccess BTM network as well as Bitcoin ATM industry directory site. 

### PR DESCRIPTION
**Pull request by Wheelerwj**
https://www.bitaccess.co is the home page of bitaccess BTMs and Canadian BItcoin brokerage.

https://coinatmradar.com/ is the industry go-to industry site for finding local bitcoin atms from multiple manufacturers.

### CODE REVIEW

**Comment by Mirobit** [comment]
Not sure about adding bitaccess twice. 
Adding coinatmradar.com is a good idea. I think we should also put it on the ressources page.

**Comment by Wheelerwj** [comment]
Why do you think bitaccess isn't a good fit?   they sell bitcoins and provide location information for bitcoin atms.

**Comment by Mirobit** [comment]
@Wheelerwj I didn't notice that coinbase is listed twice. It should be removed from one of the categories. I think an exchange is either international or is mostly for one country. I it can't be both.

@wbnns Wondering what your position is.

**Comment by wbnns** [comment]
@Wheelerwj Thanks for submitting this. As @Mirobit mentioned (thanks!), we should be cautious about adding things twice. I reviewed Bitaccess's coverage on the website, and think Canada would be a good place to start before adding to the "International" category. One there is more coverage in the US, South America, Europe, and/or Asia, feel free to resubmit it for review for the latter category.

**Comment by wbnns** [comment]
@Wheelerwj Hey there! Since it's been a few weeks and we haven't heard back from you, I'm going to close this for now. That said, when you're ready, it would be great to have your contribution on this - feel free to submit a new PR!

**Comment by sherika36** [comment]
im sorry please forgive me im going threw a financial hardship right now im
stressing out, what was it that i didnt do, people remind me im lost right
now, im sorry i didnt reply sooner

On May 29, 2017 11:02 AM, "Will Binns" <notifications@github.com> wrote:

Closed #1572 <https://github.com/bitcoin-dot-org/bitcoin.org/pull/1572>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin-dot-org/bitcoin.org/pull/1572#event-1101295234>,
or mute the thread

**Pull request closed without merging**
