### PR TITLE
Update Passport icon and product image

### PR DESCRIPTION
**Pull request by sethforprivacy**
Updates the product image and logo for Passport to better align with the design principles of the website and be a bit higher quality.

Tested both locally before PRing and they look great, are the correct sizes, and have been compressed with `optipng -o7`.

### CODE REVIEW

**Comment by sethforprivacy** [comment]
Rebased to exclude the doc changes made in #4034 from this PR to allow them to be separately reviewed/merged.

**Comment by sethforprivacy** [comment]
@Cobra-Bitcoin @crwatkins just for clarity we're planning on sharing that we've been added and give a shoutout this week, would be awesome if we could get this merged before then!

This PR should be fully inline with your spec and requirements for images, FWIW.

**Comment by crwatkins** [comment]
LGTM.   Thanks.

**Comment by sethforprivacy** [comment]
> LGTM. Thanks.

Awesome, thanks for the quick review!

**Comment by Cobra-Bitcoin** [comment]
Very nice. Thank you.

**Comment by sethforprivacy** [comment]
Thanks for the quick merge!

**Pull request merged**
