### PR TITLE
OS X Yosemite Install Instructions

### PR DESCRIPTION
**Pull request by oliverdowling**
It appeared nothing was happening with issues #862 or #954, so I've added some screenshots and made a start at writing instructions for installing Bitcoin Core on Mac OS X.

I copied and pasted some from the Windows section where applicable.

I did not include how to start Bitcoin Core once installed, because there are a number of ways to run it, including but not limited to:

* Spotlight Search (`Command`+`Space` on the keyboard)
* Launchpad (there is a key on the keyboard specifically for this, but also a Dock icon)
* Finder (folder explorer `/Applications/Bitcoin Core.app` where ".app" is hidden by default)

My preferred method is Spotlight, however, it still displays as "Bitcoin-Qt":

en-osx-start-bitcoin-core

Launchpad:

en-osx-launchpad

Launchpad with search:

en-osx-launchpad-search

Let me know if there are any other screenshots or info needed.

### CODE REVIEW

**Comment by harding** [comment]
@oliverdowling thanks!  I haven't had a chance to review it yet, but here's a preview of what it will look like:

http://dg3.dtrt.org/en/full-node#mac-os-x-instructions

**Comment by drazisil** [comment]
Staging page looks solid, I see no errors.

**Comment by oliverdowling** [comment]
I noticed that my username was included in the *Welcome to Bitcoin Core* image, so I blurred it out.

**Comment by harding** [comment]
Commit 55affa1 looks good to me.  Thanks!  Preview has been updated.

In the absence of critical feedback, this pull will be merged late Friday or early Saturday UTC.

**Pull request closed without merging**
