### PR TITLE
Include new canadian exchange!

### PR DESCRIPTION
**Pull request by clayton-duarte**

### CODE REVIEW

**Comment by wbnns** [comment]
@clayton-duarte 

Hello, it looks like the ticker is broken (alignment issue within the container) when navigating through various pages, once logged in:

image

Please let us know when this is resolved and we'll resume the review.

**Comment by clayton-duarte** [comment]
Sorry, I don't got the point about the CSS issue on coinsmart website. How this affects the Code Review?

**Comment by clayton-duarte** [comment]
> @clayton-duarte
> 
> Hello, it looks like the ticker is broken (alignment issue within the container) when navigating through various pages, once logged in:
> 
> image
> 
> Please let us know when this is resolved and we'll resume the review.

Sorry, I don't got the point about the CSS issue on coinsmart website. How this affects the Code Review?

**Comment by wbnns** [comment]
@clayton-duarte 

The exchanges page on bitcoin.org receives many visitors. Before including a new exchange on the page, one of the things we review is if the destination site can be used without issue.

**Comment by clayton-duarte** [comment]
Understood. 

I explained the issue to than and they should fix it by this week.
Once all issues are on production, I'll open the PR again.

Thanks for your help and all the explanation.

**Pull request closed without merging**
