### PR TITLE
Add more explicit RSS feed and other features from the blog layout to alerts

### PR DESCRIPTION
**Pull request by saivann**
~~@harding @btcdrak Would just adding the RSS icon into individual alerts would be good enough for now? Please feel free to merge this pull request at any time.~~

This pull request adds RSS icons and other features from the blog post layout.

Live preview:
http://bitcointest4.us.to/en/alerts
http://bitcointest4.us.to/en/alert/2015-07-04-spv-mining

### CODE REVIEW

**Comment by btcdrak** [comment]
I think you make it more explicit like on the blog 

screenshot

**Comment by btcdrak** [comment]
Notice how individual blog post pages were dont on the blog 

screenshot

**Comment by saivann** [comment]
@btcdrak I have just added commits to reuse all the layout and features of the blog posts. Does that look better to you?

Live preview:
http://bitcointest4.us.to/en/alerts
http://bitcointest4.us.to/en/alert/2015-07-04-spv-mining

I'll have to do some more testing before being confident this pull request is ready to merge.

**Comment by saivann** [comment]
In the absence of critical feedback, this pull request will be merged on July 5th.

**Comment by btcdrak** [comment]
Nicely done 

ACK

**Comment by harding** [comment]
7af80fc tested LGTM.  Thanks!

**Pull request merged**
