### PR TITLE
Remove Ledger Nano wallet

### PR DESCRIPTION
**Pull request by crwatkins**
Per @EricLarch the Ledger Nano is no longer available and should be removed.

### CODE REVIEW

**Comment by rebroad** [comment]
What do you mean "no longer available"? - it's still being sold online.

**Comment by achow101** [comment]
@rebroad Where? The Ledger Nano (not the Ledger Nano S) is not listed on Ledger's website. The only devices listed on their website are the Ledger Nano **S** and the Ledger Blue

**Comment by Roy19833** [comment]
I don,t know what you fucking meaning
Verzonden vanuit Outlook
________________________________
Van: Rebroad <notifications@github.com>
Verzonden: dinsdag 17 oktober 2017 06:34:04
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: Re: [bitcoin-dot-org/bitcoin.org] Remove Ledger Nano wallet (#1794)


What do you mean "no longer available"? - it's still being sold online.

**Comment by crwatkins** [comment]
@rebroad this was removed per Ledger's request

**Pull request merged**
