### PR TITLE
Add Edge wallet to directory resource

### PR DESCRIPTION
**Pull request by i3inary**

### CODE REVIEW

**Comment by wbnns** [comment]
cc: @crwatkins

**Comment by crwatkins** [comment]
@i3inary Thanks for the submission!

@i3inary @paullinator What is the direction for the Edge wallet?  Is it replacing the Airbitz wallet?  Should we also be removing Airbitz from the listing?

**Comment by paullinator** [comment]
Edge is a completely different app and has a different set of features. We would appreciate having both Edge and Airbitz listed for a while longer until we migrate all features of Airbitz to Edge at which point we will deprecate Airbitz.

**Comment by crwatkins** [comment]
@paullinator Thanks.

**Comment by crwatkins** [comment]
@i3inary @paullinator Is the backend architecture the same as for Airbitz or do you have any white papers on the backend similar to what you have for Airbitz?

**Comment by paullinator** [comment]
The backend is the same as it does not do much. Most work is done client-side. An updated white paper is on our website at edgesecure.co

**Comment by crwatkins** [comment]
@paullinator Thanks.  Your support pages say

>  Our architecture has undergone a 3rd party security audit and we feel very confident we’ve found the right balance of security and ease of use for the masses and advanced users.

Is that audit report available?  As I suspect you know, audits aren't required, but they can certainly help move things much faster.

**Comment by paullinator** [comment]
@crwatkins Yes, attached them here.

[AirBitzEncryptionAlgorithmThreatModel_20141217.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/2042216/AirBitzEncryptionAlgorithmThreatModel_20141217.pdf)
[AirBitzForgotPasswordRecoveryCheatsheetScore_20141217.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/2042217/AirBitzForgotPasswordRecoveryCheatsheetScore_20141217.pdf)
[AirBitzForgotPasswordThreatModel_20141217.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/2042218/AirBitzForgotPasswordThreatModel_20141217.pdf)
[AirBitzGitFileSyncArchitectureThreatModel_20140825.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/2042219/AirBitzGitFileSyncArchitectureThreatModel_20140825.pdf)

The architecture is mostly unchanged since this audit except we have upped the scrypt minimum parameter requirements and replaced the original password recovery mechanism with one that cannot be brute forced via encryption. That is well described in our white paper but not yet had a formal audit.

**Comment by crwatkins** [comment]
I have reviewed Edge based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the website that links to downloads does not yet support HSTS, I cannot at this time recommend it for listing.  I will be glad to recommend Edge for listing once this website issue is resolved.

I concur with the current scoring in the pull request.

## Edge
### Version 1.1.4 (iOS and Android)
### Review Version 2018060101

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** This wallet supports multiple cryptocurrencies.  Only Bitcoin was reviewed.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

**PASS**  Google Play Store has 10,000+ downloads and an independent audit of the security architecture is available (attached in comments in this PR)

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

**PASS** No indication using standard web searches and app store reviews

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

**PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

**PASS** No indication.  Uses bcoin.   https://github.com/Airbitz/edge-currency-bitcoin/blob/master/package.json https://github.com/Airbitz/edge-core-js/blob/develop/package.json

- No indication that changes to the code are not properly tested

**PASS** No indiction.  Code contains unit tests.

- Wallet was publicly announced and released since at least 3 months

**PASS** Wallet was released 15 Feb 2108  https://blog.edgesecure.co/edge-wallet-is-live-d844cc483210

- No concerning bug is found when testing the wallet

**PASS** No concerning bugs were found.  All bugs found were acknowledged promptly and professionally by support.  Slightly concerning issue with password recovery is being addressed by Edge.

- Website supports HTTPS and 301 redirects HTTP requests

**PASS** edgesecure.co and www.edgesecure.co redirect to https

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

**PASS** Rating of A for edgesecure.co

- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days

**FAIL** edgesecure.co links to downloads and does not have HSTS.

- The identity of CEOs and/or developers is public

**PASS** https://edgesecure.co/about/

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

**PASS** New addresses are displayed for each transaction

- Avoid address reuse by using a new change address for each transaction

**PASS** New change address is used for each transaction

- User has access to private keys
- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

**PASS** Has good password requirements with a clear UI including a password strength meter.

**NOTE** There is a lockout feature on bad PIN entries

**NOTE** There is no warning for choosing weak PINs

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

**PASS** The standard backup is automatic and opaque to users on Edge servers, but the wallet also allows exporting a BIP39 seed

**NOTE** Wallet provides option to share the seed to many appications including mail and messaging but there is no warning to the user about the potential dangers of doing so

  - Restoring wallet from backup is working

**PASS** The wallet can be restored with username and password from Edge servers.

**NOTE** There is no way to restore the BIP39 seed to the Edge wallet, but the restoration was tested to Electrum.

  - Source code is public and kept up to date under version control system

**PASS** https://github.com/Airbitz

- If user has no access to some of the private keys in a multi-signature wallet:

**N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:

**N/A**

  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element

Optional criteria (some could become requirements):

- Received independent security audit(s)

**PASS**  Independent audit of the security architecture is available (attached in comments in this PR)

- Does not show "received from" Bitcoin addresses in the UI

**PASS** Does not show

- Uses deterministic ECDSA nonces (RFC 6979)

**PASS** During review a transaction was independently signed with custom code and it was verified that the signatures were the same

- Provides a bug reporting policy on the website

**PASS** Support tab on edgesecure.co has options to contact via support form or phone number.  Support is very responsive and very helpful.

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.appspot.com/)

**FAIL** edgesecure.co links to downloads and does not have HSTS

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

**PASS** Uses standard P2WPKH in P2SH BIP49 path m/49'/0'/0'/c/i (unless migrated from an Airbitz wallet in which case it still uses the slightly non-standard Airbitz BIP32 path)

  - Provides users with step to print or write their wallet seed on setup

**NOTE** Wallet provides users with a step to write down their username/password/pin on startup 

  - Uses a strong KDF and key stretching for wallet storage and backups

**PASS** Passwords are hashed with scrypt, n=16384.  PINs use HMAC-SHA256.

  - On desktop platform:
    - Encrypt the wallet by default

**N/A**

- For hardware wallets:
  - Prevents downgrading the firmware

**N/A**

**Comment by wbnns** [comment]
Should Airbitz be removed as part of this? It looks like in the latest builds on Android and iOS, that new users are notified that Airbitz is now Edge.

**Comment by paullinator** [comment]
The notification for new Airbitz users only notifies those that do not already have an account on Edge and who have devices that meet the criteria on Edge. Edge does not have compatibility for devices as old as what Airbitz supports. 

Airbitz: iOS 8, Android 4.4
Edge: iOS 10, Android 6

Also Edge does not yet have the ability to buy/sell crypto from within app like Airbitz. We kindly request keeping the Airbitz listing for at least 6 more months while we migrate existing functionality to Edge.

**Comment by paullinator** [comment]
@crwatkins  Thanks for the thorough review. We will look into the HSTS issue.

One update. Edge does have 2FA and it is mentioned in Settings.

**Comment by crwatkins** [comment]
@paullinator Thanks!  I didn't mean to imply that there wasn't 2FA.  That criterion only applies to multisig wallets and that section was marked **N/A** in the review, but due to my failure in the proper formatting of the sections, that was not obvious.  I did review the 2FA feature.

@wbnns I agree with @paullinator that we should continue to list Airbitz.

**Comment by wbnns** [comment]
Ok, got it, thanks guys.

**Comment by paullinator** [comment]
@crwatkins Our webdevs have informed me that they have fixed the HSTS issue. Please verify and let me know if there's anything else you see.

Thanks

**Comment by crwatkins** [comment]
@paullinator Thanks for the update!  Your HSTS is set to 2 years, which meets our required criteria.
I gladly recommend the Edge wallet for listing.

However, you'll note that you aren't in the HSTS preload at https://hstspreload.org/?domain=edgesecure.co  HSTS preload is currently an optional criterium.  Our optional criteria are generally requirements that the community believs are a really good idea, and there are plans to make them requirements in the future, but we don't want to de-list existing wallets that don't yet meet them.  We request that new listings meet them.

If you follow that link, you'll get some good suggestions on how to modify your headers for preload along with with some other suggestions (your www.edgesecure.co certificate is invalid).  These are in general really good ideas for securing your site.

**Comment by wbnns** [comment]
Unless others object,  this will be merged on Wednesday, June 20th.

**Pull request merged**
