### PR TITLE
Add Israeli bitcoin change Bits of Gold

### PR DESCRIPTION
**Pull request by Bitim**
Add "Bits of Gold" Israeli bitcoin change to exchanges page

### CODE REVIEW

**Comment by Mirobit** [comment]
LGTM.

**Comment by wbnns** [comment]
@Bitim Hello, thanks for contributing. As-is, this PR would break the layout on the Exchanges page - could you please fix?

image

Please let me know if you have any questions or if you need help with this.

**Comment by Bitim** [comment]
Fixed, 

BTW, maybe we should add Israeli exhange [Bit2C](https://bit2c.co.il/) also, if we already making changes.

**Comment by wbnns** [comment]
@Bitim Thanks for the quick update! Sure, that sounds good to me. Could you please add Bit2C as the first one so they are listed alphabetically?

**Comment by Bitim** [comment]
@wbnns done :)

**Comment by wbnns** [comment]
@Bitim Awesome, thanks!

Unless others object, this will be merged on Wednesday, May 24th.

**Pull request merged**
