### PR TITLE
Added Bitcoinregulation.world site as a resource

### PR DESCRIPTION
**Pull request by dannmat**
You tried to review our site several days ago and we believe we have fixed the issue of intermittent errors that were occuring for you, which although we couldn't replicate the problem, we think it was an issue with how our website detects your area in order to give your countries regulation description on the homepage.

Please review again and also let us know if the issue is fixed for you :)

### CODE REVIEW

**Comment by Mventura77** [comment]
Hello, hope you are doing good, 

For how many time the site will be under Review ?

Thank you, have a Nice Day

**Comment by dannmat** [comment]
I don't know if you're talking to me or @wbnns but we review all countries in our database as much as we can and follow all regulation news, to update when anything new comes out :)

**Comment by dannmat** [comment]
@Mventura77 You need to fork the repository, make the changes you need to and then create a pull request like this one

**Comment by wbnns** [comment]
@dannmat 

Hello, it looks like the error is continuing to persist on the website, whenever one attempts to reload the page:
screen recording 2018-10-05 at 23 14

**Pull request closed without merging**
