### PR TITLE
Added CoinJar as a web wallet resource.

### PR DESCRIPTION
**Pull request by helveticade**
Pretty straightforward! Added appropriate information as directed.

### CODE REVIEW

**Comment by helveticade** [comment]
Hi all, any progress on this?

**Comment by harding** [comment]
@helveticade I haven't had a chance to perform a review yet, but I just took a quick look.  One blocking issue is that CoinJar doesn't seem to support [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for its servers. You can see this for yourself by clicking on one of the results from [this page](https://www.ssllabs.com/ssltest/analyze.html?d=coinjar.com&latest), scrolling to the Protocol Details section, and looking at the item named "Strict Transport Security (HSTS)".  For CoinJar's servers, it says, "No".

According to [our policy](https://github.com/bitcoin/bitcoin.org#wallets), "websites serving executable code or requiring authentication must use HSTS with a max-age of at least 180 days."

Are you able to ask CoinJar to enable HSTS on their servers?  Based on some of the other features they use on their servers, I don't think it would be complicated for them.

**Comment by harding** [comment]
@helveticade oh, I forgot to say: thanks for submitting this wallet proposal!

**Comment by saivann** [comment]
For the record, the current CEO of Coinjar (Zhou tong) was previously the CEO of bitcoinica, a service that suffered significant failures. So I wasn't sure if Coinjar could be added as per [this requirement](https://github.com/bitcoin/bitcoin.org#wallets):

~~~
No indication that users have been harmed considerably
by any issue in relation to the wallet
~~~

However, unless I'm mistaken somewhere or someone disagrees, I think the following facts could be enough to say Coinjar could pass (or eventually pass) this requirement (note: I haven't reviewed other requirements).

- Coinjar is a different service run by a different team, not just a rebranding.
- Coinjar is operating since nearly 2 years without apparent issues.
- Accusations against Zhou Tong apparently weren't founded [1] despite initial suspicions [2]

[1] https://bitcoinmagazine.com/1805/bitcoinica-stolen-from-again/
[2] https://bitcointalk.org/index.php?topic=95738.0

**Comment by helveticade** [comment]
Sorry it's taken a while to get back to you about this.

CoinJar is in the process of implementing HSTS and stronger password policies.

@saivann, you're right to be concerned about the questions re: Ryan Zhou's past. The three points you mention are well reasoned. If I can add to this – Ryan is a co-founder but is not the CEO, and shares the responsibilities of the company with others.

You guys rock for your diligence here, btw. I'll post an update when HSTS is implemented.

**Comment by helveticade** [comment]
Hi all!

CoinJar has updated with HSTS support and stronger password policies! Are we able to merge this PR now or do you need more info?

**Comment by harding** [comment]
@helveticade no one is currently available to review CoinJar.  (Sorry.)  I'm going to tag this as help needed until someone is available.  Thanks for your patience.

**Pull request closed without merging**
