### PR TITLE
Add Hodler wallet

### PR DESCRIPTION
**Pull request by HODLERTECH**

### CODE REVIEW

**Comment by crwatkins** [comment]
@HODLERTECH Thanks for your submission!

Have you reviewed the wallet listing criteria [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and believe that your wallet meets all of the criteria listed?  Verifying that and correcting any issues can save a lot of time during the review process.

A quick glance at the submission, your web site, and your source code suggests that some of the platforms listed have not been released yet.   You will want to correct the submission.  In addition, I don't see any releases tagged in GitHub.  Your source code needs to be kept up to date and releases need to be tagged.

Be sure to let us know here if you have any questions.

**Comment by Fl4reTobiasH** [comment]
Hello.

Thank you for review. 
HODLER Wallet meets all the bitcoin.org requirements except "Avoid address reuse by using a new change address for each transaction". HODLER allows creating new addresses, but it does not force this.
image
This requirement will be met in the next release 0.3.1.

The full current source code is published on GitHub, but you are right, it is not tagged - we will fix it.

We have active Windows and Android platforms. iOS is awaiting acceptance to the AppStore, but is available as a beta in TestFlight:
https://testflight.apple.com/join/fybpO1nn

We'll let you know when we're ready for a detailed review.
Thank you for suggestions and greetings.

**Comment by crwatkins** [comment]
@Fl4reTobiasH Thanks.  Looking forward to your update.

**Comment by wbnns** [comment]
@HODLERTECH 

Hello, closing this for now since it has been a couple of months without any activity. When you're ready for another look please let us know.

**Pull request closed without merging**
