### PR TITLE
Add Quebex

### PR DESCRIPTION
**Pull request by aaronkuchma**
Add the Quebex bitcoin exchange to the list of exchanges in Canada.

See https://github.com/bitcoin-dot-org/bitcoin.org/issues/2968 and https://github.com/bitcoin-dot-org/bitcoin.org/issues/2967

### CODE REVIEW

**Comment by maxwellmons** [comment]
NACK

**Comment by aaronkuchma** [comment]
I see an objection, but I don't see an accompanying explanation for it.

The notion of decentralization is an acknowledgement that only anarchy can ever exist. I understand this. But the ethos of Bitcoin's decentralization wasn't "early adopters should have unlimited power and yield it in such a way as to illustrate the ills perpetrated by fiat incumbents". 

Correct me if I'm wrong (don't just plaster NACK like it were Elon's face and this PR was your meme canvas), but Bitcoin was supposed to protect people from being debanked, from being scammed by a central authority, and from being marginalized and subjected to selectively enforced rules.

It appears that bitcoin.org plays a role in the Bitcoin ecosystem like media outlets or banks play to fiat. You don't control bitcoin. You are a "last mile" service provider.

It also seems that bitcoin.org's actions may have led to Bitcoin adopters being scammed (we have tried to assist by pointing out some of the scams being recommended). A community policing approach was probably part of Satoshi's vision, even if that vision involved Philosopher Kings doing that policing.

Quebex has tried to follow the undocumented rules for inclusion. We have reviewed the other exchanges listed in an attempt to create a deterministic algorithm that defines what should and should not be included (e.g. https://github.com/bitcoin-dot-org/bitcoin.org/issues/2976 was a way of eliminating the possibility that exchanges can't be listed if there are "signup issues when using suspicious information that violates the exchange's TOS"). Given the opposition without clear guidance on what would be required to be listed, it certainly seems like this is a string rules for some, no rules for other situation.

This seems more like an ETH Classic situation than a Bitcoin situation. "bitcoin.org was available for the taking; now we are the Borg, and we do not chose you for assimilation".

Kind regards,

- Aaron

**Comment by achow101** [comment]
There are already many issues that have been opened to add Quebex, no need to open yet another one.

**Comment by aaronkuchma** [comment]
This is a pull request though.

**Pull request closed without merging**
