### PR TITLE
wallets: Drop mSIGNA

### LINKED ISSUE #2765: Wallet selection, mSignal/ciphrex is dead. Missing Wasabi wallet.
Add https://wasabiwallet.io/

Remove https://ciphrex.com/team/

They haven't tweeted anything since 2017 and their linked website is down.

### PR DESCRIPTION
**Pull request by wbnns**
This PR drops the mSIGNA wallet from the site and will be merged once tests pass:
1. The [Ciphrex website ](https://ciphrex.com/)(maintainer) appears to no longer be accessible and is timing out.
2. The [code repository](https://github.com/ciphrex/mSIGNA/commits/master) for the wallet hasn't been updated in 11 months.

Closes #2765.

Thanks to @Transisto for raising the issue.

Cc: @crwatkins

### CODE REVIEW

**Comment by luke-jr** [comment]
The website loads fine for me...

poke @CodeShark

**Comment by Transisto** [comment]
Confirm website loads, wasn't when I checked earlier.

**Comment by crwatkins** [comment]
NACK.

1. I didn't perform the initial review in 2014, but I don't see any conflict with any of our criteria.  Specifically, I don't see any problem with 

  * No indication that users have been harmed considerably by any issue in relation to the wallet
  * No indication that security issues have been concealed, ignored, or not addressed correctly in order to prevent new or similar issues from happening in the future

2. The wallet continues to function just fine for me.

3.  I don't believe that the web site being down for some short period of time even justifies this conversation.

4. If we believe that there is no intention to maintain the wallet in the future, we should discuss it with @CodeShark and agree at what point it should be removed.  Right now, it seems to work as well as it did a year ago.

**Comment by CodeShark** [comment]
Yes, the wallet is still being actively maintained albeit with less activity than before.

**Comment by wbnns** [comment]
@CodeShark Ok, thanks for letting us know.

**Pull request closed without merging**
