### PR TITLE
Add ad infrastructure

### PR DESCRIPTION
**Pull request by Cobra-Bitcoin**
Allows us to sell ads.

### CODE REVIEW

**Comment by luke-jr** [comment]
Umm... #1136 ?

**Comment by Cobra-Bitcoin** [comment]
This version added the disclaimer discussed in the previous pull request.

I decided against showing ads in the footer. Links in the footer are getting very few clicks so this didn't seem like a good place to try to sell ads to businesses.

**Comment by SartoNess** [comment]
why bitcoin.org require funds ?

**Comment by SartoNess** [comment]
my question has been covered

**Pull request merged**
