### PR TITLE
add bluewallet

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by wbnns** [comment]
@Overtorment Hello, [here's more information](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#adding-a-wallet) regarding prerequisites for adding a wallet.

Cc: @crwatkins

**Comment by Overtorment** [comment]
I followed this guide, yes

**Comment by crwatkins** [comment]
Since there are a few wallet listings in the PR queue, I've provided @Overtorment with some notes on criteria to review.  @Overtorment, please let us know when the wallet is again ready for review.

**Comment by wbnns** [comment]
@crwatkins Thanks.

**Comment by Overtorment** [comment]
Will do. Thanks!

**Pull request closed without merging**
