### PR TITLE
Add Cypherock X1 as HWW

### PR DESCRIPTION
**Pull request by irshadjsr21**

### CODE REVIEW

**Comment by crwatkins** [comment]
@irshadjsr21 Thanks for your submission.

Have you carefully verified that Cypherock X1 meets all the listing criteria specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md)? Do you have any questions on any of the criteria?

**Comment by irshadjsr21** [comment]
Hi Craig, thanks for the quick response. I have verified that Cypherock meets all the criteria mentioned in the document. I also made sure that the content and images are according to the mentioned guidelines.

Do let me know if you need any additional information.

**Comment by crwatkins** [comment]
Great.   Thanks for checking.

**Comment by crwatkins** [comment]
@irshadjsr21 In reviewing the actual submission I noticed that the 2fa feature was included.  I don't believe that Cypherock X1 includes 2fa, at least as defined in the listing defintions [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md).  Could you remove it?

Also, I noticed that the transparency score is `checkpasstransparencyopensourcehardware`.  The folks over at [WalletScrutiny](https://walletscrutiny.com/) believe that your [builds are reproducible](https://walletscrutiny.com/hardware/cypherockx1/) (as of a year ago).  I have not yet attempted a build myself.  If you believe that your builds are still reproducible, you may want to upgrade your transparency score to `checkgoodtransparencydeterministic`.

**Comment by crwatkins** [comment]
I have reviewed the Cypherock X1 wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design, however this submission requires a couple administrative updates before I can recommend it for listing. I will be glad to recommend the Cypherock X1 for listing once this is resolved.

Note that as a "hardware wallet," only the hardware and firmware components of the device were evaluated.  Wallet software that runs externally to the Cypherock X1 device was not evaluated in this review.  Cypherock's CySync App was used during this review, but not evaluated.  CySync is currently the only app that supports the Cypherock X1.

In this PR's scoring the `2fa` feature needs to be removed from the feature list and the transparency score possibly should be changed to `checkgoodtransparencydeterministic`.  Otherwise I concur with the scoring in 173bcf9.

---

## Cypherock X1
### Firmware 0.6.768
### Review Version 2024070601

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was provided by Cypherock at no cost.

**NOTE** Only the hardware/firmware is being evaluated here.  Wallet software running external to the device is not being reviewed.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

  **PASS** Public [audit by KeyLabs](https://dl.keylabs.io/keylabs_cypherock_x1_wallet_audit_final.pdf), good discussions on Bitcointalk, and multiple review videos on YouTube

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

  **PASS** No indication.

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication.

- No indication that the wallet uses unstable or unsecure libraries

  **PASS** No indication.   Uses trezor-crypto.

- No indication that changes to the code are not properly tested

  **PASS** No indication.   Tests at https://github.com/Cypherock/x1_wallet_firmware/tree/main/tests

- Wallet was publicly announced and released since at least 3 months

  **PASS** Released October 2022

- No concerning bug is found when testing the wallet

  **PASS** No concerning bug found

  **NOTE** An edge case in required CySync app (not formally evaluated here) was found to require much higher fees than necessary.   This was reported to Cypherock.

- Provides a bug reporting method on the website and/or in the app

  **PASS** Help menu in the CySync companion app and contact button on https://cypherock.com

- Website supports HTTPS and 301 redirects HTTP requests

  **PASS** http://cypherock.com redirects to https://cypherock.com

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

  **PASS** https://cypherock.com Rating B

- Website serving or linking to executable code or requiring authentication uses HSTS
  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

  **PASS** `max-age=31536000; includeSubDomains; preload`

- The identity of CEOs and/or developers is public

  **PASS** https://www.cypherock.com/about

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **N/A** Addresses are chosen by companion app

- Avoid address reuse by using a new change address for each transaction

  **N/A** Addresses are chosen by companion app

- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS** Uses deterministic nonces

- User has access to private keys for all major components of the wallet

  **PASS** User has access to master seed

- If private keys or encryption keys are stored online:

  **N/A**

  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.
- If user has exclusive access over its private keys:
  - Allows backup of the wallet

  **PASS** BIP39 phrase is available and seed is stored 2 of 5 sharded

  - Restoring wallet from backup is working

  **PASS** X1 wallet can be restored from BIP39 or the cards

  - Source code is public and kept up to date under version control system

  **PASS** https://github.com/Cypherock/x1_wallet_firmware releases are tagged

- If user has no access to some of the private keys in a multi-signature wallet:

  **N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)

    **PASS** Requires PIN and tap of X1 card

  - Protects the seed against unsigned firmware upgrades

    **PASS** X1 Vault firmware upgrades must be signed. X1 Cards are not upgradable.

  - Has capability to prevent firmware downgrades

    **PASS** X1 Vault firmware cannot be downgraded.  X1 Cards are not upgradable.

  - Supports importing custom seeds

    **PASS** A custom seed was imported to the wallet

  - Provides source code created for all open components and provides detailed specification for blackbox testing of any closed-source secure elements

    **PASS** X1 wallet firmware source https://github.com/Cypherock/x1_wallet_firmware
    **PASS** NFC communications to closed source X1 Card https://github.com/Cypherock/x1_wallet_firmware/blob/main/docs/nfc_secure_communication.md
    **NOTE** The interface to the closed source X1 Card is only documented as code here https://github.com/Cypherock/x1_wallet_firmware/tree/main/src/card_operations
    **NOTE** The closed source X1 Card is essentially secure storage for a seed shard.  No transaction related operations are performed on the card nor does the card ever have access to the full seed.


Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

  **N/A**

  **NOTE** However, CySync, the only compatible app, shows a sender address in received transactions and would fail this criterion

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

  **PASS** cyperock.com is in the preload list

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

    **PASS** Supports HD wallets

  - Provides users with step to print or write their wallet seed on setup

    **PASS** Provides BIP39 seed

  - Uses a strong KDF and key stretching for wallet storage and backups

    **N/A**

  - On desktop platform:
    - Encrypt the wallet by default

    **N/A**

**Comment by irshadjsr21** [comment]
Thanks @crwatkins for the detailed review.

I've removed `2fa` from the submission. Also, I've updated transparency to `checkgoodtransparencydeterministic` since the Cypherock X1 firmware is still reproducible.

**Comment by crwatkins** [comment]
I concur with the scoring in 3b916e9 and I recommend Cypherock X1 for listing.

**Comment by irshadjsr21** [comment]
@crwatkins All checks have passed for this PR, can we proceed to merge this? Let me know if you need anything from my end.

Thanks for all your support

**Comment by Arth200** [comment]
Hi,

Thank you for your message and contribution.

We will review the pull request (#4221) and proceed with the merge if everything is in order. If we need any additional information or further modifications, we will reach out to you.

Thank you for your patience and hard work.

Best regards,

Arthur Dehoorne

Le 15 juil. 2024 à 09:52, Irshad Ansari ***@***.***> a écrit :

﻿

@crwatkins<https://github.com/crwatkins> All checks have passed for this PR, can we proceed to merge this? Let me know if you need anything from my end.

Thanks for all your support

**Comment by nimit-jn** [comment]
Hi, I can see the PR is approved. How long does it usually take to merge? Thanks.

**Comment by irshadjsr21** [comment]
Hi, is there anything still remaining here?

cc @crwatkins @Cobra-Bitcoin

**Comment by crwatkins** [comment]
Nothing for me.   My recommendation stands. Thanks for all your help.

**Pull request merged**
