### PR TITLE
[Bitcoin Core] Add capacity increses FAQ

### PR DESCRIPTION
**Pull request by harding**
Preview: http://dg0.dtrt.org/en/bitcoin-core/capacity-increases-faq

This adds a FAQ to accompany yesterday's roadmap statement.

### CODE REVIEW

**Comment by btcdrak** [comment]
ACK

**Comment by CodeShark** [comment]
ACK

**Comment by adam3us** [comment]
ACK

**Comment by kanzure** [comment]
ACK

**Comment by eragmus** [comment]
ACK

**Comment by theymos** [comment]
ACK

**Comment by instagibbs** [comment]
ACK

**Comment by wtogami** [comment]
ACK

**Pull request merged**
