### PR TITLE
Remove btc.com wallet

### PR DESCRIPTION
**Pull request by schildbach**
The wallet isn't open source any more. According to [Google Play](https://play.google.com/store/apps/details?id=com.blocktrail.mywallet), the latest version is 4.4.7 (April 3, 2019). The [GitHub repository](https://github.com/blocktrail/blocktrail-wallet/releases) has 4.4.2 (Dec 7, 2018) as the latest version.

### CODE REVIEW

**Comment by crwatkins** [comment]
@schildbach Thanks for this PR.  I also note that the HSTS max-age on btc.com is 1 day and our minimum requirement is 180 days.

I would recommend we ping @jiangjinyuan for an update on the status of the wallet.  Perhaps @lacksfish or @lsgrep might have some information.  This [issue](https://github.com/blocktrail/blocktrail-wallet/issues/122) suggests that the source is current, but it seems that it was not tagged.

Since this happened a while ago, if this is not corrected within a week, I would recommend removal.  Note that we should also remove the collateral images.

**Comment by jiangjinyuan** [comment]
@crwatkins Hi, thanks for your recommends. I will check the code and update on the status of the wallet ASAP.

**Comment by lacksfish** [comment]
Tag 4.4.7 has been pushed to GitHub - the latest version is open source

**Comment by lacksfish** [comment]
To emphasize this, the release has been pushed by @jiangjinyuan, not me. Nontheless, I don't see why this pull request shouldn't be closed now. The issue is resolved.

**Comment by crwatkins** [comment]
Currently the HSTS max-age on btc.com is 1 day and our minimum requirement is 180 days.  I also highly recommend submitting to the [HSTS preload list](https://hstspreload.org/) as that may soon be a requirement, and it is an especially good idea for a site hosting a web wallet.

**Comment by crwatkins** [comment]
@jiangjinyuan Has there been any progress on addressing the HSTS 
Issue or should we merge this for now?

**Comment by schildbach** [comment]
@crwatkins I generally think there should be much less grace period for requirement violations. A `git revert` is only a click away if the violation is lifted.

**Comment by jiangjinyuan** [comment]
> @jiangjinyuan Has there been any progress on addressing the HSTS
> Issue or should we merge this for now?

@crwatkins Hi, I am sorry and I will handle it ASAP!

**Comment by wbnns** [comment]
@crwatkins 

> Are there any issues with removing and re-adding wallets "quickly" that would unduly affect our SEO?

No, not for specific wallets that fail to meet the listing criteria.

**Comment by wbnns** [comment]
This is scheduled to be merged on Thursday, March 19th.

**Pull request merged**
