### PR TITLE
Add dropbit wallet

### PR DESCRIPTION
**Pull request by MitchellMalleo**

### CODE REVIEW

**Comment by SixFiveSoftware** [comment]
Good afternoon, just wanted to see if there's any update on the ability for this to be merged. Thanks!

**Comment by crwatkins** [comment]
@MitchellMalleo Thanks for the submission!

@SixFiveSoftware Wallets, along with their open source code, need to be released for over three months before being considered for listing.  I note that the source code commits started in March, making it eligible for being considered in June.   That doesn't mean that the review can't start before June (it already did), but there are two reviews that potentially need to be completed first.

You can help speed up the process by making sure that the wallet strictly complies with all of the [listing criteria ](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and requesting any clarifications or discussing any discrepancies here in the meantime.

**Comment by SixFiveSoftware** [comment]
Cool, thank you @crwatkins . I was mistaken with the understanding of 3 months; our apps have been public since September, but only open-sourced after cleaning up our repos in March. Thanks for the clarification, and we look forward to revisiting this in a few weeks. We appreciate you putting this site together!

**Comment by crwatkins** [comment]
@SixFiveSoftware Thanks for your understanding.  To be precise about the three month criterion, it technically applies to the release.  We also have a criteria that source code is public and kept up to date under revision control.    The community is fairly adamant about the latter for the purposes of review, so my interpretation is that the three month criterion would apply to that also.   Alternative interpretations are welcome, as well as PRs with clarifications. 

In this case, however, I suspect it will all work out the same anyway.

**Comment by SixFiveSoftware** [comment]
@crwatkins sounds good, no worries. Totally understandable. 👍

Please let us know if you find anything that you have questions about or something we need to fix, happy to help.

**Comment by wbnns** [comment]
@SixFiveSoftware 

Hello, we were taking a look at the wallet and noted a discrepancy between the [GitHub repository](https://github.com/coinninjadev/dropbit-android) and the [Play Store](https://play.google.com/store/apps/details?id=com.coinninja.coinkeeper) for the Android version of the app.

The Play Store references a version 2.0 of the app, and new features such as a Twitter integration, mostly recently updated on June 17, however, we noted that the GitHub repository was last updated May 9 with a 1.6.1 release candidate and doesn't seem to include these changes.

Could you please elaborate on the difference?

Cc: @crwatkins @MitchellMalleo

**Comment by MitchellMalleo** [comment]
@wbnns thanks for looking into this, I'll work with our Android team so its up to date and you can continue your review.

**Comment by MitchellMalleo** [comment]
@wbnns @crwatkins everything should be up to date. Let me know if you need anything else!

**Comment by wbnns** [comment]
@MitchellMalleo Ok, thank you.

**Comment by crwatkins** [comment]
I have reviewed DropBit based on the current wallet requirements criteria and my evaluation is below. The summary is that because of the following issues I cannot recommend the wallet for listing at this time. 

1. A serious security issue was found
2. Wallet addresses can be easily discovered by third parties
3. The published source code is not complete
4. The wallet has not received sufficient user feedback


Other issues found that should be considered:

1. Consider removing minimum transaction limit of $1.00
2. Consider displaying full Bitcoin addresses on copy & paste
1. Consider allowing entry of Bitcoin addresses from keyboard

All of these items are described in more detail in the review below.

During the review, a serious security issue was found and reported. I don't believe that the criterion

* No concerning bug is found when testing the wallet

was meant to permanently preclude a listing, but no waiting period is specified. Any input from the community is always appreciated.  I recommend that this wallet be reconsidered for listing in nine months, but no sooner than three months after the above issues are resolved.

## DropBit
### iOS version 2.1
### Android version 2.2.2
### Review Version 2019072501

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available
  
  **FAIL** Sufficient feedback was not found
  
  * Google play:  1000+ installs, 21 reviews  
  * Generic web searches found no in-depth reviews or articles  
  * r/DropBit on reddit.com seems to have no user participation
  * DropBit posts on r/Bitcoin have very little followup from DropBit users
  * Little followup to DropBit posting on https://bitcointalk.org/index.php?topic=5086724.0

  
- No indication that users have been harmed considerably by any issue in
  relation to the wallet
  
  **PASS** No indication
  
- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

	**PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

	**PASS** No indication.  Uses libbitcoin.

- No indication that changes to the code are not properly tested

	**PASS** No indication.  There is substantial test code, but numerous little bugs were found that might not be expected with sufficient testing.

- Wallet was publicly announced and released since at least 3 months

	**PASS** Released in Dec 2018 with initial public source code commit 11 Mar 2019

- No concerning bug is found when testing the wallet

	**FAIL** Concerning serious security issue was found and reported

   **NOTE** Some other bugs and/or conscience design issues were found that were less concerning
   

  **NOTE** The minimum amount that can be sent by the wallet is $1.00.  As I have [written before](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-433630363) a wallet actually refusing to sign a perfectly valid transaction requested by the user is not acceptable.

  **NOTE** When pasting a Bitcoin address, the entire address is not immediately displayed, but rather a small portion is abbreviated.  The address should always be displayed in full, particularly at this crucial step.

   **NOTE** A Bitcoin address cannot be entered from the keyboard, only from a paste or a QR scan.  This could be quite inconvenient if a QR scan is not possible.

  **NOTE** The wallet has an optional alias feature that allows third parties to retrieve Bitcoin wallet addresses by using the user's phone number, by using a statically assigned dropbit.me URL, or by using a Twitter handle (Twitter aliases were not reviewed).  This allows attackers, knowing only a static alias (such as a phone number) to trivially retrieve the next Bitcoin addresses to be used by the wallet.   Addresses are in common and shared by the wallet and all alias methods.

  **NOTE** During wallet setup new users are asked to register a phone number, but no warnings or information about the privacy risk is provided to the user.

  **NOTE** Phone numbers are stored on central servers hashed in such a way that it is likely trivial for a rogue insider or an attacker to brute force a plaintext list of all users' phone numbers.


- Website supports HTTPS and 301 redirects HTTP requests

	**PASS** http://dropbit.app redirects

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)
  
  **PASS** dropbit.app A+ rating
  
- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days
  
  **PASS** dropbit.app implements HSTS with preload
  
- The identity of CEOs and/or developers is public

	**PASS** https://dropbit.app/termsofuse.html

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI
  
  **FAIL** The alias (phone, URL) feature can give out the same address the wallet gives out
    
- Uses deterministic ECDSA nonces (RFC 6979)

	**PASS** Uses libbitcoin
	
- Avoid address reuse by using a new change address for each transaction

	**PASS** Uses a new change address for each transaction

- User has access to private keys
- If private keys or encryption keys are stored online:

	**N/A**

  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.
- If user has exclusive access over its private keys:
  - Allows backup of the wallet

	  **PASS** Allows backup of BIP39 phrase from settings and quizzes two of the words.
  
	  **NOTE** Words are in upper case which makes them incompatible with BIP39 unless the user recognizes that they need to be manually converted to lower case.  This could impair restoring funds to another wallet.  Restoring a wallet requires them entered in lower case.
  
  - Restoring wallet from backup is working

	  **PASS** Wallet was successfully restored from backup phrase
  
  - Source code is public and kept up to date under version control system

	  **FAIL** Some source code at https://github.com/coinninjadev is missing.  The missing portion makes it impossible to complete a full review.  For example, important constants on crypto functions are excluded.  Some build procedures are missing and included libraries and their version information is unknown.  Not all libraries are tagged.
  
- If user has no access to some of the private keys in a multi-signature wallet:

	**N/A**
	
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:

	**N/A**

  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element

Optional criteria (some could become requirements):

- Received independent security audit(s)

	**NOTE** No known audits

- Does not show "received from" Bitcoin addresses in the UI

	**PASS** Shows "received to" address in the UI instead

- Provides a bug reporting policy on the website

	**PASS** https://dropbit.app/faq.html provides a [Report A Bug] button

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)
  
  **PASS** dropbit.app is on the preload list
  
- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

      **PASS** BIP32 with BIP39 seed and BIP49 addresses
  
  - Provides users with step to print or write their wallet seed on setup

	**PASS** During setup user is notified to remember to backup wallet with a constant reminder in the menu
  
  - Uses a strong KDF and key stretching for wallet storage and backups

	  **NOTE** Wallet storage is not encrypted, but on iOS it is stored in the OS keychain
  
  - On desktop platform:

	**N/A**
  
    - Encrypt the wallet by default
- For hardware wallets:

	**N/A**

  - Prevents downgrading the firmware

**Pull request closed without merging**
