### PR TITLE
Add v22.0 release

### PR DESCRIPTION
**Pull request by Cobra-Bitcoin**
Add v22.0 release

### CODE REVIEW

**Comment by danger89** [comment]
Ah thank god, closes #3737

**Review by melroy89 — APPROVED** [review]

**Review by melroy89 — CHANGES_REQUESTED** [review]
There is an problem with the build:

```
TypeError: no implicit conversion of Float into String
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:37:in `+'
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:37:in `initialize'
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:90:in `new'
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:90:in `block in generate'
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:84:in `foreach'
  /builds/melroy/Bitcoin-org/_plugins/releases.rb:84:in `generate'
````

**Comment by Cobra-Bitcoin** [comment]
Trying to fix.

**Comment by Cobra-Bitcoin** [comment]
OK tests passing now. Merging.

**Pull request merged**
