### PR TITLE
add bluewallet to wallets list

### PR DESCRIPTION
**Pull request by ncoelho**
This is a second PR (https://github.com/bitcoin-dot-org/bitcoin.org/pull/2642) after being advise to wait 6 months before submitting bluewallet.

We have now a more solid and stable code base, real world usage and experience as well. We think and hope to be ready now. 

Thank you in advance.

### CODE REVIEW

**Comment by crwatkins** [comment]
@ncoelho Thanks for the resubmission!

There are currently a few wallets in the queue for review.    Also note that because of extremely serious security issue found in #2787, the review may take a bit more time than usual.

However, in the meantime, it might be a good time for the community to discuss bluewallet's custodial lightning feature.  In the past, the community has been fairly adamant about not listing custodial Bitcoin wallets.    While bluewallet's on-chain wallet is non-custodial, the lightning component has a custodial component, if I am correct.   The question is whether our custodial criteria should apply to off-chain as well as on-chain funds.

It is important to note that while we currently have no criteria pertaining to lightning wallets, we have a wallet already listed with lightning capabilities.   (As an aside, I personally have no problems with our current lack of lightning criteria.  I believe that it is still just a bit too early to establish best practices with certainty.  I fear any immature lightning criteria at this time could stifle and damage development progress.)

I could argue this either way.  Many of our listed wallets have the capability built-in to be able to transfer funds to custodial exchanges and that does not disqualify them from listing.   One could view the bluewallet custodial component as being the same as a custodial exchange with an easy way in the wallet to transfer to that component and an easy way to interact with it.

On the other hand, the custodial component does hold bitcoins, and it is a major feature of the wallet.  I have heard claims (but let me be perfectly clear:  I have not verified any yet) of some users losing (small amounts of) funds with the custodial component.  

I welcome thoughts, discussions, and facts from the community!

**Comment by crwatkins** [comment]
Considering the lack of objections, we'll proceed forward with the review with the understanding that at some point in the future Lightning Network criteria may be retroactively applied.

**Comment by wbnns** [comment]
@crwatkins Thanks.

**Comment by crwatkins** [comment]
I have reviewed Bluewallet based on the current wallet requirements criteria and my evaluation is below. The summary is that because of the issues marked below as FAIL I cannot recommend the wallet for listing at this time. 

Bluewallet is capable of sending and receiving Lightning Network payments through a custodial hosted (or user supplied) server.  This capability was demonstrated, but not evaluated (other than backup and restore) as we currently have no criteria directly pertaining to LN functionality.  With a custodial component there are certainly extra challenges and risks in implementing a discretionary system instead of one that relies solely on consensus rules, evidenced by a number of [bugs](https://github.com/BlueWallet/LndHub/issues/8) reported.  Bluewallet lightning withdrawals to on-chain require the use of a third party exchange.  That said, Bluewallet has a fairly intuitive interface for sending and receiving payments and distinguishing between on-chain and off-chain operations.  

During the review, some bugs were found and reported and mentioned below.   Also, the report of a bug that seriously affected a user was discovered. I don't believe that the criterion

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

was meant to permanently preclude a listing, but no waiting period is currently specified. Any input on this from the community is always appreciated.  Considering that this is the second time this wallet has been reviewed with significant outstanding issues I recommend that this wallet be reconsidered for listing in a year, but no sooner than nine months after the failed issues are resolved.


## Bluewallet
### iOS version 4.2.0
### Android version 4.2.0
### Review Version 2019081701


The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available
  
	**FAIL** Sufficient feedback was found, however concerning issues were found in that feedback (see below)

  - Active user participation in GitHub issues
  - Fairly active subreddit https://www.reddit.com/r/bluewallet/
  - Bitcointalk https://bitcointalk.org/index.php?topic=5168527.0
  - 10,000+ Google Play downloads
  - Reddit discussions https://www.reddit.com/r/Bitcoin/comments/ae64oc/anyone_used_bluewallet/
  - https://www.reddit.com/r/Bitcoin/comments/afycen/blue_wallet_bitcoin_lightning_network_wallet/
  - https://www.reddit.com/r/Bitcoin/comments/b522x2/these_people_dont_know_what_the_f_theyre_doing/
  
- No indication that users have been harmed considerably by any issue in
  relation to the wallet
  
  **FAIL** User lost 5 BTC using the wallet https://github.com/BlueWallet/BlueWallet/issues/527
  
- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

    **PASS** No indication.  Uses BitcoinJS.

- No indication that changes to the code are not properly tested

    **PASS** Numerous unit and integration tests at https://github.com/BlueWallet/BlueWallet/blob/master/tests/

    **NOTE** One might expect that obvious bugs, such as a recently introduced change that caused valid WIF keys to be rejected as invalid, would be able to be discoverable with more testing.  The speed of development is impressive, but perhaps it might be "overdriving" the quality and testing. 
  
- Wallet was publicly announced and released since at least 3 months

    **PASS** Beta warning in GitHub README was removed 14 May 2019

- No concerning bug is found when testing the wallet

    **FAIL**  A BIP84 wallet which was backed up was incorrectly restored as an empty BIP49 wallet.

    **NOTE** Other less serious bugs were found and reported

    * Failed wallet imports rejecting valid WIFs
    * Occasional screen layout problems positioning needed controls off the screen
    * Failed P2PKH wallet imports when wallet had more than a trivial number of transactions

     **NOTE** There were also numerous less serious, but annoying, UI/UX issues that weren't expected in a released product, such as text that can't be copied, UI that freezes for seconds, and seemingly inconsistent use of buttons, links and alerts.


- Website supports HTTPS and 301 redirects HTTP requests

   **PASS** http://bluewallet.io redirects

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)
  
  **PASS** https://bluewallet.io rating: A
  
- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days
  
  **FAIL** https::/bluewallet.io does not support HSTS
  
- The identity of CEOs and/or developers is public

   **PASS** https://bluewallet.io -> About

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI
  
  **PASS** Displays a new receive address for default HD wallets
  
- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS** Uses BitcoinJS

- Avoid address reuse by using a new change address for each transaction

  **PASS** Uses new changes addresses for default HD wallets
  
- User has access to private keys
- If private keys or encryption keys are stored online:

  **N/A**

  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.
- If user has exclusive access over its private keys:
  - Allows backup of the wallet

     **PASS** When wallet is created, user is prompted to write down mnemonic phrase
     
     **NOTE** There is no quiz or verification step to verify the user recorded the backup correctly, and thus there is no reminder to users that may have skipped the backup step.
     
     **NOTE** The lightning wallet backup is a URI with a long hex number and a QRC.  There are no suggestions on how best to copy it accurately or store it safely.  It is possible that many users are without backups.
  
  - Restoring wallet from backup is working

     **FAIL** A BIP84 Bluewallet backup incorrectly restored as an empty BIP49 wallet. 
  
  - Source code is public and kept up to date under version control system

   	 **FAIL** Not all versions released to the app store are tagged at https://github.com/bluewallet/bluewallet (e.g. v4.1.0, v3.9.7, v3.9.5, v3.9.4 are not tagged in git)

- If user has no access to some of the private keys in a multi-signature wallet:

  **N/A**
  
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:

   **N/A**
   
  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element

Optional criteria (some could become requirements):

- Received independent security audit(s)

  **NOTE** None known

- Does not show "received from" Bitcoin addresses in the UI

   **PASS**  Does not show

- Provides a bug reporting policy on the website

   **PASS** Contact email address on https://bluewallet.io

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)
  
   **FAIL** https::/bluewallet.io does not support HSTS

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

      **PASS**  Support BIP49 and BIP84
  
  - Provides users with step to print or write their wallet seed on setup

      **PASS** Provides a step
  
  - Uses a strong KDF and key stretching for wallet storage and backups

      **FAIL** Password is used directly to AES encrypt wallet storage
  
  - On desktop platform:

      **N/A**
  
    - Encrypt the wallet by default
- For hardware wallets:

    **N/A**

  - Prevents downgrading the firmware

**Pull request closed without merging**
