### PR TITLE
Update Armory with new links

### PR DESCRIPTION
**Pull request by achow101**
Armory is [no longer developed](https://bitcointalk.org/index.php?topic=1351792.0) by ATI. Its website, bitcoinarmory.com, is down and is no longer Armory's website. The source code is now maintained by goatpig. 

This PR changes the website link to point to the release download location (since a new website has not yet been set up) and the source code link to point to goatpig's repository.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
I've removed Armory from our wallets page (https://github.com/bitcoin-dot-org/bitcoin.org/commit/8f6dfb338e125ca42a83849f9c8e9cc8b0719366). 

It will take some time for this new fork maintained by goatpig to establish itself as trustworthy. We'll review the situation in 3 months.

**Comment by achow101** [comment]
Why would it be not trustworthy? Goatpig was one of the primary developers of armory; now he is the maintainer of the project.

**Comment by sunnankar** [comment]
@Cobra-Bitcoin Bitcoinarmory.com is operational with download links and signed hashes for Version 0.93.3 which was already widely considered trustworthy.

Version 0.94 is still being (1) actively developed by goatpig, who has maintained the public version of the branch for about two years, and (2)  semi-actively developed by the original developer etotheipi who has focused most of his attention on the non-public enterprise branch over the last two years. Consequently, all of the removal commits should be reverted.

**Comment by BitpopCoin** [comment]
Armory is the best wallet available

**Pull request closed without merging**
