### PR TITLE
add denarium wallet

### PR DESCRIPTION
**Pull request by ihqtzup**
I would like to have our physical bitcoin wallet included in bitcoin.org. Our physical wallet doesn't fully fit in to any category but i think hardware wallet is the closest. If you can't accept denarium to any category could you consider adding own category for physical bitcoin wallets.

### CODE REVIEW

**Comment by crwatkins** [comment]
@ihqtzup Thanks for your submission!  I don't believe your "physical wallet" fits into the hardware wallet category because there are many [criteria](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md ) for hardware wallet listing that can't be met by a "physical wallet".  I would suggest submitting to the [Vouchers](https://bitcoin.org/en/resources#vouchers) category.

**Comment by wbnns** [comment]
@ihqtzup If you'd like to open a separate pull request to be added to the Vouchers category that @crwatkins mentioned, we can consider it for potential inclusion there.

**Comment by TraderSalad** [comment]
I have stored value on a Denarium physical coin. Also added BCH after the fork. I am unable to access the wallets that store the token so can not move or spend. Can some one provide method for accessing wallet ?

**Comment by wbnns** [comment]
@TraderSalad 

Hello, would recommend reaching out directly to [Denarium](https://denarium.com/) to seek their advice on what the best course of action might be.

**Comment by TraderSalad** [comment]
Already have and still waiting for support to respond. Maybe the lords of
crypto don';y want me to do anything except hodl.
By 2025 who knows what it will be worth ?

**Pull request closed without merging**
