### PR TITLE
Added New Exchange

### PR DESCRIPTION
**Pull request by arjunparakh**
Add Masscoinex.com as International and Canadian exchange although servicing worldwide.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
This exchange is not reputable enough and will not be merged.

**Comment by arjunparakh** [comment]
How do you define reputation of an exchange?

**Comment by arjunparakh** [comment]
Cobra,

The kind of a personality you're and who controls the bitcoin.org domain.

Who says directly to a CEO of a company right on the face that your company
is not reputable sounds really disgraceful.

What is reputable to you?

Those companies who are listed on the site has somehow or the other looted
millions of dollars from people around the world. Sounds reputable to you?

Those companies who has billions of complaints claiming by customers that
they have been cheated from their hard earned. Sounds reputable to you?

Those companies who behaves with customers rudely, doesn't interact and
don't even care about their needs. Sounds reputable to you?

Those companies who has indirectly murdered several thousand individuals by
their deceiving laws, regulations, attraction which was forced on to
individuals who thought that bitcoin would change their lives and due those
companies only interest to make money screwed their lives completely and
was unlitimately forced to hang from the ceiling. Sounds reputable to you?

How long will these company be rewarded, don't you think it's time for them
to be penalized?

How long will you keep them up there and let others become victim of their
prey. Do you not think it's time to hunt these companies down?

Cobra, remember if you close your eyes then it would seem everything is
fine, but the moment you open your eyes you would realise, the main culprit
was not these exchanges it was you because you literally pushed away great
companies out of the way thinking that they were not reputable enough.

I don't know, what reputable means in the dictionary that you read, but the
one i read tells me to be honest and serve your customers till your last
breath and that is what I have been doing since the inception of my
company. All you have to do is google: Masscoinex, you wouldn't see tons of
reviews coz I never fake them, but the ones you would see are real and they
are happy.

Now I haven't wrote this to convince you to put my company up on the
Bitcoin website. It really doesn't matter if my company shows up there or
it don't.

I will still succeed coz the path I chose leads to honesty and it will
build my company it's way to the top by itself one day.

The reason why I wrote this, is for you to once do something good, so the
next time when you see your child you can proudly say that your father is a
good man.

Best of luck for your search for reputable companies.

Founder, Ceo for Masscoinex.com.
Arjun

**Comment by Cobra-Bitcoin** [comment]
I googled your brand name in quotes and found very little actual discussion about it anywhere on the internet. At least not enough to have it listed as an international exchange and a Canadian exchange. You also have very little volume.

We are under no obligation to send you free traffic. Please stop responding. Maybe we can re-consider in a few years when you build up more volume and more customers.

**Comment by arjunparakh** [comment]
Don't worry i won't need it.

**Comment by arjunparakh** [comment]
And please don't tell me to stop responding. Just like you're in no
obligation to give me free traffic. I am in no obligation to take your
orders and talking about *"Maybe we will reconsid*er in a few years". Keep
it for yourself probably we will need to reconsider who would be more
entitled to have to control over the network let's fight this through shall
we and let see who wins?

**Pull request closed without merging**
