### PR TITLE
Fix rtl text styles

### PR DESCRIPTION
**Pull request by alexcherman**

### CODE REVIEW

**Comment by wbnns** [comment]
@zeevbb

Hello, we've made some updates to fix RTL issues, based on your feedback. When you have a moment, could you please take another look - https://staging.bitcoin.org/he/ - and let us know what you think?

**Comment by ZeevBB** [comment]
@wbnns I emailed you as a word doc several more cases needing adjustments regarding RTL or links that end up in the English version. I am attaching it here as well. 
[bitcoinOrgHe_QA2.docx](https://github.com/bitcoin-dot-org/bitcoin.org/files/4707376/bitcoinOrgHe_QA2.docx)

**Comment by wbnns** [comment]
@ZeevBB 

Great, thank you for spending the time to go through this. We'll make the additional updates and let you know when ready for review.

**Comment by wbnns** [comment]
Merging into `rtl-updates`.

**Comment by wbnns** [comment]
@ZeevBB 

We're opening a new pull request with the additional updates.

**Pull request merged**
