### PR TITLE
Adding Coinome to Indian Exchanges

### PR DESCRIPTION
**Pull request by sreekanthgs**
Pull Request for https://github.com/bitcoin-dot-org/bitcoin.org/issues/1843
Addition of Coinome #1843

### CODE REVIEW

**Comment by sreekanthgs** [comment]
Can someone please merge this request? Thank you.

**Comment by Mirobit** [comment]
NACK:
- Exchange is still in beta status. We should wait at least until it is out of the beta.

**Comment by wbnns** [comment]
@sreekanthgs Please let us know when you all are out of beta and we can reconsider.

**Comment by sreekanthgs** [comment]
@wbnns @Mirobit Coinome is now out of Beta. Can you folks please reconsider this? Thank you.

**Pull request closed without merging**
