### PR TITLE
Update bitcoin-paper.html with मराठी (Marathi) translation

### PR DESCRIPTION
**Pull request by shivajiambedkar**
Hello, this is a Marathi translation of the Bitcoin whitepaper. 

The PDF for this can be found on github https://github.com/shivajiambedkar/bitcoin-marathi/blob/main/bitcoin_mr.pdf (I didn't know how or where to put the file in the repo)

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Has this been reviewed by anyone?

**Comment by shivajiambedkar** [comment]
Do you mean someone from Bitcoin org? No.

**Comment by shivajiambedkar** [comment]
> Has this been reviewed by anyone?

This paper has been reviewed by two native speakers. It is ready to be published.

**Comment by shivajiambedkar** [comment]
@Cobra-Bitcoin bump

**Comment by Cobra-Bitcoin** [comment]
Thanks a lot for working on this, this looks really slick. I especially like the cover page.

Merging this now.

**Comment by shivajiambedkar** [comment]
Thank you. 
The person on the cover is **Shivaji Maharaj**. He is one of the greatest men of all time. We were born slaves, He gave us freedom!

**Pull request merged**
