### PR TITLE
Translation dev docs

### PR DESCRIPTION
**Pull request by kuzzmi**
This pull request closes issue #1723.

This functionality got several iterations over the last few months and the current version seems to approach the requirements in the least intrusive way, meaning the amount of changes is minimized.

Currently 

- [x] Refactoring and re-configuring the source code to handle new folder structure required to enable translations
- [x] Refactored and simplified `js/devsearch.js` to handle language-specific autocompletion in the search input.
- [x] Refactored and simplified `_plugins/glossary.rb` to produce data for "Developer Glossary" page as well as for the `devsearch` input
- [x] Enabled translation of various parts of the developer-documentation related pages using the same mechanisms as for other internationalized pages
- [x] Added various static messages and strings to `_translations/en.yml`
- [x] Added a warning for translated documents that the version a user is looking at might be not the most recent version
- [x] Merged with master as of 24-Nov-2017
- [x] Fixed `qualityassurance/devsearch.html` test
- [x] Fixed other tests
- [x] Upload Transifex with English documentation

Instructions on how to contribute to the translations can be fully flashed out after the files are uploaded to Transifex.

Having a `qualityassurance/devsearch.html` test is no longer needed as all the transformations of the data are done in Ruby (see `_plugins/glossary.rb`) instead of doing hackish obscure Liquid transformations. On the other hand the test itself will need to be more intelligent and thus more fragile due to different folder structure and different languages.

---

I'm keen to see your comments and suggestions and work through them before I update Transifex (as this will trigger a lot of notifications to users).

The current version of the website with enabled development translations can be found here: https://stuff.kuzzmi.com/

**NOTE:** Only Ukrainian language was used as a language for testing different translation scenarios.
Starting from here you can check what was translated: https://stuff.kuzzmi.com/uk/developer-documentation

---

A bounty can be paid to the following address:
1NQLaMgPzQ5XvMYZoymy7fMAxnZ1C7reea

### CODE REVIEW

**Comment by wbnns** [comment]
@kuzzmi Wow, thanks so much for working on this.

screen recording 2017-11-24 at 11 53

Super-excited about helping developers amongst the millions of Bitcoin.org visitors who don't speak English, learn more about it on a technical level.

Will check this PR out in more detail and follow-up here, soon.

**Comment by wbnns** [comment]
@kuzzmi Great work - this is super-impressive. Let's go ahead and update Transifex.

**Comment by kuzzmi** [comment]
Transifex was updated with new source files. I managed to push everything to one project, so we have a better picture of the translation status of the whole project. Translations there can be done the same way as the rest of the website's strings.

After much consideration I thought this will be the easiest possible way of dealing with them in a long run.
Developers' documentation and glossary items are added and the Transifex configuration is updated.

**Comment by wbnns** [comment]
Unless others object, this will be merged on Wednesday, December 27th.

@kuzzmi Awesome job!

**Comment by kuzzmi** [comment]
@wbnns Thank you! And I hope this functionality will make bitcoin more accessible.

**Comment by wbnns** [comment]
@kuzzmi 

Thanks again for all of your hard work on this.

Here's the [transaction ID](https://blockchain.info/tx/791d3490d6b913da1b08dbdad36da656667ee8c81f68316787296eb4d11de556) for the bounty you took down.

**Comment by jnewbery** [comment]
This (or some other change) appears to have broken the link to https://bitcoin.org/en/developer-documentation in the top menu:

screen shot 2017-12-30 at 11 37 46 am

There used to be a link to developer documentation between _Community_ and _Vocabulary_.

**Comment by wbnns** [comment]
@jnewbery Hey John, happy holidays! Thanks for mentioning. We'll fix. 👍

**Comment by jnewbery** [comment]
Happy New Year Will! Thanks.

**Pull request merged**
