### PR TITLE
Add Zebpay to the list of Australia exchanges

### PR DESCRIPTION
**Pull request by nirajd-zebpay**

### CODE REVIEW

**Comment by nirajd-zebpay** [comment]
Hi @wbnns Any idea when can this be merged? Do let me know if any additional information is required.

**Comment by wbnns** [comment]
@nirajd-zebpay Thanks, not just yet, but we'll let you know once we've reviewed the exchange.

**Comment by wbnns** [comment]
Hello, we tried signing up to review the exchange, however, we were unable to receive the OTP text message confirmation required in order to create an account. When a number was provided, no text message was received. We made multiple attempts.

We are unable to review the exchange for potential inclusion at this time.

**Comment by nirajd-zebpay** [comment]
Hi @wbnns Did you tried Australia country? Can you confirm whether mobile number used was of Australia country?

**Comment by wbnns** [comment]
@nirajd-zebpay 

Hello, no, it was not. On the sign up page, a user is required to provide a mobile number in order to sign up, whereafter a text message is sent that must be received in order to activate the account. The dropdown allows a user to enter a mobile number from one of approximately 200 countries:

Screen Shot 2019-08-13 at 15 19 10

It isn't restricted to only Australia.

**Comment by nirajd-zebpay** [comment]
Hi @wbnns. Possible for you to try mobile number of Australia as requested to added in the list of Australia exchanges. 
Do let me know the country you were trying if its not possible for you to try using Australian number.

**Comment by nirajd-zebpay** [comment]
Hi @wbnns. Waiting for your response.

**Comment by wbnns** [comment]
@nirajd-zebpay 

Hello, we tried signing up multiple times with a Canadian number. The issue is that the Australian landing page defaults to asking users to sign up with a mobile number based on the country associated with their IP address.

It would potentially be confusing to users if they had the option of using any mobile number available in the list of 200+ countries in the dropdown, but Australian ones are the only ones that would work properly when chosen.

**Comment by nirajd-zebpay** [comment]
Hi @will. Agree with you. We are in process to keep only list of currently supported countries. Request you to check once by changing country to Australia and try with Australian number for smooth testing of other functionalities.

Please note that we want to be listed in Australia section of List of exchanges

image

**Comment by will** [comment]
> Hi @will. Agree with you. 

lol no you don’t, bitcoin fuckin sucks

**Comment by nirajd-zebpay** [comment]
> @nirajd-zebpay
> 
> Hello, we tried signing up multiple times with a Canadian number. The issue is that the Australian landing page defaults to asking users to sign up with a mobile number based on the country associated with their IP address.
> 
> It would potentially be confusing to users if they had the option of using any mobile number available in the list of 200+ countries in the dropdown, but Australian ones are the only ones that would work properly when chosen.

@wbnns Agree with you. We are in process to keep only list of currently supported countries. Request you to check once by changing country to Australia and try with Australian number for smooth testing of other functionalities.

Please note that we want to be listed in Australia section of List of exchanges

image

**Comment by wbnns** [comment]
@nirajd-zebpay 

Understood, thanks.

**Comment by nirajd-zebpay** [comment]
@wbnns 

Hi. Do I need to send new merge request?

**Pull request closed without merging**
