### PR TITLE
Update text on Bitcoin For X pages

### PR DESCRIPTION
**Pull request by harding**
This is aimed at improving the sections of these three pages that pull #972 attempted to remove.  The basis for several of the changes here were contributed as diff comments to that PR.

## Bitcoin for businesses

screenshot-btcorg localhost 2015-07-28 20-47-56

## Bitcoin for developers

screenshot-btcorg localhost 2015-07-28 20-51-13

## Bitcoin for individuals

(New text identical to the new text in Bitcoin For Businesses.)

screenshot-btcorg localhost 2015-07-28 20-53-06

### CODE REVIEW

**Comment by saivann** [comment]
@harding As usual, I am suggesting shorter text versions for these pages :) , how about something like the following? I feel like some extra details mentioned here could go in the [FAQ](https://bitcoin.org/en/faq#how-much-will-the-transaction-fee-be) (and we could link to it from there once it's updated).

~~~
There is no fee to receive bitcoins, and many wallets let you control how large a fee
to pay when spending. Most wallets have reasonable default fees, and higher fees can
encourage faster confirmation of your transactions. Fees are unrelated to the amount
transfered, so it's possible to send 100,000 bitcoins for the same fee it costs to
send 1 bitcoin.
~~~

Note; In the text I am suggesting a replacement for, I found a small typo s/encourgage/encourage/

Except for my comment above, 35390f2 all LGTM and is a strong improvement IMO . Thanks!

**Comment by harding** [comment]
@saivann Thanks! Made your change verbatim except for (1) adding a link to the confirmation entry on You Should Know (2) one spelling change.  Editing the related entries on the FAQ is definitely on my todo list.

I also realized that I forgot to save the final edits from my text editor before my original commit (which is why there were spelling mistakes), so two other tiny changes are added in commit 4e973dd.

This PR is scheduled to be merged Sunday, August 2nd.

**Comment by ABISprotocol** [comment]
Hello, I would like to suggest that there be some effort to synchronize somewhat the content of these three pages with the content of the pages which can be found [here at the Bitcoin Foundation Education Committee Best Practices Guides](https://github.com/btcfoundationedcom/btcfoundationedcom.github.io/blob/master/guides/README.md).  
See also https://btcfoundationedcom.github.io/ and http://bitcoinfoundationsandbox.org/education/
This might need a new issue, let me know how best to go at it.

**Comment by harding** [comment]
@ABISprotocol I read through the documents on the linked pages and didn't see anything relevant to this PR.  If you would like to open a separate PR suggesting changes, feel free---but keep in mind that goal of these three pages on Bitcoin.org is to describe the benefits of Bitcoin, not the best practices for using it well.

**Pull request merged**
