### PR TITLE
Wallet optional criteria

### PR DESCRIPTION
**Pull request by ABISprotocol**
This is a proposal to add optional criteria for how wallets are evaluated.

### CODE REVIEW

**Comment by harding** [comment]
Could you provide a rational for why these optional criteria should be added?  Also, can you clarify what you mean by "as a portal to"?  ("Portal" sounds synonymous with "hyperlink" to me in this context.)

**Comment by ABISprotocol** [comment]
@harding Sure, brief rationale follows:

The following optional criteria are proposed to be added:

"Shall not serve as a portal to a brokerage or exchange
 Shall not serve as a portal to a bank or a banking network (distributed ledger)"

The use of the word "portal" is intended to imply "a door," or "an opening to," ~ the dictionary definition of "portal" is "a doorway, gate, or other entrance, especially a large and elaborate one."

In the first example, a wallet should clearly serve the purpose of connecting one user to another,  where there is no central authority or middleperson (see https://bitcoin.org/en/faq#what-is-bitcoin) ~ the wallet should not serve the purpose of advancing the interest of a brokerage.  Brokerages act as a middleman, buying bitcoin in bulk and selling them to customers. Brokerages charge a fee for this service.  Exchanges, such as BitStamp, and BTC-E, offer direct buying and selling between currencies. Once funded,exchanges allow for quick buying and selling within the platform.
Trading fees may be low, but converting funds to and from bank accounts may be expensive and take considerable time. (Refer to: https://btcfoundationedcom.github.io/guides/pdf/buying_letter.pdf)

In the second case, the same rationale is used, but it is described as "Shall not serve as a portal to a bank or banking network (distributed ledger)" ~ for the following reasons:
1) If a bank were to develop an application in which it developed tokens and bank-oriented services, while also presenting blockchain based services, this should not be permissible as essentially it would be a portal for users to access the banking industry, not the world of bitcoin.
2) If a wallet were to be developed and presented to allow users of bitcoin to access a inter-banking system utilizing a distributed ledger (blockchain based system), it is my assertion that this would also be a portal to the banking system and not a true example of the peer to peer finance that we seek to promote through bitcoin.org

Looking forward to further comments ~ cc @crwatkins

**Comment by ABISprotocol** [comment]
To @coblee and @crwatkins - looking forward to any comments you may have on this.

**Comment by crwatkins** [comment]
As a historical note, our "Optional criteria" category has been for criteria which we've wanted to see in a wallet, but are too new or too immature to enforce the requirement on all listings at the time.   I'm not really sure that the criteria proposed fall into that category (and thus, if deemed important, should not be optional).

That said, I believe there is value in continuing to support listings that fall under those proposed criteria, but to list them in a separate category as I proposed in #1109.

**Comment by ABISprotocol** [comment]
@crwatkins In that case, could you please provide a pull request that fulfills what you have intended as you proposed here: https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702

In addition, I would also encourage that as part of your pull request, you feel free to draw from or copy whatever text you would like from my pull request here: #1223 (To the extent you feel that is feasible in the context of what you are trying to do.)

**Comment by ABISprotocol** [comment]
@crwatkins I have just gone back to observe https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-192759633 to see if there have been any pull requests generated after the date of that comment, and I have noted that you have not provided a pull request that fulfills what you have intended to do in https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702 

I had delayed commenting further here (and had delayed pressing forward with an effort to merge my own pull request here) in hopes of seeing @crwatkins generate a pull request on the issue (see above).  However, this has not occurred.

In light of that, and in the absence of further objections, I request that @harding merge my pull request as proposed.

I don't mind someone providing additional modifications now (or after it's merged) but I'd like to see it merged, I suppose.

**Comment by harding** [comment]
@ABISprotocol FYI, I dropped my merge access to this repository a few months ago.

**Comment by ABISprotocol** [comment]
@harding Ah ~ apologies, I didn't realize you no longer had merge access.  (I don't have merge access.)

@Cobra-Bitcoin or others who do have merge access, I am requesting that the PR be merged, unless you have objections based on the above comments in the thread on the PR.

**Comment by crwatkins** [comment]
I still oppose this change as I believe there is value in continuing to support listings that do not meet the proposed criteria.   As a statistical note, half of the wallets currently listed do not meet the proposed criteria.

**Comment by Cobra-Bitcoin** [comment]
@crwatkins is the maintainer of the the wallets pages, so if you haven't been able to convince him of the merits of this pull request, then I don't think it should be merged.

I think the current method of deciding what wallets get listed is working very well by the way.

**Comment by bitcoin-afterson** [comment]
Almost afraid to ask Afterson.com to be added as a wallet because it is not your ordinary wallet, but it has good intentions to make it a convenient tool to bridge bitcoin and the physical world. Can Afterson.com be added as a wallet?

**Comment by crwatkins** [comment]
@bitcoin-afterson First, this existing thread may not be the best place to ask such a question; you should probably open a  new issue to discuss it.   Extremely briefly, the wallet listing criteria is [here](https://github.com/bitcoin-dot-org/bitcoin.org#wallets). Afterson.com seems to be more of an escrow service than what we classically consider a Bitcoin wallet and we currently do not list escrow services.  After you have reviewed the criteria and believe that they can be met, feel free to open a new issue to discuss it.

**Comment by bitcoin-afterson** [comment]
New to github
How do we open a new issue 

Thanks
Peter

**Comment by bitcoin-afterson** [comment]
I hope that I followed the correct procedure and opened an issue at
https://github.com/bitcoin-afterson/bitcointool/issues/1

**Comment by crwatkins** [comment]
@bitcoin-afterson To discuss this further, you will want open an issue [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

**Comment by ABISprotocol** [comment]
@crwatkins You stated, "I still oppose this change as I believe there is value in continuing to support listings that do not meet the proposed criteria. As a statistical note, half of the wallets currently listed do not meet the proposed criteria."

My response to this statement is that, you will note that my proposed criteria are actually proposed optional criteria.  Furthermore, it is arguable that many wallets should not actually be on bitcoin.org anyway based on the ample discussion of web wallets (which there is no need to repeat in depth here).  Finally, I do not agree that half of the wallets currently on bitcoin.org would actually not meet the proposed optional criteria.  

From the proposed commit, which would change the section under "Optional criteria (some could become requirements):"

(The proposed commit simply states:)
 
_- Shall not serve as a portal to a brokerage or exchange
- Shall not serve as a portal to a bank or a banking network (distributed ledger)_

It certainly is an illogical claim to state that my proposed change would as you say result in "half of the wallets currently listed (not meeting) the proposed criteria."  That is because none of the current wallets serve as a portal to a brokerage or exchange with the exception, perhaps of Coinbase, which is a hybrid, and none of them serve as a portal to a bank or banking network (distributed ledger) - by which I mean a inter-banking system utilizing a distributed ledger (blockchain based system); this would also be a portal to the banking system and not a true example of the peer to peer finance that we seek to promote through bitcoin.org.  

I would argue that Coinbase does serve as a "portal to a brokerage or exchange" and thus would certainly fall within my proposed criteria.

But as I've pointed out, my criteria are within the OPTIONAL CRITERIA section that already exists.  Therefore, as you also (correctly) noted, and here I quote you:  "there is value in continuing to support listings that do not meet the proposed criteria."

So there you have it.  I continue to recommend that my proposed commit be merged.  There is no reason to believe that it would result in wallets suddenly being delisted from bitcoin.org - what I hope it would do is provide a guide for future, more intensive review of wallets which might be designed more particularly as a portal to the banking system rather than intending to provide users with a true peer-to-peer experience.  

@Cobra-Bitcoin I don't think that someone should have to get through a bottleneck of a single maintainer of wallets pages in order to convince people that something needs to be done.  I would also note that @crwatkins did not provide an alternative pull request to better address the issue that he himself raised in https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702

I also consider this a security concern, for as wallets continue to be proposed for inclusion in bitcoin.org that are web wallets and / or that direct users to banks or inter-banking systems using a distributed ledger, the danger to users increases more and more, especially in light of the fact that bitcoin.org has not adopted a pull request to guard against this very issue. (!)

**Comment by harding** [comment]
@ABISprotocol 

> I don't think that someone should have to get through a bottleneck of a single maintainer of wallets pages in order to convince people that something needs to be done.

@crwatkins saying "I oppose this change" is not a bottleneck, it's an outright rejection of your proposal.  Moreover, Craig isn't standing in the way of you convincing people; instead he is one of the people you have failed to convince (I'm another person you've failed to convince).

I suggest that you close this issue, or that @Cobra-Bitcoin close it for you.  Furthermore, you've been commenting on issues in this repository for a couple years now and have failed to make any useful suggestions I can recall and have zero merged contributions (this being, IIRC, your first PR).  We've also had to yell at you a couple times for posting personal attacks against other contributors.  I thank you for trying to contribute, but I suggest that you look for some other project where the project members may be more welcoming of your opinions so that your time will be more productively used.  In this project, you're just wasting both your time and everyone else's time.

**Comment by ABISprotocol** [comment]
It is clear that maintainer(s) / those with merge access for this repository don't have any interest in actually dealing with the (very real) dangers of web wallets, as well as the very real dangers to users that will come with the growth of wallet types that will ultimately be expressly designed as a portal to a bank or a banking network, or as a portal to an exchange or brokerage.  Although I have attempted for some time to provide a simple and reasonable solution to this, I fully understood that it was unlikely that my proposal in this pull request would likely never be accepted, even though it was provided as an optional criteria that would have no actual immediate effect upon any listed wallets.

I had hoped that the discussion and the pull request itself would generate further discussion, which it did, and further, that it would lead to either @crwatkins or another person who is active in the repository (someone with merge access) proposing a pull request of their own that would specifically be responsive to this item raised by @crwatkins : https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702

Yet no-one else proposed a pull request to address that item.  This has been ongoing since October 2015 - #1109 - but discussions well before then have alluded to the need for a pull request on this issue as well (specifically, a pull request that deals with the issue that I and @crwatkins, and others, have raised, developed in such a way that it guards against potential security issues relating to "bitcoin banks, etc" without being exclusionary).

No pull request on this issue has been developed, other than the one that I have proposed, and from my observations, it seems like developing one is not a priority for the persons who have merge access in this repository.

I consider this a serious enough concern about the progress of what may end up in bitcoin.org in the future (though I am satisfied with the wallets that appear today) that I am now removing myself completely from further participation in the bitcoin.org repository and will be recommending to others that they take extra precautions in the future when utilizing wallets found at bitcoin.org 

I already recommend that people not use web wallets, but **_I will now further be recommending that mobile, desktop, and hardware wallets be assessed with particular caution by potential users of bitcoin.org due to the absence of proper criteria for assessment for risk in circumstances where a wallet is expressly designed as a portal to a bank or a banking network, or as a portal to an exchange or brokerage._**

These risks are real and they are not properly addressed.

Thank you, and this is my final statement in this repository.

**Pull request closed without merging**
