### PR TITLE
Remove simple bitcoin wallet

### PR DESCRIPTION
**Pull request by btcontract**
Simple Bitcoin Wallet has been in support mode for about a year now, I have no plans to develop it further and plan to remove it from all app stores soon so I guess it would be a good idea to also remove it from recommended wallets beforehand.

### CODE REVIEW

**Comment by crwatkins** [comment]
@btcontract LGTM, and I'm sorry to see it go, but I understand the support issue.  It's a good solid, as you say, "simple" wallet, and I think simplicity in features and UI often contributes more to security and privacy than fancy features.  Thanks for your contribution; looking forward to the next.

**Comment by wbnns** [comment]
@btcontract Thank you.

@crwatkins Just to confirm current status, do you approve d7f5aa2 and 37395e7 in this PR that were also in #2752?

**Comment by crwatkins** [comment]
@wbnns Sorry; just the removal.  I believe we are stilling waiting on the addition associated with #2752.

**Comment by wbnns** [comment]
@crwatkins No worries, ok, thanks.

@btcontract Can you please rebase with just a commit removing SBW as opposed to the current set of commits which rename Simple Bitcoin Wallet to BLW, adds additional translations, and then removes BLW + aforementioned newly added translations? Alternatively, we can take care of it if you'd like.

**Comment by wbnns** [comment]
Opened #2852; closing.

**Pull request closed without merging**
