### PR TITLE
Update exchanges.html 

### PR DESCRIPTION
**Pull request by Daunus**
Update changed domain for HardBlock hardblock.net to hardblock.com.au

### CODE REVIEW

**Comment by wbnns** [comment]
@Daunus 

Hello. We can see that the domain is redirecting to the one provided in this PR, however:

+ On the Twitter profile for the exchange, it appears that this change was made on the weekend of August 24th/25th, but the domain referenced on your GitHub profile is still the old one.
+ On the About page for the exchange, the Twitter profile link to your bio also still points to the old domain.
+ The email address on the About page still references the old domain.
+ Emails from the platform still come from the old domain.

This can be potentially confusing to users. This could also potentially open your users up to phishing campaigns with higher probabilties of success.

We recommend that you all make your domain name uniform.

**Comment by Daunus** [comment]
-My Github and my personal twitter profile should reference the new domain now.

The changes are still in progress but should be changed by end of week.

**Comment by vrsasi** [comment]
Hi, can you please add coinmate.io to your list?

**Comment by Daunus** [comment]
@vrsasi I'm not ower of this repo, I would think its better to open a new pull request for that.

**Comment by Daunus** [comment]
@wbnns 

Everything is updated to hardblock.com.au

twitter accounts, 
support email address listed on website.
sending domain from website.

**Comment by wbnns** [comment]
@Daunus 

Thank you.

**Pull request merged**
