### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by Komodorpudel**
Updated German translation.

My first pull request; let's see how it goes :D

### CODE REVIEW

**Comment by Komodorpudel** [comment]
@wbnns Alright, fixed some issued, but can you assist me with the rest?

**Comment by wbnns** [comment]
@Komodorpudel Heya! Sure, happy to help - congrats on your first pull request, by the way. :)

**Comment by wbnns** [comment]
@Komodorpudel Did you run `updatetx.rb` in `_contrib/`?

**Comment by wbnns** [comment]
@Komodorpudel Hey, since we spoke on Telegram, I'm going to close this and reopen a new PR, taking care of the remaining fixes. Thanks a bunch for helping get German up to date, and also helping coordinate stuff with the other languages!

**Pull request closed without merging**
