### PR TITLE
Change bitbox product listing to bitbox02-btc

### PR DESCRIPTION
**Pull request by TheCharlatan**

### CODE REVIEW

**Comment by crwatkins** [comment]
@TheCharlatan Thanks for the update.   Note that the description must be less than 320 characters.

Just to be clear, you don't intend to continue to list BitBox01 after BitBox02 is listed, correct?

**Comment by TheCharlatan** [comment]
Yes, we decided to replace the current listing of the BitBox01 with the BitBox02-BTC. I fixed the description as well.

**Comment by crwatkins** [comment]
@TheCharlatan Thanks.   The review will begin shortly.  Please review the [requirements here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and verify that you believe that BitBox meets them. 

Be sure to note the requirements on the images submitted.  Specifically:

* Screenshot: The png files must go in /img/screenshots, be 250 X 350 px and optimized with optipng -o7 file.png.

* Icon: The png file must go in /img/wallet, be 144 X 144 px and optimized with optipng -o7 file.png. The icon must fit within 96 X 96 px inside the png, or 85 X 85 px for square icons.

Also, please confirm that the web site confirms to the current HSTS requirements.

**Comment by crwatkins** [comment]
I have reviewed the BitBox02 based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the website that links to downloads does not support HSTS, I cannot recommend it for listing at this time.  Wallets need to be released for three months before listing.  I will be glad to recommend BitBox02 for listing on 25 December after the website issue is resolved.

Note that as a "hardware wallet," usually only the hardware and firmware components of the device are evaluated. Wallet software that runs externally to the device is usually not evaluated in the review.  In the past, this has been done when other (already listed) software wallets can be used in conjunction with the hardware (and in some cases the developer provided software did not meet listing criteria).  There is currently no third party software support for BitBox02 so the BitBox App was used in the evaluation, but not scored (the "scoring" was performed ignoring the app, similarly to all other hardware wallets listed).  As an aside, I would like to change this in the future and evaluate combinations of hardware and software as a wallet system.

I concur with the current scoring in 631a556.



## BitBox02
### Firmware version 4.1.1
### App Version: 4.13.1
### Review Version 2019110801

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was supplied by Shift Cryptosecurity to bitcoin.org at no cost

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available
  
  **PASS** Shift Cryptosecurity claims to have had independent audits by Census https://census-labs.com/ and Keylabs with no significant issues found.
  
  **NOTE** Beta program feedback was presented at https://medium.com/shiftcrypto/bitbox02-beta-program-what-we-learned-387f7fea858f
  
- No indication that users have been harmed considerably by any issue in
  relation to the wallet
  
  **PASS** No indication found using standard web searches with emphasis on bitcointalk.org, Reddit, and Twitter.

  
- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

	**PASS** No indication found.  Developers are very responsive.
	
- No indication that the wallet uses unstable or unsecure libraries

	**PASS** No indication.

- No indication that changes to the code are not properly tested

	**PASS** No indication.  Tests at https://github.com/digitalbitbox/bitbox02-firmware/tree/master/test

- Wallet was publicly announced and released since at least 3 months

	**FAIL** Released 25 September 2019 and eligible for listing on 25 December 2019 https://medium.com/shiftcrypto/its-happening-the-bitbox02-and-the-bitbox02-bitcoin-only-are-finally-here-55b9d6f09d0a

- No concerning bug is found when testing the wallet

	**PASS** No concerning bug was found
	
- Provides a bug reporting method on the website and/or in the app

	**PASS** App has a "Contact us" in the guide, which takes the user to https://shiftcrypto.ch/about/ which has a support email.

- Website supports HTTPS and 301 redirects HTTP requests

	**PASS** http://shiftcrypto.ch redirects to https
	
- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)
  
  **PASS** shiftcrypto.ch grade A
  
- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days
  
  **FAIL** No HSTS headers
  
- The identity of CEOs and/or developers is public

	**PASS** https://shiftcrypto.ch/about/

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **N/A** The hardware is not involved in choosing receiving addresses (but the app does display new addresses)

- Avoid address reuse by using a new change address for each transaction

  **N/A** The hardware is not involved in choosing change addresses (but the app does use new addresses)

- Uses deterministic ECDSA nonces (RFC 6979)

	**PASS** A transaction signed by BitBox02 was also signed with other RFC6979 complaint code and the witness data matched.

- User has access to private keys
- If private keys or encryption keys are stored online:

	**N/A**

  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.
- If user has exclusive access over its private keys:
  - Allows backup of the wallet

  	**PASS** Wallet requires backup to a micro SD card
  
  - Restoring wallet from backup is working

     **PASS** Wallet was successfully restored from SD card and from BIP39 phrase
  
  - Source code is public and kept up to date under version control system

      **PASS** https://github.com/digitalbitbox/bitbox02-firmware
      
- If user has no access to some of the private keys in a multi-signature wallet:

	**N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)
    
    **PASS** User interaction is required to sign a transaction
    
  - Protects the seed against unsigned firmware upgrades

  	**PASS** Only signed firmware upgrades are allowed
  
  - Supports importing custom seeds

  	**PASS**  A seed was imported successfully from another BIP39 wallet
  
  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element
    
    **PASS** https://github.com/digitalbitbox/bitbox02-firmware
    	
    **NOTE** The ATECC608A secure element is used to supplement random generation, password authentication, and secret storage.  Interface is documented in above source code.

Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

	**PASS** Hardware does not display received from address (nor does the app)

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)
  
  **FAIL** No HSTS support
  
- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

  	**PASS** Supports BIP32
  
  - Provides users with step to print or write their wallet seed on setup

 	 **PASS** During setup, backup to SD card is required
  
  - Uses a strong KDF and key stretching for wallet storage and backups

  	**PASS** Password stretching is designed to take 0.84 seconds on the secure element
  		
  	**NOTE** SD card backup is not encrypted (good)
  
  - On desktop platform:
    - Encrypt the wallet by default

    	**N/A**
    
- For hardware wallets:
  - Prevents downgrading the firmware

  	**PASS** Downgrades are not allowed

**Comment by TheCharlatan** [comment]
@crwatkins is your HSTS requirement intended for our link page on https://shiftcrypto.ch/start/ , or the actual download links, e.g. https://github.com/digitalbitbox/bitbox-wallet-app/releases/download/v4.14.1/BitBox-4.14.1-win64-installer.exe? 

We host our binaries on github on our wallet app repository release page: https://github.com/digitalbitbox/bitbox-wallet-app/releases . The firmware updates for the BitBox are deterministically built and bundled in the app by our developers. A firmware update is always shipped with a new release of our wallet app.

**Comment by crwatkins** [comment]
@TheCharlatan It's for https://shiftcrypto.ch

**Comment by crwatkins** [comment]
@TheCharlatan BitBox02 will be eligible for listing in a week.   How are the HSTS updates to the website progressing?

**Comment by crwatkins** [comment]
@TheCharlatan It's been over three months since BitBox02 has been released and it is now eligible for listing.  I will be glad to recommend BitBox02 for listing after the website HSTS issue is resolved.  How's that going?

**Comment by TheCharlatan** [comment]
The HSTS issue is still unresolved

**Comment by wbnns** [comment]
@crwatkins 

Thanks for reviewing. We should consider allowing them to proceed with this change, since there are several other wallets that are live and listed that do not support HSTS at present:

- BitBox01 (current listing)
- Bitcoin Knots
- BTC.com (wallet.btc.com)
- KeepKey

In other words, it doesn't seem fair/impartial if it's being enforced that a wallet can't be added or updated (despite satisfying all other requirements) unless it supports HSTS, while others are allowed.

**Comment by crwatkins** [comment]
@wbnns First I want to say that I'm probably as anxious as anyone to get this merged.

I consider this a new listing (and not just an update or an edit on an old one).  When I do reviews for new listings, I evaluate the wallet against our published criteria.  If we want to change a requirement to simply being a suggestion, I recommend that we remove the requirement and add the suggestion to our developer guide.  If we do that for HSTS, I would certainly recommend merging this PR.  However, while I suspect @luke-jr might support removing this requirement, I don't recall hearing that from any others.

I don't want to waste my time and annoy developers with requirements that we are willing to ignore.  As an aside, we regularly have requirements that we make exceptions for based on specific differences in the wallet.   An example would be allowing a bug reporting method in an app instead of on the web site when it made more sense that way in the past.

> In other words, it doesn't seem fair/impartial if it's being enforced that a wallet can't be added or updated (despite satisfying all other requirements) unless it supports HSTS, while others are allowed.

I don't agree with that logic.   Just because a particular requirement is being grandfathered or currently overlooked (perhaps based on lack of resources or because we currently have no requirements for periodic re-review) that should not exempt all other new listings from that requirement.  I believe that is sort of like saying that if one person runs a red light and doesn't get a ticket, then everyone should be able to run red lights from then on.

One could definitely argue that we should place tighter controls on existing listings and encourage periodic re-reviews, and that would be a good discussion in a separate issue or PR.  However, I will mention that I believe we have a fairly rich history of grandfathering existing listings.   I'm not even sure Bitcoin Core has always met all the requirements.

**Comment by wbnns** [comment]
@crwatkins 

Let's discuss in #3232.

**Comment by jstrnbrg** [comment]
Hi everyone, https://shiftcrypto.ch/ is now being served with HSTS. 
Would be great if the PR could be merged soon :) 

Thank you

**Comment by crwatkins** [comment]
@jstrnbrg That's great news!   I recommend that this PR be merged.

However, it should be noted that the HTTP headers on shiftcrypto.ch are malformed:

```
ETag: "5e26e95f-6636"
Access-Control-Allow-Headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-
Alive,X-Requested-With,If-Modified-Since,access-control-allow-credentials,Access-Control-Allow-Origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
```
There is a newline in between "Keep-" and "Alive" causing errors in the header parsing on the site.

Also, it would be good to submit the site for [HTTPS preloading](https://hstspreload.org/) as it [may soon become a requirement](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3111) and because it's just a good idea.

**Comment by crwatkins** [comment]
@jstrnbrg Thanks!

LGTM

**Review by kuanlim990 — COMMENTED** [review]
LNFj2hnY6RuSyk9qeCSkDJo49NUS7TNa46

**Pull request merged**
