### PR TITLE
 fix input parameter from Address to TXID

### PR DESCRIPTION
**Pull request by sahabi**
The parameter description should be for TXID not address.

### CODE REVIEW

**Comment by wbnns** [comment]
@sahabi 

Thanks for updating this and congrats on your first contribution to Bitcoin.org. Unless others object, this will be merged on Friday, December 29th, along with #2029 and #2030.

**Comment by wbnns** [comment]
@sahabi 

Hello, apologies, it looks like there is now a merge conflict - could you please update your PR (along with #2029 and #2030)? Once you do, we can merge this.

**Comment by wbnns** [comment]
@sahabi 

Hello, when you have time to fix the merge conflict, please feel free to resubmit this PR and we can get it merged for you.

**Comment by sahabi** [comment]
@wbnns my apologies, I did not notice this. I'll fix it.

**Pull request closed without merging**
