### PR TITLE
Refactor wallet listings and categories into individual web pages

### LINKED ISSUE #1661: Refactor wallet listings and categories into individual web pages
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **190,000 bits / ~$500 USD**

Last month (June 2017) the wallets page was one of our most viewed pages, with over 800,000 page views. 

Currently on the [wallets page](https://bitcoin.org/en/choose-your-wallet), information about each wallet only appears via a popup overlay when touched or clicked. As a result, this data isn't easily accessible to search engines, isn't linkable and also isn't shareable for anyone who wants to direct another user to information on Bitcoin.org about a particular wallet.

We can enhance this page by turning the popup overlays into individual wallet landing pages. This will in turn bring more traffic to Bitcoin.org because it will cause Bitcoin.org to show up on Google searches for keywords like "Copay bitcoin wallet" for example. It will also provide more utility to users because they will be able to link to and share these pages so that other users can more easily connect with wallet info.

Here's a basic example of what a landing page could look like (this would be at https://bitcoin.org/en/mobile/android/greenaddress):

image

Note that the categories should also be links. For example, https://bitcoin.org/en/mobile/android/ would show all of the mobile wallets for Android:

image

The main [wallets page](https://bitcoin.org/en/choose-your-wallet) would direct users to these newly linkable categories and individual wallet pages, that would soon after start showing up on search engines.

### PR DESCRIPTION
**Pull request by kuzzmi**
_First, sorry for such a big PR, I know it will not be that easy to review._

Here are some screenshots:

http://bitcoin.org/de/wallets/desktop/windows/bitcoincore/ will look like this:

image

http://bitcoin.org/de/wallets/desktop/linux/ will look like this:

image

---

I'll try to explain what was done to resolve #1661.

- [x] refactor wallets data to separate Jekyll collection, so it's easier to maintain wallets
- [x] reduce duplication of data of wallets' data
- [x] enable individual pages for each 3-tuple of `(platform, os, wallet)` and tuple of `(platform, os)`
- [x] add plugin to make permutations of translations and new pages 
- [x] create `_layouts/wallet-container.html`  `_layouts/wallet-platform-container.html`  `_layouts/wallet-platform.html` to support wallet and platform models and enforce re-usability of layout
- [x] create `_includes/layout/base/wallets-list.html` and `_includes/layout/base/wallets-menu.html` to enforce re-usability
- [x] preserve "rotation" of wallets on the platform pages
- [x] add links to wallet page to navigate to specific OS
- [x] refactor `_templates/choose-your-wallet.html` to use updated layouts
- [x] refactor wallet-related styles from `_sass/screen.scss` to a separate file
- [x] refactor wallet-related styles to use SASS features to enforce more transparent styling and styles generation
- [x] align wallet names in the translation to reduce confusion (walletbitcoinqt -> walletbitcoincore)
- [x] add icons for hardware and web to display on the wallet page
- [x] make some small code style fixes like removing of trailing spaces etc
- [x] rework YAML validation scheme
- [x] run `make travis` locally without errors'
- [x] add new Makefile script to test empty title tags

All feedback and comments are welcome.

If this works for you, here is my address:
1GomWkkJwg9WSqiGWjvMGUP3UFN3KVxfCw

### CODE REVIEW

**Comment by kuzzmi** [comment]
Ok, I see the problem with YAML schema. Will push the changes once complete.

**Comment by crwatkins** [comment]
@kuzzmi Looks like a lot of good work here!

Just a couple quick comments on first glance:

* The pages generated for wallets have empty html titles, e.g. `<title></title>`.  We probably want page titles.

* Have you tried on iOS?  The touch interface is a little strange.  Sometimes when clicking on one menu (e.g. Mobile) another menu will come down (e.g. Desktop).   Also, there is some awkward scrolling when making selections, and multiple scoring popups can appear up at the same time, sometimes popping under a previous popup.

**Comment by kuzzmi** [comment]
Thank you!

Unfortunately, I don't have any working iOS device :(
I'll update the titles and will take a look at the mobile version, but for iOS part, it will take a few days for me to find a device for debugging.

**Comment by crwatkins** [comment]
I've noticed the exact same behaviors on Android as on iOS (both using Chrome).

**Comment by kuzzmi** [comment]
Ok, I've found the issues you were talking about and will soon update this PR

**Comment by kuzzmi** [comment]
The last two commits should fix all the issues with working on wallets pages on mobile devices.

**Comment by crwatkins** [comment]
Thanks.  I think the issues I mentioned above are fixed.  I think there are still some issues with the transitions of the wallet listings.  For example, if on mobile you select Mac, then select Hardware, the wallet listing does not switch to hardware wallets.

**Comment by wbnns** [comment]
@kuzzmi Thanks for all of the hard work on this! I'm currently working through this review. Good progress so far. I'm seeing some layout issues (13" Macbook Pro, Chrome 59).

Example: https://bitcoin.cryptopelago.com/en/wallets/desktop/windows/

image

Also on the individual pages: https://bitcoin.cryptopelago.com/en/wallets/desktop/windows/bitcoincore/

image

I was able to reproduce these layout issues on my laptop Firefox 54 and Safari 10 as well.

If anyone is interested in a live preview, one is available here: https://bitcoin.cryptopelago.com/

**Comment by kuzzmi** [comment]
Thank you!
I will spin-up a VM with Mac to take a look. And push the changes back as soon as I can find them.

**Comment by kuzzmi** [comment]
This starts looking interesting. Tested all three:

image

image

**Comment by wbnns** [comment]
@kuzzmi Hey, sorry for the false alarm - after clearing my cache the issue was resolved. 👍

**Comment by schildbach** [comment]
Note that with this PR, the category order changed from "mobile desktop hardware web" to "desktop hardware mobile web". I think such a change should be in a separate PR and discussed out of the context of this PR.

I also think the row of categories should stay at the top, even if a wallets details are shown.

Icons now do not appear in a grid if there is an uneven number of wallets in the displayed category. For these cases, it looks a bit less nice imho.

**Comment by wbnns** [comment]
@kuzzmi Great job bringing all of this together. This should improve SEO on the wallets significantly and increase traffic to the site by making them accessible to search engines. People will also now be able to link others/share individual wallet links on Bitcoin.org across the web. 👍

Unless others object, this will be merged on Thursday, July 27th.

**Comment by kuzzmi** [comment]
@wbnns Thank you! I just realized, there are still some details left, like instructions about adding a new wallet.
Over the weekend I'll update the document to align it with a new way of submitting a wallet.

**Comment by wbnns** [comment]
@kuzzmi No prob! Good catch, thanks for thinking about the documentation to help others. I'll put this on hold until you're done.

**Comment by kuzzmi** [comment]
@wbnns apparently just a few changes were needed, should be fine now.

**Comment by crwatkins** [comment]
@kuzzmi In the instructions, I believe 

`Entries are ordered by levels and new wallets must be added after the last wallet on the ordered by levels and new wallets must be added after the last wallet on the same level.` 

is no longer relevant.  Correct?

**Comment by kuzzmi** [comment]
@crwatkins good catch, that's correct. I removed this part and added a bit clearer instructions on adding a wallet, including better explanation of what is **level** property in the wallet file.

**Comment by crwatkins** [comment]
Thanks.  That's much better.  It's interesting to see that GitHub can now display most of the wallet files as Markdown.  It's a shame that it won't render the wallets with the `DEFAULT` entries.  I'm not requesting a change, but if you had a simple way to fix that, it would be cool.

**Comment by kuzzmi** [comment]
@crwatkins Oh, I didn't see this. This is a positive side effect of this change. The problem is that the `DEFAULT` is used as a link/anchor feature from YAML to reuse some parts of the file. 

The reason why GitHub can render a wallet file as a table, is that GitHub is an official supporter of Jekyll, which uses own "extended" version of Markdown with a support of YAML. The fact is that this is not a valid Mardown file, but just a way, how GitHub can render files created for Jekyll.

There won't be an easy fix to this, as it will require to update the wallet structure, the schema, and the layout files.

**Comment by wbnns** [comment]
Unless others object, this will be merged on Sunday, July 30th.

**Comment by wbnns** [comment]
@kuzzmi Thanks again for all of the work on this! Here's the [transaction confirmation](https://live.blockcypher.com/btc/tx/695c1ac908675bafd8da8f56489ed14a3d70f0ca53202438bb50eab43c26a250/) for the bounty.

**Pull request merged**
