### PR TITLE
Remove Copay

### LINKED ISSUE #2843: Copay for Android not on Google Play
@matiu It seems that Copay is [no longer](https://github.com/bitpay/copay/issues/9423) on Google Play.  Can you explain why this is?

Would you prefer to remove Android from Copay support on bitcoin.org or fix the broken link on copay.io to Google Play or do you have another suggestion?

### PR DESCRIPTION
**Pull request by maxwellmons**
Closes #2843 assuming that if BitPay wallet for Android were to be added to the site, that it would be subject to a new PR and wallet review.

### CODE REVIEW

**Comment by crwatkins** [comment]
@maxwellmons thanks for the PR!  We appreciate the help.

I believe we should hold off on this for a few days to see if we can fix the root cause of the problem (a broken link).  For right now, the wallet is still good, meets all our requirements, and can still be built from source by anyone that wants to (and maybe even downloaded from a release location?), but we might have to eventually remove it if we think it will create too much confusion.

**Comment by crwatkins** [comment]
@matiu Any comments on this?  This doesn't solve the broken link on copay.io that we still reference in this listing.  Do you have plans to remedy that?

**Comment by matiu** [comment]
Hello,

Bitpay Wallet (available for iOS, Android, MacOS, Windows and Linux) is a branded version of Copay. Build from the same source code, using `npm run apply:bitpay` target instead of `npm run apply:copay` target. All the assets needed to build the app are on the repo.

I suggest modifying the name "Copay" to "Bitpay Wallet".

`copay` will only be distributed on major versions, and its aim is to serve as base to other open source wallet projects.  Copay cannot be published on Google Play because Google's policies.

**Comment by crwatkins** [comment]
Thanks @matiu for the explanation.  If I understand it correctly 
1. Copay wallet and Bitpay wallet have the same code base
2. The only differences are branding plus some added services in the Bitpay walllet
3. You are proposing "removing" the Copay listing and replacing it with a nearly identical Bitpay listing

Is that right?  If so, I believe the listing will remain the same except for:
1.  All instances of "Copay" will be replaced with "Bitpay"
2. The link to https://copay.io will be replaced with something like https://bitpay.com/wallet
*note some wallets provide direct links to downloads for each platform if you prefer*
3. A new icon image and a new screenshot image will need to be provide as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#adding-a-wallet)
4. You fee score **checkpassfeecontroldynamic** can be upgraded to **checkpassfeecontroloverride** if you agree with me that custom fees can be specified

On a related note, I found the recommended fees in the Bitpay wallet to be very high and I have reported it [here](https://github.com/bitpay/copay/issues/9526).

One other note is that I would recommend submitting bitpay.com to the [HSTS preload list](https://hstspreload.org) which is an optional criteria for listing that may soon become required (and just a good idea).

Based on my previous [review of Copay](https://github.com/bitcoin-dot-org/bitcoin.org/pull/888#issuecomment-115489156) I believe that Bitpay also meets our criteria and I recommend it for listing.  Would you like to open a new PR for that?  We would be glad to help, but we'll need a bit of direction (see above options) plus the images mentioned above.

**Comment by matiu** [comment]
thanks a lot @crwatkins !

>1. Copay wallet and Bitpay wallet have the same code base
>2. The only differences are branding plus some added services in the Bitpay walllet
>3. You are proposing "removing" the Copay listing and replacing it with a nearly identical Bitpay listing
>Is that right? If so, I believe the listing will remain the same except for:
>1. All instances of "Copay" will be replaced with "Bitpay"
>2. The link to https://copay.io will be replaced with something like https://bitpay.com/wallet
 >  _note some wallets provide direct links to downloads for each platform if you prefer_
3. A new icon image and a new screenshot image will need to be provide as specified [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#adding-a-wallet)
>4. Your fee score **checkpassfeecontroldynamic** can be upgraded to **checkpassfeecontroloverride** if you agree with me that custom fees can be specified.

yes, thanks a lot.

Bitpay Wallet current version: 
  1) has a "custom fee" feature, so the user can set the fee/rate to the amount he wants, and
   2) uses  bitcoind 0.17.1 `estimatesmartfee` for set the default fee levels (for 2, 6, and 24 nblocks).

> On a related note, I found the recommended fees in the Bitpay wallet to be very high and I have reported it [here](https://github.com/bitpay/copay/issues/9526).

ill follow on that issue.


> One other note is that I would recommend submitting bitpay.com to the [HSTS preload list](https://hstspreload.org) which is an optional criteria for listing that may soon become required (and just a good idea).

> Based on my previous [review of Copay](https://github.com/bitcoin-dot-org/bitcoin.org/pull/888#issuecomment-115489156) I believe that Bitpay also meets our criteria and I recommend it for listing. Would you like to open a new PR for that? We would be glad to help, but we'll need a bit of direction (see above options) plus the images mentioned above.

ok, we will check that.

**Comment by maxwellmons** [comment]
I think it might be a good idea to formally review the wallet again while this maintenance is being done as a standard procedure and a general safety precaution especially since the wallet was compromised a few months back.

**Comment by crwatkins** [comment]
NAK. The Android version of Copay still exists and still meets our listing criteria, even though it is only available as a direct .apk on GitHub and no longer in the Google Play store, so I do not recommend removing it.  

@matiu Could you open a new PR when you are ready with your new Bitpay collateral files?

If urgent action is deemed necessary prior to @matiu's new PR, I would recommend pointing our Android link to the releases on GitHub like we do for Green Address.

**Comment by matiu** [comment]
Thanks. Ill send the PR in the next few days.

**Comment by matiu** [comment]
copay.io is no longer been maintained and the URL now redirects to the proyect's github page.

bitpay.com/wallet is the main wallet's site now.

thanks.

**Comment by maxwellmons** [comment]
@matiu Thank you for the notice. @crwatkins I have renamed and rebased my pull request to remove Copay. The bitcoin.org website is a very popular website. I think we should merge this and remove Copay without further delay until a new pull request is made to add the BitPay wallet. All of the links are broken now instead of just one. You said it was not a problem to have the broken link for Android and closed #2843 because people can look for the apk on GitHub. This will not be possible for iOS users, who also now have a broken link. Or Windows phone users. Please also consider that many people are also going to have no clue what to do when they click a link on bitcoin.org, and end up on the homepage of a GitHub repository. How many people who aren't developers are actually going to try to build their wallet from source?

**Comment by crwatkins** [comment]
Concept ACK.   Thanks!

Could you update this PR to also remove the image collateral as well as any associated translations?  Thanks.

**Comment by matiu** [comment]
Ill open a new PR for bitpay wallet. Thanks.

**Comment by maxwellmons** [comment]
@matiu Thank you. @crwatkins I have removed the additional image collateral and have also checked to make sure there were no other associated translations just now. Thank you.

**Comment by crwatkins** [comment]
@maxwellmons Each wallet listing has a single icon along with one or more screenshots as described [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#adding-a-wallet).   We also need to remove the screenshot.  Thanks!

@matiu Thanks Matias, it was noble to maintain the reference implementation this long!  I thought the branding, including the name and logo was pretty cool.

**Comment by maxwellmons** [comment]
@crwatkins I have removed the screenshot just now. Thank you.

**Comment by crwatkins** [comment]
ACK 257c730.

**Comment by matiu** [comment]
@crwatkins would it be enough I copy https://github.com/bitcoin-dot-org/bitcoin.org/pull/2712/files for submitting the new PR for bitpay wallet?

**Comment by crwatkins** [comment]
I *think* so along with the changes I mentioned above including the links and icon and screenshots.  

Any update on the fee issue?

**Comment by matiu** [comment]
@crwatkins was mentioned earlier:

Bitpay Wallet current version:

1. has a "custom fee" feature, so the user can set the fee/rate to the amount he wants, and
2. uses  bitcoind 0.17.1 `estimatesmartfee` for set the default fee levels (for 2, 6, and 24 nblocks).

Bitpay WALLET does not have a custom fee estimation algorithm, it uses Bitcore Core's algorithm thru the RPC interface.

**Pull request merged**
