### PR TITLE
Correct list bullet overflow

### PR DESCRIPTION
**Pull request by jdabs**
Added padding to the ul so that the bullets aren't half-hidden behind the container. Not the most eloquent and would like feedback if there's better.
bullets-cut-off

### CODE REVIEW

**Comment by wbnns** [comment]
@jdabs Could you please let me know what browser version and OS you're running so we can try to replicate the issue?

**Comment by jdabs** [comment]
@wbnns you're fast 👍 I am seeing this on Chrome 68 on Win7

**Comment by wbnns** [comment]
@jdabs Ok, thanks - we'll check it out.

**Comment by wbnns** [comment]
@jdabs It looks like this change, as-is, breaks the alignment in Firefox. You may be able to unset the padding and overflow and set `list-style-position: inside;` on `.devprojectlist` to fix.

If you have any questions, please let us know.

**Comment by jdabs** [comment]
Ok, thanks. I am setting up a more complete local clone environment and will send the changes in an update.

**Pull request closed without merging**
