### PR TITLE
Add "CoolWallet" to wallets

### PR DESCRIPTION
**Pull request by yobum**

### CODE REVIEW

**Comment by crwatkins** [comment]
@yobum Thanks for the submission.  As you may have noticed in the failed Travis run, you will need to include a screenshot as described [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#adding-a-wallet).

**Comment by crwatkins** [comment]
@yobum Is the firmware in the device open source?

**Comment by yobum** [comment]
@crwatkins The firmware in the device is not open source yet. But the application part is open source.
https://github.com/CoolBitX-Technology

**Comment by wbnns** [comment]
@crwatkins Thanks for spending the time to review everything in-depth.

**Comment by crwatkins** [comment]
I would welcome further discussion of the criteria and the results either here or in a new issue.

**Comment by crwatkins** [comment]
@ThomasMaxon Sounds good!  I'll try to clarify my personal interpretation of the requirement.  I believe that the requirement is only that a sufficient specification exists and not necessarily that blackbox testing is actually performed.  This is consistent with the requirement for software wallets that source code be open, but not necessarily requiring a formal review of that code.  However producing such a testing report based on the specification is a very strong indication that such a specification is sufficient.

The Edge wallet was reviewed recently.  Edge provided these [security reviews](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2368#issuecomment-392300337).

**Comment by ThomasMaxon** [comment]
> I don't believe that the hardware meets the open source/detailed specification criteria. CoolBitX is currently investigating possible options for meeting the criteria. I also strongly request comments and input from the community on what the correct level of detail is that is required to meet this criteria. My current metric is quite personal: I don't believe that I could test the hardware given the current level of details in the specifications. If others think that they can, it is very important to hear from them.

We will be going live with open sourced algorithms and more details about missing specs. Specifically, some of the missing hash algorithms the SE employs. 

> HSTS needs to be improved on web sites.
&
> FAIL No HSTS on www.coolbitx.com

We've been long planning to go live with our corporate website at coolbitx.com which will have HSTS.  It will be live next week. 

> The app reuses change addresses and should be corrected.
We've fixed this issue with our most recent app's update. 

> The hardware appears to not sign with deterministic signatures. It's hard to verify that I have not made an error without being able to check the source. This points out how much more difficult it is to perform adequate review and how much more effort needs to go into evaluations when functions are not transparent.
You can verify the HD by compare the address in the app and on this site http://bip32.org/.


> CoolBitX has two similar products, the "CoolWallet" and the newer "CoolWallet S". The issue of confusion between the two is noted below should be resolved. I don't know how CoolWallet users are expected to find compatible apps for their hardware.

We've listed the CoolWallet (1st gen) on our website https://coolwallet.io/1st-generation/ with links to download the app from Google Play and the App Store. Likewise, we are actively taking over the amazon account selling the CoolWallet from our old resellers. We will promote this channel and clarify all marketing materials about the distinctions. 

Over time, we'll showcase the CoolWallet even more and actively support the wallet. 

> This pull request is missing scoring for the privacy subcategories. While this is not normally needed for hardware-only wallets, this listing also reflects the app software. The subcategory scoring should be added.

We welcome the community to weigh in on this.

**Comment by ThomasMaxon** [comment]
> I don't believe that the hardware meets the open source/detailed specification criteria. CoolBitX is currently investigating possible options for meeting the criteria. I also strongly request comments and input from the community on what the correct level of detail is that is required to meet this criteria. My current metric is quite personal: I don't believe that I could test the hardware given the current level of details in the specifications. If others think that they can, it is very important to hear from them.

We will be going live with open sourced algorithms and more details about missing specs. Specifically, some of the missing hash algorithms the SE employs. 

> HSTS needs to be improved on web sites.
&
> FAIL No HSTS on www.coolbitx.com

We've been long planning to go live with our corporate website at coolbitx.com which will have HSTS.  It will be live next week. 

> The app reuses change addresses and should be corrected.
We've fixed this issue with our most recent app's update. 

> The hardware appears to not sign with deterministic signatures. It's hard to verify that I have not made an error without being able to check the source. This points out how much more difficult it is to perform adequate review and how much more effort needs to go into evaluations when functions are not transparent.

You can verify the HD by compare the address in the app and on this site http://bip32.org/.


> CoolBitX has two similar products, the "CoolWallet" and the newer "CoolWallet S". The issue of confusion between the two is noted below should be resolved. I don't know how CoolWallet users are expected to find compatible apps for their hardware.

We've listed the CoolWallet (1st gen) on our website https://coolwallet.io/1st-generation/ with links to download the app from Google Play and the App Store. Likewise, we are actively taking over the amazon account selling the CoolWallet from our old resellers. We will promote this channel and clarify all marketing materials about the distinctions. 

Over time, we'll showcase the CoolWallet even more and actively support the wallet. 

> This pull request is missing scoring for the privacy subcategories. While this is not normally needed for hardware-only wallets, this listing also reflects the app software. The subcategory scoring should be added.

We welcome the community to weigh in on this.

**Comment by crwatkins** [comment]
> The hardware appears to not sign with deterministic signatures. It's hard to verify that I have not made an error without being able to check the source. This points out how much more difficult it is to perform adequate review and how much more effort needs to go into evaluations when functions are not transparent.
> 
> You can verify our HD status by comparing the address in the app and on this site http://bip32.org/.

@ThomasMaxon the requirement is not related to BIP32.  See RFC6979.

**Comment by ThomasMaxon** [comment]
@crwatkins You are correct. The CoolWallet is not using RFC6979, we are using TRNG instead. Thoughts?

**Comment by crwatkins** [comment]
The use of RFC6979 is well accepted and expected by the community.  All wallets that we have reviewed in the last three years have implemented deterministic signatures (using RFC6979). The only downside to RFC6979 that I know of is a performance cost  that has been estimated to be about 10%.

In the case of Coolwallet, this is particularly important.  As a reviewer, and a user, I currently cannot confirm using blackbox testing the quality of the nonce being used.  Using RFC6979 mitigates that concern.  Likewise, a user cannot confirm that information is not being leaked, either inadvertently or maliciously, in signatures if deterministic signatures are not used.

**Comment by ThomasMaxon** [comment]
In the abstract of the RFC6979 article here: https://tools.ietf.org/html/rfc6979

"... Deterministic signatures retain the cryptographic security features associated with digital signatures but can be more easily implemented in various environments, since they do not need access to a source of high-quality randomness."

In the CoolWallet, we do have high-quality randomness; the Secure Element has built-in TRNG. We also use a SP800-90A DRBG to speed up random number generation. It is a common practice to chose the highest quality randomness possible, correct?

But like you said, this can only be confirmed by a white box review.

**Comment by crwatkins** [comment]
> It is a common practice to chose the highest quality randomness possible, correct?

That's a hugely open ended and leading question, but for the purpose of this comment, I'll assume you are asking in the context of the nonce in  an ECDSA signature in an HD Bitcoin wallet and by "quality" you are referring to entropy, and  perhaps more specifically "min-entropy" which I'll generically refer to as "entropy."

The entropy of the nonce in your wallet depends on the hardware which you are using and the amount of entropy which you harvest, and your method and your implementation (which I have no knowledge of) and the correctness of it; whether you intentionally or inadvertently lose any entropy in the process.  Using a deterministic nonce depends on the entropy of your private key.  The entropy of the private key is determined by the entropy of the seed of the wallet (according to BIP32).  If I provided the seed, then that entropy is up to me.  If I (much more likely) allowed the wallet to provide the seed, then again, the entropy of that seed totally depends upon your implementation (which, again, I have no knowledge of).  Assuming you provide the same entropy in both cases (with no implementation impairments) then there would be roughly no difference in the entropy, and thus the "quality," of the nonce by generating it deterministically.

**Pull request closed without merging**
