### PR TITLE
Add GET BlockHashByHeight

### PR DESCRIPTION
**Pull request by roshii**
I'm not sure if formatting is correct but content should be :)

### CODE REVIEW

**Comment by roshii** [comment]
OK, formatting isn't correct, links to the newly created page are broken. I just don' t get what I missed but I'll be happy to fix this if anyone can give me a hint :)

**Comment by wbnns** [comment]
@roshii 

Thanks for your help. Looks like there are multiple issues, but you can run `git grep` from the command line on another similar term in the root directory of your local copy of the repository to learn more about how it has been added and to get some hints on next steps.

Also, if you haven't already done so, we recommend reading the overview on [improving developer documentation](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/contributing-to-developer-documentation.md) and [setting up an environment](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/setting-up-your-environment.md) to test and preview your changes locally.


If you have any other questions, please let us know.

**Comment by roshii** [comment]
@wbnns

I don't know if were tracking new commit or awaiting a comment from me. In anycase I think above commits should fix issues.

Let me know

**Comment by wbnns** [comment]
Unless others object, this is scheduled to be merged on Monday, July 29th (will squash commits at that time).

**Pull request merged**
