### PR TITLE
Allow to set styles for alert banner

### PR DESCRIPTION
**Pull request by saivann**
README: https://github.com/saivann/bitcoin.org/tree/alertclass#alerts

Screenshot of pre-selected colors:

capture du 2015-07-04 21 48 50

### CODE REVIEW

**Comment by saivann** [comment]
Note; This pull request also sets the "warning" (orange / medium severity) class to the current alert, as suggested by @harding in https://github.com/bitcoin-dot-org/bitcoin.org/issues/934#issuecomment-118561622

**Comment by harding** [comment]
LGTM.  Thanks!

**Comment by harding** [comment]
@saivann I thought things had improved, but we just had another 3-block fork.  I think the banner should stay at red for now.  (Sorry for changing my mind.)

**Comment by saivann** [comment]
@harding That only sounds appropriate, I've set back the red alert class for the current alert at the same time that I had to rebase the commit to fix merge conflicts. So after merging, there should be no difference on the website, and it'll be easy to change the styles of the alert banner in the future.

In the absence of critical feedback, this pull request will be merged on July 6th.

**Pull request merged**
