### PR TITLE
exchanges: Re-add bitFlyer (JP, EU)

### PR DESCRIPTION
**Pull request by kobake**
bitFlyer(JP, US, EU) has restarted accepting new user since July 2019.

## Ref
https://twitter.com/bitFlyer/status/1146216150230917121
> 2019-07-03
> We would like to announce that new account creation has resumed. We sincerely apologize for the inconvenience incurred by anyone considering becoming a new customer of our services during this time.

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
LGTM.

**Comment by kobake** [comment]
@wbnns 
Hi, Could you let me know when are you planning to check and merge this PR officially, please?

I'll contribute something additional if necessary.

**Comment by wbnns** [comment]
@kobake 

Hello, we don't have an exact estimate, however, there's only one exchange in the queue before bitFlyer that's currently in the process of being reviewed at the moment. Most likely by the middle of next week, we'll be able to complete the review of bitFlyer.

**Comment by kobake** [comment]
@wbnns 
OK, I understood current status. Thanks!

**Comment by wbnns** [comment]
Unless others object, this is scheduled to be merged on Monday, July 29th.

**Comment by kobake** [comment]
No problem. Thanks for information!

**Comment by kobake** [comment]
I could see your update!
Thanks for your comment, sharing information, review, deploy, etc.
I appreciate your cooperation. 👍

**Pull request merged**
