### PR TITLE
Adding Android as supported OS for breadwallet

### PR DESCRIPTION
**Pull request by jmacwhyte**
The Android version of breadwallet came out a couple months ago.

### CODE REVIEW

**Comment by jmacwhyte** [comment]
Is this repo still maintained? Who is in charge of merging PR's? There seems to be a pretty big backlog.

**Comment by achow101** [comment]
The repo and website are still maintained, just a little slow to update. @Cobra-Bitcoin does most of the merging and such with input from some other people. It's all listed on the about page.

**Comment by Cobra-Bitcoin** [comment]
With stuff concerning wallets, I usually wait until @crwatkins leaves a comment to decide whether to merge or not (he's the wallets maintainer).

There's also not much space available for Android wallets, we're already listing way too many, that's why I'm holding off on merging this until I know what @crwatkins thinks about it.

**Comment by crwatkins** [comment]
I had reviewed screen shots, the source code, and the submitted scoring criteria, but I was having trouble finding a device to test on.  My current device is running Android 5.  Another device I tried wouldn't let me set a PIN (and thus breadwallet wouldn't run).  A more recent device had some strange PIN interaction with the device (which I have reported to support).  It hasn't been for a lack of trying.
I just tried a device that breadwallet seems to be happy with and had the same excellent experience as breadwallet on iOS (except for an occasion message from Android concerned that breadwallet was not responding and wondering if I wanted to wait, which I did).

I'm happy to recommend adding Android to the breadwallet listing.  I concur with the current scoring in the PR.

**Comment by jmacwhyte** [comment]
Thank you for the thorough review!

**Comment by jmacwhyte** [comment]
@Cobra-Bitcoin What do you think? Could we merge? It would fill out the second row of Android wallets ;)

**Pull request merged**
