### PR TITLE
Remove circle

### LINKED ISSUE #1426: Sounds like circle is discontinuing their Bitcoin offerings and should be removed.
http://www.wsj.com/articles/bitcoin-powerhouse-will-pull-the-plug-on-bitcoin-1481104800

### PR DESCRIPTION
**Pull request by achow101**
Closes #1426

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by harding** [comment]
Tested working.  (I'm not familiar enough with them to argue for or against removal.)

**Comment by crwatkins** [comment]
@achow101 thanks for the PR!  Could you also remove img/screenshots/circle.png in this PR?

**Comment by achow101** [comment]
@crwatkins done

**Comment by crwatkins** [comment]
Thanks @achow101 

I recommend that we remove Circle from the wallet listings via this PR.

**Pull request merged**
