### PR TITLE
Added a new Bitcoin forum and eliminated two disused

### PR DESCRIPTION
**Pull request by TheBitcoin**
First of all, I remove in this request two forums of community, the first is forobtc.com that don't have any hosting or website running. The second one is forobitco.in only used at now for spaming cloud mining, faucet referals and tiered link building.
The second thing I did was add a new alternative forum in Spanish about bitcoin and other decentralized applications.

### CODE REVIEW

**Comment by jrmithdobbs** [comment]
Is there an English translation of their FAQ? I think maybe inclusion on this list is where I should have started with the CoC request.

bitcoin.org should not endorse community forums that support or harbor abusive community members and I would like to be able to read this forum's policies before commenting on it specifically.

**Comment by jrmithdobbs** [comment]
Cc @sipa @petertodd: hopefully this is a more constructive attempt?

**Comment by escalicha** [comment]
I don't understand what you are trying to mean.
Try to write it as simple as possible because some community members like me are not English native speakers.

**Comment by jrmithdobbs** [comment]
Sure. I am asking for a translation of the site's frequently asked questions page.

In order to review policies concerning harassment and discrimination.

**Comment by luke-jr** [comment]
@jrmithdobbs Excluding forums that are generally comprised of abusive people is one thing. Excluding forums because their policies are more inclusive (eg, of abusive people) is another.

**Comment by MarcoFalke** [comment]
LGTM 356454d

**Comment by jrmithdobbs** [comment]
@luke-jr I think I generally agree but since this, in particular, is a Spanish language site I thought a translation of their basic FAQ would be helpful for review purposes. But I do get your point.

Can someone who speaks Spanish vouch that it doesn't appear to be just a huge bundle of threads insulting other parts of the community/etc?

**Comment by jrmithdobbs** [comment]
If so then :+1:

**Comment by escalicha** [comment]
If you want  @jrmithdobbs just use the search option: https://forobits.com/t/faq-guias/5 but its the same of the https://meta.discourse.org/guidelines
This is a spanish forum, you can use Google Translate or another tools to translate to see the community.

**Comment by TheBitcoin** [comment]
Hello @harding, any news about this pull request? This pull request have two month and half opened.

**Comment by TheBitcoin** [comment]
update: forobitco.in and http://www.forobtc.com seems that they will not run anymore. Both servers down.

**Comment by jtimon** [comment]
The two older forums don't work and the new one does.
ACK 356454d

**Comment by Mirobit** [comment]
ACK. Old ones are offline.

**Comment by wbnns** [comment]
Unless others object, this will be merged on Sunday, December 11th.

**Pull request merged**
