### PR TITLE
Inclusion of a link to the list of commercial establishments.

### PR DESCRIPTION
**Pull request by Cmte-Kirk**
Inclusion of a link to the list of commercial establishments that accept Bitcoin as a means of payment.

### CODE REVIEW

**Comment by wbnns** [comment]
@Cmte-Kirk 

Hello, thank you. We were reviewing this potential new resource and noted the following translated excerpt, near the top of the page:

>Dell and Microsoft: The two world-renowned companies in the technology market accept payment with crypto-coins. In Brazil and worldwide, it is possible to buy software and hardware from these companies with Bitcoins.

We're not sure this is an accurate statement. Could you please elaborate?

**Comment by Cmte-Kirk** [comment]
> @Cmte-Kirk
> 
> Hello, thank you. We were reviewing this potential new resource and noted the following translated excerpt, near the top of the page:
> 
> > Dell and Microsoft: The two world-renowned companies in the technology market accept payment with crypto-coins. In Brazil and worldwide, it is possible to buy software and hardware from these companies with Bitcoins.
> 
> We're not sure this is an accurate statement. Could you please elaborate?
> 
> Also, the top navigation is overflowing onto the logo:
> 
> image

Hello, @wbnns, thank you for review our page. 

Sorry about the erros , we have fixed the top bar menu. And we reviewed the microsoft and Dell Info:

Microsoft says in this page that is possible to pay with bitcoin:
https://support.microsoft.com/en-us/help/13942/microsoft-account-how-to-use-bitcoin-to-add-money-to-your-account

But we have tested now, and it's not working anymore, so, we have deleted this info from the page.

Thanks again, let me know if there is any change that we have to do.

**Comment by Cmte-Kirk** [comment]
Hello, @wbnns, thank you for review our page. 

Sorry about the erros , we have fixed the top bar menu. And we reviewed the microsoft and Dell Info:

Microsoft says in this page that is possible to pay with bitcoin:
https://support.microsoft.com/en-us/help/13942/microsoft-account-how-to-use-bitcoin-to-add-money-to-your-account

But we have tested now, and it's not working anymore, so, we have deleted this info from the page.

Thanks again, let me know if there is any change that we have to do.

**Comment by wbnns** [comment]
@Cmte-Kirk 

Thank you for the update. Upon additional review, we would be unable to merge this as a result of #2697, which was related to a similar PR involving Livecoins, #2670.

The post that is linked to in this PR is helpful and provides insightful guidance on places people can spend bitcoin in Brazil, however, the site is a news resource, which relates it to issues that were discussed when #2697 was opened earlier last year.

It wouldn't be fair to other news-related resources that are no longer on the site if this were included.

**Pull request closed without merging**
