### PR TITLE
Add Eclair Mobile

### PR DESCRIPTION
**Pull request by sstone**
Eclair Mobile is an open-source, SPV mobile wallet that can be used as a regular Bitcoin wallet and also supports connecting to the Lightning Network.

It implements BIP39, BIP32 and uses p2sh-of-p2wpkh addresses, which are rotated automatically.

It has been been available on Google Play since April 2018.

### CODE REVIEW

**Comment by Vant13425** [comment]
body can’t be blank

**Comment by sstone** [comment]
> body can’t be blank

Can you be more specific ?

**Comment by wbnns** [comment]
@sstone 

Hello, thanks for trying to help. Looks like it may have just been comment spam, though (the user just posted the same message in another thread).

**Comment by sstone** [comment]
We don't support yet RBF/CPFP but it's on our roadmap (we should have RBF soon).
We use Electrum servers to download and verify headers and wallet transactions, and also to broadcast wallet transactions.

**Comment by sstone** [comment]
Thanks @crwatkins , https://acinq.co now supports HSTS.

**Comment by crwatkins** [comment]
@sstone Thanks; the HSTS LGTM.  I recommend Eclair Mobile for listing.

I concur with the scoring in 8d678c9.  I recommend this PR for merging.

**Comment by wbnns** [comment]
This is scheduled to be merged on Friday, February 8th.

**Pull request merged**
