### PR TITLE
Add BlockSettle terminal

### PR DESCRIPTION
**Pull request by BlockSettle**
@wbnns, @crwatkins, please find our PR ready for review

### CODE REVIEW

**Comment by crwatkins** [comment]
@BlockSettle Thanks for the submission.   Looks interesting!  I'll get back to you soon.

**Comment by BlockSettle** [comment]
@crwatkins Please let us know if there is anything further we can do to support your efforts. Keen to hear back.

**Comment by crwatkins** [comment]
@BlockSettle Absolutely!   I had some unexpected scheduling issues and the delay is all on me.

**Comment by BlockSettle** [comment]
@crwatkins Thank you. We're just about done with PSBT and should be ready for review.

**Comment by crwatkins** [comment]
@BlockSettle I've been looking at 0.90.7.  Is that where I should be right now?

**Comment by BlockSettle** [comment]
Please base your review on bs_dev (https://github.com/BlockSettle/terminal/commits/bs_dev). We aim to merge this branch to master this week.

**Comment by crwatkins** [comment]
I have to say that attempting to type the root private key (by the way, I'm not sure you should be abbreviating that to "RPK" in the GUI; it took me a bit to figure out what it meant) in was quite a challenge with it being random letters.   My fingers wanted to type in words, so I kept getting checksums wrong, but perhaps that's me.  Is it anticipated that users will be saving that to disk instead of writing it down?  When I tried to restore a wallet, I got the message 
```
Import wallet failed with error:  Internal error
```
Can you suggest where to find more information?

**Comment by goatpig** [comment]
> by the way, I'm not sure you should be abbreviating that to "RPK" in the GUI; it took me a bit to figure out what it meant
> Import wallet failed with error:  Internal error

Could you tell me what branch/commit did you build?

> was quite a challenge with it being random letters.

This the same custom alphabet Armory uses for its printed backups. It does not carry digits nor caps, and a few letters are kept out as well. It may be unpalatable but it reduces the chances at confusing characters when users write down their seed. It also carries a unique look which tends to help users identify what software generated the seed.

In general users are expected to write the seed down. Printing is more convenient but is unlikely there is such a thing as a printer without loads of non volatile memory these days, so it is preferable that users write their seeds down, hence a standard that demands user attention and reduces the potential for human error was picked.

There should also be a dialog to input the seed back into the wallet in order to test the backup prior to moving forward with wallet creation.

> Can you suggest where to find more information?

What operating system are you on? You want to look the signer log (~/.local/share/blocksettle/bs_signer.log on linux systems) for more informations.

**Comment by crwatkins** [comment]
> Could you tell me what branch/commit did you build? Also are you trying to import a wallet you just created?

I was still on 0.90.7.  Yes; that was the problem, see below.

> This the same custom character set Armory uses for its printed backups. 

Yep;  It's been a while since I've done an Armory restore!

> What operating system are you on? You want to look for the signer log (~/.local/share/blocksettle/bs_signer.log on linux systems) for more informations.

Linux.  That file made the issue obvious.  I was trying to clone an existing wallet.  It worked after I deleted the first wallet.
(The error message could be better :) )  Thanks.

**Comment by goatpig** [comment]
> Linux. That file made the issue obvious. I was trying to clone an existing wallet. It worked after I deleted the first wallet.
(The error message could be better :) ) Thanks.

Thanks for the report, JIRA ticket has been made to deal with that.

**Comment by crwatkins** [comment]
Thanks.   Perhaps someone might actually attempt to do that (if they forget their password) before deleting the old wallet.

**Comment by crwatkins** [comment]
Could you point me to any information on the architecture of how the terminal interfaces to the signer?  (I hope I have the terminology correct there)

**Comment by goatpig** [comment]
There is no explicit documentation on that front, I could explain it to you here or conjure a write up if you'd like.

The thousand foot view is that the terminal is the GUI and carries address hashes for blockchain lookups, the signer runs the actual wallet code. The signer listens on incoming connections over a socket and enforces a 2 way authenticated encrypted connection. Depending on how the signer is spawned, different strategies are implemented to share authentication keys.

**Comment by crwatkins** [comment]
That's good for now, thanks!

**Comment by crwatkins** [comment]
Where can I see a list of my transactions in the bitcoin wallet?   I have numerous transactions in the wallet I imported, and I see the addresses used, but there are no transactions displayed on the TRANSACTIONS tab with "All Wallets" selected.  Am I misunderstanding the function of that tab?

**Comment by goatpig** [comment]
> I was still on 0.90.7. Yes; that was the problem, see below.

What version are you on now? If you're looking for updates from the PPA, we can't push builds there because the more recent packages exceed the 1GB limit. We're looking to address the build process to reduce that but for now you would have to grab updates from the release page: https://github.com/BlockSettle/terminal/releases.

> Where can I see a list of my transactions in the bitcoin wallet? 

This is the right tab. It is likely you're not connected to the blockchain service. There is a Bitcoin icon at the bottom right corner of the terminal. If it's greyed out, the connection is not established. I suggest you update to 0.90.9 and try again, we cycled the server authentication keys since 0.90.7.

You could also setup your own DB if you're trying things out on the testnet (https://github.com/BlockSettle/BlockSettleDB/releases). You will need a local instance of a Core full node. Mainnet is pretty beefy however atm, the terminal can't work with the lighter Armory database yet.

**Comment by crwatkins** [comment]
I’m running 0.90.9 from the tagged release repo. Will check the connection.

**Comment by crwatkins** [comment]
I've sent screenshots to the support address.   We can take this debugging offline so those folks that are interested in the review won't unsubscribe because of all the debugging going on.

**Comment by crwatkins** [comment]
I have reviewed the Bitcoin wallet component of the BlockSettle Terminal based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the wallet is new and has received very little feedback, and there is an issue with HSTS on the BlockSettle website I cannot recommend it for listing at this time. I will be glad to recommend BlockSettle for listing when these items are resolved.  I recommend revisiting this listing in three to six months.   

I concur with the scoring in 489822d, however I believe the **user: beginner** tag should be removed.   We don't yet have a formal definition for that tag, but we currently base it on this [discussion](https://github.com/bitcoin-dot-org/Bitcoin.org/issues/3022) and I believe this wallet is more suited for experience users.

---

## BlockSettle
### Version 0.91.2
### Review Version 2021010501

The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** BlockSettle Terminal is a full trading terminal with a Bitcoin wallet component.  Only the wallet component of BlockSettle Terminal was reviewed.  Specifically, none of the trading components, nor any of the token components were reviewed.

**NOTE** Architecture and code is based on Armory, a wallet with a long listing history.

Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

  **FAIL**  Very little feedback on Bitcointalk, Reddit, Twitter, or by using generic web searches

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

  **PASS** No indication using standard web searches

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

  **PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

  **PASS** No indication.  Based on the Armory code.

- No indication that changes to the code are not properly tested

  **PASS** https://github.com/BlockSettle/terminal/tree/master/UnitTests

- Wallet was publicly announced and released since at least 3 months

  **PASS** Released 27 May 2020 https://blocksettle.com/news/terminal-release

- No concerning bug is found when testing the wallet

  **PASS** No concerning bugs found

- Provides a bug reporting method on the website and/or in the app

  **PASS** Help->Support in the app and under Contact on web site

- Website supports HTTPS and 301 redirects HTTP requests

  **PASS** https://blocksettle.com

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

  **PASS** Rating: A

- Website serving or linking to executable code or requiring authentication uses HSTS
  - Existing listings: With a max-age of at least 180 days
  - New listings: With a max-age of at least 1 year, and preload and includeSubDomains directives to qualify for browser preload list inclusion
  `e.g. Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`


  **FAIL** No HSTS headers https://blocksettle.com

- The identity of CEOs and/or developers is public

  **PASS** BlockSettle is a licensed payment service provider in Sweden

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

  **PASS** Displays a new address each time requested

- Avoid address reuse by using a new change address for each transaction

  **PASS** Uses new change address for each transaction

- Uses deterministic ECDSA nonces (RFC 6979)

  **PASS** Uses Armory code for deterministic signatures

- User has access to private keys for all major components of the wallet

  **PASS**

- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

  **N/A**

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

  **PASS** Allows writing down of a "private root key" or downloading digital or PDF backups

  - Restoring wallet from backup is working

  **PASS** Wallet was restored successfully using "private root key"

  - Source code is public and kept up to date under version control system

    **PASS** https://github.com/BlockSettle/terminal

- If user has no access to some of the private keys in a multi-signature wallet:

  **N/A**

  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet

- For hardware wallets:

  **N/A**

  - Uses the push model (computer malware cannot sign a transaction without user
    input)
  - Protects the seed against unsigned firmware upgrades
  - Supports importing custom seeds
  - Provides source code created for all open components and provides detailed specification for blackbox testing of
    any closed-source secure elements

Optional criteria (some could become requirements):

- Does not show "received from" Bitcoin addresses in the UI

  **PASS** Does not

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)

  **FAIL** Not included https://blocksettle.com

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

    **PASS** Supports BIP32 with BIP44, BIP49, and BIP84 paths
  - Provides users with step to print or write their wallet seed on setup

  **PASS** Allows copying of "root private key"

  - Uses a strong KDF and key stretching for wallet storage and backups

    **PASS** Scrypt is used for KDF

  - On desktop platform:
    - Encrypt the wallet by default

      **PASS** Each wallet is encrypted with mandatory password

- For hardware wallets:
  - Prevents downgrading the firmware

    **N/A**

**Comment by crwatkins** [comment]
@goatpig It's been a while since there has been any activity here.  If this project is still active, let's re-open this and start things moving again.

**Comment by goatpig** [comment]
Hey Craig,

We're working on adding Liquid support and building up a userbase from there. I think it makes more sense to reopen this ticket once we deliver on that update. Thanks for the support.

**Comment by crwatkins** [comment]
Sounds good.   Thanks!

**Pull request closed without merging**
