### PR TITLE
Improve warning with details for 'estimatepriority' RPC

### PR DESCRIPTION
**Pull request by jonathancross**
Per https://github.com/bitcoin/bitcoin/pull/9602 - Remove coin age priority and free transactions - implementation

### CODE REVIEW

**Comment by Mirobit** [comment]
LGTM

**Comment by harding** [comment]
I sent a couple minor suggested edits in https://github.com/jonathancross/bitcoin.org/pull/1 but otherwise this LGTM.  Thanks, @jonathancross !

**Comment by jonathancross** [comment]
Cheers @harding.  Merged :-)

**Comment by wbnns** [comment]
This is now scheduled to be merged on Sunday, May 14th (tomorrow).

**Pull request merged**
