### PR TITLE
Add Infinity Wallet to wallets

### PR DESCRIPTION
**Pull request by InfinityWallet**
Bitcoin has been integrated into the Infinity Wallet, as part of the coin integration our only requirement is that we are listed as a supporting wallet on the coins website. We have submitted the pull request after meeting all the requirements.

### CODE REVIEW

**Comment by crwatkins** [comment]
Thanks for your submission!

I glanced over the update for a few seconds and noticed the following:

1.  Your submission points to an Armory wallet image
2.  The screenshot you included is for a mobile phone and your submission is for a desktop
3.  The link you provided to you source code is to your download page

Please correct these and very carefully review all of the other entries in your submission.  If you need additional information or clarifications, please feel free to ask for them here.   Also, please carefully go over each of the submission criteria and be sure that you meet all the criteria.  Please ask for clarification on anything that is unsure and do not assume that you meet the criteria if you don't understand them.

**Comment by InfinityWallet** [comment]
> Thanks for your submission!
> 
> I glanced over the update for a few seconds and noticed the following:
> 
> 1. Your submission points to an Armory wallet image
> 2. The screenshot you included is for a mobile phone and your submission is for a desktop
> 3. The link you provided to you source code is to your download page
> 
> Please correct these and very carefully review all of the other entries in your submission. If you need additional information or clarifications, please feel free to ask for them here. Also, please carefully go over each of the submission criteria and be sure that you meet all the criteria. Please ask for clarification on anything that is unsure and do not assume that you meet the criteria if you don't understand them.

Hello,

We have changed the image.

We used our mobile wallet screenshot previously as the required dimensions for your site were not suitable for desktop. The link is to the download page to allow users to directly download easily for ease of use and as the official download location.

**Comment by crwatkins** [comment]
The **link** attribute is for the website or download address.   The **source** attribute is for the address of the source code (all current entries reference GitHub).

**Comment by crwatkins** [comment]
@InfinityWallet Could you link to your source code as it is required for listing?   Thanks.

**Comment by crwatkins** [comment]
I have not been able to determine that Infinity Wallet meets the open source requirements for listing, so I will close this request for now.   Please re-open this request or submit a new request should this situation change.

**Comment by InfinityWallet** [comment]
We do not open-source code for increased security of users assets, it additionally incentivizes cloning projects damaging platforms and the blockchain ecosystem. However we are willing to share a security review and possibly on an NDA basis limited access if needed. However listing based on open source or not seems to lead to the bitcoin.org website listing wallets which are unusable for the majority of users, with very little developments, or are no longer active.

**Pull request closed without merging**
