### PR TITLE
bitcoin_et: Whitepaper Estonian translation

### PR DESCRIPTION
**Pull request by ekukxs**
[bitcoin_et.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5922446/bitcoin_et.pdf)

### CODE REVIEW

**Comment by ekukxs** [comment]
Sorry about the mess, it's my first time using Github.

**Comment by TonightEE** [comment]
Verified, translation is OK.

**Comment by GZXDQW** [comment]
verified, translation OK.

**Comment by Hysteria-est** [comment]
Verified, well done!

**Comment by jdabs** [comment]
Sidenote... it's really cool to see more people contributing. I always believed that it is one of the most interesting things in history to have a direct impact on an asset you can hold.

**Comment by ekukxs** [comment]
> Sidenote... it's really cool to see more people contributing. I always believed that it is one of the most interesting things in history to have a direct impact on an asset you can hold.

I agree! It's been a great honor translating this document and I hope it will help get more Estonians into Bitcoin and crypto generally.

Thanks to everyone for verifying this! Lovely!

**Comment by liigalihtnebtc** [comment]
[bitcoin_et.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5929071/bitcoin_et.pdf)

Fixed some typos and changed the formatting to look more like Satoshis original.

**Comment by Cobra-Bitcoin** [comment]
Thank you. I'll merge now, and clean up the file structure later.

**Pull request merged**
