### PR TITLE
Prefinal alert take 2

### PR DESCRIPTION
**Pull request by achow101**
This is the post for the prefinal alert.

@gmaxwell @Cobra-Bitcoin @laanwj

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK a1a8ebbae5d

**Comment by Cobra-Bitcoin** [comment]
I'll leave this one for @laanwj to merge when all the dates are confirmed among the core team; there was a lot of confusion last time.

**Comment by laanwj** [comment]
Yes, the confusion last time was unfortunate. We should just do this, and stop finding excuses.

ACK https://github.com/bitcoin-dot-org/bitcoin.org/pull/1401/commits/a1a8ebbae5d70d67a8111cd40736c66ead7aab0b

**Comment by achow101** [comment]
This is what the network status page looks like. It shows the blue banner
network-status-page

As with all other alerts, the warning symbol will be displayed for the network status and the RSS feed will be updated.

**Comment by harding** [comment]
LGTM a1a8ebb

**Comment by achow101** [comment]
pushing the date back, again.

**Comment by achow101** [comment]
Pushed the date back again to 31st and 1st.

@laanwj merge please?

**Comment by MarcoFalke** [comment]
@achow101 Please check with @gmaxwell first, who is going to prepare the alert IIRC.

**Comment by achow101** [comment]
ping @gmaxwell

**Comment by gmaxwell** [comment]
ACK. Feel free to merge at will.

**Comment by achow101** [comment]
ping @laanwj

**Pull request merged**
