### PR TITLE
Add the ARCHOS Safe-T mini hardware wallet

### PR DESCRIPTION
**Pull request by jcrona**
This PR adds the ARCHOS Safe-t mini hardware wallet to the list of available wallets.

The firmware of the Safe-T mini is based on the proven open source software from TREZOR, and provides an additional security layer relying on a dedicated hardware component (crypto-memory).
The frontend of the wallet relies on Electrum (support for the Safe-T mini has been officially merged in Electrum).

We saw in your requirements that "The codebase and final releases must be public since at least 6 months and previous commits must remain unchanged.", and since we released it last month (July 17 2018), the 6 month period is not met.

Nevertheless, we would really love to add our wallet to bitcoin.org. Would it be possible to make an exception for this 6 month period ?

### CODE REVIEW

**Comment by crwatkins** [comment]
@jcrona Thanks for your submission!  The "six month" item that you quoted is actually in the **Score** section and relates to the transparency score that the wallet is given (yes, it is a bit confusing).  You'll note that in the **Basic requirements** section, the requirement is:

* Wallet was publicly announced and released since at least 3 months

Which would qualify you for listing in October.  We can start the review process in the meantime.

**Comment by jcrona** [comment]
@crwatkins October would be great !
Do not hesitate if you need anything for the review process.

**Comment by crwatkins** [comment]
@jcrona Thanks for the updates!

**Comment by wbnns** [comment]
@jcrona Hello, could you please drop the changes to `de.yml` and `fr.yml`. It is only necessary to update `en.yml`. That will ensure it gets queued to be translated into the other languages (i.e. German and French).

**Comment by crwatkins** [comment]
I have reviewed the Archos Safe-T mini wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the device was released less than three months ago, I cannot recommend it for listing at this time.  Being very new also often means that there is currently extremely little user or developer feedback which can be found to satisfy the sufficient usage criterium.  While the wallet will be eligible for listing on 17 October 2018, it may or may not meet immediately meet the sufficient usage criterium at that time.  In addition, a support issue opened with Archos five days ago (on a weekend) has not yet been answered.  I'm hoping that response timeliness will be rectified by listing time.  I'll include some more of my thoughts on the usage criterium following the review.  

Note that as a "hardware wallet," only the hardware and firmware components of the device were evaluated.  Wallet software that runs externally to the Safe-T mini device was not evaluated in this review.  As an aside, I would like to change this in the future and evaluate combinations of hardware and software as a wallet system, but that's for another day.  The safe-t.io web management tool and Electrum were used during this review, but not evaluated.

I concur with the scoring in 6a3ad32.

---

## Safe-T mini
### Firmware v1.0.7
### Review Version 2018092001


The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was provided to bitcoin.org by Archos at no cost

**NOTE** Only the hardware/firmware is being evaluated here.  The wallet software running external to the device is ignored as out of scope.


Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

**FAIL** Many targeted (reddit, bitcointalk, etc.) and generic web searches were performed with multiple search engines to find many announcements over the last eight months and a handful of "unboxing" videos and reviews, but no non-superficial reviews which address the security, usability, or quality of the device.  There was an unusual absence of questions, complaints, and praise about the device to help estimate the amount of usage.

**NOTE** There were no concerning issues found

**NOTE** No independent security audit is available

- No indication that users have been harmed considerably by any issue in
  relation to the wallet

**PASS** No indication

- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

**PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

**PASS** No indication.  Uses same libraries as Trezor.

- No indication that changes to the code are not properly tested

**PASS** No indication

- Wallet was publicly announced and released since at least 3 months

**NOTE** Released 17 July 2018.  Eligible for listing on 17 October 2018.

- No concerning bug is found when testing the wallet

**PASS** No concerning bug was found testing the hardware

- Website supports HTTPS and 301 redirects HTTP requests

**PASS** http://safe-t.io and http://www.safe-t.io redirect to https://

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)

**PASS** https://safe-t.io rating A+

- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days

**PASS** https://safe-t.io has max-age of one year

- The identity of CEOs and/or developers is public

**PASS** Archos is French multinational company established 20 years ago by Henri Crohas

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI

**N/A** Addresses and paths are chosen by wallet software

- Uses deterministic ECDSA nonces (RFC 6979)

**PASS** A transaction signed by Safe-T mini was also signed using Electrum and the signatures were the same

- Avoid address reuse by using a new change address for each transaction

**N/A** Addresses and paths are chosen by wallet software

- User has access to private keys

**PASS** User has access to BIP39 seed

- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

**N/A** Keys are stored on the device

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

**PASS** Allows manual copying of the BIP39 phrase at startup

**NOTE** Safe-T mini provides a review to check the phrase, but no test that the copied phrase is correct

  - Restoring wallet from backup is working

**PASS** Restoring 24 word BIP39 phrase was successful

  - Source code is public and kept up to date under version control system

**PASS** https://github.com/archos-safe-t

- If user has no access to some of the private keys in a multi-signature wallet:
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet

**N/A**

- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)

**PASS** Two button input

  - Protects the seed against unsigned firmware upgrades

**PASS** Seeds are erased on unsigned firmware upgrades

  - Supports importing custom seeds

**PASS** Importing a 24 word seed from a BIP49 wallet succeeded

**NOTE** Only 24 (not 12) word seed imports are supported using the safe-t.io web app

  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element

**PASS** Source code at https://github.com/archos-safe-t

Optional criteria (some could become requirements):

- Received independent security audit(s)

**NOTE** No known audits

- Does not show "received from" Bitcoin addresses in the UI

**N/A**

- Provides a bug reporting policy on the website

**PASS** Provides support and contact information at ww.archos.com

**NOTE** An issue opened five days ago has not yet been responded to

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.appspot.com/)

**FAIL** https://safe-t.io is not on preload list

- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

**PASS**  Supports BIP32

  - Provides users with step to print or write their wallet seed on setup

**PASS** Provides a sequence of BIP39 words to write down, and a second pass to verify

**NOTE** There is no confirmation "quiz"

  - Uses a strong KDF and key stretching for wallet storage and backups

**PASS** Uses a crypto based memory chip

  - On desktop platform:
    - Encrypt the wallet by default

**N/A**

- For hardware wallets:
  - Prevents downgrading the firmware

**FAIL** Firmware can currently be downgraded.  Archos is planning to address this.

---


Our "sufficient usage" criterium is the hardest requirement for me to review both in terms of the amount of effort required to research and and the amount effort required to analyze and reach a conclusion.  It is also a real "catch-22" for wallet developers that are looking for exposure.  Since bitcoin.org doesn't have resources for performing general QA testing, let alone detailed security analysis, our community must rely on the generosity of others to post reviews, analysis, and even questions, complaints, and praise simply to indicate that the wallet is being used successfully.  (In lieu of such usage indications, independent audits are also accepted to satisfy this requirement.)  While this requirement is unfortunate, I believe it is still necessary and I welcome suggestions for methods to establish any metrics in this area which would serve to indicate that there is a low probability of significant outstanding issues with a wallet.

**Comment by wbnns** [comment]
@crwatkins Thank you.

**Comment by crwatkins** [comment]
Above I mentioned 
> ... a support issue opened with Archos five days ago (on a weekend) has not yet been answered. 

As a followup, Archos found a glitch in their support routing system which they claim has been rectified.

I've done a more recent, fairly quick, search for continuing user feedback.  I still haven't been able to find any user reviews on retail sites such as newegg.com (US) or amazon.uk (UK).  Also, I have not found any new non-superficial reviews which address the security, usability, or quality of the device. I suspect these will be coming soon.

It is also concerning that three months after [this issue and fix](https://blog.trezor.io/trezor-one-firmware-update-1-6-3-73894c0506d) was announced, there has not been a firmware update released to address this, perhaps now failing the following listing criteria:

* No indication that security issues have been concealed, ignored, or not
addressed correctly in order to prevent new or similar issues from happening
in the future

I recommend that the Safe-T mini be reevaluated in six months unless there are compelling new developments such as updates to release and support processes, or references to non-superficial reviews or formal evaluations.

**Comment by jcrona** [comment]
@crwatkins The issue you are referring to has never been an issue for the Safe-T mini that already includes the fix.

**Pull request closed without merging**
