### PR TITLE
choose-your-wallet: Adding info about wallet properties.

### PR DESCRIPTION
**Pull request by jonathancross**
I did not find a clear page defining what the various properties like "checkfailtransparencynew" mean.  Is there something better we can link to?

### CODE REVIEW

**Comment by crwatkins** [comment]
@jonathancross I believe you have indeed found the definitive self-describing definition at https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_translations/en.yml

**Comment by crwatkins** [comment]
@jonathancross I know this is really picky, but should the file reference in the comment be relative to our source tree instead of an absolute github URL?

I'm good with the addition either way.

**Comment by jonathancross** [comment]
@crwatkins I think a full url is easier to copy / paste into a new tab for reference.
But happy to change if you'd prefer relative path.

**Comment by crwatkins** [comment]
LGTM

**Comment by wbnns** [comment]
Unless others object, this will be merged on Wednesday, December 14th.

**Pull request merged**
