### PR TITLE
Rename Coin.Space to Coin

### PR DESCRIPTION
**Pull request by nikashitsa**
This PR updates screenshots and titles.  
Coin.Space = Coin Wallet. Just minor rebranding.

### CODE REVIEW

**Comment by crwatkins** [comment]
@nikashitsa None of the other wallets (except **Bitcoin Wallet**) have the word "Wallet" in their short title.  Take a look at the [list on bitcoin.org](https://bitcoin.org/en/choose-your-wallet) and consider whether you think your short title should be just **Coin** and let us know why or why not.

**Comment by jspeigner** [comment]
@crwatkins I agree that it should be just Coin. I had not noticed that no others used Wallet in the name. Thanks for calling that out.

**Comment by nikashitsa** [comment]
Fixed.

**Comment by crwatkins** [comment]
LGTM 412f054.

**Comment by nikashitsa** [comment]
@wbnns you are right. Fixed in d9cb5b1.

**Comment by wbnns** [comment]
@nikashitsa Thank you.

**Pull request merged**
