### PR TITLE
Split: Update with instructions for splitting coins and choosing chains

### PR DESCRIPTION
**Pull request by achow101**
I have included instructions for the general idea of what to do to choose a chain to use and the easiest process for splitting coins to be used on each chain. Instructions for Bitcoin Core are included here, and I would like to add instructions for other wallets as well. However I don't use many other wallets nor know them well enough to add instructions, so others will have to help me with that.

### CODE REVIEW

**Comment by wbnns** [comment]
@achow101 Thanks for putting this together. Could you please rebase your PR so we can see what it will look like with the latest changes?

**Comment by achow101** [comment]
rebased

**Comment by wbnns** [comment]
@achow101 Ok, thanks.

**Comment by theymos** [comment]
I feel that talking about this will over-complexifying the page for now, and will confuse people. If a split looks likely, this could be put up the day before or something.

The instructions are good, but even though it's *fairly* simple, I think that a ton of people are going to find anything like this too difficult, unfortunately...

**Comment by Mirobit** [comment]
This could be useful for the [Claim/Sell your BCash guide](https://github.com/yellowblood/sell-bcash).

I would not put this on the main page, since it is too complicated for the average user. >90% of them don't use Core.

**Comment by wbnns** [comment]
Closing this for now since the current alert is being discontinued.

**Pull request closed without merging**
