### PR TITLE
Add Coldcard

### PR DESCRIPTION
**Pull request by nvk**
Hi, this PR adds Coldcard to Bitcoin.org

### CODE REVIEW

**Comment by wbnns** [comment]
@nvk Thank you.

Cc: @crwatkins

**Comment by nvk** [comment]
Sure, I understand there is a wait :)

We announced while back, source has been public and some folks have had it in their since July. (Electrum already merged the plugin too)

I was thinking September, but no biggie.

**Comment by nvk** [comment]
Just checking in.

**Comment by crwatkins** [comment]
@nvk Do you support Bitcoin Core 0.17.0 now that it has been released?  Do you have a step-by-step guide perhaps?

**Comment by nvk** [comment]
We only officially support Electrum.

I haven't tried, but I hear It is possible to use Core 0.17 with Andrew's HWI script and some modifications to Core. https://github.com/achow101/HWI

**Comment by crwatkins** [comment]
I have reviewed the Coinkite Coldcard wallet based on the current wallet requirements criteria and my evaluation is below. The summary is that the wallet passes on security and overall design. However, because the device was released less than three months ago, and because of the other issues noted below, I cannot recommend it for listing at this time.  Being new often means that there is very little user or developer feedback which can be found to satisfy the sufficient usage criterium.  While the wallet will be eligible for listing on 15 November 2018, it may or may not immediately meet the sufficient usage criterium at that time.  I'll include some more of my thoughts on the usage criterium following the review.  I will be glad to recommend Coldcard for listing after the following items are addressed:

1. The wallet has been released for at least three months
1. The wallet has received sufficient user feedback
1. The coldcard.com web site security (redirection, HSTS) has been improved
1. The device keypad no longer generates spurious presses and is easier to use
1. The PR has been updated for style and scoring
1. Removal of the 10% fee restriction has been considered

All of these items are described in more detail in the review below.

Note that as a "hardware wallet," only the hardware and firmware components of the device were evaluated.  Wallet software that runs externally to the Coldcard device was not evaluated in this review.  As an aside, I would like to change this in the future and evaluate combinations of hardware and software as a wallet system, but that's for another day.  Electrum was used during this review, but not evaluated.

In regards to the description text in bbaaa45, for style and consistency reasons, there should be no words in all capitals nor any exclamation marks, and the spellings "open-source" and "MicroPython" should be used.  I would further recommend, but up to you, for readability that open-source be only mentioned once, backup be only mentioned once (sentences combined), and that "no app required" be removed or reworded because clearly Electrum is required.  The score for transparency is `checkgoodtransparencydeterministic` but I don't see any deterministic build procedures such as Gitian or Docker, so I suspect you want to change it to `checkpasstransparencyopensource`.


---

## Coldcard
### Firmware v1.0.2
### Review Version 2018102701


The wallet list is based on the personal evaluation of the maintainer(s) and
regular contributors of this site, according to the criteria detailed below.

These requirements are meant to be updated and strengthened over time.
Innovative wallets are exciting and encouraged, so if your wallet has a good
reason for not following some of the rules below, please submit it anyway and
we'll consider updating the rules.

**NOTE** The hardware device used for testing was provided to bitcoin.org by Coinkite at no cost.

**NOTE** Only the hardware/firmware is being evaluated here.  Wallet software running external to the device is not being reviewed.


Basic requirements:

- Sufficient users and/or developers feedback can be found without concerning
  issues, or independent security audit(s) is available

**FAIL** This wallet is so new that there is not sufficient feedback at this time.  I would expect more in the near future.  Current searches, using multiple search engines with extra focus on reddit.com, bitcointalk.org, and Twitter, yielded similar preliminary articles back to December and recent tweets and "unboxing" videos about receiving the wallet.  However, I could find only two non-superficial reviews which addressed the security, usability, or quality of the device.

https://cryptonewsreview.com/review-coinkite-coldcard-bitcoin-and-litecoin-hardware-wallet/

http://bittybot.co/uk/coldcard-review/

No customer reviews could be currently found on Amazon https://www.amazon.com/Opendime-Coinkite-Coldcard-Hardware-Wallet/dp/B079NKBSG5

- No indication that users have been harmed considerably by any issue in
  relation to the wallet
  
**PASS** No indication
  
  
- No indication that security issues have been concealed, ignored, or not
  addressed correctly in order to prevent new or similar issues from happening
in the future

**PASS** No indication

- No indication that the wallet uses unstable or unsecure libraries

**PASS** No indication.  Some libraries are based on Trezor libraries.

- No indication that changes to the code are not properly tested

**PASS** No indication.  Test code at https://github.com/Coldcard/firmware/tree/master/testing

- Wallet was publicly announced and released since at least 3 months

**NOTE** Released 15 August 2018.  Eligible for listing on 15 November 2018.  https://twitter.com/nvk/status/1029815780865499136

- No concerning bug is found when testing the wallet

**FAIL** While these concerns usually relate directly to security, this one is a bit different and relates to the keypad.  The keypad is extremely difficult to use.  On my first usage, it took me a long time to set my initial PIN because the keypad was generating many digits that I did not enter.  This was addressed with a firmware update that made the "phantom" presses less frequent but did not eliminate them and added a setting for keyboard sensitivity.  While using the "Normal" setting I still get some phantoms, and sometimes I have the keyboard stop responding (I don't know if that is related or not) but a power cycle usually makes it somewhat better.  In "Normal" mode, the keypad is difficult to use and requires long presses which sometimes don't register and sometimes register more than once. I've had the spurious presses actually navigate me to the signing menu while I wasn't touching the device.  The keypad really has to work better.  Both of the reviews linked above described similar issues with the keypad.

**NOTE** Some other bugs were found that were less concerning, including error messages that flashed too fast to read and a firmware crash that were reported.  A couple of bugs in the Coldcard Electrum plugin (not part of this review) were reported and already fixed. 

**NOTE**  The wallet currently will not allow the signing of any transaction where the fee is over 10% of the transaction value.  This is not a bug but rather a design decision that I believe should be addressed.    This presented issues sending transactions during testing, and since the wallet has no knowledge of the current network condition, this can make it impossible to send reasonable transactions.  The wallet already displays warnings when the fee is over 1% of the transaction value; actually refusing to sign a perfectly valid transaction requested by the user is not acceptable.

- Website supports HTTPS and 301 redirects HTTP requests

**FAIL** http://coldcardwallet.com does not redirect to HTTPS.

- SSL certificate passes [Qualys SSL Labs SSL
  test](https://www.ssllabs.com/ssltest/)
  
**PASS** https://coldcardwallet.com/ rating A
    
- Website serving executable code or requiring authentication uses HSTS with a
  max-age of at least 180 days
  
**FAIL** https://coldcardwallet.com does not use HSTS.
  
- The identity of CEOs and/or developers is public

**PASS** Coldcard is made by Coinkite, a long standing member of the community with their principals well known and a legal contact at https://coldcardwallet.com/legal

**NOTE** A more direct reference to details about the company or individuals would be preferred.

- Avoid address reuse by displaying a new receiving address for each transaction
  in the wallet UI
  
**N/A** Addresses and paths are chosen by wallet software
  
- Uses deterministic ECDSA nonces (RFC 6979)

**PASS** A transaction was signed both by Coldcard and custom code implementing deterministic signatures and the signature did match. 

- Avoid address reuse by using a new change address for each transaction

**N/A** Addresses and paths are chosen by wallet software

- User has access to private keys

**PASS** User has access to BIP39 seed

- If private keys or encryption keys are stored online:
  - Refuses weak passwords (short passwords and/or common passwords) used to
    secure access to any funds, or provides an aggressive account lock-out
feature in response to failed login attempts along with a strict account
recovery process.

**N/A** Keys are stored on the device

- If user has exclusive access over its private keys:
  - Allows backup of the wallet

**PASS** Allows manual copying of the BIP39 phrase at startup, as well as a password encrypted backup to microSD card
  
  - Restoring wallet from backup is working

**PASS** Seed words were successfully restored. Also restoring a password encrypted microSD card backup was successful.
  
  - Source code is public and kept up to date under version control system

**PASS** https://github.com/Coldcard
  
- If user has no access to some of the private keys in a multi-signature wallet:
  - Provides 2FA authentication feature
  - Reminds the user to enable 2FA by email or in the main UI of the wallet
  - User session is not persistent, or requires authentication for spending
  - Gives control to the user over moving their funds out of the multi-signature
    wallet
    
**N/A**
    
- For hardware wallets:
  - Uses the push model (computer malware cannot sign a transaction without user
    input)
    
**PASS** Uses a full keypad for confirmation

  - Protects the seed against unsigned firmware upgrades

**PASS** Upgraded firmware cannot access the seed until the user enters the PIN.  It is expected that the user will protect against this situation when being warned that the firmware was not signed by Coinkite.

  - Supports importing custom seeds

**PASS**  Supports importing 12, 18, and 24 English word BIP39 seeds as well as xprv

  - Provides source code and/or detailed specification for blackbox testing if
    using a closed-source Secure Element
    
**PASS** Full source code at https://github.com/Coldcard

Optional criteria (some could become requirements):

- Received independent security audit(s)

**NOTE** No known audits

- Does not show "received from" Bitcoin addresses in the UI

**N/A**

- Provides a bug reporting policy on the website

**PASS** https://coldcardwallet.com has a Support link which emails support@coinkite.com

**NOTE** All support requests were answered promptly and professionally.

- Website serving executable code or requiring authentication is included in the
  [HSTS preload list](https://hstspreload.org/)
  
**FAIL** https://coldcardwallet.com does not use HSTS.
  
- If user has exclusive access over its private keys:
  - Supports HD wallets (BIP32)

**PASS**  Supports BIP32
  
  - Provides users with step to print or write their wallet seed on setup

**PASS** Provides such a step with a "quiz" for confirmation

  - Uses a strong KDF and key stretching for wallet storage and backups
  
**PASS** Uses a crypto based memory chip

  - On desktop platform:
    - Encrypt the wallet by default

**N/A**

- For hardware wallets:
  - Prevents downgrading the firmware

**PASS** It is possible for the firmware to set a "high water mark" such that downgrading is not possible.  This is enforced in bootloader firmware (not the secure element) and was not tested.

---

As I've mentioned in other recent reviews, our "sufficient usage" criterium is the hardest requirement for me to review both in terms of the amount of effort required to research and the amount effort required to analyze and reach a conclusion.  It is also a real "catch-22" for wallet developers that are looking for exposure.  Since bitcoin.org doesn't have resources for performing general QA testing, let alone detailed security analysis, our community must rely on the generosity of others to post reviews, analysis, and even questions, complaints, and praise simply to indicate that the wallet is being used successfully.  (In lieu of such usage indications, independent audits are also accepted to satisfy this requirement.)  While this requirement is unfortunate, I believe it is still necessary and I welcome suggestions for methods to establish any metrics in this area which would serve to indicate that there is a low probability of significant outstanding issues with a wallet.

**Comment by peter-conalgo** [comment]
- coldcardwallet.com now has HSTS enabled and has been successfully submitted to the HSTS preload list.

**Comment by peter-conalgo** [comment]
- http://coldcardwallet.com does redirect to HTTPS now (required for HSTS anyway)

**Comment by wbnns** [comment]
Closing for now, but we can reopen once all items have been addressed:

1. The wallet has been released for at least three months
2. The wallet has received sufficient user feedback
3. The coldcard.com web site security (redirection, HSTS) has been improved
4. The device keypad no longer generates spurious presses and is easier to use
5. The PR has been updated for style and scoring
6. Removal of the 10% fee restriction has been considered

**Comment by nvk** [comment]
@wbnns there is some confusion there.

1. We are passed that.
2. There are thousands in the wild, including on hands of prominent Bitcoin project developers.
3. this was completed https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-437074901
4. This is not an issue for most users and was addressed on the last firmware.
5. Happy to do this once @crwatkins is ready to merge
6. This is a personal choice, but we made this change any ways on the coming firmware.

This is becoming a bit of a goal post moving target here.

**Comment by wbnns** [comment]
@nvk

Hello, I'm sorry you feel that way. In my comment yesterday, I copied and pasted the six items verbatim that were mentioned in the [review of Coldcard](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2612#issuecomment-433630363) by @crwatkins approximately a month ago.

Thanks for the additional information regarding the status of things on your side.

I would prefer to yield to any further recommendations from @crwatkins for the time being in case there is anything else he would like to add. Also, if anyone else would like to add feedback as well.

**Comment by nvk** [comment]
Fee limiting code and more touch sensitivity setting options now public https://github.com/Coldcard/firmware/pull/11

**Comment by nvk** [comment]
New firmware is not officially released https://coldcardwallet.com/docs/upgrade

**Pull request closed without merging**
